import type { Assessment } from '@/types/content';

export const chapter10Assessment: Assessment = {
  id: 'trigonometry-assessment',
  questions: [
    {
      id: 'trig-a1',
      part: 'concept',
      conceptSlug: 'the-six-trigonometric-ratios',
      conceptTitle: 'The Six Trigonometric Ratios',
      question: {
        id: 'trig-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does SOH-CAH-TOA help you remember?',
        options: [
          { id: 'a', text: 'sin=opp/hyp, cos=adj/hyp, tan=opp/adj' },
          { id: 'b', text: 'The Pythagorean theorem' },
          { id: 'c', text: 'The area of a triangle' },
          { id: 'd', text: 'How to convert degrees to radians' },
        ],
        correctOptionId: 'a',
        hints: ['S=sine, O=opposite, H=hypotenuse...'],
        explanation: 'SOH-CAH-TOA encodes the three basic trig ratio definitions.',
      },
    },
    {
      id: 'trig-a2',
      part: 'concept',
      conceptSlug: 'angle-of-elevation-and-depression',
      conceptTitle: 'Angle of Elevation and Angle of Depression',
      question: {
        id: 'trig-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'From what reference line is the angle of elevation always measured?',
        options: [
          { id: 'a', text: 'The horizontal' },
          { id: 'b', text: 'The vertical' },
          { id: 'c', text: 'The ground directly below the object' },
          { id: 'd', text: 'North' },
        ],
        correctOptionId: 'a',
        hints: ['Elevation means looking up FROM somewhere level.'],
        explanation: 'The angle of elevation is always measured upward from the horizontal.',
      },
    },
    {
      id: 'trig-b1',
      part: 'formula-application',
      conceptSlug: 'degree-radian-conversion',
      conceptTitle: 'Degree-Radian Conversion',
      question: {
        id: 'trig-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Convert 270° to radians.',
        options: [
          { id: 'a', text: '3π/2' },
          { id: 'b', text: 'π/2' },
          { id: 'c', text: '2π' },
          { id: 'd', text: '270π' },
        ],
        correctOptionId: 'a',
        hints: ['270 × (π/180) = 270/180 × π.'],
        explanation: '270 × (π/180) = 3π/2.',
      },
    },
    {
      id: 'trig-b2',
      part: 'formula-application',
      conceptSlug: 'arc-length-of-a-sector',
      conceptTitle: 'Arc Length of a Sector',
      question: {
        id: 'trig-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A circle has radius 12. Find the arc length for a central angle of 0.5 radians.',
        hints: ['s = rθ = 12 × 0.5.'],
        correctAnswer: 6,
        explanation: 's = 12 × 0.5 = 6.',
      },
    },
    {
      id: 'trig-c1',
      part: 'problem-solving',
      conceptSlug: 'pythagorean-identity-and-reciprocal-relations',
      conceptTitle: 'The Pythagorean Identity and Reciprocal Relations',
      question: {
        id: 'trig-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'If sinθ = 8/17 and θ is acute, find cosθ. (Give as a fraction\'s numerator over 17 — just the numerator.)',
        hints: ['cos²θ = 1 − (8/17)².'],
        correctAnswer: 15,
        explanation: 'cos²θ = 1 − 64/289 = 225/289, so cosθ = 15/17.',
      },
    },
    {
      id: 'trig-c2',
      part: 'problem-solving',
      conceptSlug: 'solving-right-triangles',
      conceptTitle: 'Solving Right Triangles',
      question: {
        id: 'trig-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In a right triangle, the hypotenuse is 20 and one acute angle is 53°. Find the side adjacent to that angle. (cos53° ≈ 0.602. Round to 1 decimal place.)',
        hints: ['cosθ = adj/hyp.', 'adj = hyp × cosθ.'],
        correctAnswer: 12.0,
        tolerance: 0.2,
        explanation: 'adj = 20 × cos(53°) ≈ 20 × 0.602 ≈ 12.0.',
      },
    },
    {
      id: 'trig-d1',
      part: 'real-life-application',
      conceptSlug: 'area-of-a-sector',
      conceptTitle: 'Area of a Sector',
      question: {
        id: 'trig-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A sprinkler waters a circular sector of radius 5 m, rotating through 1.2 radians. Find the watered area.',
        hints: ['A = (1/2)(5²)(1.2).'],
        correctAnswer: 15,
        explanation: 'A = (1/2)(25)(1.2) = 15 m².',
      },
    },
    {
      id: 'trig-d2',
      part: 'real-life-application',
      conceptSlug: 'angle-of-elevation-and-depression',
      conceptTitle: 'Angle of Elevation and Angle of Depression',
      question: {
        id: 'trig-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'From a point 60 m from a building\'s base, the angle of elevation to its top is 40°. Find the building\'s height. (tan40° ≈ 0.839. Round to the nearest metre.)',
        hints: ['tan(40°) = height/60.'],
        correctAnswer: 50,
        tolerance: 1,
        explanation: 'height = 60 × tan(40°) ≈ 60 × 0.839 ≈ 50 m.',
      },
    },
    {
      id: 'trig-e1',
      part: 'challenge',
      conceptSlug: 'trig-ratios-for-special-angles',
      conceptTitle: 'Trigonometric Ratios for Special Angles',
      question: {
        id: 'trig-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why do sin(30°) and cos(60°) have exactly the same value?',
        options: [
          { id: 'a', text: '30° and 60° are complementary angles, and sine of an angle always equals cosine of its complement.' },
          { id: 'b', text: 'It is a coincidence.' },
          { id: 'c', text: 'Because 30 + 60 = 90.' },
          { id: 'd', text: 'Because both angles are acute.' },
        ],
        correctOptionId: 'a',
        hints: ['In a right triangle, what happens to opposite and adjacent when you switch which acute angle you look from?'],
        explanation: 'For complementary angles, the "opposite" side for one angle is the "adjacent" side for the other, so sin(θ) = cos(90°−θ) always.',
      },
    },
    {
      id: 'trig-e2',
      part: 'challenge',
      conceptSlug: 'the-six-trigonometric-ratios',
      conceptTitle: 'The Six Trigonometric Ratios',
      question: {
        id: 'trig-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In a right triangle, tanθ = 5/12. Find secθ (the hypotenuse over the adjacent side), as a fraction\'s numerator over 12 (just the numerator — hint: this is a 5-12-13 triangle).',
        hints: ['5-12-13 is a Pythagorean triple.', 'secθ = hyp/adj = 13/12.'],
        correctAnswer: 13,
        explanation: 'Since tanθ=5/12 matches a 5-12-13 right triangle, secθ = hyp/adj = 13/12.',
      },
    },
  ],
};
