import type { Assessment } from '@/types/content';

export const chapter11ElectronicsAssessment: Assessment = {
  id: 'fundamentals-of-electronics-assessment',
  questions: [
    {
      id: 'fe-a1',
      part: 'concept',
      conceptSlug: 'semiconductors',
      conceptTitle: 'Semiconductors',
      question: {
        id: 'fe-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What does doping a semiconductor achieve?',
        options: [
          { id: 'a', text: 'It precisely controls the material\'s conductivity by adding impurity atoms.' },
          { id: 'b', text: 'It permanently destroys the semiconductor\'s conductivity.' },
          { id: 'c', text: 'It turns the semiconductor into a perfect insulator.' },
          { id: 'd', text: 'Doping has no effect on conductivity.' },
        ],
        correctOptionId: 'a',
        hints: ['Doping introduces extra charge carriers.'],
        explanation: 'Doping adds impurity atoms that create extra free electrons (n-type) or holes (p-type), precisely controlling conductivity.',
      },
    },
    {
      id: 'fe-a2',
      part: 'concept',
      conceptSlug: 'the-transistor',
      conceptTitle: 'Transistor',
      question: {
        id: 'fe-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What is the basic function of a transistor?',
        options: [
          { id: 'a', text: 'To amplify a small current/signal or act as an electronic switch.' },
          { id: 'b', text: 'To store large amounts of electrical energy permanently.' },
          { id: 'c', text: 'To convert electrical energy into light only.' },
          { id: 'd', text: 'Transistors have no practical function in circuits.' },
        ],
        correctOptionId: 'a',
        hints: ['Think of what makes transistors so important to electronics.'],
        explanation: 'A transistor amplifies a small signal into a larger one or acts as a controllable switch.',
      },
    },
    {
      id: 'fe-a3',
      part: 'concept',
      conceptSlug: 'logic-gates-b-level',
      conceptTitle: 'Logic Gate',
      question: {
        id: 'fe-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'When is the output of an AND gate (with two inputs) HIGH?',
        options: [
          { id: 'a', text: 'Only when BOTH inputs are HIGH.' },
          { id: 'b', text: 'When at least one input is HIGH.' },
          { id: 'c', text: 'When both inputs are LOW.' },
          { id: 'd', text: 'An AND gate\'s output is always HIGH.' },
        ],
        correctOptionId: 'a',
        hints: ['"AND" requires both conditions to be true.'],
        explanation: 'An AND gate\'s output is HIGH only when every input is HIGH.',
      },
    },
    {
      id: 'fe-b1',
      part: 'formula-application',
      conceptSlug: 'the-transistor',
      conceptTitle: 'Transistor',
      question: {
        id: 'fe-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A transistor has current gain 80 and base current 0.05 mA. Find the collector current.',
        hints: ['I_C = β × I_B.'],
        correctAnswer: 4,
        tolerance: 0.2,
        unit: 'mA',
        explanation: 'I_C = 80 × 0.05 = 4 mA.',
      },
    },
    {
      id: 'fe-b2',
      part: 'formula-application',
      conceptSlug: 'the-transistor',
      conceptTitle: 'Transistor',
      question: {
        id: 'fe-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A transistor has collector current 6 mA and base current 0.05 mA. Find its current gain.',
        hints: ['β = I_C/I_B.'],
        correctAnswer: 120,
        tolerance: 2,
        explanation: 'β = 6/0.05 = 120.',
      },
    },
    {
      id: 'fe-c1',
      part: 'problem-solving',
      conceptSlug: 'semiconductors',
      conceptTitle: 'Semiconductors',
      question: {
        id: 'fe-c1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'An engineer wants to create a semiconductor region with extra mobile positive "holes" as charge carriers. What should they do?',
        options: [
          { id: 'a', text: 'Dope the material with impurity atoms that have FEWER valence electrons, creating p-type material.' },
          { id: 'b', text: 'Dope the material with impurity atoms that have MORE valence electrons.' },
          { id: 'c', text: 'Doping cannot create positive charge carriers.' },
          { id: 'd', text: 'Heat the material until it becomes a perfect insulator.' },
        ],
        correctOptionId: 'a',
        hints: ['p-type material has extra "holes" as majority charge carriers.'],
        explanation: 'Doping with fewer-valence-electron impurities creates p-type material, with extra holes acting as mobile positive charge carriers.',
      },
    },
    {
      id: 'fe-c2',
      part: 'problem-solving',
      conceptSlug: 'logic-gates-b-level',
      conceptTitle: 'Logic Gate',
      question: {
        id: 'fe-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A security system should trigger an alarm if EITHER a window sensor OR a door sensor detects intrusion. Which logic gate matches this requirement?',
        options: [
          { id: 'a', text: 'OR gate, since the alarm should trigger if at least one sensor detects intrusion.' },
          { id: 'b', text: 'AND gate, since both sensors must detect intrusion simultaneously.' },
          { id: 'c', text: 'A logic gate cannot be used for this purpose.' },
          { id: 'd', text: 'NOT gate.' },
        ],
        correctOptionId: 'a',
        hints: ['"Either...or" language directly matches one specific gate type.'],
        explanation: 'An OR gate matches this scenario exactly: the output (alarm) is HIGH if at least one input (sensor) is HIGH.',
      },
    },
    {
      id: 'fe-d1',
      part: 'real-life-application',
      conceptSlug: 'the-integrated-circuit',
      conceptTitle: 'Integrated Circuit',
      question: {
        id: 'fe-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can a modern smartphone processor contain billions of transistors in such a small space?',
        options: [
          { id: 'a', text: 'Integrated circuit technology manufactures huge numbers of components together on a single semiconductor chip.' },
          { id: 'b', text: 'Smartphone processors do not actually use transistors.' },
          { id: 'c', text: 'Each transistor is manually wired by hand.' },
          { id: 'd', text: 'Integrated circuits can only contain a few components.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about the manufacturing process for a chip versus individually wired components.'],
        explanation: 'Integrated circuit manufacturing allows billions of components to be built together on a single small chip, which individually wired components never could achieve.',
      },
    },
    {
      id: 'fe-d2',
      part: 'real-life-application',
      conceptSlug: 'the-transistor',
      conceptTitle: 'Transistor',
      question: {
        id: 'fe-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How does a transistor help amplify a weak microphone signal to drive a loudspeaker?',
        options: [
          { id: 'a', text: 'The weak signal controls the base current, which controls a much larger current from a power supply, producing a stronger output.' },
          { id: 'b', text: 'The transistor directly generates new energy from the weak signal alone.' },
          { id: 'c', text: 'Transistors cannot be used for audio amplification.' },
          { id: 'd', text: 'The microphone signal bypasses the transistor entirely.' },
        ],
        correctOptionId: 'a',
        hints: ['Where does the extra power in the amplified signal actually come from?'],
        explanation: 'The transistor uses the weak input signal to control a much larger current drawn from an external power supply, amplifying the signal.',
      },
    },
    {
      id: 'fe-e1',
      part: 'challenge',
      conceptSlug: 'the-transistor',
      conceptTitle: 'Transistor',
      question: {
        id: 'fe-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A transistor with β = 200 is used, but the base current is accidentally reduced to zero. What happens to the collector current?',
        options: [
          { id: 'a', text: 'It also drops to zero, since I_C = β × I_B and any value times zero is zero.' },
          { id: 'b', text: 'It stays at its previous large value.' },
          { id: 'c', text: 'It increases to compensate.' },
          { id: 'd', text: 'Current gain has no relationship to base current.' },
        ],
        correctOptionId: 'a',
        hints: ['Apply I_C = β × I_B directly.'],
        explanation: 'Since I_C = β × I_B, a base current of zero forces the collector current to zero as well, regardless of β.',
      },
    },
  ],
};
