import type { Assessment } from '@/types/content';

export const chapter11AQuantumAssessment: Assessment = {
  id: 'quantum-and-atomic-physics-assessment',
  questions: [
    {
      id: 'quantum-a1',
      part: 'concept',
      conceptSlug: 'thermionic-emission-vacuum-diode-a-level',
      conceptTitle: 'Thermionic Emission and the Vacuum Diode',
      question: {
        id: 'quantum-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'In a conducting vacuum diode (heated cathode, positive anode), electrons flow from the cathode to the anode. In which direction does CONVENTIONAL current flow through the tube?',
        hints: ['Conventional current flows opposite to the direction electrons actually move.'],
        options: [
          { id: 'a', text: 'From the cathode to the anode, same as the electrons' },
          { id: 'b', text: 'From the anode to the cathode, opposite to the electrons' },
          { id: 'c', text: 'Current does not flow in a vacuum diode' },
          { id: 'd', text: 'In both directions simultaneously' },
        ],
        correctOptionId: 'b',
        explanation: 'Conventional current is defined as flowing opposite to the actual electron flow, so it flows from the anode to the cathode inside the tube.',
      },
    },
    {
      id: 'quantum-a2',
      part: 'concept',
      conceptSlug: 'atomic-structure-a-level',
      conceptTitle: 'Atomic Structure',
      question: {
        id: 'quantum-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'An atom has 20 protons and 20 neutrons. Find its mass number A.',
        hints: ['A = protons + neutrons.', '20 + 20.'],
        correctAnswer: 40,
        explanation: 'A = 20 + 20 = 40 (this matches calcium-40).',
      },
    },
    {
      id: 'quantum-b1',
      part: 'formula-application',
      conceptSlug: 'photon-energy-a-level',
      conceptTitle: 'The Photon',
      question: {
        id: 'quantum-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the energy of a photon of blue light with a frequency of 6.5 × 10¹⁴ Hz (h = 6.63 × 10⁻³⁴ J·s). (Enter the coefficient × 10⁻¹⁹, e.g. for 4.31×10⁻¹⁹, enter 4.31.)',
        hints: ['E = hf.', '6.63×10⁻³⁴ × 6.5×10¹⁴.'],
        correctAnswer: 4.31,
        tolerance: 0.05,
        explanation: 'E = 6.63×10⁻³⁴ × 6.5×10¹⁴ ≈ 4.31×10⁻¹⁹ J.',
      },
    },
    {
      id: 'quantum-b2',
      part: 'formula-application',
      conceptSlug: 'blackbody-radiation-a-level',
      conceptTitle: 'Blackbody Radiation',
      question: {
        id: 'quantum-b2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "As a blackbody's temperature increases, what happens to its total emitted radiation and peak wavelength?",
        hints: ['Think about a metal rod glowing brighter and changing color as it heats up.'],
        options: [
          { id: 'a', text: 'Total emission increases; peak wavelength shifts shorter (bluer)' },
          { id: 'b', text: 'Total emission decreases; peak wavelength shifts longer (redder)' },
          { id: 'c', text: 'Neither changes with temperature' },
          { id: 'd', text: 'Total emission increases; peak wavelength shifts longer (redder)' },
        ],
        correctOptionId: 'a',
        explanation: 'A hotter blackbody emits more total radiation, with its peak wavelength shifting to shorter (bluer) wavelengths.',
      },
    },
    {
      id: 'quantum-c1',
      part: 'problem-solving',
      conceptSlug: 'models-of-the-atom-a-level',
      conceptTitle: 'Models of the Atom',
      question: {
        id: 'quantum-c1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: "If Thomson's 'plum pudding' model had been correct, what result would Rutherford's alpha-scattering experiment have shown?",
        hints: ["Thomson's model has no concentrated, dense positive charge anywhere."],
        options: [
          { id: 'a', text: 'Nearly all alpha particles would pass through with little to no deflection, and none would bounce back sharply' },
          { id: 'b', text: 'All alpha particles would bounce straight back' },
          { id: 'c', text: 'The alpha particles would be absorbed completely' },
          { id: 'd', text: 'The result would be identical to what was actually observed' },
        ],
        correctOptionId: 'a',
        explanation: "With charge spread evenly throughout the atom (as in Thomson's model), there would be no concentrated charge strong enough to sharply deflect any alpha particles — which is why the actual sharp deflections observed disproved this model.",
      },
    },
    {
      id: 'quantum-c2',
      part: 'problem-solving',
      conceptSlug: 'atomic-structure-a-level',
      conceptTitle: 'Atomic Structure',
      question: {
        id: 'quantum-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An isotope of uranium has an atomic number of 92 and 143 neutrons. Find its mass number.',
        hints: ['A = Z + neutrons.', '92 + 143.'],
        correctAnswer: 235,
        explanation: 'A = 92 + 143 = 235 (this is uranium-235, used in nuclear reactors).',
      },
    },
    {
      id: 'quantum-d1',
      part: 'real-life-application',
      conceptSlug: 'structure-evolution-universe-a-level',
      conceptTitle: 'The Structure and Evolution of the Visible Universe',
      question: {
        id: 'quantum-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why do astronomers consider the discovery of the cosmic microwave background strong evidence for the Big Bang?',
        hints: ['It matches a very specific prediction about the early universe.'],
        options: [
          { id: 'a', text: 'It matches the predicted cooled, leftover radiation from a hot, dense early universe' },
          { id: 'b', text: 'It proves the universe is not expanding' },
          { id: 'c', text: 'It comes from only one direction in the sky' },
          { id: 'd', text: 'It was predicted to not exist at all' },
        ],
        correctOptionId: 'a',
        explanation: "The cosmic microwave background is the predicted, cooled afterglow of the universe's hot, dense early state — its detection strongly supported the Big Bang theory.",
      },
    },
    {
      id: 'quantum-d2',
      part: 'real-life-application',
      conceptSlug: 'photon-energy-a-level',
      conceptTitle: 'The Photon',
      question: {
        id: 'quantum-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'X-rays can penetrate soft tissue for medical imaging, while visible light cannot. What property of X-ray photons explains this?',
        hints: ['Think about frequency and photon energy.'],
        options: [
          { id: 'a', text: 'X-ray photons have a much higher frequency, and therefore much more energy, than visible-light photons' },
          { id: 'b', text: 'X-rays are brighter than visible light' },
          { id: 'c', text: 'X-rays travel slower than visible light' },
          { id: 'd', text: 'X-ray photons have no energy at all' },
        ],
        correctOptionId: 'a',
        explanation: "X-ray photons have a much higher frequency (and therefore much higher energy per photon, E=hf) than visible light, allowing them to penetrate soft tissue.",
      },
    },
    {
      id: 'quantum-e1',
      part: 'challenge',
      conceptSlug: 'models-of-the-atom-a-level',
      conceptTitle: 'Models of the Atom',
      question: {
        id: 'quantum-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: "Bohr's model proposed that electrons can only orbit at specific, quantized energy levels. Which experimental observation does this idea help explain?",
        hints: ['Think about what atoms emit when excited, and the PATTERN of that emission.'],
        options: [
          { id: 'a', text: 'Why excited atoms emit light only at discrete, specific wavelengths (line spectra), rather than a continuous spread' },
          { id: 'b', text: 'Why atoms have mass' },
          { id: 'c', text: 'Why the nucleus is positively charged' },
          { id: 'd', text: 'Why atoms of different elements have different colors when solid' },
        ],
        correctOptionId: 'a',
        explanation: "Quantized electron energy levels mean electrons can only jump between specific fixed energies, emitting photons of only specific, discrete frequencies — exactly matching the observed discrete line spectra of excited atoms.",
      },
    },
    {
      id: 'quantum-e2',
      part: 'challenge',
      conceptSlug: 'structure-evolution-universe-a-level',
      conceptTitle: 'The Structure and Evolution of the Visible Universe',
      question: {
        id: 'quantum-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "By Hubble's Law, a galaxy's recession speed is proportional to its distance. Galaxy A recedes at 15,000 km/s; galaxy B recedes at 45,000 km/s. How many times farther away is galaxy B compared to galaxy A?",
        hints: ['Since speed is proportional to distance, the ratio of speeds equals the ratio of distances.', '45,000 / 15,000.'],
        correctAnswer: 3,
        explanation: 'Since recession speed is proportional to distance, the distance ratio equals the speed ratio: 45,000/15,000 = 3 times farther.',
      },
    },
  ],
};
