import type { Assessment } from '@/types/content';

export const chapter3CFluidAssessment: Assessment = {
  id: 'fluid-dynamics-assessment',
  questions: [
    {
      id: 'fluiddyn-a1',
      part: 'concept',
      conceptSlug: 'laminar-and-turbulent-flow',
      conceptTitle: 'Laminar and Turbulent Flow',
      question: {
        id: 'fluiddyn-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Water (ρ=1000 kg/m³, η=0.001 Pa·s) flows through a pipe of diameter 0.05 m at 0.2 m/s. Find the Reynolds number.',
        hints: ['Re = ρvd/η.'],
        correctAnswer: 10000,
        explanation: 'Re = (1000)(0.2)(0.05)/0.001 = 10/0.001 = 10000.',
      },
    },
    {
      id: 'fluiddyn-a2',
      part: 'concept',
      conceptSlug: 'equation-of-continuity',
      conceptTitle: 'Equation of Continuity',
      question: {
        id: 'fluiddyn-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A pipe narrows from A₁=0.04 m² (v₁=3 m/s) to A₂=0.02 m². Find v₂.',
        hints: ['v₂ = A₁v₁/A₂.'],
        correctAnswer: 6,
        explanation: 'v₂ = (0.04)(3)/0.02 = 0.12/0.02 = 6 m/s.',
      },
    },
    {
      id: 'fluiddyn-b1',
      part: 'formula-application',
      conceptSlug: 'bernoullis-equation',
      conceptTitle: "Bernoulli's Equation",
      question: {
        id: 'fluiddyn-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Water (ρ=1000 kg/m³) flows through a horizontal pipe at P₁=150000 Pa, v₁=1 m/s, speeding up to v₂=6 m/s. Find P₂.',
        hints: ['P₁+½ρv₁² = P₂+½ρv₂².'],
        correctAnswer: 132500,
        explanation: '150000+500 = P₂+18000. P₂ = 150500−18000 = 132500 Pa.',
      },
    },
    {
      id: 'fluiddyn-b2',
      part: 'formula-application',
      conceptSlug: 'viscosity-and-fluid-friction',
      conceptTitle: 'Viscosity (Fluid Friction)',
      question: {
        id: 'fluiddyn-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A fluid layer (η=0.0012 Pa·s) of area 0.3 m² moves at 0.4 m/s relative to a fixed layer 0.0015 m away. Find the viscous force.',
        hints: ['F = ηA(v/d).'],
        correctAnswer: 0.096,
        explanation: 'F = (0.0012)(0.3)(0.4/0.0015) = (0.0012)(0.3)(266.7) ≈ 0.096 N.',
      },
    },
    {
      id: 'fluiddyn-c1',
      part: 'problem-solving',
      conceptSlug: 'capillarity',
      conceptTitle: 'Capillarity',
      question: {
        id: 'fluiddyn-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Water (γ=0.072 N/m, ρ=1000 kg/m³, θ≈0°) rises 0.02 m in a capillary tube. Find the tube\'s radius.',
        hints: ['Rearrange h=2γcosθ/(ρgr) to solve for r.'],
        correctAnswer: 0.000735,
        tolerance: 0.00002,
        explanation: 'r = 2γ/(ρgh) = 2(0.072)/[(1000)(9.8)(0.02)] = 0.144/196 ≈ 0.000735 m.',
      },
    },
    {
      id: 'fluiddyn-c2',
      part: 'problem-solving',
      conceptSlug: 'surface-tension',
      conceptTitle: 'Surface Tension',
      question: {
        id: 'fluiddyn-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A needle of length 0.03 m floats on water (γ=0.072 N/m), supported by surface tension along both sides of the needle. Find the maximum supporting force.',
        hints: ['Both sides of the needle touch the surface: F=γ×2L.'],
        correctAnswer: 0.00432,
        explanation: 'F = 0.072 × (2 × 0.03) = 0.072 × 0.06 = 0.00432 N.',
      },
    },
    {
      id: 'fluiddyn-d1',
      part: 'real-life-application',
      conceptSlug: 'bernoulli-theorem-applications',
      conceptTitle: "Manifestations of Bernoulli's Theorem",
      question: {
        id: 'fluiddyn-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A Venturi meter narrows a pipe to measure flow speed by measuring a pressure drop in the narrow section. Which principle explains why pressure drops there?',
        hints: ['The same principle behind wing lift.'],
        options: [
          { id: 'a', text: "Bernoulli's principle — faster flow has lower pressure" },
          { id: 'b', text: 'The pipe material changes in the narrow section' },
          { id: 'c', text: 'Gravity increases in narrow sections' },
          { id: 'd', text: 'Friction disappears in narrow sections' },
        ],
        correctOptionId: 'a',
        explanation: "The continuity equation forces the fluid to speed up in the narrow section, and Bernoulli's equation then predicts a corresponding pressure drop.",
      },
    },
    {
      id: 'fluiddyn-d2',
      part: 'real-life-application',
      conceptSlug: 'equation-of-continuity',
      conceptTitle: 'Equation of Continuity',
      question: {
        id: 'fluiddyn-d2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Blood flow slows down significantly in the body\'s tiny capillaries, even though each individual capillary is extremely narrow. What explains this?',
        hints: ['Think about the TOTAL cross-sectional area, not just one capillary.'],
        options: [
          { id: 'a', text: 'The total combined cross-sectional area of all the capillaries together is much larger than the main artery' },
          { id: 'b', text: 'Capillaries are completely frictionless' },
          { id: 'c', text: 'Blood becomes less dense inside capillaries' },
          { id: 'd', text: 'Gravity is weaker inside capillaries' },
        ],
        correctOptionId: 'a',
        explanation: 'By the equation of continuity, flow speed depends on total cross-sectional area — millions of tiny capillaries together have a far larger total area than the artery feeding them, so the flow slows down.',
      },
    },
    {
      id: 'fluiddyn-e1',
      part: 'challenge',
      conceptSlug: 'bernoullis-equation',
      conceptTitle: "Bernoulli's Equation",
      question: {
        id: 'fluiddyn-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Water (ρ=1000 kg/m³) flows through a pipe of constant cross-section (so v stays the same) from P₁=300000 Pa at height h₁=0 m up to height h₂=5 m. Find P₂.',
        hints: ['With v₁=v₂, the kinetic energy terms cancel: P₁+ρgh₁ = P₂+ρgh₂.'],
        correctAnswer: 251000,
        explanation: 'P₂ = P₁−ρg(h₂−h₁) = 300000 − (1000)(9.8)(5) = 300000−49000 = 251000 Pa.',
      },
    },
    {
      id: 'fluiddyn-e2',
      part: 'challenge',
      conceptSlug: 'capillarity',
      conceptTitle: 'Capillarity',
      question: {
        id: 'fluiddyn-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two capillary tubes of radii 0.0004 m and 0.0008 m are dipped in the same liquid (γ=0.05 N/m, ρ=800 kg/m³, θ≈0°). Find the difference in rise height between the narrower and wider tube.',
        hints: ['Find h for each radius using h=2γcosθ/(ρgr), then subtract.'],
        correctAnswer: 0.0159,
        tolerance: 0.001,
        explanation: 'h₁=0.1/3.136≈0.03189m (r=0.0004m). h₂=0.1/6.272≈0.01594m (r=0.0008m). Difference ≈ 0.0159 m.',
      },
    },
  ],
};
