import type { Formula } from '@/types/content';

export const chapter3CFluidFormulas: Record<string, Formula> = {
  'reynolds-number-formula': {
    slug: 'reynolds-number-formula',
    name: "Reynolds Number",
    expression: 'Re = ρvd / η',
    meaning: 'A dimensionless number that predicts whether a fluid\'s flow will be smooth (laminar) or chaotic (turbulent) — comparing the fluid\'s inertia to its internal friction (viscosity).',
    variables: [
      { symbol: 'Re', meaning: 'Reynolds number (dimensionless — no units)' },
      { symbol: 'ρ', meaning: 'fluid density, in kilograms per cubic metre (kg/m³)' },
      { symbol: 'v', meaning: 'flow speed, in metres per second (m/s)' },
      { symbol: 'd', meaning: 'characteristic diameter of the flow (e.g. pipe diameter), in metres (m)' },
      { symbol: 'η', meaning: 'dynamic viscosity of the fluid, in pascal-seconds (Pa·s)' },
    ],
    whenToUse: 'Whenever predicting or classifying whether a flow is laminar (Re below about 2000) or turbulent (Re above about 4000).',
    relatedConceptSlugs: ['laminar-and-turbulent-flow'],
  },
  'equation-of-continuity-formula': {
    slug: 'equation-of-continuity-formula',
    name: 'Equation of Continuity',
    expression: 'A₁v₁ = A₂v₂',
    meaning: 'For an incompressible fluid flowing through a pipe, the same volume of fluid must pass every cross-section every second — so where the pipe narrows, the fluid must speed up.',
    variables: [
      { symbol: 'A₁, A₂', meaning: 'cross-sectional area at two points along the pipe, in square metres (m²)' },
      { symbol: 'v₁, v₂', meaning: 'flow speed at those same two points, in metres per second (m/s)' },
    ],
    whenToUse: 'Whenever fluid flows through a pipe or channel that changes cross-sectional area, and the speed at one point needs to be found from the speed and areas elsewhere.',
    relatedConceptSlugs: ['equation-of-continuity'],
  },
  'bernoullis-equation-formula': {
    slug: 'bernoullis-equation-formula',
    name: "Bernoulli's Equation",
    expression: 'P + ½ρv² + ρgh = constant',
    meaning: 'Along a streamline in a flowing, incompressible, non-viscous fluid, the sum of pressure energy, kinetic energy per volume, and gravitational potential energy per volume stays constant.',
    variables: [
      { symbol: 'P', meaning: 'pressure at a point in the fluid, in pascals (Pa)' },
      { symbol: 'ρ', meaning: 'fluid density, in kilograms per cubic metre (kg/m³)' },
      { symbol: 'v', meaning: 'flow speed at that point, in metres per second (m/s)' },
      { symbol: 'h', meaning: 'height of that point above a reference level, in metres (m)' },
      { symbol: 'g', meaning: 'acceleration due to gravity, 9.8 m/s²' },
    ],
    whenToUse: 'Whenever relating pressure, speed, and height at two different points along the same flow.',
    relatedConceptSlugs: ['bernoullis-equation'],
  },
  'bernoulli-lift-formula': {
    slug: 'bernoulli-lift-formula',
    name: 'Pressure Difference and Lift from Bernoulli\'s Equation',
    expression: 'ΔP = ½ρ(v₁² − v₂²);   F_lift = ΔP × A',
    meaning: 'When fluid moves faster over one surface than another at the same height, Bernoulli\'s equation predicts a pressure difference between the two sides — pushing toward the faster-moving, lower-pressure side.',
    variables: [
      { symbol: 'ΔP', meaning: 'pressure difference between the two sides, in pascals (Pa)' },
      { symbol: 'v₁, v₂', meaning: 'flow speeds on the two sides, in metres per second (m/s)' },
      { symbol: 'F_lift', meaning: 'net force from the pressure difference, in newtons (N)' },
      { symbol: 'A', meaning: 'surface area the pressure difference acts over, in square metres (m²)' },
    ],
    whenToUse: 'Whenever explaining or calculating the force created by a speed difference across two sides of a surface — such as lift on a wing or the pull of an atomizer.',
    relatedConceptSlugs: ['bernoulli-theorem-applications'],
  },
  'viscosity-formula': {
    slug: 'viscosity-formula',
    name: "Newton's Law of Viscosity",
    expression: 'F = ηA(v/d)',
    meaning: 'The tangential force needed to drag one layer of fluid over another, at speed v, across a fluid layer of thickness d — proportional to how "thick" (viscous) the fluid is.',
    variables: [
      { symbol: 'F', meaning: 'tangential (viscous) force, in newtons (N)' },
      { symbol: 'η', meaning: 'dynamic viscosity of the fluid, in pascal-seconds (Pa·s)' },
      { symbol: 'A', meaning: 'area of the moving layer in contact with the fluid, in square metres (m²)' },
      { symbol: 'v', meaning: 'relative speed between the two layers, in metres per second (m/s)' },
      { symbol: 'd', meaning: 'perpendicular distance (thickness) between the two layers, in metres (m)' },
    ],
    whenToUse: 'Whenever the internal friction force within a flowing fluid, or between a fluid and a moving surface, needs to be found.',
    relatedConceptSlugs: ['viscosity-and-fluid-friction'],
  },
  'surface-tension-formula': {
    slug: 'surface-tension-formula',
    name: 'Surface Tension',
    expression: 'γ = F / L',
    meaning: 'Surface tension is the force per unit length acting along the surface of a liquid, caused by the liquid\'s molecules pulling on each other more strongly than they are pulled by the air above.',
    variables: [
      { symbol: 'γ', meaning: 'surface tension coefficient, in newtons per metre (N/m)' },
      { symbol: 'F', meaning: 'force acting along the liquid surface, in newtons (N)' },
      { symbol: 'L', meaning: 'length of the contact line along which the force acts, in metres (m)' },
    ],
    whenToUse: 'Whenever the force needed to stretch, break, or hold together a liquid surface (like a soap film) needs to be found from the liquid\'s surface tension.',
    relatedConceptSlugs: ['surface-tension'],
  },
  'capillary-rise-formula': {
    slug: 'capillary-rise-formula',
    name: 'Capillary Rise (or Fall)',
    expression: 'h = 2γcosθ / (ρgr)',
    meaning: 'How high (or low) a liquid rises inside a narrow tube, due to the balance between surface tension pulling the liquid up the tube walls and gravity pulling it back down.',
    variables: [
      { symbol: 'h', meaning: 'height the liquid rises (or falls) in the tube, in metres (m)' },
      { symbol: 'γ', meaning: 'surface tension coefficient of the liquid, in newtons per metre (N/m)' },
      { symbol: 'θ', meaning: 'contact angle between the liquid and the tube wall, in degrees' },
      { symbol: 'ρ', meaning: 'density of the liquid, in kilograms per cubic metre (kg/m³)' },
      { symbol: 'r', meaning: 'radius of the tube, in metres (m)' },
    ],
    whenToUse: 'Whenever the height a liquid rises or falls inside a thin (capillary) tube needs to be predicted.',
    relatedConceptSlugs: ['capillarity'],
  },
};
