import type { Assessment } from '@/types/content';

export const chapter7RefractionAssessment: Assessment = {
  id: 'refraction-of-light-assessment',
  questions: [
    {
      id: 'rl-a1',
      part: 'concept',
      conceptSlug: 'the-nature-of-light',
      conceptTitle: 'The Nature of Light',
      question: {
        id: 'rl-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is meant by "wave-particle duality" of light?',
        options: [
          { id: 'a', text: 'Light exhibits both wave-like and particle-like behaviour depending on the situation.' },
          { id: 'b', text: 'Light is purely a particle.' },
          { id: 'c', text: 'Light is purely a wave.' },
          { id: 'd', text: 'Light has no measurable properties.' },
        ],
        correctOptionId: 'a',
        hints: ['Both interference and the photoelectric effect are real phenomena.'],
        explanation: 'Light shows both wave and particle behaviour, depending on the experiment or phenomenon.',
      },
    },
    {
      id: 'rl-a2',
      part: 'concept',
      conceptSlug: 'refraction-at-a-boundary',
      conceptTitle: 'Refraction of Light',
      question: {
        id: 'rl-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What causes light to bend when entering a new medium at an angle?',
        options: [
          { id: 'a', text: 'A change in speed at the boundary, causing the wavefront to pivot.' },
          { id: 'b', text: 'Light never actually bends.' },
          { id: 'c', text: 'A change in the light\'s colour.' },
          { id: 'd', text: 'Refraction only happens in a vacuum.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about a wavefront crossing a boundary at an angle.'],
        explanation: 'The change in speed at the boundary causes the wavefront to pivot, producing refraction.',
      },
    },
    {
      id: 'rl-a3',
      part: 'concept',
      conceptSlug: 'refractive-index-b-level',
      conceptTitle: 'Refractive Index',
      question: {
        id: 'rl-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What does a HIGHER refractive index indicate about a medium?',
        options: [
          { id: 'a', text: 'Light travels more SLOWLY in that medium.' },
          { id: 'b', text: 'Light travels more quickly in that medium.' },
          { id: 'c', text: 'The medium is transparent to all wavelengths equally.' },
          { id: 'd', text: 'Refractive index has no relationship to light speed.' },
        ],
        correctOptionId: 'a',
        hints: ['n = c/v — what happens to v as n increases?'],
        explanation: 'A higher refractive index (n = c/v) means a lower speed of light (v) in that medium.',
      },
    },
    {
      id: 'rl-b1',
      part: 'formula-application',
      conceptSlug: 'laws-of-refraction',
      conceptTitle: 'Laws of Refraction',
      question: {
        id: 'rl-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Light travels from air (n₁ = 1.00) into a medium (n₂ = 1.6) at 35° (sin35° ≈ 0.574). Find sinθ₂.',
        hints: ['n₁ sinθ₁ = n₂ sinθ₂.'],
        correctAnswer: 0.359,
        tolerance: 0.02,
        explanation: 'sinθ₂ = (1.00 × 0.574)/1.6 ≈ 0.359.',
      },
    },
    {
      id: 'rl-b2',
      part: 'formula-application',
      conceptSlug: 'refractive-index-b-level',
      conceptTitle: 'Refractive Index',
      question: {
        id: 'rl-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the speed of light in a medium with refractive index 1.6 (c = 3 × 10⁸ m/s).',
        hints: ['v = c/n.'],
        correctAnswer: 1.875e8,
        tolerance: 0.02e8,
        unit: 'm/s',
        explanation: 'v = (3 × 10⁸)/1.6 ≈ 1.875 × 10⁸ m/s.',
      },
    },
    {
      id: 'rl-c1',
      part: 'problem-solving',
      conceptSlug: 'critical-angle-and-total-internal-reflection',
      conceptTitle: 'Critical Angle and Total Internal Reflection',
      question: {
        id: 'rl-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A medium has refractive index 1.4. Find its critical angle for light travelling into air.',
        hints: ['sinθc = 1/n.'],
        correctAnswer: 45.6,
        tolerance: 0.5,
        unit: '°',
        explanation: 'sinθc = 1/1.4 ≈ 0.714. θc = sin⁻¹(0.714) ≈ 45.6°.',
      },
    },
    {
      id: 'rl-c2',
      part: 'problem-solving',
      conceptSlug: 'velocity-of-light',
      conceptTitle: 'Velocity of Light',
      question: {
        id: 'rl-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Blue light has a wavelength of 450 nm (4.5 × 10⁻⁷ m). Find its frequency in a vacuum (c = 3 × 10⁸ m/s).',
        hints: ['f = c/λ.'],
        correctAnswer: 6.67e14,
        tolerance: 0.1e14,
        unit: 'Hz',
        explanation: 'f = (3 × 10⁸)/(4.5 × 10⁻⁷) ≈ 6.67 × 10¹⁴ Hz.',
      },
    },
    {
      id: 'rl-d1',
      part: 'real-life-application',
      conceptSlug: 'critical-angle-and-total-internal-reflection',
      conceptTitle: 'Critical Angle and Total Internal Reflection',
      question: {
        id: 'rl-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How do optical fibres keep light signals trapped inside the fibre core over long distances?',
        options: [
          { id: 'a', text: 'Light repeatedly strikes the core-cladding boundary beyond the critical angle, undergoing total internal reflection.' },
          { id: 'b', text: 'A physical mirror is placed every few metres inside the fibre.' },
          { id: 'c', text: 'The fibre core is completely opaque.' },
          { id: 'd', text: 'Total internal reflection has no role in optical fibres.' },
        ],
        correctOptionId: 'a',
        hints: ['This relies directly on the critical angle concept.'],
        explanation: 'Light striking the core-cladding boundary beyond the critical angle undergoes total internal reflection repeatedly, keeping it trapped and travelling along the fibre.',
      },
    },
    {
      id: 'rl-d2',
      part: 'real-life-application',
      conceptSlug: 'refractive-index-b-level',
      conceptTitle: 'Refractive Index',
      question: {
        id: 'rl-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "Why does diamond sparkle more brilliantly than a glass imitation of similar cut?",
        options: [
          { id: 'a', text: "Diamond's much higher refractive index causes light to bend and reflect more dramatically inside it." },
          { id: 'b', text: 'Diamond has a lower refractive index than glass.' },
          { id: 'c', text: 'Refractive index has no effect on sparkle.' },
          { id: 'd', text: 'Diamond does not actually refract light.' },
        ],
        correctOptionId: 'a',
        hints: ["Compare diamond's refractive index (2.42) to glass's (about 1.5)."],
        explanation: "Diamond's unusually high refractive index causes stronger internal bending and reflection of light, contributing to its brilliant sparkle.",
      },
    },
    {
      id: 'rl-e1',
      part: 'challenge',
      conceptSlug: 'critical-angle-and-total-internal-reflection',
      conceptTitle: 'Critical Angle and Total Internal Reflection',
      question: {
        id: 'rl-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why can total internal reflection only occur when light travels from a denser medium toward a less dense one, never the reverse?',
        options: [
          { id: 'a', text: "Going from less dense to denser, Snell's law always gives a valid (smaller) refraction angle, so light always refracts out — sinθ₂ can never exceed 1 in that direction." },
          { id: 'b', text: 'Total internal reflection can happen in either direction equally.' },
          { id: 'c', text: 'Refractive index is irrelevant to this direction dependence.' },
          { id: 'd', text: 'Light traveling into a denser medium always reflects, never refracts.' },
        ],
        correctOptionId: 'a',
        hints: ["Consider what Snell's law predicts for sinθ₂ in each direction."],
        explanation: 'Going from less dense to denser, the refraction angle is always smaller than the incidence angle, so sinθ₂ never exceeds 1 — light always refracts out, so total internal reflection cannot occur in this direction.',
      },
    },
  ],
};
