import type { Assessment } from '@/types/content';

export const chapter9Assessment: Assessment = {
  id: 'circles-assessment',
  questions: [
    {
      id: 'circ-a1',
      part: 'concept',
      conceptSlug: 'central-and-inscribed-angles',
      conceptTitle: 'Central and Inscribed Angles',
      question: {
        id: 'circ-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'How does an inscribed angle relate to the central angle subtending the same arc?',
        options: [
          { id: 'a', text: 'The inscribed angle is half the central angle' },
          { id: 'b', text: 'The inscribed angle equals the central angle' },
          { id: 'c', text: 'The inscribed angle is double the central angle' },
          { id: 'd', text: 'There is no fixed relationship' },
        ],
        correctOptionId: 'a',
        hints: ['Inscribed angle = (1/2) × central angle.'],
        explanation: 'The inscribed angle is always exactly half the central angle, for the same arc.',
      },
    },
    {
      id: 'circ-a2',
      part: 'concept',
      conceptSlug: 'angle-in-a-semicircle',
      conceptTitle: 'Angle in a Semicircle',
      question: {
        id: 'circ-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'An angle is inscribed in a semicircle. What is its measure?',
        options: [
          { id: 'a', text: '90°' },
          { id: 'b', text: '180°' },
          { id: 'c', text: '45°' },
          { id: 'd', text: 'It depends on the triangle' },
        ],
        correctOptionId: 'a',
        hints: ['This is a special case of the inscribed angle theorem.'],
        explanation: 'Any angle inscribed in a semicircle is always exactly 90°.',
      },
    },
    {
      id: 'circ-b1',
      part: 'formula-application',
      conceptSlug: 'cyclic-quadrilateral-angles',
      conceptTitle: 'Angles of a Cyclic Quadrilateral',
      question: {
        id: 'circ-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In cyclic quadrilateral WXYZ, ∠W = 112°. Find ∠Y.',
        hints: ['∠W and ∠Y are opposite angles.'],
        correctAnswer: 68,
        explanation: '180 − 112 = 68°.',
      },
    },
    {
      id: 'circ-b2',
      part: 'formula-application',
      conceptSlug: 'perpendicular-from-centre-to-a-chord',
      conceptTitle: 'The Perpendicular from the Centre to a Chord',
      question: {
        id: 'circ-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A circle has radius 17. A chord is 8 units from the centre. Find the chord\'s length.',
        hints: ['half-chord² = 17² − 8².'],
        correctAnswer: 30,
        explanation: '√(289−64) = √225 = 15. Full chord = 2×15 = 30.',
      },
    },
    {
      id: 'circ-c1',
      part: 'problem-solving',
      conceptSlug: 'the-intersecting-chords-theorem',
      conceptTitle: 'The Intersecting Chords Theorem',
      question: {
        id: 'circ-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Chords intersect at P. PA=10, PC=6, PB=5. Find PD.',
        hints: ['PA × PC = PB × PD.'],
        correctAnswer: 12,
        explanation: '10×6 = 5×PD → 60 = 5×PD → PD=12.',
      },
    },
    {
      id: 'circ-c2',
      part: 'problem-solving',
      conceptSlug: 'central-and-inscribed-angles',
      conceptTitle: 'Central and Inscribed Angles',
      question: {
        id: 'circ-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two inscribed angles subtend the same arc. One measures 42°. What is the other?',
        hints: ['Inscribed angles subtending the same arc are always equal to each other.'],
        correctAnswer: 42,
        explanation: 'Inscribed angles subtending the same arc are always equal (both equal half the central angle).',
      },
    },
    {
      id: 'circ-d1',
      part: 'real-life-application',
      conceptSlug: 'angle-in-a-semicircle',
      conceptTitle: 'Angle in a Semicircle',
      question: {
        id: 'circ-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A carpenter draws a circle using a beam as diameter, then marks any point C on the circle. Why does connecting C to both beam ends always form a right angle?',
        options: [
          { id: 'a', text: 'Because the beam is a diameter, so its arc is 180°, making any inscribed angle on it exactly 90°.' },
          { id: 'b', text: 'Because circles always contain right angles.' },
          { id: 'c', text: 'Only if C is exactly at the top of the circle.' },
          { id: 'd', text: 'It is a coincidence specific to that beam length.' },
        ],
        correctOptionId: 'a',
        hints: ['This is the "angle in a semicircle" rule.'],
        explanation: 'A diameter subtends a 180° arc, so any inscribed angle on that arc is half of 180°, always 90°.',
      },
    },
    {
      id: 'circ-d2',
      part: 'real-life-application',
      conceptSlug: 'equal-chords-and-equal-arcs',
      conceptTitle: 'Equal Chords and Equal Arcs',
      question: {
        id: 'circ-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A gear designer confirms two slot openings (chords) on a circular gear are the same distance from the centre. What can be concluded?',
        options: [
          { id: 'a', text: 'The two slot openings (chords) are equal in length.' },
          { id: 'b', text: 'The slots must be adjacent.' },
          { id: 'c', text: 'Nothing about the slot lengths can be concluded.' },
          { id: 'd', text: 'One slot must be twice as long as the other.' },
        ],
        correctOptionId: 'a',
        hints: ['Equal distance from the centre implies equal chord length.'],
        explanation: 'Equal distance from the centre (same circle) always means equal chord length.',
      },
    },
    {
      id: 'circ-e1',
      part: 'challenge',
      conceptSlug: 'perpendicular-from-centre-to-a-chord',
      conceptTitle: 'The Perpendicular from the Centre to a Chord',
      question: {
        id: 'circ-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A chord of length 24 is drawn in a circle of radius 13. Find the chord\'s distance from the centre.',
        hints: ['half-chord = 12.', 'distance² = 13² − 12².'],
        correctAnswer: 5,
        explanation: '√(169−144) = √25 = 5.',
      },
    },
    {
      id: 'circ-e2',
      part: 'challenge',
      conceptSlug: 'cyclic-quadrilateral-angles',
      conceptTitle: 'Angles of a Cyclic Quadrilateral',
      question: {
        id: 'circ-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why must opposite angles of a cyclic quadrilateral sum to 180°?',
        options: [
          { id: 'a', text: 'Each is an inscribed angle whose arc, together with the other\'s arc, makes the full 360° circle, and each angle is half its arc.' },
          { id: 'b', text: 'All quadrilaterals have angles summing to 360°, split evenly.' },
          { id: 'c', text: 'Opposite angles are always equal in any quadrilateral.' },
          { id: 'd', text: 'It only works for squares.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about the two arcs the opposite vertices divide the circle into.'],
        explanation: 'The two opposite inscribed angles subtend arcs that together cover the whole circle (360°), so their angle sum is half of 360°, which is 180°.',
      },
    },
  ],
};
