import type { Assessment } from '@/types/content';

export const chapter3BAssessment: Assessment = {
  id: 'elementary-functions-and-transformations-assessment',
  questions: [
    {
      id: 'eft-a1',
      part: 'concept',
      conceptSlug: 'the-elementary-function-family',
      conceptTitle: 'The Elementary Function Family',
      question: {
        id: 'eft-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which family does y = √x belong to?',
        options: [
          { id: 'a', text: 'Square root' },
          { id: 'b', text: 'Reciprocal' },
          { id: 'c', text: 'Exponential' },
          { id: 'd', text: 'Cubic' },
        ],
        correctOptionId: 'a',
        hints: ['x is under a root.'],
        explanation: 'y = √x is the basic square root function.',
      },
    },
    {
      id: 'eft-a2',
      part: 'concept',
      conceptSlug: 'reflections-of-functions',
      conceptTitle: 'Reflections of Functions',
      question: {
        id: 'eft-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which equation reflects y=f(x) over the y-axis?',
        options: [
          { id: 'a', text: 'y = f(−x)' },
          { id: 'b', text: 'y = −f(x)' },
          { id: 'c', text: 'y = f(x) − 1' },
          { id: 'd', text: 'y = 2f(x)' },
        ],
        correctOptionId: 'a',
        hints: ['Negate the input for a y-axis reflection.'],
        explanation: 'y=f(−x) negates the input, reflecting over the y-axis.',
      },
    },
    {
      id: 'eft-b1',
      part: 'formula-application',
      conceptSlug: 'the-exponential-function',
      conceptTitle: 'The Exponential Function',
      question: {
        id: 'eft-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'For y = 2·3ˣ, find y when x = 3.',
        hints: ['3³ = 27.'],
        correctAnswer: 54,
        explanation: 'y = 2 × 27 = 54.',
      },
    },
    {
      id: 'eft-b2',
      part: 'formula-application',
      conceptSlug: 'translations-of-functions',
      conceptTitle: 'Translations of Functions',
      question: {
        id: 'eft-b2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'The graph of y = x³ is shifted 2 right and 1 down. What is the new equation?',
        options: [
          { id: 'a', text: 'y = (x−2)³ − 1' },
          { id: 'b', text: 'y = (x+2)³ − 1' },
          { id: 'c', text: 'y = (x−2)³ + 1' },
          { id: 'd', text: 'y = x³ − 2 − 1' },
        ],
        correctOptionId: 'a',
        hints: ['Right shift: h=2, positive.'],
        explanation: 'h=2, k=−1, giving y=(x−2)³−1.',
      },
    },
    {
      id: 'eft-c1',
      part: 'problem-solving',
      conceptSlug: 'the-square-root-function',
      conceptTitle: 'The Square Root Function',
      question: {
        id: 'eft-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'For y = √(x − 4), find y when x = 13.',
        hints: ['√(13−4) = √9.'],
        correctAnswer: 3,
        explanation: '√9 = 3.',
      },
    },
    {
      id: 'eft-c2',
      part: 'problem-solving',
      conceptSlug: 'stretches-and-compressions-of-functions',
      conceptTitle: 'Stretches and Compressions of Functions',
      question: {
        id: 'eft-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'The point (6, 10) lies on y=f(x). What point lies on y=f(x/2)?',
        options: [
          { id: 'a', text: '(12, 10)' },
          { id: 'b', text: '(3, 10)' },
          { id: 'c', text: '(6, 5)' },
          { id: 'd', text: '(6, 20)' },
        ],
        correctOptionId: 'a',
        hints: ['b=1/2 here, so it stretches horizontally (since |b|<1).', 'new x = original x / b = 6 / (1/2).'],
        explanation: 'For y=f(bx), new x = old x / b = 6 / 0.5 = 12; y stays 10.',
      },
    },
    {
      id: 'eft-d1',
      part: 'real-life-application',
      conceptSlug: 'the-reciprocal-function',
      conceptTitle: 'The Reciprocal Function',
      question: {
        id: 'eft-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Travel time = 120/speed (distance 120 km). Find the travel time in hours at speed 40 km/h.',
        hints: ['120/40.'],
        correctAnswer: 3,
        explanation: '120/40 = 3 hours.',
      },
    },
    {
      id: 'eft-d2',
      part: 'real-life-application',
      conceptSlug: 'the-exponential-function',
      conceptTitle: 'The Exponential Function',
      question: {
        id: 'eft-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A bacteria population doubles every hour, starting at 50. Find the population after 3 hours (Population = 50·2ᵗ).',
        hints: ['50 × 2³.'],
        correctAnswer: 400,
        explanation: '50 × 8 = 400.',
      },
    },
    {
      id: 'eft-e1',
      part: 'challenge',
      conceptSlug: 'combining-transformations',
      conceptTitle: 'Combining Transformations',
      question: {
        id: 'eft-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'What is the vertex of y = −4(x + 3)² + 7, viewed as a transformation of y = x²?',
        options: [
          { id: 'a', text: '(−3, 7)' },
          { id: 'b', text: '(3, 7)' },
          { id: 'c', text: '(−3, −7)' },
          { id: 'd', text: '(−4, 7)' },
        ],
        correctOptionId: 'a',
        hints: ['x+3 = x−(−3), so h=−3.'],
        explanation: 'h=−3, k=7, so the vertex (0,0) moves to (−3,7).',
      },
    },
    {
      id: 'eft-e2',
      part: 'challenge',
      conceptSlug: 'the-cubic-function',
      conceptTitle: 'The Cubic Function',
      question: {
        id: 'eft-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why is y = x³ described as an "odd" function?',
        options: [
          { id: 'a', text: 'Because f(−x) = −f(x) for every x — it is symmetric about the origin.' },
          { id: 'b', text: 'Because its exponent, 3, is an odd number.' },
          { id: 'c', text: 'Because it only produces odd output values.' },
          { id: 'd', text: 'Because its graph has an odd number of turns.' },
        ],
        correctOptionId: 'a',
        hints: ['"Odd function" is a formal property about symmetry, not about the exponent being odd.'],
        explanation: 'A function is "odd" specifically when f(−x)=−f(x) for every x, giving origin symmetry — true for y=x³, though the name does happen to echo its odd exponent.',
      },
    },
  ],
};
