import type { Assessment } from '@/types/content';

export const chapter6AHeatAssessment: Assessment = {
  id: 'heat-and-temperature-assessment',
  questions: [
    {
      id: 'heat-a1',
      part: 'concept',
      conceptSlug: 'heat-and-temperature-a-level',
      conceptTitle: 'Heat and Temperature',
      question: {
        id: 'heat-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Two blocks of the same metal, one twice the mass of the other, are both heated by the same 10°C rise. Which needs MORE heat energy?',
        hints: ['Heat energy depends on mass as well as temperature change.'],
        options: [
          { id: 'a', text: 'The more massive block' },
          { id: 'b', text: 'The less massive block' },
          { id: 'c', text: 'Both need exactly the same heat energy' },
          { id: 'd', text: 'Neither needs any heat energy' },
        ],
        correctOptionId: 'a',
        explanation: 'Since Q = mcΔT, a greater mass needs proportionally more heat energy for the same temperature rise.',
      },
    },
    {
      id: 'heat-a2',
      part: 'concept',
      conceptSlug: 'types-of-thermometer-a-level',
      conceptTitle: 'Types of Thermometer',
      question: {
        id: 'heat-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which thermometer type is best suited to measuring the temperature of molten steel from a safe distance?',
        hints: ['Think about which type needs no physical contact.'],
        options: [
          { id: 'a', text: 'Liquid-in-glass thermometer' },
          { id: 'b', text: 'Infrared thermometer' },
          { id: 'c', text: 'A standard mercury thermometer' },
          { id: 'd', text: 'None of these can measure such high temperatures' },
        ],
        correctOptionId: 'b',
        explanation: 'An infrared thermometer measures emitted radiation with no contact needed, making it ideal for extremely hot or dangerous objects like molten steel.',
      },
    },
    {
      id: 'heat-b1',
      part: 'formula-application',
      conceptSlug: 'specific-heat-capacity-a-level',
      conceptTitle: 'Specific Heat Capacity',
      question: {
        id: 'heat-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the heat energy needed to raise the temperature of 3 kg of water by 15°C (c = 4200 J/(kg·K)).',
        hints: ['Q = mcΔT.', '3 × 4200 × 15.'],
        correctAnswer: 189000,
        unit: 'J',
        explanation: 'Q = 3 × 4200 × 15 = 189,000 J.',
      },
    },
    {
      id: 'heat-b2',
      part: 'formula-application',
      conceptSlug: 'temperature-scales-a-level',
      conceptTitle: 'Temperature Scales',
      question: {
        id: 'heat-b2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Convert 50°C to kelvin.',
        hints: ['T(K) = T(°C) + 273.', '50 + 273.'],
        correctAnswer: 323,
        unit: 'K',
        explanation: 'T(K) = 50 + 273 = 323 K.',
      },
    },
    {
      id: 'heat-c1',
      part: 'problem-solving',
      conceptSlug: 'thermal-expansion-a-level',
      conceptTitle: 'Thermal Expansion of Substances',
      question: {
        id: 'heat-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A copper wire 10 m long at 5°C is heated to 45°C. Find its increase in length (α for copper = 1.7 × 10⁻⁵ K⁻¹).',
        hints: ['ΔT = 45 − 5 = 40.', 'ΔL = L₀αΔT.'],
        correctAnswer: 0.0068,
        unit: 'm',
        explanation: 'ΔT = 40. ΔL = 10 × 1.7×10⁻⁵ × 40 = 0.0068 m (6.8 mm).',
      },
    },
    {
      id: 'heat-c2',
      part: 'problem-solving',
      conceptSlug: 'specific-heat-capacity-a-level',
      conceptTitle: 'Specific Heat Capacity',
      question: {
        id: 'heat-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: '25,200 J of heat raises the temperature of an unknown mass of water (c = 4200 J/(kg·K)) by 6°C. Find the mass of water.',
        hints: ['Rearrange Q = mcΔT to m = Q/(cΔT).', '25,200 / (4200 × 6).'],
        correctAnswer: 1,
        unit: 'kg',
        explanation: 'm = Q/(cΔT) = 25,200/(4200×6) = 25,200/25,200 = 1 kg.',
      },
    },
    {
      id: 'heat-d1',
      part: 'real-life-application',
      conceptSlug: 'temperature-scales-a-level',
      conceptTitle: 'Temperature Scales',
      question: {
        id: 'heat-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Normal human body temperature is about 37°C. Convert this to degrees Fahrenheit.',
        hints: ['T(°F) = (9/5)T(°C) + 32.', '(9/5)×37 + 32.'],
        correctAnswer: 98.6,
        tolerance: 0.1,
        unit: '°F',
        explanation: 'T(°F) = (9/5)×37 + 32 = 66.6 + 32 = 98.6°F.',
      },
    },
    {
      id: 'heat-d2',
      part: 'real-life-application',
      conceptSlug: 'types-of-thermometer-a-level',
      conceptTitle: 'Types of Thermometer',
      question: {
        id: 'heat-d2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why can\'t a normal mercury-in-glass thermometer be used to measure liquid nitrogen at −196°C?',
        hints: ["Consider mercury's own freezing point."],
        options: [
          { id: 'a', text: 'Mercury freezes solid at about −39°C, well above −196°C' },
          { id: 'b', text: 'Glass cannot exist below 0°C' },
          { id: 'c', text: 'Mercury thermometers can only measure positive temperatures' },
          { id: 'd', text: 'There is no actual limitation — it would work fine' },
        ],
        correctOptionId: 'a',
        explanation: "Mercury freezes solid at about −39°C, so it can no longer expand or contract to indicate temperature well before reaching −196°C — a different thermometer type is needed.",
      },
    },
    {
      id: 'heat-e1',
      part: 'challenge',
      conceptSlug: 'thermal-expansion-a-level',
      conceptTitle: 'Thermal Expansion of Substances',
      question: {
        id: 'heat-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A brass rod is 2.5 m long at 20°C. Heated to 120°C, its length increases by 2.5 mm (0.0025 m). Find the coefficient of linear expansion α for brass.',
        hints: ['Rearrange ΔL = L₀αΔT to α = ΔL/(L₀ΔT).', 'ΔT = 120 − 20 = 100.'],
        correctAnswer: 0.00001,
        tolerance: 0.000001,
        unit: 'K⁻¹',
        explanation: 'α = ΔL/(L₀ΔT) = 0.0025/(2.5×100) = 0.0025/250 = 1×10⁻⁵ K⁻¹.',
      },
    },
    {
      id: 'heat-e2',
      part: 'challenge',
      conceptSlug: 'heat-and-temperature-a-level',
      conceptTitle: 'Heat and Temperature',
      question: {
        id: 'heat-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: '300 g of water at 90°C is mixed with 700 g of water at 20°C. Ignoring heat loss, find the final equilibrium temperature (heat lost by the hot water equals heat gained by the cold water).',
        hints: ['300×(90 − T) = 700×(T − 20), since both are water (same c, which cancels).', 'Expand and solve for T.'],
        correctAnswer: 41,
        unit: '°C',
        explanation: '300(90−T) = 700(T−20) → 27,000 − 300T = 700T − 14,000 → 41,000 = 1000T → T = 41°C.',
      },
    },
  ],
};
