import type { Assessment } from '@/types/content';

export const chapter5Assessment: Assessment = {
  id: 'quadratic-functions-assessment',
  questions: [
    {
      id: 'quad-a1',
      part: 'concept',
      conceptSlug: 'effect-of-a-on-the-parabola',
      conceptTitle: 'The Effect of a on the Graph of y = ax²',
      question: {
        id: 'quad-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a negative value of a do to the graph of y = ax²?',
        options: [
          { id: 'a', text: 'Makes it open downward' },
          { id: 'b', text: 'Makes it open upward' },
          { id: 'c', text: 'Makes it a straight line' },
          { id: 'd', text: 'Has no effect on the graph' },
        ],
        correctOptionId: 'a',
        hints: ['Compare y=x² to y=-x².'],
        explanation: 'A negative a flips the parabola to open downward, giving it a maximum instead of a minimum.',
      },
    },
    {
      id: 'quad-a2',
      part: 'concept',
      conceptSlug: 'the-discriminant',
      conceptTitle: 'The Discriminant',
      question: {
        id: 'quad-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'If a quadratic\'s discriminant is 0, how many real roots does it have?',
        options: [
          { id: 'a', text: 'Exactly one (repeated) root' },
          { id: 'b', text: 'Two distinct roots' },
          { id: 'c', text: 'No real roots' },
          { id: 'd', text: 'Three roots' },
        ],
        correctOptionId: 'a',
        hints: ['D = 0 means the square root term vanishes.'],
        explanation: 'D = 0 makes the ± term in the quadratic formula disappear, leaving exactly one repeated root.',
      },
    },
    {
      id: 'quad-b1',
      part: 'formula-application',
      conceptSlug: 'the-vertex-formula-and-general-quadratic-graphs',
      conceptTitle: 'The Vertex Formula and Graphing y = ax² + bx + c',
      question: {
        id: 'quad-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What is the vertex of y = x² + 6x + 5?',
        options: [
          { id: 'a', text: '(−3, −4)' },
          { id: 'b', text: '(3, −4)' },
          { id: 'c', text: '(−3, 4)' },
          { id: 'd', text: '(−6, 5)' },
        ],
        correctOptionId: 'a',
        hints: ['x = −b/2a = −6/2.'],
        explanation: 'x = −3, and y = 9 − 18 + 5 = −4, so the vertex is (−3, −4).',
      },
    },
    {
      id: 'quad-b2',
      part: 'formula-application',
      conceptSlug: 'the-quadratic-formula',
      conceptTitle: 'The Quadratic Formula',
      question: {
        id: 'quad-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Solve x² + 2x − 8 = 0 for the larger root.',
        hints: ['a=1, b=2, c=-8.', 'D = 4 + 32 = 36.'],
        correctAnswer: 2,
        explanation: 'x = (−2 ± 6)/2, giving x = 2 or x = −4. The larger root is 2.',
      },
    },
    {
      id: 'quad-c1',
      part: 'problem-solving',
      conceptSlug: 'the-discriminant',
      conceptTitle: 'The Discriminant',
      question: {
        id: 'quad-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the discriminant of 3x² − 2x + 4 = 0.',
        hints: ['D = b² − 4ac = (−2)² − 4(3)(4).'],
        correctAnswer: -44,
        explanation: 'D = 4 − 48 = −44.',
      },
    },
    {
      id: 'quad-c2',
      part: 'problem-solving',
      conceptSlug: 'solving-quadratic-inequalities',
      conceptTitle: 'Solving Quadratic Inequalities',
      question: {
        id: 'quad-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Solve x² − 5x + 6 ≤ 0.',
        options: [
          { id: 'a', text: '2 ≤ x ≤ 3' },
          { id: 'b', text: 'x ≤ 2 or x ≥ 3' },
          { id: 'c', text: 'x < 2' },
          { id: 'd', text: 'x > 3' },
        ],
        correctOptionId: 'a',
        hints: ['Roots are x=2 and x=3.', 'An upward parabola is ≤ 0 between its roots (inclusive, since the inequality is ≤).'],
        explanation: '(x−2)(x−3) ≤ 0 holds for 2 ≤ x ≤ 3, including the roots since the inequality is non-strict.',
      },
    },
    {
      id: 'quad-d1',
      part: 'real-life-application',
      conceptSlug: 'graphing-y-negative-x-squared-plus-bx-plus-c',
      conceptTitle: 'Graphing y = −x² + bx + c',
      question: {
        id: 'quad-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A ball\'s height is h(t) = −t² + 8t (t in seconds). At what time does it reach its maximum height?',
        hints: ['Find the vertex: t = −b/2a with a=-1, b=8.'],
        correctAnswer: 4,
        explanation: 't = −8/(2×−1) = 4 seconds.',
      },
    },
    {
      id: 'quad-d2',
      part: 'real-life-application',
      conceptSlug: 'the-quadratic-formula',
      conceptTitle: 'The Quadratic Formula',
      question: {
        id: 'quad-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A ball\'s height is h(t) = −5t² + 20t + 1. Why is the quadratic formula the best tool to find when it lands (h=0)?',
        options: [
          { id: 'a', text: '−5t² + 20t + 1 = 0 does not factor into nice integers, but the formula always works.' },
          { id: 'b', text: 'The quadratic formula only works for real-life problems.' },
          { id: 'c', text: 'Factoring would give a negative time.' },
          { id: 'd', text: 'The discriminant is always zero for real-life problems.' },
        ],
        correctOptionId: 'a',
        hints: ['Try factoring −5t²+20t+1 — do the numbers work out cleanly?'],
        explanation: 'Since the equation does not factor into nice integers, the quadratic formula is the reliable, general method.',
      },
    },
    {
      id: 'quad-e1',
      part: 'challenge',
      conceptSlug: 'the-vertex-formula-and-general-quadratic-graphs',
      conceptTitle: 'The Vertex Formula and Graphing y = ax² + bx + c',
      question: {
        id: 'quad-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A quadratic has vertex (2, −5) and passes through (0, 3). What is a? (Hint: use y = a(x−2)² − 5, then substitute (0,3).)',
        options: [
          { id: 'a', text: 'a = 2' },
          { id: 'b', text: 'a = 3' },
          { id: 'c', text: 'a = −2' },
          { id: 'd', text: 'a = 4' },
        ],
        correctOptionId: 'a',
        hints: ['3 = a(0−2)² − 5 → 8 = 4a.'],
        explanation: '3 = a(−2)² − 5 = 4a − 5, so 4a = 8, giving a = 2.',
      },
    },
    {
      id: 'quad-e2',
      part: 'challenge',
      conceptSlug: 'the-discriminant',
      conceptTitle: 'The Discriminant',
      question: {
        id: 'quad-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'For what value of k does x² + 6x + k = 0 have exactly one repeated root?',
        options: [
          { id: 'a', text: 'k = 9' },
          { id: 'b', text: 'k = 6' },
          { id: 'c', text: 'k = 36' },
          { id: 'd', text: 'k = 3' },
        ],
        correctOptionId: 'a',
        hints: ['Set D = 0: 6² − 4(1)(k) = 0.'],
        explanation: '36 − 4k = 0 gives k = 9.',
      },
    },
  ],
};
