-- Mubarak Science Medical Knowledge (MSMK) — Supabase schema.
--
-- Separate from the main app's storage (which is 100% localStorage — see
-- README/CLAUDE.md). MSMK needs server-side truth because: (1) registration
-- submissions must be visible to the site owner for manual payment review,
-- and (2) access-code + email login must be checked against real records,
-- not something shippable in client JS.
--
-- Run this in the Supabase SQL Editor (a fresh project, or a new schema in
-- an existing one — either is fine, table names are namespaced with
-- `msmk_`). As with the sibling Shwe-Pinya-Nandaw project: Supabase's
-- default is that a new table isn't reachable through the API without an
-- explicit `grant`, on top of RLS — RLS controls *which rows* a role sees,
-- `grant` controls whether the role can touch the table *at all*.
--
-- Access model:
--   msmk_registrations      anon: insert only               staff: full (review + status updates)
--   msmk_access_codes       anon: no access at all           staff: full (issue codes after verifying payment)
--   msmk_progress           anon: no access at all           staff: full (support/debugging)
--   msmk_assessment_attempts anon: no access at all          staff: full
--
-- Learner-facing reads/writes to msmk_access_codes / msmk_progress /
-- msmk_assessment_attempts all go through Next.js Route Handlers using the
-- SERVICE ROLE key (server-only env var, never shipped to the browser),
-- gated by a signed session cookie set at login. That keeps these three
-- tables completely closed to anon — nothing here depends on RLS correctly
-- modelling "only this learner's own row," which would otherwise need
-- Postgres session variables wired through PostgREST headers.

create extension if not exists pgcrypto;

-- 1. Registrations ------------------------------------------------------

create table if not exists public.msmk_registrations (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null,
  phone text not null,
  location text not null,
  bkash_transaction_id text not null,
  status text not null default 'pending' check (status in ('pending', 'verified', 'rejected')),
  staff_notes text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.msmk_registrations enable row level security;

create policy "anon can submit a registration"
  on public.msmk_registrations for insert
  to anon
  with check (true);

create policy "staff can review registrations"
  on public.msmk_registrations for select
  to authenticated
  using (true);

create policy "staff can update registrations"
  on public.msmk_registrations for update
  to authenticated
  using (true)
  with check (true);

create policy "staff can delete registrations"
  on public.msmk_registrations for delete
  to authenticated
  using (true);

grant insert on public.msmk_registrations to anon;
grant select, insert, update, delete on public.msmk_registrations to authenticated;

-- 2. Access codes ---------------------------------------------------------
-- Issued by hand by staff after verifying the bKash transaction against a
-- 'verified' registration. Code format: MSMK01, MSMK02, ... (staff's own
-- convention — not generated by this schema).

create table if not exists public.msmk_access_codes (
  code text primary key,
  email text not null,
  full_name text not null,
  registration_id uuid references public.msmk_registrations(id) on delete set null,
  active boolean not null default true,
  issued_at timestamptz not null default now()
);

create index if not exists msmk_access_codes_email_idx on public.msmk_access_codes (lower(email));

alter table public.msmk_access_codes enable row level security;

create policy "staff can manage access codes"
  on public.msmk_access_codes for all
  to authenticated
  using (true)
  with check (true);

grant select, insert, update, delete on public.msmk_access_codes to authenticated;
-- No grant to anon at all — learner login is validated server-side with
-- the service role key, which bypasses RLS/grants entirely.

-- 3. Per-module progress ---------------------------------------------------

create table if not exists public.msmk_progress (
  access_code text not null references public.msmk_access_codes(code) on delete cascade,
  module_id text not null,
  completed_sections text[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (access_code, module_id)
);

alter table public.msmk_progress enable row level security;

create policy "staff can view all progress"
  on public.msmk_progress for select
  to authenticated
  using (true);

grant select on public.msmk_progress to authenticated;
-- Reads/writes for the learner's own dashboard go through the service-role
-- Route Handler, not direct table access — see note above.

-- 4. Assessment attempts ---------------------------------------------------

create table if not exists public.msmk_assessment_attempts (
  access_code text not null references public.msmk_access_codes(code) on delete cascade,
  module_id text not null,
  score integer not null,
  total integer not null,
  percent integer not null,
  attempt_count integer not null default 1,
  last_attempt_at timestamptz not null default now(),
  primary key (access_code, module_id)
);

alter table public.msmk_assessment_attempts enable row level security;

create policy "staff can view all assessment attempts"
  on public.msmk_assessment_attempts for select
  to authenticated
  using (true);

grant select on public.msmk_assessment_attempts to authenticated;

-- 5. Convenience view for staff: overall course completion per learner ---

create or replace view public.msmk_learner_summary as
select
  ac.code as access_code,
  ac.full_name,
  ac.email,
  count(aa.module_id) as modules_attempted,
  coalesce(round(avg(aa.percent)), 0) as average_percent,
  (coalesce(round(avg(aa.percent)), 0) >= 80 and count(aa.module_id) >= 11) as certificate_unlocked
from public.msmk_access_codes ac
left join public.msmk_assessment_attempts aa on aa.access_code = ac.code
group by ac.code, ac.full_name, ac.email;

grant select on public.msmk_learner_summary to authenticated;
