import type { Assessment } from '@/types/content';

export const chapter9BAssessment: Assessment = {
  id: 'introduction-to-vectors-assessment',
  questions: [
    {
      id: 'vec-a1',
      part: 'concept',
      conceptSlug: 'scalar-and-vector-quantities',
      conceptTitle: 'Scalar and Vector Quantities',
      question: {
        id: 'vec-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which of the following is a vector quantity?',
        options: [
          { id: 'a', text: 'Temperature of 25°C' },
          { id: 'b', text: 'A force of 20 N acting downward' },
          { id: 'c', text: 'Mass of 10 kg' },
          { id: 'd', text: 'Speed of 40 km/h' },
        ],
        correctOptionId: 'b',
        hints: ['Look for the option with both a size AND a direction.'],
        explanation: 'A force of 20 N downward has magnitude and direction, so it is a vector. The others are scalars.',
      },
    },
    {
      id: 'vec-a2',
      part: 'concept',
      conceptSlug: 'representing-and-naming-vectors',
      conceptTitle: 'Representing and Naming Vectors',
      question: {
        id: 'vec-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does the notation →PQ mean?',
        options: [
          { id: 'a', text: 'A vector running from P to Q' },
          { id: 'b', text: 'A vector running from Q to P' },
          { id: 'c', text: 'The distance between P and Q, with no direction' },
          { id: 'd', text: 'The midpoint of P and Q' },
        ],
        correctOptionId: 'a',
        hints: ['Read vector notation left letter to right letter.'],
        explanation: '→PQ is a vector running from P (start) to Q (end).',
      },
    },
    {
      id: 'vec-b1',
      part: 'formula-application',
      conceptSlug: 'adding-and-subtracting-vectors-geometrically',
      conceptTitle: 'Adding and Subtracting Vectors Geometrically',
      question: {
        id: 'vec-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Vector a is 3 km east and vector b is 4 km north (perpendicular to a). Find the magnitude of a+b, in km.',
        hints: ['Use the Pythagorean theorem: |a+b| = √(3²+4²).'],
        correctAnswer: 5,
        explanation: '√(9+16) = √25 = 5.',
      },
    },
    {
      id: 'vec-b2',
      part: 'formula-application',
      conceptSlug: 'ratio-and-division-of-a-line-segment-using-vectors',
      conceptTitle: 'Ratio and Division of a Line Segment Using Vectors',
      question: {
        id: 'vec-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Point P divides segment AB such that AP:PB = 3:2. If OP = (a·OA + b·OB)/5, find the value of a.',
        hints: ['m=3, n=2 here.', 'OP = (n·OA + m·OB)/(m+n).'],
        correctAnswer: 2,
        explanation: 'm=3, n=2, so OP = (2·OA + 3·OB)/5, giving a=2.',
      },
    },
    {
      id: 'vec-c1',
      part: 'problem-solving',
      conceptSlug: 'using-vectors-to-prove-geometric-results',
      conceptTitle: 'Using Vectors to Prove Geometric Results',
      question: {
        id: 'vec-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In triangle XYZ, M is the midpoint of XY and N is the midpoint of XZ. If YZ = 22, find the length of MN.',
        hints: ['MN = ½YZ.'],
        correctAnswer: 11,
        explanation: 'MN = ½ × 22 = 11.',
      },
    },
    {
      id: 'vec-c2',
      part: 'problem-solving',
      conceptSlug: 'finding-a-vector-between-two-points',
      conceptTitle: 'Finding a Vector Between Two Points',
      question: {
        id: 'vec-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'OA has magnitude 10, and OB = −OA (opposite direction, same magnitude). Find the magnitude of AB.',
        hints: ['AB = OB − OA.'],
        correctAnswer: 20,
        explanation: 'AB = (−OA) − OA = −2OA, so |AB| = 2 × 10 = 20.',
      },
    },
    {
      id: 'vec-d1',
      part: 'real-life-application',
      conceptSlug: 'adding-and-subtracting-vectors-geometrically',
      conceptTitle: 'Adding and Subtracting Vectors Geometrically',
      question: {
        id: 'vec-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A plane has its own airspeed vector, and the wind has a separate velocity vector. How should a pilot find the plane\'s actual resultant velocity over the ground?',
        options: [
          { id: 'a', text: 'Add the two vectors using the Triangle Law' },
          { id: 'b', text: 'Add only their magnitudes' },
          { id: 'c', text: 'Ignore the wind vector entirely' },
          { id: 'd', text: 'Subtract the wind\'s magnitude from the airspeed\'s magnitude' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly what the Triangle Law of vector addition is for.'],
        explanation: 'Adding the airspeed and wind vectors with the Triangle Law gives the actual resultant ground velocity vector.',
      },
    },
    {
      id: 'vec-d2',
      part: 'real-life-application',
      conceptSlug: 'column-vector-notation-and-components',
      conceptTitle: 'Column Vector Notation and Components',
      question: {
        id: 'vec-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A game character moves each turn according to the vector (x, y) = (5, −3), where positive y means up. What does this movement look like?',
        options: [
          { id: 'a', text: '5 units right and 3 units down' },
          { id: 'b', text: '5 units left and 3 units up' },
          { id: 'c', text: '3 units right and 5 units down' },
          { id: 'd', text: '5 units up and 3 units right' },
        ],
        correctOptionId: 'a',
        hints: ['x is horizontal (positive = right); y is vertical (positive = up, so negative = down).'],
        explanation: 'x=5 means 5 right; y=−3 means 3 down (since positive y is up).',
      },
    },
    {
      id: 'vec-e1',
      part: 'challenge',
      conceptSlug: 'using-vectors-to-prove-geometric-results',
      conceptTitle: 'Using Vectors to Prove Geometric Results',
      question: {
        id: 'vec-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why must MN (joining the midpoints of two sides of a triangle) be parallel to the third side BC?',
        options: [
          { id: 'a', text: 'Because MN equals a positive scalar multiple (½) of BC, and scalar multiples of a vector never change its direction' },
          { id: 'b', text: 'Because all triangles have this property by coincidence' },
          { id: 'c', text: 'Because M and N are always at the same height' },
          { id: 'd', text: 'It is only true for right triangles' },
        ],
        correctOptionId: 'a',
        hints: ['Recall: MN = ½(c−b) = ½BC.'],
        explanation: 'MN = ½BC — a positive scalar multiple, which by definition points in the same direction as BC, i.e. is parallel to it.',
      },
    },
    {
      id: 'vec-e2',
      part: 'challenge',
      conceptSlug: 'magnitude-of-a-two-dimensional-vector',
      conceptTitle: 'Magnitude of a Two-Dimensional Vector',
      question: {
        id: 'vec-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A vector v = (x, y) has x = 5 and magnitude |v| = 13. Find y, given y > 0.',
        hints: ['|v|² = x² + y².', '13² − 5² = y².'],
        correctAnswer: 12,
        explanation: '169 − 25 = 144, √144 = 12.',
      },
    },
  ],
};
