import type { Assessment } from '@/types/content';

export const chapter7CAssessment: Assessment = {
  id: 'trigonometric-functions-and-graphs-assessment',
  questions: [
    {
      id: 'trigfn-a1',
      part: 'concept',
      conceptSlug: 'the-graph-of-sine',
      conceptTitle: 'The Graph of Sine',
      question: {
        id: 'trigfn-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find sin(π/2).',
        hints: ['This is the sine graph\'s maximum value.'],
        correctAnswer: 1,
        explanation: 'sin(π/2) = 1.',
      },
    },
    {
      id: 'trigfn-a2',
      part: 'concept',
      conceptSlug: 'the-graph-of-cosine',
      conceptTitle: 'The Graph of Cosine',
      question: {
        id: 'trigfn-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find cos(π).',
        hints: ['This is the cosine graph\'s minimum value.'],
        correctAnswer: -1,
        explanation: 'cos(π) = −1.',
      },
    },
    {
      id: 'trigfn-b1',
      part: 'formula-application',
      conceptSlug: 'the-graph-of-tangent',
      conceptTitle: 'The Graph of Tangent',
      question: {
        id: 'trigfn-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find tan(π/4).',
        hints: ['A standard reference angle value.'],
        correctAnswer: 1,
        explanation: 'tan(π/4) = 1.',
      },
    },
    {
      id: 'trigfn-b2',
      part: 'formula-application',
      conceptSlug: 'amplitude-period-and-phase-shift',
      conceptTitle: 'Amplitude, Period, and Phase Shift',
      question: {
        id: 'trigfn-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the amplitude of y = 7sin(3x).',
        hints: ['Amplitude = |A|.'],
        correctAnswer: 7,
        explanation: 'A=7, so amplitude=7.',
      },
    },
    {
      id: 'trigfn-c1',
      part: 'problem-solving',
      conceptSlug: 'graphs-of-cosecant-secant-and-cotangent',
      conceptTitle: 'Graphs of Cosecant, Secant, and Cotangent',
      question: {
        id: 'trigfn-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find sec(π/3).',
        hints: ['sec(x) = 1/cos(x).', 'cos(π/3) = 0.5.'],
        correctAnswer: 2,
        explanation: '1/0.5 = 2.',
      },
    },
    {
      id: 'trigfn-c2',
      part: 'problem-solving',
      conceptSlug: 'reflections-and-vertical-shifts-of-trig-graphs',
      conceptTitle: 'Reflections and Vertical Shifts of Trigonometric Graphs',
      question: {
        id: 'trigfn-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the minimum value of y = −cos(x) + 3.',
        hints: ['−cos(x) ranges from −1 to 1.'],
        correctAnswer: 2,
        explanation: '−cos(x) has min value −1, so −cos(x)+3 has min value −1+3=2.',
      },
    },
    {
      id: 'trigfn-d1',
      part: 'real-life-application',
      conceptSlug: 'the-inverse-sine-function-and-its-graph',
      conceptTitle: 'The Inverse Sine Function and Its Graph',
      question: {
        id: 'trigfn-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An engineer knows the sine of an unknown angle from a triangle\'s side ratios and needs the actual angle itself. Which function do they need?',
        options: [
          { id: 'a', text: 'arcsin (inverse sine)' },
          { id: 'b', text: 'sin (sine itself)' },
          { id: 'c', text: 'The derivative of sine' },
          { id: 'd', text: 'The reciprocal of sine' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly what an inverse function is for.'],
        explanation: 'arcsin recovers the angle directly from a known sine value.',
      },
    },
    {
      id: 'trigfn-d2',
      part: 'real-life-application',
      conceptSlug: 'the-inverse-cosine-and-inverse-tangent-functions',
      conceptTitle: 'The Inverse Cosine and Inverse Tangent Functions',
      question: {
        id: 'trigfn-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A navigator knows the ratio of a ship\'s northward and eastward speed components and needs the actual heading angle. Which inverse function is most directly useful here?',
        options: [
          { id: 'a', text: 'arctan (inverse tangent)' },
          { id: 'b', text: 'arcsin (inverse sine)' },
          { id: 'c', text: 'The derivative of tangent' },
          { id: 'd', text: 'The reciprocal of tangent' },
        ],
        correctOptionId: 'a',
        hints: ['A ratio of two components is exactly what tangent measures.'],
        explanation: 'arctan of the ratio of the two velocity components gives the heading angle directly.',
      },
    },
    {
      id: 'trigfn-e1',
      part: 'challenge',
      conceptSlug: 'derivatives-of-sine-and-cosine',
      conceptTitle: 'Derivatives of Sine and Cosine',
      question: {
        id: 'trigfn-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "Find f'(π/2) for f(x)=sinx+cosx.",
        hints: ["f'(x) = cosx − sinx."],
        correctAnswer: -1,
        explanation: "f'(π/2) = cos(π/2)−sin(π/2) = 0−1 = −1.",
      },
    },
    {
      id: 'trigfn-e2',
      part: 'challenge',
      conceptSlug: 'derivatives-of-tangent-and-other-trig-functions',
      conceptTitle: 'Derivatives of Tangent and Other Trigonometric Functions',
      question: {
        id: 'trigfn-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the derivative of f(x)=cot(x) at x=π/2.',
        hints: ["f'(x) = −csc²x.", 'csc(π/2) = 1/sin(π/2).'],
        correctAnswer: -1,
        explanation: 'csc(π/2)=1, so f\'(π/2) = −1² = −1.',
      },
    },
  ],
};
