import type { Assessment } from '@/types/content';

export const chapter8ALightAssessment: Assessment = {
  id: 'light-assessment',
  questions: [
    {
      id: 'light-a1',
      part: 'concept',
      conceptSlug: 'sources-of-light-a-level',
      conceptTitle: 'Sources of Light',
      question: {
        id: 'light-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which of these objects is non-luminous (produces no light of its own)?',
        hints: ['A non-luminous object is only visible because it reflects light.'],
        options: [
          { id: 'a', text: 'A burning candle' },
          { id: 'b', text: 'A star' },
          { id: 'c', text: 'A planet, seen by reflected starlight' },
          { id: 'd', text: 'A light bulb' },
        ],
        correctOptionId: 'c',
        explanation: 'A planet produces no light of its own — it is only visible because it reflects light from a nearby star, making it non-luminous.',
      },
    },
    {
      id: 'light-a2',
      part: 'concept',
      conceptSlug: 'reflection-of-light-a-level',
      conceptTitle: 'Reflection of Light',
      question: {
        id: 'light-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A ray of light hits a mirror at an angle of incidence of 62°. Find the angle of reflection.',
        hints: ['Law of reflection: angle of incidence = angle of reflection.'],
        correctAnswer: 62,
        unit: '°',
        explanation: 'By the law of reflection, the angle of reflection equals the angle of incidence: 62°.',
      },
    },
    {
      id: 'light-b1',
      part: 'formula-application',
      conceptSlug: 'mirror-formula-a-level',
      conceptTitle: 'The Mirror Formula and Magnification',
      question: {
        id: 'light-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A convex mirror has a focal length of +12 cm. An object is placed 24 cm in front of it (u = −24 cm). Find the image distance v.',
        hints: ['1/v = 1/f − 1/u.', '1/12 − 1/(−24).'],
        correctAnswer: 8,
        unit: 'cm',
        explanation: '1/v = 1/12 − 1/(−24) = 1/12 + 1/24 = 2/24 + 1/24 = 3/24 = 1/8, so v = 8 cm (positive: virtual image behind the mirror).',
      },
    },
    {
      id: 'light-b2',
      part: 'formula-application',
      conceptSlug: 'plane-mirror-images-a-level',
      conceptTitle: 'Image Formation in a Plane Mirror',
      question: {
        id: 'light-b2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'An object is placed 2.5 m from a plane mirror. Find the total distance between the object and its image.',
        hints: ['The image forms 2.5 m behind the mirror.', 'Total distance = object distance + image distance.'],
        correctAnswer: 5,
        unit: 'm',
        explanation: 'Total distance = 2.5 + 2.5 = 5 m.',
      },
    },
    {
      id: 'light-c1',
      part: 'problem-solving',
      conceptSlug: 'curved-mirrors-a-level',
      conceptTitle: 'Curved Mirrors',
      question: {
        id: 'light-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "A dentist holds a small concave mirror close to a tooth to see a magnified, upright view. For this to work, the tooth (the object) must be placed:",
        hints: ['A concave mirror only gives a magnified, upright (virtual) image under one particular condition.'],
        options: [
          { id: 'a', text: 'Beyond the centre of curvature' },
          { id: 'b', text: 'Closer to the mirror than the focal point' },
          { id: 'c', text: 'Exactly at the focal point' },
          { id: 'd', text: 'It does not matter where the object is placed' },
        ],
        correctOptionId: 'b',
        explanation: 'A concave mirror gives a magnified, virtual, upright image only when the object is placed closer to the mirror than the focal point.',
      },
    },
    {
      id: 'light-c2',
      part: 'problem-solving',
      conceptSlug: 'mirror-formula-a-level',
      conceptTitle: 'The Mirror Formula and Magnification',
      question: {
        id: 'light-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A concave mirror produces a real image at v = −40 cm when the object is at u = −20 cm. Find the magnification.',
        hints: ['m = −v/u.', '−(−40)/(−20).'],
        correctAnswer: -2,
        explanation: 'm = −v/u = −(−40)/(−20) = 40/(−20) = −2 (real, inverted, twice the size).',
      },
    },
    {
      id: 'light-d1',
      part: 'real-life-application',
      conceptSlug: 'reflection-of-light-a-level',
      conceptTitle: 'Reflection of Light',
      question: {
        id: 'light-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a cinema screen look equally bright from many different seats, unlike a mirror?',
        hints: ['Think about which type of reflection scatters light in all directions.'],
        options: [
          { id: 'a', text: 'The screen produces diffuse reflection, scattering light toward every seat' },
          { id: 'b', text: 'The screen is luminous, like a light bulb' },
          { id: 'c', text: 'The screen absorbs all the light and re-emits it evenly' },
          { id: 'd', text: 'Cinema screens use regular reflection, just like a mirror' },
        ],
        correctOptionId: 'a',
        explanation: "A cinema screen's rough surface produces diffuse reflection, scattering the projected light in many directions so every seat receives some of it.",
      },
    },
    {
      id: 'light-d2',
      part: 'real-life-application',
      conceptSlug: 'curved-mirrors-a-level',
      conceptTitle: 'Curved Mirrors',
      question: {
        id: 'light-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why are convex mirrors commonly used as security mirrors in shops?',
        hints: ['Think about field of view and the type of image formed.'],
        options: [
          { id: 'a', text: 'They give a wide field of view and always show an upright image' },
          { id: 'b', text: 'They magnify everything, making shoplifters easier to see' },
          { id: 'c', text: 'They are cheaper to manufacture than flat mirrors' },
          { id: 'd', text: 'They only work in bright light' },
        ],
        correctOptionId: 'a',
        explanation: "A convex mirror's diverging shape gives a wide field of view (covering more of the shop) while always forming an upright, easily interpreted image.",
      },
    },
    {
      id: 'light-e1',
      part: 'challenge',
      conceptSlug: 'mirror-formula-a-level',
      conceptTitle: 'The Mirror Formula and Magnification',
      question: {
        id: 'light-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A concave mirror forms a real image at v = −60 cm when the object is placed at u = −40 cm. Find the focal length f.',
        hints: ['1/f = 1/v + 1/u.', '1/(−60) + 1/(−40).'],
        correctAnswer: -24,
        unit: 'cm',
        explanation: '1/f = 1/(−60) + 1/(−40) = −2/120 − 3/120 = −5/120 = −1/24, so f = −24 cm.',
      },
    },
    {
      id: 'light-e2',
      part: 'challenge',
      conceptSlug: 'plane-mirror-images-a-level',
      conceptTitle: 'Image Formation in a Plane Mirror',
      question: {
        id: 'light-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two plane mirrors, A and B, face each other 4 m apart. An object stands 1.5 m from mirror A. Find the distance behind mirror B at which the image of the object (formed by reflection in mirror B) appears.',
        hints: ['First find the object\'s distance from mirror B.', 'A plane mirror places the image as far behind it as the object is in front.'],
        correctAnswer: 2.5,
        unit: 'm',
        explanation: 'Distance from the object to mirror B = 4 − 1.5 = 2.5 m. The image in mirror B forms 2.5 m behind mirror B.',
      },
    },
  ],
};
