import type { Assessment } from '@/types/content';

export const chapter12ModernAssessment: Assessment = {
  id: 'atomic-and-modern-physics-assessment',
  questions: [
    {
      id: 'mp-a1',
      part: 'concept',
      conceptSlug: 'cathode-rays',
      conceptTitle: 'Cathode Rays',
      question: {
        id: 'mp-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What did the study of cathode rays directly lead to the discovery of?',
        options: [
          { id: 'a', text: 'The electron' },
          { id: 'b', text: 'The proton' },
          { id: 'c', text: 'The neutron' },
          { id: 'd', text: 'The photon' },
        ],
        correctOptionId: 'a',
        hints: ["Thomson's experiments on cathode rays measured a charge-to-mass ratio."],
        explanation: "Thomson's cathode ray experiments led directly to the discovery of the electron.",
      },
    },
    {
      id: 'mp-a2',
      part: 'concept',
      conceptSlug: 'photoelectric-effect-and-photon-concept',
      conceptTitle: 'Photoelectric Effect & Photon Concept',
      question: {
        id: 'mp-a2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'What key observation about the photoelectric effect could NOT be explained by treating light as a pure wave?',
        options: [
          { id: 'a', text: 'No electrons are ejected below a threshold frequency, no matter how intense the light.' },
          { id: 'b', text: 'Brighter light always ejects more energetic electrons.' },
          { id: 'c', text: 'Light never ejects electrons from any material.' },
          { id: 'd', text: 'Electrons are ejected regardless of light frequency.' },
        ],
        correctOptionId: 'a',
        hints: ['A wave model predicts that dim light should eventually eject electrons given enough time.'],
        explanation: 'A wave model cannot explain the existence of a threshold frequency independent of intensity — this required treating light as discrete photons.',
      },
    },
    {
      id: 'mp-a3',
      part: 'concept',
      conceptSlug: 'isotopes-b-level',
      conceptTitle: 'Isotopes',
      question: {
        id: 'mp-a3-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is the same, and what differs, between isotopes of the same element?',
        options: [
          { id: 'a', text: 'Same number of protons; different number of neutrons.' },
          { id: 'b', text: 'Same number of neutrons; different number of protons.' },
          { id: 'c', text: 'Both protons and neutrons differ.' },
          { id: 'd', text: 'Isotopes are simply different elements entirely.' },
        ],
        correctOptionId: 'a',
        hints: ['What defines which element an atom is?'],
        explanation: 'Isotopes of the same element share the same proton number but differ in neutron number.',
      },
    },
    {
      id: 'mp-b1',
      part: 'formula-application',
      conceptSlug: 'bohrs-hydrogen-atom-and-atomic-spectra',
      conceptTitle: "Bohr's Hydrogen Atom & Atomic Spectra",
      question: {
        id: 'mp-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the energy of an electron in the n=4 level of hydrogen using Eₙ = −13.6/n² eV.',
        hints: ['Substitute n=4.'],
        correctAnswer: -0.85,
        tolerance: 0.05,
        unit: 'eV',
        explanation: 'E₄ = −13.6/16 = −0.85 eV.',
      },
    },
    {
      id: 'mp-b2',
      part: 'formula-application',
      conceptSlug: 'redshift-hubbles-law-and-age-of-universe',
      conceptTitle: "Red Shift, Hubble's Law & Age of Universe",
      question: {
        id: 'mp-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: "Find the recession speed of a galaxy 150 Mpc away, using H₀ ≈ 70 km/s/Mpc.",
        hints: ['v = H₀d.'],
        correctAnswer: 10500,
        tolerance: 200,
        unit: 'km/s',
        explanation: 'v = 70 × 150 = 10,500 km/s.',
      },
    },
    {
      id: 'mp-c1',
      part: 'problem-solving',
      conceptSlug: 'photoelectric-effect-and-photon-concept',
      conceptTitle: 'Photoelectric Effect & Photon Concept',
      question: {
        id: 'mp-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Light of frequency 6 × 10¹⁴ Hz strikes a metal with work function 1.5 eV. Find the maximum kinetic energy of ejected electrons, in eV (h = 6.63×10⁻³⁴ J·s, 1 eV = 1.6×10⁻¹⁹ J).',
        hints: ['First find hf in joules, convert to eV by dividing by 1.6×10⁻¹⁹, then subtract φ.'],
        correctAnswer: 1.0,
        tolerance: 0.1,
        unit: 'eV',
        explanation: 'hf = 6.63×10⁻³⁴×6×10¹⁴ = 3.978×10⁻¹⁹ J ≈ 2.49 eV. KEmax = 2.49 − 1.5 ≈ 1.0 eV.',
      },
    },
    {
      id: 'mp-c2',
      part: 'problem-solving',
      conceptSlug: 'bohrs-hydrogen-atom-and-atomic-spectra',
      conceptTitle: "Bohr's Hydrogen Atom & Atomic Spectra",
      question: {
        id: 'mp-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An electron drops from n=2 (E=−3.4 eV) to n=1 (E=−13.6 eV). Find the energy of the emitted photon.',
        hints: ['ΔE = E₂ − E₁ (energy lost by the electron equals the photon energy).'],
        correctAnswer: 10.2,
        tolerance: 0.2,
        unit: 'eV',
        explanation: 'ΔE = −3.4 − (−13.6) = 10.2 eV.',
      },
    },
    {
      id: 'mp-d1',
      part: 'real-life-application',
      conceptSlug: 'x-rays',
      conceptTitle: 'X-Rays',
      question: {
        id: 'mp-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why do bones appear bright/white on a standard medical X-ray image?',
        options: [
          { id: 'a', text: 'Bone absorbs X-rays more strongly than soft tissue, so less radiation reaches the detector behind it.' },
          { id: 'b', text: 'Bone produces its own X-rays.' },
          { id: 'c', text: 'Bone is completely transparent to X-rays.' },
          { id: 'd', text: 'X-rays have no interaction with bone at all.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about which tissue blocks more radiation.'],
        explanation: 'Denser bone absorbs more X-ray photons than soft tissue, leaving a brighter (less exposed) area on the image where the detector received less radiation.',
      },
    },
    {
      id: 'mp-d2',
      part: 'real-life-application',
      conceptSlug: 'isotopes-b-level',
      conceptTitle: 'Isotopes',
      question: {
        id: 'mp-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How does carbon dating use isotopes to estimate the age of ancient remains?',
        options: [
          { id: 'a', text: 'It compares the remaining radioactive carbon-14 to stable carbon-12, using the known, constant decay rate of carbon-14.' },
          { id: 'b', text: 'It measures how much oxygen the sample contains.' },
          { id: 'c', text: 'Carbon dating does not use isotopes at all.' },
          { id: 'd', text: 'It relies on measuring the sample\'s exact chemical composition alone.' },
        ],
        correctOptionId: 'a',
        hints: ['Carbon-14 is the key radioactive isotope involved.'],
        explanation: 'Carbon dating compares the ratio of radioactive carbon-14 (which decays at a known rate) to stable carbon-12 to estimate elapsed time since the organism died.',
      },
    },
    {
      id: 'mp-e1',
      part: 'challenge',
      conceptSlug: 'redshift-hubbles-law-and-age-of-universe',
      conceptTitle: "Red Shift, Hubble's Law & Age of Universe",
      question: {
        id: 'mp-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: "What does Hubble's law imply about the origin of the universe?",
        options: [
          { id: 'a', text: 'Since galaxies farther away recede faster, tracing this expansion backward suggests the universe originated from a single point in the past (Big Bang).' },
          { id: 'b', text: 'Hubble\'s law implies the universe is not expanding.' },
          { id: 'c', text: 'Hubble\'s law has no implications for the universe\'s history.' },
          { id: 'd', text: 'Hubble\'s law shows the universe is contracting.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider running the observed expansion backward in time.'],
        explanation: "The linear relationship between distance and recession speed, traced backward, suggests all galaxies originated from a single point — strong evidence supporting the Big Bang theory.",
      },
    },
  ],
};
