import type { Assessment } from '@/types/content';

export const chapter7COpticsAssessment: Assessment = {
  id: 'applications-of-light-and-optical-instruments-assessment',
  questions: [
    {
      id: 'optics-a1',
      part: 'concept',
      conceptSlug: 'the-camera',
      conceptTitle: 'The Camera',
      question: {
        id: 'optics-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A camera lens (f=0.06 m) photographs an object 4 m away. Find the image distance, rounded to 4 decimal places.',
        hints: ['1/v = 1/f − 1/u.'],
        correctAnswer: 0.0609,
        tolerance: 0.0005,
        explanation: '1/v = 1/0.06 − 1/4 = 16.667 − 0.25 = 16.417. v = 1/16.417 ≈ 0.0609 m.',
      },
    },
    {
      id: 'optics-a2',
      part: 'concept',
      conceptSlug: 'the-human-eye',
      conceptTitle: 'The Human Eye',
      question: {
        id: 'optics-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: "A myopic person's far point is 5 m. Find the power of the corrective lens needed.",
        hints: ['P = −1/f, with f equal to the far point.'],
        correctAnswer: -0.2,
        explanation: 'P = −1/5 = −0.2 D.',
      },
    },
    {
      id: 'optics-b1',
      part: 'formula-application',
      conceptSlug: 'compound-microscope',
      conceptTitle: 'The Compound Microscope',
      question: {
        id: 'optics-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A microscope has L=0.20 m, f₀=0.008 m, and fₑ=0.02 m. Find its magnifying power (D=0.25 m).',
        hints: ['M ≈ (L/f₀)(D/fₑ).'],
        correctAnswer: 312.5,
        explanation: '(0.20/0.008)=25. (0.25/0.02)=12.5. M=25×12.5=312.5.',
      },
    },
    {
      id: 'optics-b2',
      part: 'formula-application',
      conceptSlug: 'astronomical-telescope',
      conceptTitle: 'The Telescope',
      question: {
        id: 'optics-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A telescope has f₀=1.2 m and fₑ=0.03 m. Find its magnifying power.',
        hints: ['M = f₀/fₑ.'],
        correctAnswer: 40,
        explanation: 'M = 1.2/0.03 = 40.',
      },
    },
    {
      id: 'optics-c1',
      part: 'problem-solving',
      conceptSlug: 'laser-light',
      conceptTitle: 'The Laser',
      question: {
        id: 'optics-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A laser emits light at 450 nm (blue). Find the energy of each photon.',
        hints: ['E = hc/λ.'],
        correctAnswer: 4.42e-19,
        tolerance: 0.05e-19,
        explanation: 'E = (6.626×10⁻³⁴)(3×10⁸)/(450×10⁻⁹) ≈ 4.42×10⁻¹⁹ J.',
      },
    },
    {
      id: 'optics-c2',
      part: 'problem-solving',
      conceptSlug: 'fibre-optics-and-total-internal-reflection',
      conceptTitle: 'Fibre Optics',
      question: {
        id: 'optics-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An optical fibre has a critical angle of 45°. Find its refractive index n.',
        hints: ['Rearrange θc=sin⁻¹(1/n) to solve for n.'],
        correctAnswer: 1.414,
        tolerance: 0.01,
        explanation: 'n = 1/sin(45°) = 1/0.7071 ≈ 1.414.',
      },
    },
    {
      id: 'optics-d1',
      part: 'real-life-application',
      conceptSlug: 'spectrometer',
      conceptTitle: 'The Spectrometer',
      question: {
        id: 'optics-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "A spectrometer analyzing sunlight reveals dark lines at specific missing wavelengths. What are these lines known as, and what do they reveal?",
        hints: ['These are named after the scientist who first studied them in detail.'],
        options: [
          { id: 'a', text: "Fraunhofer (absorption) lines, revealing elements in the Sun's outer atmosphere" },
          { id: 'b', text: 'Random noise with no physical meaning' },
          { id: 'c', text: 'Evidence the Sun is cooling down' },
          { id: 'd', text: "Reflections from Earth's atmosphere only" },
        ],
        correctOptionId: 'a',
        explanation: 'These are Fraunhofer (absorption) lines — elements in the Sun\'s outer layers absorb specific wavelengths, which a spectrometer reveals as dark gaps in the spectrum.',
      },
    },
    {
      id: 'optics-d2',
      part: 'real-life-application',
      conceptSlug: 'photometry-and-light-intensity',
      conceptTitle: 'Photometry',
      question: {
        id: 'optics-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A photographer moves a studio light from 1 m to 2 m away from a subject. By what factor does the illuminance on the subject change?',
        hints: ['E∝1/d². The distance doubled.'],
        options: [
          { id: 'a', text: 'Decreases to 1/4' },
          { id: 'b', text: 'Decreases to 1/2' },
          { id: 'c', text: 'Stays the same' },
          { id: 'd', text: 'Decreases to 1/8' },
        ],
        correctOptionId: 'a',
        explanation: 'Since E=I/d², doubling the distance divides illuminance by 2²=4.',
      },
    },
    {
      id: 'optics-e1',
      part: 'challenge',
      conceptSlug: 'the-camera',
      conceptTitle: 'The Camera',
      question: {
        id: 'optics-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A camera lens forms a sharp image at v=0.052 m for an object at u=2.6 m. Find the lens\'s focal length.',
        hints: ['1/f = 1/v + 1/u.'],
        correctAnswer: 0.051,
        tolerance: 0.0005,
        explanation: '1/f = 1/0.052 + 1/2.6 ≈ 19.231+0.385 = 19.615. f = 1/19.615 ≈ 0.0510 m.',
      },
    },
    {
      id: 'optics-e2',
      part: 'challenge',
      conceptSlug: 'astronomical-telescope',
      conceptTitle: 'The Telescope',
      question: {
        id: 'optics-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A telescope has magnification 60 and an eyepiece focal length of 0.015 m. Find its objective focal length.',
        hints: ['Rearrange M=f₀/fₑ to solve for f₀.'],
        correctAnswer: 0.9,
        explanation: 'f₀ = M × fₑ = 60 × 0.015 = 0.9 m.',
      },
    },
  ],
};
