import type { Formula } from '@/types/content';

export const chapter7COpticsFormulas: Record<string, Formula> = {
  'camera-lens-formula': {
    slug: 'camera-lens-formula',
    name: 'The Thin Lens Equation',
    expression: '1/f = 1/v + 1/u',
    meaning: "A camera's converging lens forms a sharp, focused image on the sensor (or film) exactly where the lens equation predicts, given the lens's focal length and the object's distance.",
    variables: [
      { symbol: 'f', meaning: 'focal length of the lens, in metres (m)' },
      { symbol: 'v', meaning: 'image distance — from the lens to the focused image, in metres (m)' },
      { symbol: 'u', meaning: 'object distance — from the lens to the object being photographed, in metres (m)' },
    ],
    whenToUse: 'Whenever the distance a camera lens must be from its sensor to form a sharp image of an object at a given distance needs to be found.',
    relatedConceptSlugs: ['the-camera'],
  },
  'eye-correction-formula': {
    slug: 'eye-correction-formula',
    name: 'Power of a Corrective Lens',
    expression: 'P = 1/f',
    meaning: "A corrective lens's power (in diopters) is the reciprocal of its focal length — for a myopic (near-sighted) eye, a diverging lens with a focal length equal to the eye's far point brings distant objects into focus.",
    variables: [
      { symbol: 'P', meaning: 'power of the lens, in diopters (D)' },
      { symbol: 'f', meaning: 'focal length needed, in metres (m) — negative for a diverging (myopia-correcting) lens' },
    ],
    whenToUse: "Whenever the power of a corrective lens needs to be found from an eye's near or far point.",
    relatedConceptSlugs: ['the-human-eye'],
  },
  'microscope-magnification-formula': {
    slug: 'microscope-magnification-formula',
    name: 'Compound Microscope Magnifying Power',
    expression: 'M ≈ (L/f₀)(D/fₑ)',
    meaning: "A compound microscope's total magnification comes from two lenses working together: the objective lens creates a magnified real image, which the eyepiece lens then magnifies again as a virtual image.",
    variables: [
      { symbol: 'M', meaning: 'total magnifying power (dimensionless)' },
      { symbol: 'L', meaning: 'tube length — the distance between the objective and eyepiece lenses, in metres (m)' },
      { symbol: 'f₀', meaning: 'focal length of the objective lens, in metres (m)' },
      { symbol: 'D', meaning: 'the near point distance of the eye, conventionally 0.25 m' },
      { symbol: 'fₑ', meaning: 'focal length of the eyepiece lens, in metres (m)' },
    ],
    whenToUse: "Whenever a compound microscope's total magnifying power needs to be estimated from its lens focal lengths and tube length.",
    relatedConceptSlugs: ['compound-microscope'],
  },
  'telescope-magnification-formula': {
    slug: 'telescope-magnification-formula',
    name: 'Astronomical Telescope Magnifying Power',
    expression: 'M = f₀/fₑ',
    meaning: "A telescope's magnifying power is simply the ratio of its objective lens's focal length to its eyepiece lens's focal length — a longer objective or a shorter eyepiece both increase magnification.",
    variables: [
      { symbol: 'M', meaning: 'magnifying power (dimensionless)' },
      { symbol: 'f₀', meaning: 'focal length of the objective lens, in metres (m)' },
      { symbol: 'fₑ', meaning: 'focal length of the eyepiece lens, in metres (m)' },
    ],
    whenToUse: "Whenever a telescope's magnifying power needs to be found from its two lenses' focal lengths.",
    relatedConceptSlugs: ['astronomical-telescope'],
  },
  'photon-energy-formula': {
    slug: 'photon-energy-formula',
    name: 'Photon Energy',
    expression: 'E = hf = hc/λ',
    meaning: 'Light (including laser light) is carried by photons, each with an energy directly proportional to its frequency (or inversely proportional to its wavelength).',
    variables: [
      { symbol: 'E', meaning: 'energy of a single photon, in joules (J)' },
      { symbol: 'h', meaning: "Planck's constant, 6.626×10⁻³⁴ J·s" },
      { symbol: 'f', meaning: 'frequency of the light, in hertz (Hz)' },
      { symbol: 'c', meaning: 'speed of light, 3×10⁸ m/s' },
      { symbol: 'λ', meaning: 'wavelength of the light, in metres (m)' },
    ],
    whenToUse: 'Whenever the energy carried by a single photon of light (such as laser light of a known wavelength) needs to be found.',
    relatedConceptSlugs: ['laser-light'],
  },
  'fibre-critical-angle-formula': {
    slug: 'fibre-critical-angle-formula',
    name: 'Critical Angle for Total Internal Reflection',
    expression: 'θc = sin⁻¹(1/n)',
    meaning: "Light traveling inside an optical fibre's core reflects perfectly off the core-cladding boundary (total internal reflection) whenever it strikes at an angle steeper than this critical angle — trapping the light inside the fibre.",
    variables: [
      { symbol: 'θc', meaning: 'critical angle, in degrees' },
      { symbol: 'n', meaning: 'refractive index of the fibre core relative to the surrounding medium (dimensionless)' },
    ],
    whenToUse: "Whenever the critical angle for total internal reflection inside an optical fibre needs to be found from its core's refractive index.",
    relatedConceptSlugs: ['fibre-optics-and-total-internal-reflection'],
  },
  'spectrometer-grating-formula': {
    slug: 'spectrometer-grating-formula',
    name: "A Spectrometer's Grating Equation",
    expression: 'd sinθ = mλ',
    meaning: "A spectrometer's diffraction grating splits light into its component wavelengths, each appearing at its own precise angle — measuring that angle lets the instrument determine the light's exact wavelength.",
    variables: [
      { symbol: 'd', meaning: 'spacing between adjacent grating lines, in metres (m)' },
      { symbol: 'θ', meaning: 'angle of the diffracted beam from the straight-through direction, in degrees' },
      { symbol: 'm', meaning: 'order of the diffraction maximum (m=1, 2, 3, …)' },
      { symbol: 'λ', meaning: 'wavelength of the light being measured, in metres (m)' },
    ],
    whenToUse: "Whenever a spectrometer's diffraction grating is used to measure or predict the wavelength of light from the angle at which it diffracts.",
    relatedConceptSlugs: ['spectrometer'],
  },
  'illuminance-formula': {
    slug: 'illuminance-formula',
    name: 'Illuminance from a Point Source',
    expression: 'E = I/d²',
    meaning: 'The illuminance (brightness of light falling on a surface) from a point source falls off with the square of the distance — moving twice as far away makes a light source appear four times dimmer.',
    variables: [
      { symbol: 'E', meaning: 'illuminance, in lux (lx)' },
      { symbol: 'I', meaning: 'luminous intensity of the source, in candela (cd)' },
      { symbol: 'd', meaning: 'distance from the source, in metres (m)' },
    ],
    whenToUse: 'Whenever the brightness of light falling on a surface at a known distance from a point light source needs to be found.',
    relatedConceptSlugs: ['photometry-and-light-intensity'],
  },
};
