import type { Assessment } from '@/types/content';

export const chapter2RotationalDynamicsAssessment: Assessment = {
  id: 'rotational-dynamics-assessment',
  questions: [
    {
      id: 'rd-a1',
      part: 'concept',
      conceptSlug: 'scalar-product-of-vectors',
      conceptTitle: 'Scalar (Dot) Product of Vectors',
      question: {
        id: 'rd-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What kind of quantity does the scalar (dot) product of two vectors produce?',
        options: [
          { id: 'a', text: 'A number (scalar), with no direction' },
          { id: 'b', text: 'A new vector, perpendicular to both' },
          { id: 'c', text: 'A matrix' },
          { id: 'd', text: 'Another vector parallel to the first' },
        ],
        correctOptionId: 'a',
        hints: ['The name "scalar product" is a hint.'],
        explanation: 'The scalar product produces a plain number (scalar), unlike the vector product, which produces a new vector.',
      },
    },
    {
      id: 'rd-a2',
      part: 'concept',
      conceptSlug: 'moment-of-inertia',
      conceptTitle: 'Moment of Inertia',
      question: {
        id: 'rd-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does moment of inertia depend on r² rather than just r?',
        options: [
          { id: 'a', text: 'Mass farther from the axis resists rotational change disproportionately more, captured by the squared term.' },
          { id: 'b', text: 'It is simply a mathematical convention with no physical meaning.' },
          { id: 'c', text: 'r² makes the units simpler.' },
          { id: 'd', text: 'Moment of inertia does not actually depend on r at all.' },
        ],
        correctOptionId: 'a',
        hints: ['Compare a mass close to the axis with one farther away, spun at the same angular velocity.'],
        explanation: 'The r² dependence reflects how strongly distance from the axis affects rotational resistance to change.',
      },
    },
    {
      id: 'rd-a3',
      part: 'concept',
      conceptSlug: 'conditions-for-equilibrium',
      conceptTitle: 'Conditions for Equilibrium',
      question: {
        id: 'rd-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An object has zero net force acting on it. Is it necessarily in complete equilibrium?',
        options: [
          { id: 'a', text: 'No — it could still have a nonzero net torque and begin rotating.' },
          { id: 'b', text: 'Yes, zero net force always guarantees complete equilibrium.' },
          { id: 'c', text: 'Only if the object has no mass.' },
          { id: 'd', text: 'Torque is irrelevant to equilibrium.' },
        ],
        correctOptionId: 'a',
        hints: ['Complete equilibrium requires checking BOTH conditions.'],
        explanation: 'Zero net force alone only rules out linear acceleration — a nonzero net torque could still cause the object to start rotating.',
      },
    },
    {
      id: 'rd-b1',
      part: 'formula-application',
      conceptSlug: 'torque-and-turning-effect',
      conceptTitle: 'Torque and the Turning Effect of Force',
      question: {
        id: 'rd-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 40 N force acts at 90° to a 0.5 m lever arm. Find the torque.',
        hints: ['τ = rF sinθ.'],
        correctAnswer: 20,
        tolerance: 0.3,
        unit: 'N·m',
        explanation: 'τ = 0.5 × 40 × sin90° = 20 N·m.',
      },
    },
    {
      id: 'rd-b2',
      part: 'formula-application',
      conceptSlug: 'angular-momentum',
      conceptTitle: 'Angular Momentum',
      question: {
        id: 'rd-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A rotor with moment of inertia 3.5 kg·m² spins at 6 rad/s. Find its angular momentum.',
        hints: ['L = Iω.'],
        correctAnswer: 21,
        tolerance: 0.3,
        unit: 'kg·m²/s',
        explanation: 'L = 3.5 × 6 = 21 kg·m²/s.',
      },
    },
    {
      id: 'rd-c1',
      part: 'problem-solving',
      conceptSlug: 'torque-moment-of-inertia-relation',
      conceptTitle: 'Relation Between Torque and Moment of Inertia',
      question: {
        id: 'rd-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A net torque of 18 N·m produces an angular acceleration of 3 rad/s² in a rotating disc. Find the moment of inertia.',
        hints: ['τ = Iα, rearranged: I = τ/α.'],
        correctAnswer: 6,
        tolerance: 0.2,
        unit: 'kg·m²',
        explanation: 'I = τ/α = 18/3 = 6 kg·m².',
      },
    },
    {
      id: 'rd-c2',
      part: 'problem-solving',
      conceptSlug: 'conservation-of-angular-momentum',
      conceptTitle: 'Law of Conservation of Angular Momentum',
      question: {
        id: 'rd-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A diver spinning at 4 rad/s with I₁ = 8 kg·m² (tucked) straightens out to I₂ = 16 kg·m². Find the new angular velocity (no external torque).',
        hints: ['I₁ω₁ = I₂ω₂.'],
        correctAnswer: 2,
        tolerance: 0.1,
        unit: 'rad/s',
        explanation: '8 × 4 = 16 × ω₂ → 32 = 16ω₂ → ω₂ = 2 rad/s.',
      },
    },
    {
      id: 'rd-d1',
      part: 'real-life-application',
      conceptSlug: 'conservation-of-angular-momentum',
      conceptTitle: 'Law of Conservation of Angular Momentum',
      question: {
        id: 'rd-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a collapsing star spin dramatically faster as it shrinks into a neutron star?',
        options: [
          { id: 'a', text: 'Its moment of inertia decreases sharply as it shrinks, so conservation of angular momentum forces its angular velocity to increase.' },
          { id: 'b', text: 'An external torque speeds it up during collapse.' },
          { id: 'c', text: 'Angular momentum is not conserved during stellar collapse.' },
          { id: 'd', text: 'The star gains additional mass, which speeds up its spin.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall the figure-skater analogy.'],
        explanation: 'With negligible external torque, the sharp decrease in moment of inertia as the star shrinks forces a dramatic increase in angular velocity to keep angular momentum constant.',
      },
    },
    {
      id: 'rd-d2',
      part: 'real-life-application',
      conceptSlug: 'torque-and-turning-effect',
      conceptTitle: 'Torque and the Turning Effect of Force',
      question: {
        id: 'rd-d2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why are door handles placed far from the hinge rather than close to it?',
        options: [
          { id: 'a', text: 'A larger r means less force is needed to produce the same torque to open the door.' },
          { id: 'b', text: 'Distance from the hinge has no effect on how easily a door opens.' },
          { id: 'c', text: 'Handles near the hinge always work equally well.' },
          { id: 'd', text: 'It is purely a design tradition with no physical reason.' },
        ],
        correctOptionId: 'a',
        hints: ['τ = rF sinθ — what happens to the force needed for a fixed torque, as r increases?'],
        explanation: 'Since torque is force times distance (times sinθ), placing the handle far from the hinge (large r) lets a smaller force produce the same turning torque.',
      },
    },
    {
      id: 'rd-e1',
      part: 'challenge',
      conceptSlug: 'vector-product-of-vectors',
      conceptTitle: 'Vector (Cross) Product of Vectors',
      question: {
        id: 'rd-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A force is applied exactly along the direction of a lever arm (parallel to it, θ = 0°). What torque results, and why?',
        options: [
          { id: 'a', text: 'Zero torque, because sin0° = 0 — a force pointing along the lever arm has no turning effect.' },
          { id: 'b', text: 'Maximum torque, because the force is fully aligned with the arm.' },
          { id: 'c', text: 'Torque cannot be calculated in this case.' },
          { id: 'd', text: 'The torque equals the force magnitude times the lever arm length exactly.' },
        ],
        correctOptionId: 'a',
        hints: ['Torque is a cross product, which depends on sinθ, not cosθ.'],
        explanation: 'Since torque uses sinθ, and sin0° = 0, a force applied directly along the lever arm (parallel to r) produces zero torque — it has no component that would cause turning.',
      },
    },
  ],
};
