import type { Assessment } from '@/types/content';

export const chapter4CAssessment: Assessment = {
  id: 'vectors-in-three-dimensions-assessment',
  questions: [
    {
      id: 'vec3d-a1',
      part: 'concept',
      conceptSlug: 'vectors-in-three-dimensions-and-their-magnitude',
      conceptTitle: 'Vectors in Three Dimensions and Their Magnitude',
      question: {
        id: 'vec3d-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the magnitude of v=(6,8,0).',
        hints: ['|v| = √(x²+y²+z²).'],
        correctAnswer: 10,
        explanation: '√(36+64+0) = √100 = 10.',
      },
    },
    {
      id: 'vec3d-a2',
      part: 'concept',
      conceptSlug: 'the-dot-product-of-two-vectors',
      conceptTitle: 'The Dot Product of Two Vectors',
      question: {
        id: 'vec3d-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the dot product of a=(1,1,1) and b=(2,3,4).',
        hints: ['a·b = a₁b₁+a₂b₂+a₃b₃.'],
        correctAnswer: 9,
        explanation: '1(2)+1(3)+1(4) = 9.',
      },
    },
    {
      id: 'vec3d-b1',
      part: 'formula-application',
      conceptSlug: 'the-angle-between-two-vectors',
      conceptTitle: 'The Angle Between Two Vectors',
      question: {
        id: 'vec3d-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the angle (in degrees) between a=(1,0,0) and b=(0,5,0).',
        hints: ['Find a·b first.'],
        correctAnswer: 90,
        explanation: 'a·b=0, so cosθ=0, meaning θ=90°.',
      },
    },
    {
      id: 'vec3d-b2',
      part: 'formula-application',
      conceptSlug: 'the-cross-product-of-two-vectors',
      conceptTitle: 'The Cross Product of Two Vectors',
      question: {
        id: 'vec3d-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the y-component of a×b for a=(0,1,0) and b=(0,0,1).',
        hints: ['The y-component is a₃b₁−a₁b₃.'],
        correctAnswer: 0,
        explanation: 'a₃b₁−a₁b₃ = (0)(0)−(0)(1) = 0 (this confirms j×k=i, with x-component 1 and the rest 0).',
      },
    },
    {
      id: 'vec3d-c1',
      part: 'problem-solving',
      conceptSlug: 'the-cross-product-and-area-of-a-parallelogram',
      conceptTitle: 'The Cross Product and Area of a Parallelogram',
      question: {
        id: 'vec3d-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the area of the parallelogram formed by a=(4,0,0) and b=(0,6,0).',
        hints: ['a×b = (0,0,24).'],
        correctAnswer: 24,
        explanation: '|a×b| = 24 (matches the simple 4×6 rectangle check).',
      },
    },
    {
      id: 'vec3d-c2',
      part: 'problem-solving',
      conceptSlug: 'the-vector-equation-of-a-line-in-space',
      conceptTitle: 'The Vector Equation of a Line in Space',
      question: {
        id: 'vec3d-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'For the line r=(3+t, 1−2t, 5+t), find the z-coordinate at t=4.',
        hints: ['Substitute t=4 into the z-component.'],
        correctAnswer: 9,
        explanation: '5+4 = 9.',
      },
    },
    {
      id: 'vec3d-d1',
      part: 'real-life-application',
      conceptSlug: 'the-vector-equation-of-a-plane-in-space',
      conceptTitle: 'The Vector Equation of a Plane in Space',
      question: {
        id: 'vec3d-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A game engine needs a compact test for whether a point lies on a flat surface, given the surface\'s normal vector and one known point on it. Which equation gives this directly?',
        options: [
          { id: 'a', text: 'n · (r − r₀) = 0' },
          { id: 'b', text: 'r = r₀ + t·v' },
          { id: 'c', text: 'Volume = |a·(b×c)|' },
          { id: 'd', text: '|v| = √(x²+y²+z²)' },
        ],
        correctOptionId: 'a',
        hints: ['This is the vector equation of a plane.'],
        explanation: 'n·(r−r₀)=0 evaluates to zero exactly for points on the plane — the compact test needed.',
      },
    },
    {
      id: 'vec3d-d2',
      part: 'real-life-application',
      conceptSlug: 'the-scalar-triple-product-and-volume',
      conceptTitle: 'The Scalar Triple Product and Volume',
      question: {
        id: 'vec3d-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An engineer needs the volume of a parallelepiped-shaped storage tank, described by three edge vectors from one corner. Which technique gives this directly?',
        options: [
          { id: 'a', text: 'The scalar triple product' },
          { id: 'b', text: 'The dot product alone' },
          { id: 'c', text: 'The vector equation of a line' },
          { id: 'd', text: 'The magnitude formula alone' },
        ],
        correctOptionId: 'a',
        hints: ['This combines the cross product and dot product together.'],
        explanation: 'Volume = |a·(b×c)| gives the tank\'s volume directly from the three edge vectors.',
      },
    },
    {
      id: 'vec3d-e1',
      part: 'challenge',
      conceptSlug: 'the-dot-product-of-two-vectors',
      conceptTitle: 'The Dot Product of Two Vectors',
      question: {
        id: 'vec3d-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'If a and b are perpendicular unit vectors, what is a·b?',
        hints: ['a·b = |a||b|cosθ, with θ=90°.'],
        correctAnswer: 0,
        explanation: 'cos90°=0, so a·b = (1)(1)(0) = 0.',
      },
    },
    {
      id: 'vec3d-e2',
      part: 'challenge',
      conceptSlug: 'the-cross-product-of-two-vectors',
      conceptTitle: 'The Cross Product of Two Vectors',
      question: {
        id: 'vec3d-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the x-component of a×b for a=(0,2,0) and b=(0,0,3).',
        hints: ['The x-component is a₂b₃−a₃b₂.'],
        correctAnswer: 6,
        explanation: '(2)(3)−(0)(0) = 6.',
      },
    },
  ],
};
