import type { Assessment } from '@/types/content';

export const chapter4PowerAssessment: Assessment = {
  id: 'power-and-efficiency-assessment',
  questions: [
    {
      id: 'pe-a1',
      part: 'concept',
      conceptSlug: 'power-and-its-units',
      conceptTitle: 'Power and Its Units',
      question: {
        id: 'pe-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does power measure?',
        options: [
          { id: 'a', text: 'The rate at which work is done or energy is transferred.' },
          { id: 'b', text: 'The total amount of energy used, regardless of time.' },
          { id: 'c', text: 'The force applied to an object.' },
          { id: 'd', text: 'The distance an object travels.' },
        ],
        correctOptionId: 'a',
        hints: ['Power involves a time element.'],
        explanation: 'Power is specifically the rate (per unit time) at which work is done or energy transferred, not the total amount.',
      },
    },
    {
      id: 'pe-a2',
      part: 'concept',
      conceptSlug: 'efficiency-of-machines',
      conceptTitle: 'Efficiency',
      question: {
        id: 'pe-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can no real machine reach 100% efficiency?',
        options: [
          { id: 'a', text: 'Some input energy is always converted to unwanted forms, usually heat from friction.' },
          { id: 'b', text: 'Machines create energy from nothing, making the concept meaningless.' },
          { id: 'c', text: '100% efficiency is common in real machines.' },
          { id: 'd', text: 'Efficiency has no relationship to energy loss.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider what happens to energy lost to friction.'],
        explanation: 'Real machines always lose some input energy to unwanted forms (typically heat), so useful output is always less than total input.',
      },
    },
    {
      id: 'pe-a3',
      part: 'concept',
      conceptSlug: 'hookes-law-and-spring-constant',
      conceptTitle: "Hooke's Law and the Spring Constant",
      question: {
        id: 'pe-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "Within its elastic limit, what happens to a spring's extension if the applied force is doubled?",
        options: [
          { id: 'a', text: 'The extension doubles too, since force and extension are directly proportional.' },
          { id: 'b', text: 'The extension stays exactly the same.' },
          { id: 'c', text: 'The extension quadruples.' },
          { id: 'd', text: 'The extension is halved.' },
        ],
        correctOptionId: 'a',
        hints: ['F = kx — what kind of relationship is this?'],
        explanation: "Hooke's law describes a direct proportionality between force and extension, so doubling the force doubles the extension.",
      },
    },
    {
      id: 'pe-b1',
      part: 'formula-application',
      conceptSlug: 'power-and-its-units',
      conceptTitle: 'Power and Its Units',
      question: {
        id: 'pe-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A pump does 24,000 J of work in 8 seconds. Find its power.',
        hints: ['P = W/t.'],
        correctAnswer: 3000,
        tolerance: 50,
        unit: 'W',
        explanation: 'P = 24,000/8 = 3000 W.',
      },
    },
    {
      id: 'pe-b2',
      part: 'formula-application',
      conceptSlug: 'elastic-potential-energy-in-a-spring',
      conceptTitle: 'Elastic Potential Energy in a Spring',
      question: {
        id: 'pe-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A spring with spring constant 200 N/m is stretched by 0.15 m. Find the elastic potential energy stored.',
        hints: ['E = ½kx².'],
        correctAnswer: 2.25,
        tolerance: 0.1,
        unit: 'J',
        explanation: 'E = ½ × 200 × 0.15² = ½ × 200 × 0.0225 = 2.25 J.',
      },
    },
    {
      id: 'pe-c1',
      part: 'problem-solving',
      conceptSlug: 'efficiency-of-machines',
      conceptTitle: 'Efficiency',
      question: {
        id: 'pe-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A machine is 40% efficient and produces 120 J of useful output. Find the total energy input.',
        hints: ['η = (useful output/total input) × 100%, rearranged: total input = useful output / (η/100).'],
        correctAnswer: 300,
        tolerance: 5,
        unit: 'J',
        explanation: 'Total input = 120 / 0.40 = 300 J.',
      },
    },
    {
      id: 'pe-c2',
      part: 'problem-solving',
      conceptSlug: 'hookes-law-and-spring-constant',
      conceptTitle: "Hooke's Law and the Spring Constant",
      question: {
        id: 'pe-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A spring stretches 0.04 m under a 60 N force. Find its spring constant.',
        hints: ['F = kx, rearranged: k = F/x.'],
        correctAnswer: 1500,
        tolerance: 20,
        unit: 'N/m',
        explanation: 'k = 60/0.04 = 1500 N/m.',
      },
    },
    {
      id: 'pe-d1',
      part: 'real-life-application',
      conceptSlug: 'sources-of-energy-b-level',
      conceptTitle: 'Sources of Energy',
      question: {
        id: 'pe-d1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why is coal considered a non-renewable energy source?',
        options: [
          { id: 'a', text: 'It formed over millions of years and is being used up far faster than it can reform.' },
          { id: 'b', text: 'Coal replenishes itself within a few years.' },
          { id: 'c', text: 'Coal is not actually used for energy.' },
          { id: 'd', text: 'Coal has no environmental impact.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider the geological timescale needed to form coal.'],
        explanation: 'Coal took millions of years to form from ancient organic matter and is being consumed much faster than any natural process could replace it.',
      },
    },
    {
      id: 'pe-d2',
      part: 'real-life-application',
      conceptSlug: 'elastic-potential-energy-in-a-spring',
      conceptTitle: 'Elastic Potential Energy in a Spring',
      question: {
        id: 'pe-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How does drawing a bow relate to launching an arrow?',
        options: [
          { id: 'a', text: 'Drawing the bow stores elastic potential energy, which converts to the kinetic energy of the launched arrow.' },
          { id: 'b', text: 'Drawing the bow has no relationship to the arrow\'s speed.' },
          { id: 'c', text: 'The bow\'s stored energy is destroyed when the string is released.' },
          { id: 'd', text: 'Only the archer\'s muscles provide the arrow\'s energy, not the bow.' },
        ],
        correctOptionId: 'a',
        hints: ['Where does the energy come from that launches the arrow?'],
        explanation: 'The work done drawing the bow is stored as elastic potential energy, which converts to kinetic energy in the arrow upon release.',
      },
    },
    {
      id: 'pe-e1',
      part: 'challenge',
      conceptSlug: 'efficiency-of-machines',
      conceptTitle: 'Efficiency',
      question: {
        id: 'pe-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A machine is upgraded so that its energy losses to friction are halved, while total input energy stays the same. What happens to its efficiency?',
        options: [
          { id: 'a', text: 'Efficiency increases, since useful output rises when less energy is lost to friction.' },
          { id: 'b', text: 'Efficiency decreases.' },
          { id: 'c', text: 'Efficiency stays exactly the same.' },
          { id: 'd', text: 'Efficiency becomes undefined.' },
        ],
        correctOptionId: 'a',
        hints: ['If less input energy is wasted, what happens to the useful output?'],
        explanation: 'Reducing energy lost to friction (with the same total input) increases the useful output, and therefore increases efficiency.',
      },
    },
  ],
};
