import type { Assessment } from '@/types/content';

export const chapter11BAssessment: Assessment = {
  id: 'methods-of-differentiation-assessment',
  questions: [
    {
      id: 'diff-a1',
      part: 'concept',
      conceptSlug: 'the-idea-of-a-limit',
      conceptTitle: 'The Idea of a Limit',
      question: {
        id: 'diff-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does lim(x→a) f(x) = L mean?',
        options: [
          { id: 'a', text: 'f(x) gets closer and closer to L as x gets closer and closer to a' },
          { id: 'b', text: 'f(a) always equals L' },
          { id: 'c', text: 'f(x) equals L for every value of x' },
          { id: 'd', text: 'a always equals L' },
        ],
        correctOptionId: 'a',
        hints: ['A limit describes behavior NEAR a point, not necessarily AT it.'],
        explanation: 'The limit describes what f(x) approaches as x approaches a — f(a) itself doesn\'t even need to be defined.',
      },
    },
    {
      id: 'diff-a2',
      part: 'concept',
      conceptSlug: 'the-power-rule',
      conceptTitle: 'The Power Rule',
      question: {
        id: 'diff-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is d/dx[x⁷]?',
        options: [
          { id: 'a', text: '7x⁶' },
          { id: 'b', text: '7x⁷' },
          { id: 'c', text: 'x⁶' },
          { id: 'd', text: '6x⁷' },
        ],
        correctOptionId: 'a',
        hints: ['Bring the exponent down, then subtract 1.'],
        explanation: 'd/dx[x⁷] = 7x^(7−1) = 7x⁶.',
      },
    },
    {
      id: 'diff-b1',
      part: 'formula-application',
      conceptSlug: 'the-sum-and-difference-rules',
      conceptTitle: 'The Sum and Difference Rules',
      question: {
        id: 'diff-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Differentiate f(x) = x² + 3x, then find f\'(2).',
        hints: ["f'(x) = 2x + 3."],
        correctAnswer: 7,
        explanation: "f'(x) = 2x+3, so f'(2) = 4+3 = 7.",
      },
    },
    {
      id: 'diff-b2',
      part: 'formula-application',
      conceptSlug: 'the-product-rule',
      conceptTitle: 'The Product Rule',
      question: {
        id: 'diff-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Differentiate f(x) = (x+1)(x+4) using the Product Rule, then find f\'(0).',
        hints: ["u=x+1, v=x+4, u'=1, v'=1.", "(uv)' = u'v + uv'."],
        correctAnswer: 5,
        explanation: "f'(x) = 1(x+4) + (x+1)(1) = 2x+5. f'(0) = 5.",
      },
    },
    {
      id: 'diff-c1',
      part: 'problem-solving',
      conceptSlug: 'the-quotient-rule',
      conceptTitle: 'The Quotient Rule',
      question: {
        id: 'diff-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Differentiate f(x) = (x+3)/x using the Quotient Rule, then find f\'(1).',
        hints: ["u=x+3, v=x, u'=1, v'=1.", "(u/v)' = (u'v − uv')/v²."],
        correctAnswer: -3,
        explanation: "f'(x) = [1(x) − (x+3)(1)]/x² = −3/x². f'(1) = −3.",
      },
    },
    {
      id: 'diff-c2',
      part: 'problem-solving',
      conceptSlug: 'the-chain-rule',
      conceptTitle: 'The Chain Rule',
      question: {
        id: 'diff-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Differentiate f(x) = (x+5)² using the Chain Rule, then find f\'(3).',
        hints: ['Outer: u², so d/du[u²]=2u. Inner: u=x+5, du/dx=1.'],
        correctAnswer: 16,
        explanation: "f'(x) = 2(x+5)(1) = 2(x+5). f'(3) = 2(8) = 16.",
      },
    },
    {
      id: 'diff-d1',
      part: 'real-life-application',
      conceptSlug: 'the-derivative-as-a-rate-of-change',
      conceptTitle: 'The Derivative as a Rate of Change',
      question: {
        id: 'diff-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A company\'s profit function is P(x), for x units produced. What does the derivative P\'(x) represent?',
        options: [
          { id: 'a', text: 'The marginal (instantaneous) profit rate at production level x' },
          { id: 'b', text: 'The average profit over all production levels' },
          { id: 'c', text: 'The total profit at production level x' },
          { id: 'd', text: 'The number of units produced' },
        ],
        correctOptionId: 'a',
        hints: ['The derivative is an instantaneous rate, not a total or an average.'],
        explanation: 'P\'(x) is the instantaneous rate of change of profit — the "marginal profit" — at exactly production level x.',
      },
    },
    {
      id: 'diff-d2',
      part: 'real-life-application',
      conceptSlug: 'implicit-differentiation',
      conceptTitle: 'Implicit Differentiation',
      question: {
        id: 'diff-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An engineer needs the slope of a curved cam profile given by an equation relating x and y that cannot easily be solved for y. Which technique should they use?',
        options: [
          { id: 'a', text: 'Implicit differentiation' },
          { id: 'b', text: 'The Power Rule alone' },
          { id: 'c', text: 'Direct substitution into a limit' },
          { id: 'd', text: 'Measuring the slope by hand instead' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation implicit differentiation is designed for.'],
        explanation: 'Implicit differentiation finds dy/dx directly from the equation, without needing to isolate y first.',
      },
    },
    {
      id: 'diff-e1',
      part: 'challenge',
      conceptSlug: 'the-quotient-rule',
      conceptTitle: 'The Quotient Rule',
      question: {
        id: 'diff-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why does the order of subtraction in the Quotient Rule\'s numerator (u\'v − uv\', not uv\' − u\'v) matter?',
        options: [
          { id: 'a', text: 'Subtraction is not commutative — reversing the order gives the negative of the correct derivative' },
          { id: 'b', text: 'It doesn\'t actually matter, both orders give the same answer' },
          { id: 'c', text: 'The order only matters when g(x) is negative' },
          { id: 'd', text: 'The order only matters for polynomials' },
        ],
        correctOptionId: 'a',
        hints: ['Try swapping the order on a known example and compare results.'],
        explanation: 'Since a−b ≠ b−a in general, reversing the Quotient Rule\'s numerator order gives the exact negative of the correct derivative.',
      },
    },
    {
      id: 'diff-e2',
      part: 'challenge',
      conceptSlug: 'applications-of-implicit-differentiation',
      conceptTitle: 'Applications of Implicit Differentiation',
      question: {
        id: 'diff-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'For the curve x² − xy + y² = 3, find dy/dx at the point (1, −1).',
        hints: ['Check: 1−(1)(−1)+1 = 3, so (1,−1) is on the curve.', 'dy/dx = (y−2x)/(2y−x).'],
        correctAnswer: 1,
        explanation: 'dy/dx = (−1−2)/(−2−1) = (−3)/(−3) = 1.',
      },
    },
  ],
};
