import type { Assessment } from '@/types/content';

export const chapter1AUnitsAssessment: Assessment = {
  id: 'units-and-measurements-assessment',
  questions: [
    {
      id: 'units-a1',
      part: 'concept',
      conceptSlug: 'basic-and-derived-units',
      conceptTitle: 'Basic and Derived Units',
      question: {
        id: 'units-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Energy (the joule) is defined by work = force × distance. Which base-unit combination is correct for the joule?',
        hints: ['Force in base units is kg·m/s². Multiply by a length (m).'],
        options: [
          { id: 'a', text: 'kg·m/s²' },
          { id: 'b', text: 'kg·m²/s²' },
          { id: 'c', text: 'kg·m²/s' },
          { id: 'd', text: 'kg/(m·s²)' },
        ],
        correctOptionId: 'b',
        explanation: 'joule = force × distance = (kg·m/s²) × m = kg·m²/s².',
      },
    },
    {
      id: 'units-a2',
      part: 'concept',
      conceptSlug: 'systems-of-units',
      conceptTitle: 'System of Units',
      question: {
        id: 'units-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Convert 0.75 m to centimetres.',
        hints: ['1 m = 100 cm.', '0.75 × 100.'],
        correctAnswer: 75,
        unit: 'cm',
        explanation: '0.75 m = 0.75 × 100 = 75 cm.',
      },
    },
    {
      id: 'units-b1',
      part: 'formula-application',
      conceptSlug: 'vernier-caliper',
      conceptTitle: 'The Vernier Caliper',
      question: {
        id: 'units-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A vernier caliper (least count 0.01 cm) has a main scale reading of 3.7 cm, with the 8th vernier division coinciding. Find the total reading.',
        hints: ['Total reading = MSR + (VC × LC).', '3.7 + (8 × 0.01).'],
        correctAnswer: 3.78,
        unit: 'cm',
        explanation: 'Total reading = 3.7 + (8×0.01) = 3.7 + 0.08 = 3.78 cm.',
      },
    },
    {
      id: 'units-b2',
      part: 'formula-application',
      conceptSlug: 'micrometer-screw-gauge',
      conceptTitle: 'The Micrometer Screw Gauge',
      question: {
        id: 'units-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A micrometer (least count 0.001 cm) has a main scale reading of 0.2 cm and a circular scale reading of 35. Find the total reading.',
        hints: ['Total reading = MSR + (CSR × LC).', '0.2 + (35 × 0.001).'],
        correctAnswer: 0.235,
        unit: 'cm',
        explanation: 'Total reading = 0.2 + (35×0.001) = 0.2 + 0.035 = 0.235 cm.',
      },
    },
    {
      id: 'units-c1',
      part: 'problem-solving',
      conceptSlug: 'si-prefixes',
      conceptTitle: 'Prefixes',
      question: {
        id: 'units-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A capacitor is rated at 220 nanofarads (nF). Express this in microfarads (μF).',
        hints: ['1 nano = 10⁻⁹; 1 micro = 10⁻⁶.', '220 × 10⁻⁹ = 0.22 × 10⁻⁶.'],
        correctAnswer: 0.22,
        unit: 'μF',
        explanation: '220 nF = 220 × 10⁻⁹ F = 0.22 × 10⁻⁶ F = 0.22 μF.',
      },
    },
    {
      id: 'units-c2',
      part: 'problem-solving',
      conceptSlug: 'measurement-of-mass',
      conceptTitle: 'Measurement of Mass',
      question: {
        id: 'units-c2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A beam balance balances against standard masses of 500 g, 100 g, 10 g, and 2 g. Find the total mass of the object.',
        hints: ['Add up all the standard masses.', '500+100+10+2.'],
        correctAnswer: 612,
        unit: 'g',
        explanation: 'Mass = 500+100+10+2 = 612 g.',
      },
    },
    {
      id: 'units-d1',
      part: 'real-life-application',
      conceptSlug: 'standards-of-measurement',
      conceptTitle: 'Standards and Units',
      question: {
        id: 'units-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which fixed constant of nature is used to define the modern SI metre?',
        hints: ['The metre is defined using how far light travels in a fixed time.'],
        options: [
          { id: 'a', text: 'The speed of sound' },
          { id: 'b', text: 'The speed of light in a vacuum' },
          { id: 'c', text: "Avogadro's number" },
          { id: 'd', text: 'The mass of a proton' },
        ],
        correctOptionId: 'b',
        explanation: 'The metre is defined as the distance light travels in a vacuum in exactly 1/299,792,458 of a second.',
      },
    },
    {
      id: 'units-d2',
      part: 'real-life-application',
      conceptSlug: 'measurement-of-time',
      conceptTitle: 'Measurement of Time',
      question: {
        id: 'units-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A grandfather clock needs a pendulum with a period of exactly 2.0 s. Using g = 9.8 m/s², find the required length. (Round to 2 decimal places.)',
        hints: ['Rearrange T = 2π√(L/g) to solve for L.', 'L = g(T/2π)².'],
        correctAnswer: 0.99,
        tolerance: 0.02,
        unit: 'm',
        explanation: 'L = g(T/2π)² = 9.8 × (2.0/6.283)² = 9.8 × 0.1013 ≈ 0.99 m — this is why "seconds pendulums" are close to 1 metre long.',
      },
    },
    {
      id: 'units-e1',
      part: 'challenge',
      conceptSlug: 'micrometer-screw-gauge',
      conceptTitle: 'The Micrometer Screw Gauge',
      question: {
        id: 'units-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A micrometer reading is 0.462 cm, with a main scale reading of 0.4 cm and a least count of 0.001 cm. Find the circular scale reading (CSR).',
        hints: ['Rearrange Total reading = MSR + (CSR × LC) to solve for CSR.', 'CSR = (Total − MSR) / LC.'],
        correctAnswer: 62,
        explanation: 'CSR = (0.462 − 0.4) / 0.001 = 0.062/0.001 = 62.',
      },
    },
    {
      id: 'units-e2',
      part: 'challenge',
      conceptSlug: 'measurement-of-time',
      conceptTitle: 'Measurement of Time',
      question: {
        id: 'units-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A pendulum of length 0.5 m is measured to have a period of 1.42 s. Use this data to estimate g.',
        hints: ['Rearrange T = 2π√(L/g) to solve for g.', 'g = 4π²L / T².'],
        correctAnswer: 9.79,
        tolerance: 0.1,
        unit: 'm/s²',
        explanation: 'g = 4π²L/T² = 4×9.8696×0.5 / 1.42² = 19.739/2.0164 ≈ 9.79 m/s².',
      },
    },
  ],
};
