import type { Assessment } from '@/types/content';

export const chapter1BAssessment: Assessment = {
  id: 'remainder-and-factor-theorem-assessment',
  questions: [
    {
      id: 'rft-a1',
      part: 'concept',
      conceptSlug: 'the-remainder-theorem',
      conceptTitle: 'The Remainder Theorem',
      question: {
        id: 'rft-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'According to the remainder theorem, what does P(a) equal when P(x) is divided by (x−a)?',
        options: [
          { id: 'a', text: 'The remainder' },
          { id: 'b', text: 'The quotient' },
          { id: 'c', text: 'Always zero' },
          { id: 'd', text: 'The degree of P(x)' },
        ],
        correctOptionId: 'a',
        hints: ['This is the entire content of the remainder theorem.'],
        explanation: 'P(a) always equals the remainder of P(x) divided by (x−a).',
      },
    },
    {
      id: 'rft-a2',
      part: 'concept',
      conceptSlug: 'the-factor-theorem',
      conceptTitle: 'The Factor Theorem',
      question: {
        id: 'rft-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does the factor theorem tell you about P(x) when P(a) = 0?',
        options: [
          { id: 'a', text: '(x − a) is a factor of P(x)' },
          { id: 'b', text: 'P(x) has no real roots' },
          { id: 'c', text: 'a is not a root of P(x)' },
          { id: 'd', text: 'P(x) cannot be factored' },
        ],
        correctOptionId: 'a',
        hints: ['P(a)=0 means remainder 0.'],
        explanation: 'P(a) = 0 means (x−a) divides P(x) exactly — it is a factor.',
      },
    },
    {
      id: 'rft-b1',
      part: 'formula-application',
      conceptSlug: 'the-remainder-theorem',
      conceptTitle: 'The Remainder Theorem',
      question: {
        id: 'rft-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the remainder when P(x) = x³ + 2x² − x + 5 is divided by (x − 1).',
        hints: ['Compute P(1).'],
        correctAnswer: 7,
        explanation: 'P(1) = 1 + 2 − 1 + 5 = 7.',
      },
    },
    {
      id: 'rft-b2',
      part: 'formula-application',
      conceptSlug: 'synthetic-division',
      conceptTitle: 'Synthetic Division',
      question: {
        id: 'rft-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Use synthetic division to divide x² − 5x + 6 by (x − 2). What is the remainder?',
        hints: ['x²−5x+6 = (x−2)(x−3).'],
        correctAnswer: 0,
        explanation: '(x−2)(x−3) = x²−5x+6, so the remainder is 0.',
      },
    },
    {
      id: 'rft-c1',
      part: 'problem-solving',
      conceptSlug: 'the-factor-theorem',
      conceptTitle: 'The Factor Theorem',
      question: {
        id: 'rft-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which value of a makes (x − a) a factor of P(x) = x³ − x² − 4x + 4?',
        options: [
          { id: 'a', text: 'a = 1' },
          { id: 'b', text: 'a = 3' },
          { id: 'c', text: 'a = 4' },
          { id: 'd', text: 'a = −4' },
        ],
        correctOptionId: 'a',
        hints: ['Test each option by evaluating P(a).'],
        explanation: 'P(1) = 1 − 1 − 4 + 4 = 0, so a = 1 works.',
      },
    },
    {
      id: 'rft-c2',
      part: 'problem-solving',
      conceptSlug: 'factoring-polynomials-using-the-factor-theorem',
      conceptTitle: 'Factoring Polynomials Using the Factor Theorem',
      question: {
        id: 'rft-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Fully factor x³ − 3x² − x + 3. (Hint: try a = 1 first.)',
        options: [
          { id: 'a', text: '(x−1)(x−3)(x+1)' },
          { id: 'b', text: '(x+1)(x−3)(x−1)' },
          { id: 'c', text: '(x−1)(x+3)(x−1)' },
          { id: 'd', text: '(x−3)(x+3)(x−1)' },
        ],
        correctOptionId: 'a',
        hints: ['P(1) = 1−3−1+3 = 0.', 'Dividing gives x²−2x−3, which factors further.'],
        explanation: 'P(1)=0, dividing gives x²−2x−3=(x−3)(x+1), so x³−3x²−x+3=(x−1)(x−3)(x+1).',
      },
    },
    {
      id: 'rft-d1',
      part: 'real-life-application',
      conceptSlug: 'dividing-polynomials',
      conceptTitle: 'Dividing Polynomials by Long Division',
      question: {
        id: 'rft-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An engineer has a cost formula that is a cubic polynomial divided by a linear expression. Why would they use polynomial long division?',
        options: [
          { id: 'a', text: 'To rewrite the complicated fraction as a simpler polynomial plus a small remainder term.' },
          { id: 'b', text: 'To make the cost formula more complicated.' },
          { id: 'c', text: 'Long division only works on numbers, not formulas.' },
          { id: 'd', text: 'To find the formula\'s roots directly, without any other steps.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about what P(x) = D(x)Q(x) + R(x) achieves.'],
        explanation: 'Long division simplifies a complicated rational expression into a polynomial plus a small remainder, genuinely easier to work with.',
      },
    },
    {
      id: 'rft-d2',
      part: 'real-life-application',
      conceptSlug: 'the-factor-theorem',
      conceptTitle: 'The Factor Theorem',
      question: {
        id: 'rft-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A proposed break-even quantity for a cubic profit model P(x) = x³ − 6x² + 11x − 6 is x = 2. Confirm by finding P(2). (0 would confirm it is a break-even point.)',
        hints: ['P(2) = 8 − 24 + 22 − 6.'],
        correctAnswer: 0,
        explanation: 'P(2) = 8 − 24 + 22 − 6 = 0, confirming x=2 is indeed a break-even point (a root).',
      },
    },
    {
      id: 'rft-e1',
      part: 'challenge',
      conceptSlug: 'the-remainder-theorem',
      conceptTitle: 'The Remainder Theorem',
      question: {
        id: 'rft-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'P(x) = x³ + kx − 4 leaves a remainder of 5 when divided by (x − 1). Find k.',
        hints: ['P(1) = 1 + k − 4 = 5.'],
        correctAnswer: 8,
        explanation: '1 + k − 4 = 5 → k = 8.',
      },
    },
    {
      id: 'rft-e2',
      part: 'challenge',
      conceptSlug: 'factoring-polynomials-using-the-factor-theorem',
      conceptTitle: 'Factoring Polynomials Using the Factor Theorem',
      question: {
        id: 'rft-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Is x = 2 a root of P(x) = x³ − 2x² − 5x + 6?',
        options: [
          { id: 'a', text: 'No — P(2) = −4, not 0' },
          { id: 'b', text: 'Yes — P(2) = 0' },
          { id: 'c', text: 'No — P(2) = 8, not 0' },
          { id: 'd', text: 'Cannot be evaluated' },
        ],
        correctOptionId: 'a',
        hints: ['P(2) = 2³ − 2(2)² − 5(2) + 6.'],
        explanation: 'P(2) = 8 − 8 − 10 + 6 = −4, which is not 0, so x=2 is not a root of this polynomial.',
      },
    },
  ],
};
