import type { Assessment } from '@/types/content';

export const chapter3PressureAssessment: Assessment = {
  id: 'pressure-assessment',
  questions: [
    {
      id: 'pr-a1',
      part: 'concept',
      conceptSlug: 'atmospheric-pressure-explained',
      conceptTitle: 'Atmospheric Pressure',
      question: {
        id: 'pr-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "Why don't we feel crushed by atmospheric pressure?",
        options: [
          { id: 'a', text: 'It acts equally in all directions, balanced by pressure from inside our bodies.' },
          { id: 'b', text: 'Atmospheric pressure does not actually exist.' },
          { id: 'c', text: 'It only acts downward, and our skeletons resist it.' },
          { id: 'd', text: 'It only exists at high altitude.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about pressure acting from every direction, including from within.'],
        explanation: 'Atmospheric pressure acts equally in all directions and is balanced by internal pressure in our bodies, so we do not feel it.',
      },
    },
    {
      id: 'pr-a2',
      part: 'concept',
      conceptSlug: 'archimedes-principle',
      conceptTitle: "Archimedes' Principle",
      question: {
        id: 'pr-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What determines the buoyant force on a submerged object?',
        options: [
          { id: 'a', text: 'The weight of the fluid displaced by the object.' },
          { id: 'b', text: "The object's own material density alone." },
          { id: 'c', text: "The object's colour." },
          { id: 'd', text: 'The temperature of the object only.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall the exact statement of the principle.'],
        explanation: "Archimedes' principle states buoyant force equals the weight of fluid displaced by the object.",
      },
    },
    {
      id: 'pr-a3',
      part: 'concept',
      conceptSlug: 'pascals-law',
      conceptTitle: "Pascal's Law",
      question: {
        id: 'pr-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "Does a hydraulic press create extra energy when it multiplies force?",
        options: [
          { id: 'a', text: 'No — the large piston moves a smaller distance, so work (force × distance) is conserved.' },
          { id: 'b', text: 'Yes, hydraulic systems create energy from nothing.' },
          { id: 'c', text: 'Energy has no relevance to hydraulic systems.' },
          { id: 'd', text: 'Only if the fluid used is water.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider the distance each piston moves.'],
        explanation: 'Force is multiplied, but the large piston moves proportionally less far, so total work is conserved, not created.',
      },
    },
    {
      id: 'pr-b1',
      part: 'formula-application',
      conceptSlug: 'the-mercury-barometer',
      conceptTitle: 'The Barometer',
      question: {
        id: 'pr-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A mercury barometer shows a column height of 0.70 m. Find the atmospheric pressure it indicates (ρ = 13,600 kg/m³, g = 9.8 m/s²).',
        hints: ['P = hρg.'],
        correctAnswer: 93296,
        tolerance: 1000,
        unit: 'Pa',
        explanation: 'P = 0.70 × 13,600 × 9.8 ≈ 93,296 Pa.',
      },
    },
    {
      id: 'pr-b2',
      part: 'formula-application',
      conceptSlug: 'pressure-in-a-liquid-b-level',
      conceptTitle: 'Pressure in a Liquid',
      question: {
        id: 'pr-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the extra pressure (beyond atmospheric) at a depth of 8 m in water (ρ = 1000 kg/m³, g = 9.8 m/s²).',
        hints: ['Extra pressure = hρg.'],
        correctAnswer: 78400,
        tolerance: 800,
        unit: 'Pa',
        explanation: 'hρg = 8 × 1000 × 9.8 = 78,400 Pa.',
      },
    },
    {
      id: 'pr-c1',
      part: 'problem-solving',
      conceptSlug: 'archimedes-principle',
      conceptTitle: "Archimedes' Principle",
      question: {
        id: 'pr-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A solid block displaces 0.008 m³ of water when fully submerged. Find the buoyant force (ρ = 1000 kg/m³, g = 9.8 m/s²).',
        hints: ['Fᵦ = ρVg.'],
        correctAnswer: 78.4,
        tolerance: 1,
        unit: 'N',
        explanation: 'Fᵦ = 1000 × 0.008 × 9.8 = 78.4 N.',
      },
    },
    {
      id: 'pr-c2',
      part: 'problem-solving',
      conceptSlug: 'pascals-law',
      conceptTitle: "Pascal's Law",
      question: {
        id: 'pr-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A hydraulic lift has a small piston of area 0.015 m² and a large piston of area 0.6 m². What force must be applied to the small piston to lift a 4000 N load on the large piston?',
        hints: ['F₁/A₁ = F₂/A₂, rearranged: F₁ = F₂ × (A₁/A₂).'],
        correctAnswer: 100,
        tolerance: 2,
        unit: 'N',
        explanation: 'F₁ = 4000 × (0.015/0.6) = 4000 × 0.025 = 100 N.',
      },
    },
    {
      id: 'pr-d1',
      part: 'real-life-application',
      conceptSlug: 'atmospheric-pressure-explained',
      conceptTitle: 'Atmospheric Pressure',
      question: {
        id: 'pr-d1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why does liquid rise up a straw when you suck on it?',
        options: [
          { id: 'a', text: 'Reduced pressure inside the straw lets atmospheric pressure outside push the liquid up.' },
          { id: 'b', text: 'Sucking directly pulls the liquid with a mysterious force.' },
          { id: 'c', text: 'The straw material attracts the liquid.' },
          { id: 'd', text: 'Atmospheric pressure has no role in this.' },
        ],
        correctOptionId: 'a',
        hints: ['What happens to the air pressure inside the straw when you suck?'],
        explanation: 'Sucking lowers the pressure inside the straw; the now-greater atmospheric pressure on the liquid outside pushes it up into the straw.',
      },
    },
    {
      id: 'pr-d2',
      part: 'real-life-application',
      conceptSlug: 'archimedes-principle',
      conceptTitle: "Archimedes' Principle",
      question: {
        id: 'pr-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a large steel ship float despite steel being much denser than water?',
        options: [
          { id: 'a', text: "The ship's hollow hull shape displaces enough water that the buoyant force equals the ship's total weight." },
          { id: 'b', text: 'Steel is actually less dense than water.' },
          { id: 'c', text: 'Ships do not actually float; they are supported by the seabed.' },
          { id: 'd', text: 'Buoyant force depends only on the material, not the shape.' },
        ],
        correctOptionId: 'a',
        hints: ["Consider the volume of water the ship's overall shape displaces, not just the steel's density."],
        explanation: "The ship's hull shape displaces a large volume of water, producing enough buoyant force to support the ship's entire weight, even though steel itself is denser than water.",
      },
    },
    {
      id: 'pr-e1',
      part: 'challenge',
      conceptSlug: 'the-manometer',
      conceptTitle: 'The Manometer',
      question: {
        id: 'pr-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A manometer shows the liquid on the gas side is HIGHER than the open side. What does this indicate about the gas pressure?',
        options: [
          { id: 'a', text: 'The gas pressure is LOWER than atmospheric pressure, since the gas is pulling the liquid up on its side less than atmospheric pressure pushes on the open side.' },
          { id: 'b', text: 'The gas pressure is higher than atmospheric pressure.' },
          { id: 'c', text: 'The gas pressure equals atmospheric pressure exactly.' },
          { id: 'd', text: 'The liquid level has no relationship to gas pressure.' },
        ],
        correctOptionId: 'a',
        hints: ['If the gas side is higher, which side is being pushed down more strongly?'],
        explanation: 'If the liquid is higher on the gas side, atmospheric pressure (on the open side) is pushing down more strongly than the gas pressure, meaning the gas pressure is below atmospheric.',
      },
    },
  ],
};
