import type { Assessment } from '@/types/content';

export const chapter8Assessment: Assessment = {
  id: 'similarity-assessment',
  questions: [
    {
      id: 'sim-a1',
      part: 'concept',
      conceptSlug: 'meaning-of-similar-figures-and-similar-triangles',
      conceptTitle: 'Meaning of Similar Figures and Similar Triangles',
      question: {
        id: 'sim-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Two similar triangles must have:',
        options: [
          { id: 'a', text: 'Equal corresponding angles and proportional corresponding sides' },
          { id: 'b', text: 'Equal corresponding sides' },
          { id: 'c', text: 'Equal areas' },
          { id: 'd', text: 'The same perimeter' },
        ],
        correctOptionId: 'a',
        hints: ['Similar means same shape, possibly different size.'],
        explanation: 'Similar triangles have equal angles and sides in a common ratio (the scale factor).',
      },
    },
    {
      id: 'sim-a2',
      part: 'concept',
      conceptSlug: 'the-pythagoras-theorem',
      conceptTitle: 'The Pythagoras Theorem',
      question: {
        id: 'sim-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'In a²+b²=c², what is c?',
        options: [
          { id: 'a', text: 'The hypotenuse, opposite the right angle' },
          { id: 'b', text: 'Either leg' },
          { id: 'c', text: 'The shortest side' },
          { id: 'd', text: 'The perimeter' },
        ],
        correctOptionId: 'a',
        hints: ['c is always the longest side of a right triangle.'],
        explanation: 'c is the hypotenuse — the side opposite the right angle, always the longest side.',
      },
    },
    {
      id: 'sim-b1',
      part: 'formula-application',
      conceptSlug: 'the-basic-proportionality-theorem',
      conceptTitle: 'The Basic Proportionality Theorem',
      question: {
        id: 'sim-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In △ABC, DE ∥ BC. AD=5, DB=10, AE=4. Find EC.',
        hints: ['AD/DB = AE/EC.'],
        correctAnswer: 8,
        explanation: '5/10 = 4/EC → 5·EC = 40 → EC = 8.',
      },
    },
    {
      id: 'sim-b2',
      part: 'formula-application',
      conceptSlug: 'the-pythagoras-theorem',
      conceptTitle: 'The Pythagoras Theorem',
      question: {
        id: 'sim-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A right triangle has legs 9 and 12. Find the hypotenuse.',
        hints: ['9² + 12² = c².'],
        correctAnswer: 15,
        explanation: '81 + 144 = 225, √225 = 15.',
      },
    },
    {
      id: 'sim-c1',
      part: 'problem-solving',
      conceptSlug: 'the-angle-bisector-theorem',
      conceptTitle: 'The Angle Bisector Theorem',
      question: {
        id: 'sim-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In △ABC, AD bisects ∠A. AB=8, AC=12, BC=25. Find DC.',
        hints: ['BD/DC = 8/12 = 2/3.', 'Split BC=25 into 2+3=5 parts.'],
        correctAnswer: 15,
        explanation: 'Each part = 25/5 = 5. DC = 3×5 = 15.',
      },
    },
    {
      id: 'sim-c2',
      part: 'problem-solving',
      conceptSlug: 'special-right-triangles',
      conceptTitle: 'Special Right Triangles (45-45-90 and 30-60-90)',
      question: {
        id: 'sim-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 30-60-90 triangle has hypotenuse 20. Find the short leg (opposite the 30° angle).',
        hints: ['Hypotenuse = 2x, so x = hypotenuse/2.'],
        correctAnswer: 10,
        explanation: '2x = 20 → x = 10.',
      },
    },
    {
      id: 'sim-d1',
      part: 'real-life-application',
      conceptSlug: 'similarity-tests-for-triangles',
      conceptTitle: 'Similarity Tests for Triangles (AA, SAS, SSS)',
      question: {
        id: 'sim-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A student and a flagpole cast shadows at the same time. Why does this form similar triangles?',
        options: [
          { id: 'a', text: 'Both triangles share the same sun angle and a right angle with the ground (AA).' },
          { id: 'b', text: 'The student and flagpole are the same height.' },
          { id: 'c', text: 'The shadows are always the same length.' },
          { id: 'd', text: 'Similarity does not apply to shadows.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about which two angles match in both triangles.'],
        explanation: 'Both triangles have a right angle with the ground and the same angle of elevation to the sun, satisfying AA similarity.',
      },
    },
    {
      id: 'sim-d2',
      part: 'real-life-application',
      conceptSlug: 'the-pythagoras-theorem',
      conceptTitle: 'The Pythagoras Theorem',
      question: {
        id: 'sim-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A ladder 13 m long leans against a wall, with its base 5 m from the wall. How high up the wall does it reach?',
        hints: ['5² + h² = 13².'],
        correctAnswer: 12,
        explanation: '25 + h² = 169 → h² = 144 → h = 12 m.',
      },
    },
    {
      id: 'sim-e1',
      part: 'challenge',
      conceptSlug: 'the-basic-proportionality-theorem',
      conceptTitle: 'The Basic Proportionality Theorem',
      question: {
        id: 'sim-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why does DE ∥ BC in △ABC guarantee △ADE ~ △ABC?',
        options: [
          { id: 'a', text: 'They share ∠A, and DE ∥ BC makes the angles at D and B equal (corresponding angles), giving AA similarity.' },
          { id: 'b', text: 'DE and BC must be the same length.' },
          { id: 'c', text: 'All triangles with a shared vertex are automatically similar.' },
          { id: 'd', text: 'AD must equal DB.' },
        ],
        correctOptionId: 'a',
        hints: ['This is the proof idea behind the basic proportionality theorem.'],
        explanation: 'The shared angle at A plus equal corresponding angles (from the parallel lines) satisfies the AA similarity test.',
      },
    },
    {
      id: 'sim-e2',
      part: 'challenge',
      conceptSlug: 'the-angle-bisector-theorem',
      conceptTitle: 'The Angle Bisector Theorem',
      question: {
        id: 'sim-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In △ABC, AD bisects ∠A. AB=10, AC=15, and DC=12. Find BD.',
        hints: ['BD/DC = AB/AC = 10/15 = 2/3.', 'BD = (2/3)×DC.'],
        correctAnswer: 8,
        explanation: 'BD/12 = 10/15 → BD = 12×(10/15) = 8.',
      },
    },
  ],
};
