import type { Assessment } from '@/types/content';

export const chapter13CModernAssessment: Assessment = {
  id: 'modern-physics-assessment',
  questions: [
    {
      id: 'modernphys-a1',
      part: 'concept',
      conceptSlug: 'radioactivity-and-its-uses',
      conceptTitle: 'Radioactivity and Its Uses',
      question: {
        id: 'modernphys-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A radioactive sample has a half-life of 5 years. Find the percentage remaining after 15 years.',
        hints: ['Find n=t/T_half first, then compute (1/2) to the power n.'],
        correctAnswer: 12.5,
        explanation: 'n=15/5=3. (1/2) to the power 3 = 1/8 = 12.5%.',
      },
    },
    {
      id: 'modernphys-a2',
      part: 'concept',
      conceptSlug: 'nuclear-energy-and-environmental-impact',
      conceptTitle: 'Nuclear Energy and Its Environmental Impact',
      question: {
        id: 'modernphys-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A nuclear reaction converts 0.0002 kg of mass into energy. Find the energy released.',
        hints: ['E = mc squared.'],
        correctAnswer: 1.8e13,
        tolerance: 0.05e13,
        explanation: 'E = (0.0002)(9 times 10 to the power 16) = 1.8 times 10 to the power 13 J.',
      },
    },
    {
      id: 'modernphys-b1',
      part: 'formula-application',
      conceptSlug: 'wave-particle-duality',
      conceptTitle: 'Wave-Particle Dualism',
      question: {
        id: 'modernphys-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A proton (mass 1.67 times 10 to the power -27 kg) moves at 3 times 10 to the power 5 m/s. Find its de Broglie wavelength.',
        hints: ['Find p=mv first, then lambda=h/p.'],
        correctAnswer: 1.32e-12,
        tolerance: 0.05e-12,
        explanation: 'p = (1.67e-27)(3e5) = 5.01e-22 kg m/s. lambda = (6.626e-34)/(5.01e-22) approximately 1.32e-12 m.',
      },
    },
    {
      id: 'modernphys-b2',
      part: 'formula-application',
      conceptSlug: 'special-theory-of-relativity',
      conceptTitle: 'Principle of Special Theory of Relativity',
      question: {
        id: 'modernphys-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the Lorentz factor (gamma) for an object moving at 0.6c.',
        hints: ['gamma = 1/sqrt(1 minus (v/c) squared).'],
        correctAnswer: 1.25,
        explanation: 'gamma = 1/sqrt(1-0.36) = 1/sqrt(0.64) = 1/0.8 = 1.25.',
      },
    },
    {
      id: 'modernphys-c1',
      part: 'problem-solving',
      conceptSlug: 'radioactivity-and-its-uses',
      conceptTitle: 'Radioactivity and Its Uses',
      question: {
        id: 'modernphys-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A radioactive sample decays to 1/16 of its original amount. How many half-lives have passed?',
        hints: ['(1/2) to the power n = 1/16.'],
        correctAnswer: 4,
        explanation: '(1/2) to the power 4 = 1/16, so n=4.',
      },
    },
    {
      id: 'modernphys-c2',
      part: 'problem-solving',
      conceptSlug: 'nuclear-energy-and-environmental-impact',
      conceptTitle: 'Nuclear Energy and Its Environmental Impact',
      question: {
        id: 'modernphys-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'How much mass must be converted to release 3.6 times 10 to the power 14 J of energy?',
        hints: ['Rearrange E=mc squared to solve for m.'],
        correctAnswer: 0.004,
        explanation: 'm = E/c squared = (3.6e14)/(9e16) = 0.004 kg.',
      },
    },
    {
      id: 'modernphys-d1',
      part: 'real-life-application',
      conceptSlug: 'wave-particle-duality',
      conceptTitle: 'Wave-Particle Dualism',
      question: {
        id: 'modernphys-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can electron microscopes image details far smaller than light microscopes can?',
        hints: ['Think about the de Broglie wavelength of a fast electron compared to visible light.'],
        options: [
          { id: 'a', text: 'Fast electrons have a much shorter de Broglie wavelength than visible light, allowing finer resolution' },
          { id: 'b', text: 'Electrons are physically much bigger than photons' },
          { id: 'c', text: 'Electron microscopes do not use waves at all' },
          { id: 'd', text: 'Light microscopes use higher energy than electron microscopes' },
        ],
        correctOptionId: 'a',
        explanation: "A fast electron's de Broglie wavelength is far shorter than visible light's wavelength, allowing much finer resolution of small details.",
      },
    },
    {
      id: 'modernphys-d2',
      part: 'real-life-application',
      conceptSlug: 'special-theory-of-relativity',
      conceptTitle: 'Principle of Special Theory of Relativity',
      question: {
        id: 'modernphys-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why must GPS satellite clocks be corrected using special relativity?',
        hints: ['Think about the relative speed between the satellite and a receiver on Earth.'],
        options: [
          { id: 'a', text: 'Satellites move at high speed relative to Earth, causing their onboard clocks to run at a measurably different rate' },
          { id: 'b', text: 'GPS satellites do not use clocks at all' },
          { id: 'c', text: 'Relativity only applies to light, never to satellites' },
          { id: 'd', text: 'Correction is unnecessary and never actually done' },
        ],
        correctOptionId: 'a',
        explanation: "A satellite's high relative speed causes real, measurable time dilation, which must be corrected for or GPS positions would drift significantly.",
      },
    },
    {
      id: 'modernphys-e1',
      part: 'challenge',
      conceptSlug: 'radioactivity-and-its-uses',
      conceptTitle: 'Radioactivity and Its Uses',
      question: {
        id: 'modernphys-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A radioactive sample starts with 800 atoms and decays to 50 atoms. If the half-life is 3 hours, how many hours have passed?',
        hints: ['Find how many times 800 must be halved to reach 50, then multiply by the half-life.'],
        correctAnswer: 12,
        explanation: '800 to 400 to 200 to 100 to 50 is 4 halvings. t = 4 times 3 = 12 hours.',
      },
    },
    {
      id: 'modernphys-e2',
      part: 'challenge',
      conceptSlug: 'special-theory-of-relativity',
      conceptTitle: 'Principle of Special Theory of Relativity',
      question: {
        id: 'modernphys-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A muon travels at a speed such that its Lorentz factor gamma equals 10. Find v/c.',
        hints: ['Rearrange gamma = 1/sqrt(1 minus (v/c) squared) to solve for v/c.'],
        correctAnswer: 0.995,
        tolerance: 0.002,
        explanation: '1/gamma = 0.1, so 1-(v/c) squared = 0.01, giving (v/c) squared = 0.99, so v/c approximately 0.995.',
      },
    },
  ],
};
