import type { Assessment } from '@/types/content';

export const chapter10BAssessment: Assessment = {
  id: 'trigonometry-advanced-assessment',
  questions: [
    {
      id: 'trig2-a1',
      part: 'concept',
      conceptSlug: 'the-quadrants-and-signs-of-trigonometric-ratios',
      conceptTitle: 'The Quadrants and Signs of Trigonometric Ratios',
      question: {
        id: 'trig2-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'In Quadrant III, which trigonometric ratio is positive?',
        options: [
          { id: 'a', text: 'Sine' },
          { id: 'b', text: 'Cosine' },
          { id: 'c', text: 'Tangent' },
          { id: 'd', text: 'None of them' },
        ],
        correctOptionId: 'c',
        hints: ['Recall the ASTC rule.'],
        explanation: 'In Quadrant III, both sin and cos are negative, so their quotient, tan, is positive.',
      },
    },
    {
      id: 'trig2-a2',
      part: 'concept',
      conceptSlug: 'trigonometric-ratios-of-quadrantal-angles',
      conceptTitle: 'Trigonometric Ratios of Quadrantal Angles',
      question: {
        id: 'trig2-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'At which of these angles is tan θ undefined?',
        options: [
          { id: 'a', text: '0°' },
          { id: 'b', text: '90°' },
          { id: 'c', text: '180°' },
          { id: 'd', text: '360°' },
        ],
        correctOptionId: 'b',
        hints: ['tan is undefined wherever cos = 0.'],
        explanation: 'At 90°, x=0, so tanθ=y/x requires dividing by zero — undefined.',
      },
    },
    {
      id: 'trig2-b1',
      part: 'formula-application',
      conceptSlug: 'the-pythagorean-identity',
      conceptTitle: 'The Pythagorean Identity',
      question: {
        id: 'trig2-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Given sin θ = 0.28 and θ is in Quadrant I, find cos θ.',
        hints: ['cos²θ = 1 − sin²θ.'],
        correctAnswer: 0.96,
        tolerance: 0.01,
        explanation: 'cos²θ = 1 − 0.0784 = 0.9216, √0.9216 = 0.96 (positive, since QI).',
      },
    },
    {
      id: 'trig2-b2',
      part: 'formula-application',
      conceptSlug: 'the-law-of-sines',
      conceptTitle: 'The Law of Sines',
      question: {
        id: 'trig2-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In triangle JKL, angle J = 90°, angle K = 30°, and side j = 20. Find side k.',
        hints: ['j/sinJ = k/sinK.'],
        correctAnswer: 10,
        explanation: '20/sin90° = k/sin30° → k = 20 × 0.5/1 = 10.',
      },
    },
    {
      id: 'trig2-c1',
      part: 'problem-solving',
      conceptSlug: 'the-law-of-cosines',
      conceptTitle: 'The Law of Cosines',
      question: {
        id: 'trig2-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In triangle ABC, a = 5, b = 12, and angle C = 90°. Find side c.',
        hints: ['cos90°=0, so this reduces to Pythagoras.'],
        correctAnswer: 13,
        explanation: 'c² = 25 + 144 − 0 = 169, c = 13.',
      },
    },
    {
      id: 'trig2-c2',
      part: 'problem-solving',
      conceptSlug: 'the-basic-acute-angle',
      conceptTitle: 'The Basic Acute Angle',
      question: {
        id: 'trig2-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find sin 300° using the basic acute angle. (Give your answer to 3 decimal places.)',
        hints: ['300° is in Quadrant IV: α = 360°−300° = 60°.', 'Sine is negative in Quadrant IV.'],
        correctAnswer: -0.866,
        tolerance: 0.01,
        explanation: 'α=60°, sin negative in QIV, so sin300° = −sin60° ≈ −0.866.',
      },
    },
    {
      id: 'trig2-d1',
      part: 'real-life-application',
      conceptSlug: 'bearings-and-solving-triangle-problems',
      conceptTitle: 'Bearings and Solving Triangle Problems',
      question: {
        id: 'trig2-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A plane flies 100 km on a bearing of 070°, then turns and flies 100 km on a bearing of 160°. What is the interior angle of the flight path at the turning point?',
        options: [
          { id: 'a', text: '90°' },
          { id: 'b', text: '70°' },
          { id: 'c', text: '160°' },
          { id: 'd', text: '110°' },
        ],
        correctOptionId: 'a',
        hints: ['Reverse bearing = 070°+180° = 250°.', 'Interior angle = |250°−160°|.'],
        explanation: 'Reverse bearing is 250°; the interior angle is |250°−160°| = 90°.',
      },
    },
    {
      id: 'trig2-d2',
      part: 'real-life-application',
      conceptSlug: 'the-area-of-a-triangle-using-sine',
      conceptTitle: 'The Area of a Triangle Using Sine',
      question: {
        id: 'trig2-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A surveyor measures two sides of a triangular plot as 40 m and 25 m, with a 90° angle between them, but cannot measure the height directly. Which formula should they use for the area?',
        options: [
          { id: 'a', text: 'Area = ½ab·sinC' },
          { id: 'b', text: 'Area = ½ × base × height, measuring the height by eye' },
          { id: 'c', text: 'Area = a × b' },
          { id: 'd', text: 'Area = a + b' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation the sine area formula is designed for.'],
        explanation: 'Area = ½ab·sinC computes the area directly from the two measured sides and the included angle, with no height measurement needed.',
      },
    },
    {
      id: 'trig2-e1',
      part: 'challenge',
      conceptSlug: 'the-law-of-cosines',
      conceptTitle: 'The Law of Cosines',
      question: {
        id: 'trig2-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why does the Law of Cosines reduce exactly to the Pythagorean theorem when C = 90°?',
        options: [
          { id: 'a', text: 'Because cos90° = 0, which eliminates the −2ab·cosC term entirely' },
          { id: 'b', text: 'Because all triangles with a 90° angle are equilateral' },
          { id: 'c', text: 'It is a coincidence with no underlying reason' },
          { id: 'd', text: 'Because sin90° = 0' },
        ],
        correctOptionId: 'a',
        hints: ['Substitute cos90° into the formula.'],
        explanation: 'cos90°=0, so −2ab·cos90°=0, leaving exactly c²=a²+b² — the Pythagorean theorem.',
      },
    },
    {
      id: 'trig2-e2',
      part: 'challenge',
      conceptSlug: 'the-quadrants-and-signs-of-trigonometric-ratios',
      conceptTitle: 'The Quadrants and Signs of Trigonometric Ratios',
      question: {
        id: 'trig2-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Given tan θ = 3/4 and θ is in Quadrant III (where both sin and cos are negative), find sin θ.',
        hints: ['Use the 3-4-5 reference triangle.', 'Apply the correct Quadrant III sign.'],
        correctAnswer: -0.6,
        explanation: 'Reference triangle 3-4-5 gives sin of the acute angle = 3/5=0.6; in QIII sine is negative, so sinθ = −0.6.',
      },
    },
  ],
};
