import type { Assessment } from '@/types/content';

export const chapter5AWorkEnergyAssessment: Assessment = {
  id: 'work-and-energy-assessment',
  questions: [
    {
      id: 'work-energy-a1',
      part: 'concept',
      conceptSlug: 'work-done-a-level',
      conceptTitle: 'Work Done',
      question: {
        id: 'work-energy-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'A weightlifter holds a barbell perfectly still above their head for 10 seconds. How much work do they do on the barbell during this time?',
        hints: ['Work requires the object to move in the direction of the force.'],
        options: [
          { id: 'a', text: 'A large amount' },
          { id: 'b', text: 'Zero' },
          { id: 'c', text: 'It depends on the barbell\'s mass' },
          { id: 'd', text: 'A small, non-zero amount' },
        ],
        correctOptionId: 'b',
        explanation: 'Since the barbell does not move at all, zero distance means zero work is done on it, in the physics sense.',
      },
    },
    {
      id: 'work-energy-a2',
      part: 'concept',
      conceptSlug: 'kinetic-energy-a-level',
      conceptTitle: 'Kinetic Energy',
      question: {
        id: 'work-energy-a2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the kinetic energy of a 0.5 kg ball moving at 10 m/s.',
        hints: ['KE = ½mv².', '½ × 0.5 × 10².'],
        correctAnswer: 25,
        unit: 'J',
        explanation: 'KE = ½ × 0.5 × 100 = 25 J.',
      },
    },
    {
      id: 'work-energy-b1',
      part: 'formula-application',
      conceptSlug: 'power-a-level',
      conceptTitle: 'Power',
      question: {
        id: 'work-energy-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A pump does 12,000 J of work in 3 minutes. Find its power. (Round to the nearest whole number.)',
        hints: ['Convert 3 minutes to seconds first: 3 × 60 = 180 s.', 'P = W/t.'],
        correctAnswer: 67,
        tolerance: 1,
        unit: 'W',
        explanation: 'P = 12,000/180 ≈ 66.7 W ≈ 67 W.',
      },
    },
    {
      id: 'work-energy-b2',
      part: 'formula-application',
      conceptSlug: 'gravitational-potential-energy-a-level',
      conceptTitle: 'Gravitational Potential Energy',
      question: {
        id: 'work-energy-b2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the GPE of a 20 kg object at a height of 8 m (g = 9.8 m/s²).',
        hints: ['GPE = mgh.', '20 × 9.8 × 8.'],
        correctAnswer: 1568,
        unit: 'J',
        explanation: 'GPE = 20 × 9.8 × 8 = 1568 J.',
      },
    },
    {
      id: 'work-energy-c1',
      part: 'problem-solving',
      conceptSlug: 'elastic-potential-energy-a-level',
      conceptTitle: 'Elastic Potential Energy',
      question: {
        id: 'work-energy-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A spring with spring constant 300 N/m is compressed by 0.08 m. Find the elastic potential energy stored.',
        hints: ['EPE = ½kx².', '½ × 300 × 0.08².'],
        correctAnswer: 0.96,
        unit: 'J',
        explanation: 'EPE = ½ × 300 × 0.0064 = 0.96 J.',
      },
    },
    {
      id: 'work-energy-c2',
      part: 'problem-solving',
      conceptSlug: 'conservation-of-energy-a-level',
      conceptTitle: 'Conservation of Energy',
      question: {
        id: 'work-energy-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A pendulum bob of mass 0.3 kg swings down from a height of 0.2 m above its lowest point. Ignoring air resistance, find its speed at the lowest point (g = 9.8 m/s²). (Round to 2 decimal places.)',
        hints: ['mgh = ½mv², so v = √(2gh).', '√(2 × 9.8 × 0.2).'],
        correctAnswer: 1.98,
        tolerance: 0.05,
        unit: 'm/s',
        explanation: 'v = √(2×9.8×0.2) = √3.92 ≈ 1.98 m/s.',
      },
    },
    {
      id: 'work-energy-d1',
      part: 'real-life-application',
      conceptSlug: 'work-done-a-level',
      conceptTitle: 'Work Done',
      question: {
        id: 'work-energy-d1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A tow truck pulls a broken-down car with a force of 2000 N over a distance of 15 m. Find the work done.',
        hints: ['W = Fd.', '2000 × 15.'],
        correctAnswer: 30000,
        unit: 'J',
        explanation: 'W = 2000 × 15 = 30,000 J.',
      },
    },
    {
      id: 'work-energy-d2',
      part: 'real-life-application',
      conceptSlug: 'kinetic-energy-a-level',
      conceptTitle: 'Kinetic Energy',
      question: {
        id: 'work-energy-d2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "A 900 kg car's speed increases from 10 m/s to 20 m/s. Find the increase in its kinetic energy.",
        hints: ['Find KE at each speed, then subtract.', '½×900×20² − ½×900×10².'],
        correctAnswer: 135000,
        unit: 'J',
        explanation: 'ΔKE = (½×900×400) − (½×900×100) = 180,000 − 45,000 = 135,000 J.',
      },
    },
    {
      id: 'work-energy-e1',
      part: 'challenge',
      conceptSlug: 'conservation-of-energy-a-level',
      conceptTitle: 'Conservation of Energy',
      question: {
        id: 'work-energy-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A 2 kg block slides from rest down a frictionless ramp, dropping a height of 1.5 m, then slides onto a rough horizontal surface where friction brings it to rest after 3 m. Find the average friction force (g = 9.8 m/s²).',
        hints: ['All the GPE lost on the ramp converts to KE, which is then removed entirely by friction over the 3 m.', 'F(friction) × 3 = mgh.'],
        correctAnswer: 9.8,
        unit: 'N',
        explanation: 'mgh = 2×9.8×1.5 = 29.4 J. F(friction) = 29.4/3 = 9.8 N.',
      },
    },
    {
      id: 'work-energy-e2',
      part: 'challenge',
      conceptSlug: 'power-a-level',
      conceptTitle: 'Power',
      question: {
        id: 'work-energy-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A crane lifts a 500 kg load a height of 6 m in 4 s. Find the power required (g = 9.8 m/s²).',
        hints: ['First find the work done against gravity: W = mgh.', 'Then P = W/t.'],
        correctAnswer: 7350,
        unit: 'W',
        explanation: 'W = 500×9.8×6 = 29,400 J. P = 29,400/4 = 7350 W.',
      },
    },
  ],
};
