import type { Assessment } from '@/types/content';

export const chapter1CRotationAssessment: Assessment = {
  id: 'rotational-motion-assessment',
  questions: [
    {
      id: 'rotmot-a1',
      part: 'concept',
      conceptSlug: 'angular-displacement',
      conceptTitle: 'Angular Displacement',
      question: {
        id: 'rotmot-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A point on a wheel of radius 5 m travels an arc length of 15 m. Find its angular displacement in radians.',
        hints: ['θ = s/r.'],
        correctAnswer: 3,
        explanation: 'θ = 15/5 = 3 rad.',
      },
    },
    {
      id: 'rotmot-a2',
      part: 'concept',
      conceptSlug: 'angular-velocity',
      conceptTitle: 'Angular Velocity',
      question: {
        id: 'rotmot-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A blade turns through 20 rad in 5 s. Find its average angular velocity.',
        hints: ['ω = Δθ/Δt.'],
        correctAnswer: 4,
        explanation: 'ω = 20/5 = 4 rad/s.',
      },
    },
    {
      id: 'rotmot-b1',
      part: 'formula-application',
      conceptSlug: 'angular-acceleration',
      conceptTitle: 'Angular Acceleration',
      question: {
        id: 'rotmot-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A rotor\'s angular velocity increases from 4 rad/s to 20 rad/s in 8 s. Find its angular acceleration.',
        hints: ['α = Δω/Δt.'],
        correctAnswer: 2,
        explanation: 'α = (20−4)/8 = 16/8 = 2 rad/s².',
      },
    },
    {
      id: 'rotmot-b2',
      part: 'formula-application',
      conceptSlug: 'linear-and-angular-quantity-relationships',
      conceptTitle: 'Linear and Angular Quantity Relationships',
      question: {
        id: 'rotmot-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A point at radius 1.2 m rotates at ω=5 rad/s. Find its linear speed.',
        hints: ['v = rω.'],
        correctAnswer: 6,
        explanation: 'v = 1.2 × 5 = 6 m/s.',
      },
    },
    {
      id: 'rotmot-c1',
      part: 'problem-solving',
      conceptSlug: 'rotational-kinematics-equations',
      conceptTitle: 'Rotational Kinematics Equations',
      question: {
        id: 'rotmot-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A disc starts at ω₀=3 rad/s and accelerates at α=2 rad/s² for 5 s. Find its angular displacement θ.',
        hints: ['θ = ω₀t + ½αt².'],
        correctAnswer: 40,
        explanation: 'θ = 3(5) + 0.5(2)(25) = 15+25 = 40 rad.',
      },
    },
    {
      id: 'rotmot-c2',
      part: 'problem-solving',
      conceptSlug: 'tangential-velocity-and-tangential-acceleration',
      conceptTitle: 'Tangential Velocity and Tangential Acceleration',
      question: {
        id: 'rotmot-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A point on a disc of radius 0.25 m experiences an angular acceleration of 8 rad/s². Find its tangential acceleration.',
        hints: ['aₜ = rα.'],
        correctAnswer: 2,
        explanation: 'aₜ = 0.25 × 8 = 2 m/s².',
      },
    },
    {
      id: 'rotmot-d1',
      part: 'real-life-application',
      conceptSlug: 'centripetal-acceleration',
      conceptTitle: 'Centripetal Acceleration',
      question: {
        id: 'rotmot-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A satellite orbits Earth at constant speed in a circular orbit. Why does it still have acceleration?',
        hints: ['Acceleration is any change in velocity — speed or direction.'],
        options: [
          { id: 'a', text: 'Because its direction of motion is constantly changing' },
          { id: 'b', text: 'Because its speed is increasing' },
          { id: 'c', text: 'Because gravity does no work on it' },
          { id: 'd', text: 'It does not actually accelerate' },
        ],
        correctOptionId: 'a',
        explanation: 'Even at constant speed, continuously changing direction is itself an acceleration — the centripetal acceleration, directed toward Earth\'s center.',
      },
    },
    {
      id: 'rotmot-d2',
      part: 'real-life-application',
      conceptSlug: 'period-frequency-and-revolution',
      conceptTitle: 'Period, Frequency and Revolution',
      question: {
        id: 'rotmot-d2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'A turbine blade completes 600 revolutions per minute. Approximately what is its frequency in Hz?',
        hints: ['Convert revolutions per minute to revolutions per second.'],
        options: [
          { id: 'a', text: '10 Hz' },
          { id: 'b', text: '600 Hz' },
          { id: 'c', text: '60 Hz' },
          { id: 'd', text: '1 Hz' },
        ],
        correctOptionId: 'a',
        explanation: '600 revolutions per minute = 600/60 = 10 revolutions per second = 10 Hz.',
      },
    },
    {
      id: 'rotmot-e1',
      part: 'challenge',
      conceptSlug: 'rotational-kinematics-equations',
      conceptTitle: 'Rotational Kinematics Equations',
      question: {
        id: 'rotmot-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A wheel decelerates from ω₀=30 rad/s to rest at a constant rate over 6 s. Through how many radians does it turn before stopping?',
        hints: ['Find α first, then use θ = ω₀t + ½αt² (or ω²=ω₀²+2αθ).'],
        correctAnswer: 90,
        explanation: 'α = (0−30)/6 = −5 rad/s². θ = 30(6) + 0.5(−5)(36) = 180−90 = 90 rad.',
      },
    },
    {
      id: 'rotmot-e2',
      part: 'challenge',
      conceptSlug: 'centripetal-acceleration',
      conceptTitle: 'Centripetal Acceleration',
      question: {
        id: 'rotmot-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A ball on a string moves in a horizontal circle of radius 0.8 m, completing 2 revolutions per second. Find its centripetal acceleration. (Use ω=2πf.)',
        hints: ['First find ω=2πf, then apply a_c=ω²r.'],
        correctAnswer: 126.3,
        tolerance: 1,
        explanation: 'ω = 2π(2) ≈ 12.566 rad/s. a_c = ω²r = 12.566² × 0.8 ≈ 126.3 m/s².',
      },
    },
  ],
};
