import type { Formula } from '@/types/content';

export const chapter1CRotationFormulas: Record<string, Formula> = {
  'angular-displacement-formula': {
    slug: 'angular-displacement-formula',
    name: 'Angular Displacement',
    expression: 'θ = s / r',
    meaning: 'The angle swept out by a rotating object, measured in radians, found from the arc length traveled divided by the radius.',
    variables: [
      { symbol: 'θ', meaning: 'angular displacement, in radians (rad)' },
      { symbol: 's', meaning: 'arc length traveled along the circular path, in metres (m)' },
      { symbol: 'r', meaning: 'radius of the circular path, in metres (m)' },
    ],
    whenToUse: 'Whenever the arc length and radius of a circular path are known, and the angle swept (in radians) is needed.',
    relatedConceptSlugs: ['angular-displacement'],
  },
  'angular-velocity-formula': {
    slug: 'angular-velocity-formula',
    name: 'Angular Velocity',
    expression: 'ω = Δθ / Δt',
    meaning: 'The rate at which angular displacement changes over time — how fast something is rotating.',
    variables: [
      { symbol: 'ω', meaning: 'angular velocity, in radians per second (rad/s)' },
      { symbol: 'Δθ', meaning: 'change in angular displacement, in radians (rad)' },
      { symbol: 'Δt', meaning: 'time interval, in seconds (s)' },
    ],
    whenToUse: 'Whenever the rate of rotation needs to be found from the angle swept and the time it took.',
    relatedConceptSlugs: ['angular-velocity'],
  },
  'angular-acceleration-formula': {
    slug: 'angular-acceleration-formula',
    name: 'Angular Acceleration',
    expression: 'α = Δω / Δt',
    meaning: 'The rate at which angular velocity changes over time — how quickly a rotation speeds up or slows down.',
    variables: [
      { symbol: 'α', meaning: 'angular acceleration, in radians per second squared (rad/s²)' },
      { symbol: 'Δω', meaning: 'change in angular velocity, in radians per second (rad/s)' },
      { symbol: 'Δt', meaning: 'time interval, in seconds (s)' },
    ],
    whenToUse: 'Whenever a rotation is speeding up or slowing down, and the rate of that change is needed.',
    relatedConceptSlugs: ['angular-acceleration'],
  },
  'rotational-kinematics-formula': {
    slug: 'rotational-kinematics-formula',
    name: 'Rotational Kinematics Equations',
    expression: 'ω = ω₀ + αt;   θ = ω₀t + ½αt²;   ω² = ω₀² + 2αθ',
    meaning: 'The rotational counterparts of the straight-line "suvat" equations — they relate angular displacement, initial and final angular velocity, angular acceleration, and time, for constant angular acceleration.',
    variables: [
      { symbol: 'ω₀', meaning: 'initial angular velocity, in radians per second (rad/s)' },
      { symbol: 'ω', meaning: 'final angular velocity, in radians per second (rad/s)' },
      { symbol: 'α', meaning: 'constant angular acceleration, in radians per second squared (rad/s²)' },
      { symbol: 't', meaning: 'time elapsed, in seconds (s)' },
      { symbol: 'θ', meaning: 'angular displacement over that time, in radians (rad)' },
    ],
    whenToUse: 'Whenever a rotation has constant angular acceleration, and any three of the five quantities (ω₀, ω, α, t, θ) are known — pick the equation missing the one unknown that is not needed.',
    relatedConceptSlugs: ['rotational-kinematics-equations'],
  },
  'linear-angular-relations-formula': {
    slug: 'linear-angular-relations-formula',
    name: 'Linear Speed from Angular Velocity',
    expression: 'v = rω',
    meaning: 'The linear (tangential) speed of a point on a rotating object equals its distance from the axis times the angular velocity.',
    variables: [
      { symbol: 'v', meaning: 'linear (tangential) speed, in metres per second (m/s)' },
      { symbol: 'r', meaning: 'distance from the axis of rotation, in metres (m)' },
      { symbol: 'ω', meaning: 'angular velocity, in radians per second (rad/s)' },
    ],
    whenToUse: 'Whenever converting between how fast something spins (angular velocity) and how fast a specific point on it moves through space (linear speed).',
    relatedConceptSlugs: ['linear-and-angular-quantity-relationships'],
  },
  'tangential-acceleration-formula': {
    slug: 'tangential-acceleration-formula',
    name: 'Tangential Acceleration',
    expression: 'aₜ = rα',
    meaning: 'The linear acceleration of a point on a rotating object, directed along its direction of travel (tangent to the circle) — caused by the rotation speeding up or slowing down.',
    variables: [
      { symbol: 'aₜ', meaning: 'tangential acceleration, in metres per second squared (m/s²)' },
      { symbol: 'r', meaning: 'distance from the axis of rotation, in metres (m)' },
      { symbol: 'α', meaning: 'angular acceleration, in radians per second squared (rad/s²)' },
    ],
    whenToUse: 'Whenever a rotating object\'s angular acceleration needs to be converted into the linear acceleration of a specific point along its direction of motion.',
    relatedConceptSlugs: ['tangential-velocity-and-tangential-acceleration'],
  },
  'rotational-centripetal-acceleration-formula': {
    slug: 'rotational-centripetal-acceleration-formula',
    name: 'Centripetal Acceleration',
    expression: 'a_c = v² / r = ω²r',
    meaning: 'The acceleration of an object moving on a circular path, always directed toward the centre of the circle — it changes the direction of motion, not the speed.',
    variables: [
      { symbol: 'a_c', meaning: 'centripetal acceleration, in metres per second squared (m/s²)' },
      { symbol: 'v', meaning: 'linear (tangential) speed, in metres per second (m/s)' },
      { symbol: 'r', meaning: 'radius of the circular path, in metres (m)' },
      { symbol: 'ω', meaning: 'angular velocity, in radians per second (rad/s)' },
    ],
    whenToUse: 'Whenever an object moves on a circular path at constant speed and the acceleration responsible for curving that path is needed.',
    relatedConceptSlugs: ['centripetal-acceleration'],
  },
  'rotational-period-frequency-formula': {
    slug: 'rotational-period-frequency-formula',
    name: 'Period, Frequency and Angular Velocity',
    expression: 'T = 1 / f;   ω = 2πf = 2π / T',
    meaning: 'Connects how long one full revolution takes (period), how many revolutions happen per second (frequency), and the angular velocity of the rotation.',
    variables: [
      { symbol: 'T', meaning: 'period — time for one full revolution, in seconds (s)' },
      { symbol: 'f', meaning: 'frequency — revolutions per second, in hertz (Hz)' },
      { symbol: 'ω', meaning: 'angular velocity, in radians per second (rad/s)' },
    ],
    whenToUse: 'Whenever converting between how often something rotates (frequency), how long one rotation takes (period), and its angular velocity.',
    relatedConceptSlugs: ['period-frequency-and-revolution'],
  },
};
