import type { Assessment } from '@/types/content';

export const chapter8BAssessment: Assessment = {
  id: 'areas-of-similar-triangles-assessment',
  questions: [
    {
      id: 'ast-a1',
      part: 'concept',
      conceptSlug: 'the-area-ratio-theorem-for-similar-triangles',
      conceptTitle: 'The Area Ratio Theorem for Similar Triangles',
      question: {
        id: 'ast-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Two similar triangles have a side ratio of 2:3. What is the ratio of their areas?',
        options: [
          { id: 'a', text: '4:9' },
          { id: 'b', text: '2:3' },
          { id: 'c', text: '8:27' },
          { id: 'd', text: '6:9' },
        ],
        correctOptionId: 'a',
        hints: ['Square the side ratio.'],
        explanation: '(2/3)² = 4/9, so the area ratio is 4:9.',
      },
    },
    {
      id: 'ast-a2',
      part: 'concept',
      conceptSlug: 'perimeter-and-area-ratios-together',
      conceptTitle: 'Perimeter and Area Ratios Together',
      question: {
        id: 'ast-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'For similar triangles, does the perimeter scale the same way as the area?',
        options: [
          { id: 'a', text: 'No — perimeter scales linearly (same ratio as the sides), area scales squared' },
          { id: 'b', text: 'Yes, both scale squared' },
          { id: 'c', text: 'Yes, both scale linearly' },
          { id: 'd', text: 'No — perimeter scales squared, area scales linearly' },
        ],
        correctOptionId: 'a',
        hints: ['Perimeter is a sum of lengths; area is a product of two lengths.'],
        explanation: 'Perimeter scales linearly with the side ratio; only area scales with the square of the side ratio.',
      },
    },
    {
      id: 'ast-b1',
      part: 'formula-application',
      conceptSlug: 'the-area-ratio-theorem-for-similar-triangles',
      conceptTitle: 'The Area Ratio Theorem for Similar Triangles',
      question: {
        id: 'ast-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two similar triangles have corresponding sides 4 and 10. The smaller triangle has area 12. Find the larger triangle\'s area.',
        hints: ['Scale factor = 10/4 = 2.5.', 'Area ratio = 2.5² = 6.25.'],
        correctAnswer: 75,
        explanation: 'k = 10/4 = 2.5, k² = 6.25. Larger area = 12 × 6.25 = 75.',
      },
    },
    {
      id: 'ast-b2',
      part: 'formula-application',
      conceptSlug: 'perimeter-and-area-ratios-together',
      conceptTitle: 'Perimeter and Area Ratios Together',
      question: {
        id: 'ast-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two similar triangles have corresponding sides 7 and 21. The smaller triangle\'s perimeter is 15. Find the larger triangle\'s perimeter.',
        hints: ['Scale factor = 21/7 = 3.', 'Perimeter scales the same way as the sides.'],
        correctAnswer: 45,
        explanation: 'k = 21/7 = 3. Larger perimeter = 15 × 3 = 45.',
      },
    },
    {
      id: 'ast-c1',
      part: 'problem-solving',
      conceptSlug: 'applying-the-area-ratio-theorem',
      conceptTitle: 'Applying the Area Ratio Theorem',
      question: {
        id: 'ast-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two similar triangles have areas 27 and 48. A side of the smaller triangle is 6. Find the corresponding side of the larger triangle.',
        hints: ['Side ratio = √(48/27).', '48/27 = 16/9.'],
        correctAnswer: 8,
        explanation: '48/27 = 16/9, √(16/9) = 4/3. Larger side = 6 × 4/3 = 8.',
      },
    },
    {
      id: 'ast-c2',
      part: 'problem-solving',
      conceptSlug: 'perimeter-and-area-ratios-together',
      conceptTitle: 'Perimeter and Area Ratios Together',
      question: {
        id: 'ast-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two similar triangles have a perimeter ratio of 5:8. The larger triangle\'s area is 128. Find the smaller triangle\'s area.',
        hints: ['The perimeter ratio equals the side ratio.', 'Area ratio = (5/8)².'],
        correctAnswer: 50,
        explanation: 'Side ratio = 5/8, so area ratio = 25/64. Smaller area = 128 × 25/64 = 50.',
      },
    },
    {
      id: 'ast-d1',
      part: 'real-life-application',
      conceptSlug: 'the-area-ratio-theorem-for-similar-triangles',
      conceptTitle: 'The Area Ratio Theorem for Similar Triangles',
      question: {
        id: 'ast-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A garden designer doubles every side length of a triangular flower bed. If the original needed 5 bags of mulch to cover it, how many bags will the new bed need?',
        options: [
          { id: 'a', text: '20 bags' },
          { id: 'b', text: '10 bags' },
          { id: 'c', text: '15 bags' },
          { id: 'd', text: '25 bags' },
        ],
        correctOptionId: 'a',
        hints: ['Mulch coverage follows area, which scales by k².'],
        explanation: 'k=2, so area scales by k²=4. 5 × 4 = 20 bags.',
      },
    },
    {
      id: 'ast-d2',
      part: 'real-life-application',
      conceptSlug: 'perimeter-and-area-ratios-together',
      conceptTitle: 'Perimeter and Area Ratios Together',
      question: {
        id: 'ast-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A fencing contractor quotes a triangular yard scaled up by a factor of 3 in every linear dimension. How does the amount of fencing needed change?',
        options: [
          { id: 'a', text: 'It triples' },
          { id: 'b', text: 'It becomes 9 times as much' },
          { id: 'c', text: 'It stays the same' },
          { id: 'd', text: 'It becomes 1.5 times as much' },
        ],
        correctOptionId: 'a',
        hints: ['Fencing follows the perimeter, which scales linearly.'],
        explanation: 'Fencing follows perimeter, which scales directly with the scale factor: it triples.',
      },
    },
    {
      id: 'ast-e1',
      part: 'challenge',
      conceptSlug: 'perimeter-and-area-ratios-together',
      conceptTitle: 'Perimeter and Area Ratios Together',
      question: {
        id: 'ast-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why does perimeter scale linearly with the scale factor k, while area scales with k²?',
        options: [
          { id: 'a', text: 'Perimeter is a sum of side lengths, each scaling by k once; area is a product of two linear dimensions, each scaling by k, so it scales by k×k=k²' },
          { id: 'b', text: 'Perimeter and area are unrelated to scale factor entirely' },
          { id: 'c', text: 'It is simply a rule with no underlying reason' },
          { id: 'd', text: 'Area only scales by k² for right triangles' },
        ],
        correctOptionId: 'a',
        hints: ['Think about what perimeter and area are built from: sums versus products of lengths.'],
        explanation: 'Perimeter is a sum of lengths (scales once by k); area is a product of two lengths (scales by k twice, i.e. k²).',
      },
    },
    {
      id: 'ast-e2',
      part: 'challenge',
      conceptSlug: 'applying-the-area-ratio-theorem',
      conceptTitle: 'Applying the Area Ratio Theorem',
      question: {
        id: 'ast-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two similar triangles have an area ratio of 49:4. The smaller triangle\'s longest side is 8. Find the larger triangle\'s longest side.',
        hints: ['Side ratio = √(49/4).'],
        correctAnswer: 28,
        explanation: '√(49/4) = 7/2. Larger side = 8 × 7/2 = 28.',
      },
    },
  ],
};
