import type { Assessment } from '@/types/content';

export const chapter11CInductionAssessment: Assessment = {
  id: 'electromagnetic-induction-generation-and-distribution-assessment',
  questions: [
    {
      id: 'induction-a1',
      part: 'concept',
      conceptSlug: 'alternating-current',
      conceptTitle: 'Alternating Current',
      question: {
        id: 'induction-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An AC supply has a peak voltage of 325 V. Find its RMS voltage, rounded to the nearest whole volt.',
        hints: ['V_rms = V0 / sqrt(2).'],
        correctAnswer: 230,
        tolerance: 1,
        explanation: 'V_rms = 325/1.4142 approximately 230 V.',
      },
    },
    {
      id: 'induction-a2',
      part: 'concept',
      conceptSlug: 'electromagnetic-induction-basics',
      conceptTitle: 'Electromagnetic Induction',
      question: {
        id: 'induction-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A loop of area 0.04 square metres sits perpendicular to a 0.6 T field. Find the magnetic flux.',
        hints: ['Phi = BA, with theta = 0 degrees.'],
        correctAnswer: 0.024,
        explanation: 'Phi = (0.6)(0.04) = 0.024 Wb.',
      },
    },
    {
      id: 'induction-b1',
      part: 'formula-application',
      conceptSlug: 'faradays-law-and-lenzs-law',
      conceptTitle: "Faraday's Law and Lenz's Law",
      question: {
        id: 'induction-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A coil of 50 turns experiences a flux change of 0.03 Wb over 0.6 seconds. Find the magnitude of the induced EMF.',
        hints: ['epsilon = N(DeltaPhi/Deltat).'],
        correctAnswer: 2.5,
        explanation: 'epsilon = 50(0.03/0.6) = 50(0.05) = 2.5 V.',
      },
    },
    {
      id: 'induction-b2',
      part: 'formula-application',
      conceptSlug: 'applications-of-electromagnetic-induction',
      conceptTitle: 'Applications of Electromagnetic Induction',
      question: {
        id: 'induction-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A transformer has 800 turns on its primary and 200 on its secondary, with 100 V applied to the primary. Find the secondary voltage.',
        hints: ['Vs = Vp(Ns/Np).'],
        correctAnswer: 25,
        explanation: 'Vs = 100(200/800) = 100(0.25) = 25 V.',
      },
    },
    {
      id: 'induction-c1',
      part: 'problem-solving',
      conceptSlug: 'power-transmission',
      conceptTitle: 'Power Transmission',
      question: {
        id: 'induction-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A power station transmits 200000 W at 20000 V through a line of resistance 4 ohms. Find the power lost.',
        hints: ['Find I=P/V first, then apply P_loss=I squared R.'],
        correctAnswer: 400,
        explanation: 'I = 200000/20000 = 10 A. P_loss = (10 squared)(4) = 400 W.',
      },
    },
    {
      id: 'induction-c2',
      part: 'problem-solving',
      conceptSlug: 'house-wiring-principles',
      conceptTitle: 'Principles of House Wiring',
      question: {
        id: 'induction-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Five appliances draw 1 A, 2 A, 1.5 A, 0.5 A, and 3 A on the same household circuit. Find the total current drawn.',
        hints: ['I_total = sum of the individual currents.'],
        correctAnswer: 8,
        explanation: 'I_total = 1+2+1.5+0.5+3 = 8 A.',
      },
    },
    {
      id: 'induction-d1',
      part: 'real-life-application',
      conceptSlug: 'electrical-safety',
      conceptTitle: 'Dangers of Electricity',
      question: {
        id: 'induction-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is it especially dangerous to use an electrical appliance with wet hands?',
        hints: ['Think about how skin resistance changes when wet.'],
        options: [
          { id: 'a', text: 'Wet skin has much lower resistance, allowing a larger, more dangerous shock current for the same voltage' },
          { id: 'b', text: 'Water makes electricity physically weaker' },
          { id: 'c', text: 'Wet skin completely blocks all current' },
          { id: 'd', text: 'Voltage itself increases when skin is wet' },
        ],
        correctOptionId: 'a',
        explanation: 'By I=V/R, lower resistance (from wet skin) produces a larger current for the same voltage, making the shock more dangerous.',
      },
    },
    {
      id: 'induction-d2',
      part: 'real-life-application',
      conceptSlug: 'faradays-law-and-lenzs-law',
      conceptTitle: "Faraday's Law and Lenz's Law",
      question: {
        id: 'induction-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An induction cooktop heats a pan without an open flame. Which principle explains how it works?',
        hints: ['Think about what a rapidly changing magnetic field does to a nearby conductor.'],
        options: [
          { id: 'a', text: 'A changing magnetic field induces eddy currents in the pan, heating it via Joule heating' },
          { id: 'b', text: 'The cooktop directly burns gas beneath the pan' },
          { id: 'c', text: 'It uses infrared light only' },
          { id: 'd', text: 'The pan is heated by static electricity' },
        ],
        correctOptionId: 'a',
        explanation: "A rapidly alternating magnetic field beneath the cooktop induces circulating (eddy) currents directly in the metal pan, which then heat up via Joule heating (H=I squared Rt).",
      },
    },
    {
      id: 'induction-e1',
      part: 'challenge',
      conceptSlug: 'power-transmission',
      conceptTitle: 'Power Transmission',
      question: {
        id: 'induction-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A utility wants to reduce transmission power loss to one quarter of its current value, delivering the same power through the same line. By what factor should the voltage be increased?',
        hints: ['P_loss is proportional to 1/(V squared), since I=P/V.'],
        correctAnswer: 2,
        explanation: 'Since P_loss proportional to 1/(V squared), quartering the loss requires doubling V, since (1/2) squared = 1/4.',
      },
    },
    {
      id: 'induction-e2',
      part: 'challenge',
      conceptSlug: 'applications-of-electromagnetic-induction',
      conceptTitle: 'Applications of Electromagnetic Induction',
      question: {
        id: 'induction-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A step-up transformer converts 400 V to 8000 V, with 50 turns on the primary. Find the number of turns on the secondary.',
        hints: ['Rearrange Vs/Vp=Ns/Np to solve for Ns.'],
        correctAnswer: 1000,
        explanation: 'Ns = Np(Vs/Vp) = 50(8000/400) = 50(20) = 1000 turns.',
      },
    },
  ],
};
