import type { Assessment } from '@/types/content';

export const chapter4APressureAssessment: Assessment = {
  id: 'pressure-assessment',
  questions: [
    {
      id: 'pressure-a1',
      part: 'concept',
      conceptSlug: 'pressure-force-and-area-a-level',
      conceptTitle: 'Pressure, Force and Area',
      question: {
        id: 'pressure-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: "For a similar total force, which produces a GREATER pressure on the ground: an elephant's large, flat foot, or a narrow stiletto heel?",
        hints: ['A smaller area concentrates the same force into a bigger pressure.'],
        options: [
          { id: 'a', text: "The elephant's foot" },
          { id: 'b', text: 'The stiletto heel' },
          { id: 'c', text: 'Both produce exactly the same pressure' },
          { id: 'd', text: 'Pressure does not depend on area' },
        ],
        correctOptionId: 'b',
        explanation: 'The stiletto heel has a much smaller contact area, so the same force is concentrated into a far greater pressure.',
      },
    },
    {
      id: 'pressure-a2',
      part: 'concept',
      conceptSlug: 'hydrometer-a-level',
      conceptTitle: 'The Hydrometer',
      question: {
        id: 'pressure-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A hydrometer floats higher in liquid X than in liquid Y. Which liquid is denser?',
        hints: ['A hydrometer floats higher in a denser liquid.'],
        options: [
          { id: 'a', text: 'Liquid X' },
          { id: 'b', text: 'Liquid Y' },
          { id: 'c', text: 'They must be equally dense' },
          { id: 'd', text: 'Cannot be determined' },
        ],
        correctOptionId: 'a',
        explanation: 'A hydrometer floats higher in the denser liquid, since less volume needs to be displaced to support its weight — so liquid X is denser.',
      },
    },
    {
      id: 'pressure-b1',
      part: 'formula-application',
      conceptSlug: 'pressure-in-fluids-a-level',
      conceptTitle: 'Pressure in Fluids',
      question: {
        id: 'pressure-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the pressure due to 5 m of seawater (density 1030 kg/m³, g = 9.8 m/s²).',
        hints: ['P = hρg.', '5 × 1030 × 9.8.'],
        correctAnswer: 50470,
        unit: 'Pa',
        explanation: 'P = 5 × 1030 × 9.8 = 50,470 Pa.',
      },
    },
    {
      id: 'pressure-b2',
      part: 'formula-application',
      conceptSlug: 'density-a-level',
      conceptTitle: 'Density',
      question: {
        id: 'pressure-b2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A gas sample has a mass of 0.08 kg and a volume of 0.1 m³. Find its density.',
        hints: ['ρ = m/V.', '0.08/0.1.'],
        correctAnswer: 0.8,
        unit: 'kg/m³',
        explanation: 'ρ = 0.08/0.1 = 0.8 kg/m³.',
      },
    },
    {
      id: 'pressure-c1',
      part: 'problem-solving',
      conceptSlug: 'relative-density-a-level',
      conceptTitle: 'Relative Density (Specific Gravity)',
      question: {
        id: 'pressure-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: "A liquid's relative density is 0.92. Find its density (water = 1000 kg/m³).",
        hints: ['Rearrange RD = ρ(substance)/ρ(water).', '0.92 × 1000.'],
        correctAnswer: 920,
        unit: 'kg/m³',
        explanation: 'ρ(substance) = RD × ρ(water) = 0.92 × 1000 = 920 kg/m³.',
      },
    },
    {
      id: 'pressure-c2',
      part: 'problem-solving',
      conceptSlug: 'pressure-force-and-area-a-level',
      conceptTitle: 'Pressure, Force and Area',
      question: {
        id: 'pressure-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A hydraulic press piston of area 0.01 m² needs to produce a pressure of 500,000 Pa. Find the force required.',
        hints: ['Rearrange P = F/A to F = PA.', '500,000 × 0.01.'],
        correctAnswer: 5000,
        unit: 'N',
        explanation: 'F = PA = 500,000 × 0.01 = 5000 N.',
      },
    },
    {
      id: 'pressure-d1',
      part: 'real-life-application',
      conceptSlug: 'pressure-in-fluids-a-level',
      conceptTitle: 'Pressure in Fluids',
      question: {
        id: 'pressure-d1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A submarine dives to a depth of 200 m in seawater (density 1030 kg/m³, g = 9.8 m/s²). Find the pressure due to the water alone at that depth.',
        hints: ['P = hρg.', '200 × 1030 × 9.8.'],
        correctAnswer: 2018800,
        tolerance: 500,
        unit: 'Pa',
        explanation: 'P = 200 × 1030 × 9.8 = 2,018,800 Pa — about 2.02 MPa, showing why submarines need very strong hulls.',
      },
    },
    {
      id: 'pressure-d2',
      part: 'real-life-application',
      conceptSlug: 'hydrometer-a-level',
      conceptTitle: 'The Hydrometer',
      question: {
        id: 'pressure-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'It is much easier to float in the Dead Sea than in an ordinary swimming pool. What is the best explanation?',
        hints: ['Think about what a hydrometer reading would show in each.'],
        options: [
          { id: 'a', text: 'The Dead Sea has much higher relative density (dissolved salt), so less volume needs to be displaced to float' },
          { id: 'b', text: 'The Dead Sea has lower gravity' },
          { id: 'c', text: 'Swimming pools are always deeper' },
          { id: 'd', text: 'Body density changes depending on the sea' },
        ],
        correctOptionId: 'a',
        explanation: "The Dead Sea's extremely high salt content gives it a much higher relative density than fresh or ordinary sea water, so a swimmer (or a hydrometer) needs to displace far less volume to float.",
      },
    },
    {
      id: 'pressure-e1',
      part: 'challenge',
      conceptSlug: 'density-a-level',
      conceptTitle: 'Density',
      question: {
        id: 'pressure-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An irregular rock of mass 350 g is lowered into a measuring cylinder; the water level rises from 100 cm³ to 150 cm³. Find the density of the rock.',
        hints: ['The volume displaced equals the rise in water level.', 'ρ = m/V, with V = 150 − 100.'],
        correctAnswer: 7,
        unit: 'g/cm³',
        explanation: 'Volume displaced = 150 − 100 = 50 cm³. ρ = 350/50 = 7 g/cm³.',
      },
    },
    {
      id: 'pressure-e2',
      part: 'challenge',
      conceptSlug: 'relative-density-a-level',
      conceptTitle: 'Relative Density (Specific Gravity)',
      question: {
        id: 'pressure-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A hydrometer reads 1.15 when floated in a salt solution. Find the density of the salt solution (pure water = 1000 kg/m³).',
        hints: ['The hydrometer reading IS the relative density.', 'ρ(substance) = RD × ρ(water).'],
        correctAnswer: 1150,
        unit: 'kg/m³',
        explanation: 'ρ(substance) = 1.15 × 1000 = 1150 kg/m³.',
      },
    },
  ],
};
