import type { Assessment } from '@/types/content';

export const chapter5HeatAssessment: Assessment = {
  id: 'heat-and-thermal-phenomena-assessment',
  questions: [
    {
      id: 'ht-a1',
      part: 'concept',
      conceptSlug: 'heat-and-internal-energy',
      conceptTitle: 'Heat and Internal Energy',
      question: {
        id: 'ht-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which statement correctly distinguishes heat from internal energy?',
        options: [
          { id: 'a', text: 'Heat is energy in transfer due to a temperature difference; internal energy is the total energy a substance has.' },
          { id: 'b', text: 'They are identical concepts.' },
          { id: 'c', text: 'Internal energy only applies to liquids.' },
          { id: 'd', text: 'Heat is a property an object permanently has.' },
        ],
        correctOptionId: 'a',
        hints: ['One is a process; the other is a stored quantity.'],
        explanation: 'Heat describes energy transfer; internal energy is the total kinetic and potential energy already present in a substance.',
      },
    },
    {
      id: 'ht-a2',
      part: 'concept',
      conceptSlug: 'change-of-state-and-latent-heat',
      conceptTitle: 'Change of State and Latent Heat',
      question: {
        id: 'ht-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does temperature remain constant while a substance melts or boils?',
        options: [
          { id: 'a', text: 'Added energy breaks intermolecular bonds instead of increasing particle kinetic energy.' },
          { id: 'b', text: 'No energy is being added during a state change.' },
          { id: 'c', text: 'Temperature always rises during melting.' },
          { id: 'd', text: 'State changes are unrelated to heat.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about where the energy goes at the molecular level.'],
        explanation: 'During a phase change, energy goes into overcoming intermolecular bonds rather than raising kinetic energy, so temperature plateaus.',
      },
    },
    {
      id: 'ht-a3',
      part: 'concept',
      conceptSlug: 'thermal-capacity',
      conceptTitle: 'Thermal Capacity',
      question: {
        id: 'ht-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What is the key difference between thermal capacity and specific heat capacity?',
        options: [
          { id: 'a', text: 'Thermal capacity depends on an object\'s total mass; specific heat capacity is a per-kilogram material property.' },
          { id: 'b', text: 'They are exactly the same quantity.' },
          { id: 'c', text: 'Specific heat capacity depends on total mass, not thermal capacity.' },
          { id: 'd', text: 'Thermal capacity applies only to gases.' },
        ],
        correctOptionId: 'a',
        hints: ['Which one changes if you double the amount of material?'],
        explanation: 'Thermal capacity is for a specific object (depends on its mass); specific heat capacity is a material property, independent of quantity.',
      },
    },
    {
      id: 'ht-b1',
      part: 'formula-application',
      conceptSlug: 'specific-heat-capacity',
      conceptTitle: 'Specific Heat Capacity',
      question: {
        id: 'ht-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the heat energy needed to raise 3 kg of water by 15°C (c = 4200 J/(kg·°C)).',
        hints: ['Q = mcΔT.'],
        correctAnswer: 189000,
        tolerance: 2000,
        unit: 'J',
        explanation: 'Q = 3 × 4200 × 15 = 189,000 J.',
      },
    },
    {
      id: 'ht-b2',
      part: 'formula-application',
      conceptSlug: 'vaporization-and-specific-latent-heat',
      conceptTitle: 'Vaporization and Specific Latent Heat of Vaporization',
      question: {
        id: 'ht-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the heat energy needed to vaporize 0.1 kg of water at its boiling point (Lᵥ = 2,260,000 J/kg).',
        hints: ['Q = mLᵥ.'],
        correctAnswer: 226000,
        tolerance: 3000,
        unit: 'J',
        explanation: 'Q = 0.1 × 2,260,000 = 226,000 J.',
      },
    },
    {
      id: 'ht-c1',
      part: 'problem-solving',
      conceptSlug: 'law-of-heat-exchange',
      conceptTitle: 'Law of Heat Exchange',
      question: {
        id: 'ht-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: '0.25 kg of water at 95°C is mixed with 0.75 kg of water at 15°C (same c). Find the final temperature.',
        hints: ['0.25(95 − Tf) = 0.75(Tf − 15).'],
        correctAnswer: 35,
        tolerance: 1,
        unit: '°C',
        explanation: '23.75 − 0.25Tf = 0.75Tf − 11.25 → 35 = 1.0Tf → Tf = 35°C.',
      },
    },
    {
      id: 'ht-c2',
      part: 'problem-solving',
      conceptSlug: 'fusion-and-specific-latent-heat',
      conceptTitle: 'Fusion and Specific Latent Heat of Fusion',
      question: {
        id: 'ht-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'How much ice (in kg) can be melted by 668,000 J of heat energy (Lf = 334,000 J/kg)?',
        hints: ['Q = mLf, rearranged: m = Q/Lf.'],
        correctAnswer: 2,
        tolerance: 0.05,
        unit: 'kg',
        explanation: 'm = 668,000/334,000 = 2 kg.',
      },
    },
    {
      id: 'ht-d1',
      part: 'real-life-application',
      conceptSlug: 'specific-heat-capacity',
      conceptTitle: 'Specific Heat Capacity',
      question: {
        id: 'ht-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: "Why do coastal regions typically have milder, more stable temperatures than inland regions?",
        options: [
          { id: 'a', text: "Water's high specific heat capacity lets large bodies of water absorb/release heat with only small temperature changes, moderating nearby air temperature." },
          { id: 'b', text: 'Water has no effect on nearby air temperature.' },
          { id: 'c', text: 'Coastal regions receive less sunlight.' },
          { id: 'd', text: "Water's specific heat capacity is unusually low." },
        ],
        correctOptionId: 'a',
        hints: ["Consider how much water's temperature changes for a given amount of heat exchanged."],
        explanation: "Water's high specific heat capacity means it changes temperature slowly, moderating the climate of nearby coastal areas.",
      },
    },
    {
      id: 'ht-d2',
      part: 'real-life-application',
      conceptSlug: 'pressure-dependence-of-melting-and-boiling-point',
      conceptTitle: 'Dependence of Melting Point and Boiling Point on Pressure',
      question: {
        id: 'ht-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does water boil at a lower temperature on a high mountain?',
        options: [
          { id: 'a', text: 'Lower atmospheric pressure at altitude lowers the boiling point of water.' },
          { id: 'b', text: 'Mountains are always colder, so water never actually boils there.' },
          { id: 'c', text: 'Pressure has no relationship to boiling point.' },
          { id: 'd', text: 'Water boils at a higher temperature at altitude.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall how boiling point relates to surrounding atmospheric pressure.'],
        explanation: 'Boiling occurs when vapour pressure matches atmospheric pressure — at high altitude, lower atmospheric pressure means boiling happens at a lower temperature.',
      },
    },
    {
      id: 'ht-e1',
      part: 'challenge',
      conceptSlug: 'vaporization-and-specific-latent-heat',
      conceptTitle: 'Vaporization and Specific Latent Heat of Vaporization',
      question: {
        id: 'ht-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why are steam burns typically more severe than burns from an equal mass of boiling water, even though both are at 100°C?',
        options: [
          { id: 'a', text: 'As steam condenses on skin, it releases its large latent heat of vaporization, transferring much more total energy than liquid water at the same temperature.' },
          { id: 'b', text: 'Steam is actually much hotter than 100°C.' },
          { id: 'c', text: 'Steam and boiling water transfer exactly the same amount of energy.' },
          { id: 'd', text: 'Latent heat has no relationship to burn severity.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider the extra energy release specifically from condensation.'],
        explanation: 'Condensing steam releases its large latent heat of vaporization in addition to cooling from 100°C, transferring far more total energy to the skin than liquid water at the same temperature.',
      },
    },
  ],
};
