import type { Assessment } from '@/types/content';

export const chapter6BAssessment: Assessment = {
  id: 'statistics-assessment',
  questions: [
    {
      id: 'stat-a1',
      part: 'concept',
      conceptSlug: 'range-and-interquartile-range',
      conceptTitle: 'Range and Interquartile Range',
      question: {
        id: 'stat-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why is the IQR often preferred over the range?',
        options: [
          { id: 'a', text: 'It is much less affected by extreme outliers' },
          { id: 'b', text: 'It is always a bigger number' },
          { id: 'c', text: 'It uses every data value' },
          { id: 'd', text: 'It cannot be negative' },
        ],
        correctOptionId: 'a',
        hints: ['Think about what happens with one very extreme value.'],
        explanation: 'The IQR only considers the middle 50% of data, so extreme outliers barely affect it.',
      },
    },
    {
      id: 'stat-a2',
      part: 'concept',
      conceptSlug: 'scatter-diagrams-and-correlation',
      conceptTitle: 'Scatter Diagrams and Correlation',
      question: {
        id: 'stat-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a downward-trending scatter diagram indicate?',
        options: [
          { id: 'a', text: 'Negative correlation' },
          { id: 'b', text: 'Positive correlation' },
          { id: 'c', text: 'No correlation' },
          { id: 'd', text: 'A calculation error' },
        ],
        correctOptionId: 'a',
        hints: ['As one variable increases, the other decreases.'],
        explanation: 'A downward trend is negative correlation.',
      },
    },
    {
      id: 'stat-b1',
      part: 'formula-application',
      conceptSlug: 'variance-and-standard-deviation',
      conceptTitle: 'Variance and Standard Deviation',
      question: {
        id: 'stat-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the variance of: 3, 3, 3, 3. (Mean = 3.)',
        hints: ['Every deviation is 0.'],
        correctAnswer: 0,
        explanation: 'Every value equals the mean, so every squared deviation is 0, giving variance 0.',
      },
    },
    {
      id: 'stat-b2',
      part: 'formula-application',
      conceptSlug: 'range-and-interquartile-range',
      conceptTitle: 'Range and Interquartile Range',
      question: {
        id: 'stat-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the IQR of: 2, 4, 6, 8, 10, 12, 14, 16. (Lower half: 2,4,6,8. Upper half: 10,12,14,16.)',
        hints: ['Q1 = (4+6)/2. Q3 = (12+14)/2.'],
        correctAnswer: 8,
        explanation: 'Q1=5, Q3=13, IQR=13−5=8.',
      },
    },
    {
      id: 'stat-c1',
      part: 'problem-solving',
      conceptSlug: 'cumulative-frequency-tables-and-the-ogive',
      conceptTitle: 'Cumulative Frequency Tables and the Ogive',
      question: {
        id: 'stat-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Classes 0-20 (8), 20-40 (15), 40-60 (12) have what cumulative frequency at boundary 60?',
        hints: ['Add all three frequencies.'],
        correctAnswer: 35,
        explanation: '8+15+12 = 35.',
      },
    },
    {
      id: 'stat-c2',
      part: 'problem-solving',
      conceptSlug: 'reading-the-median-and-quartiles-from-an-ogive',
      conceptTitle: 'Reading the Median and Quartiles from an Ogive',
      question: {
        id: 'stat-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A dataset has n=80. At what cumulative frequency value should you read Q1 from the ogive?',
        hints: ['Q1 is at n/4.'],
        correctAnswer: 20,
        explanation: '80/4 = 20.',
      },
    },
    {
      id: 'stat-d1',
      part: 'real-life-application',
      conceptSlug: 'variance-and-standard-deviation',
      conceptTitle: 'Variance and Standard Deviation',
      question: {
        id: 'stat-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Two factories produce parts with the same mean length, but Factory A has a much smaller standard deviation than Factory B. What does this tell you?',
        options: [
          { id: 'a', text: "Factory A's parts are more consistent in length" },
          { id: 'b', text: "Factory A's parts are on average longer" },
          { id: 'c', text: "Factory B's parts are more consistent" },
          { id: 'd', text: 'Nothing can be concluded' },
        ],
        correctOptionId: 'a',
        hints: ['Smaller standard deviation means less spread.'],
        explanation: 'A smaller standard deviation means Factory A\'s part lengths cluster more tightly around the mean — more consistent.',
      },
    },
    {
      id: 'stat-d2',
      part: 'real-life-application',
      conceptSlug: 'the-correlation-coefficient',
      conceptTitle: 'The Correlation Coefficient',
      question: {
        id: 'stat-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A study finds r = 0.05 between shoe size and exam scores. What does this suggest?',
        options: [
          { id: 'a', text: 'Little to no linear relationship between the two variables' },
          { id: 'b', text: 'A strong positive relationship' },
          { id: 'c', text: 'A strong negative relationship' },
          { id: 'd', text: 'Shoe size causes exam performance' },
        ],
        correctOptionId: 'a',
        hints: ['|r| is very close to 0.'],
        explanation: '|r|=0.05 is very close to 0, indicating essentially no linear relationship.',
      },
    },
    {
      id: 'stat-e1',
      part: 'challenge',
      conceptSlug: 'variance-and-standard-deviation',
      conceptTitle: 'Variance and Standard Deviation',
      question: {
        id: 'stat-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the standard deviation of: 5, 5, 9, 9. (Mean=7.) Give as a whole number.',
        hints: ['Deviations: −2,−2,2,2. Squares: 4,4,4,4.', 'Variance = 16/4 = 4.'],
        correctAnswer: 2,
        explanation: 'Variance=4, so σ=√4=2.',
      },
    },
    {
      id: 'stat-e2',
      part: 'challenge',
      conceptSlug: 'reading-the-median-and-quartiles-from-an-ogive',
      conceptTitle: 'Reading the Median and Quartiles from an Ogive',
      question: {
        id: 'stat-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A dataset has cumulative frequencies 6 (at boundary 10) and 20 (at boundary 20), with n=40. Between which boundaries does the median (at cumulative frequency 20) fall?',
        options: [
          { id: 'a', text: 'The median is exactly at boundary 20, since cumulative frequency reaches 20 there' },
          { id: 'b', text: 'Between 0 and 10' },
          { id: 'c', text: 'It cannot be determined' },
          { id: 'd', text: 'Beyond boundary 20' },
        ],
        correctOptionId: 'a',
        hints: ['n/2 = 20, and the cumulative frequency at boundary 20 is exactly 20.'],
        explanation: 'Since cumulative frequency exactly reaches n/2=20 right at boundary 20, the median is estimated at x=20.',
      },
    },
  ],
};
