import type { Assessment } from '@/types/content';

export const chapter5BAssessment: Assessment = {
  id: 'matrices-assessment',
  questions: [
    {
      id: 'mat-a1',
      part: 'concept',
      conceptSlug: 'matrix-notation-and-definitions',
      conceptTitle: 'Matrix Notation and Definitions',
      question: {
        id: 'mat-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does the "order" of a matrix describe?',
        options: [
          { id: 'a', text: 'Its number of rows and columns' },
          { id: 'b', text: 'The sum of all its entries' },
          { id: 'c', text: 'Its determinant' },
          { id: 'd', text: 'Whether it has an inverse' },
        ],
        correctOptionId: 'a',
        hints: ['Order = size, written rows × columns.'],
        explanation: 'A matrix\'s order is its number of rows × number of columns.',
      },
    },
    {
      id: 'mat-a2',
      part: 'concept',
      conceptSlug: 'the-determinant-of-a-2x2-matrix',
      conceptTitle: 'The Determinant of a 2×2 Matrix',
      question: {
        id: 'mat-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'A matrix has an inverse exactly when its determinant is:',
        options: [
          { id: 'a', text: 'Nonzero' },
          { id: 'b', text: 'Zero' },
          { id: 'c', text: 'Negative' },
          { id: 'd', text: 'Equal to 1' },
        ],
        correctOptionId: 'a',
        hints: ['A zero determinant means no inverse exists.'],
        explanation: 'A nonzero determinant is required for a matrix to have an inverse.',
      },
    },
    {
      id: 'mat-b1',
      part: 'formula-application',
      conceptSlug: 'matrix-addition-and-subtraction',
      conceptTitle: 'Matrix Addition and Subtraction',
      question: {
        id: 'mat-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Find A+B, where A=[[2,1],[0,3]] and B=[[1,4],[5,2]].',
        options: [
          { id: 'a', text: '[[3,5],[5,5]]' },
          { id: 'b', text: '[[2,4],[5,3]]' },
          { id: 'c', text: '[[1,3],[−5,1]]' },
          { id: 'd', text: '[[3,5],[5,6]]' },
        ],
        correctOptionId: 'a',
        hints: ['Add matching entries.'],
        explanation: '[[2+1,1+4],[0+5,3+2]] = [[3,5],[5,5]].',
      },
    },
    {
      id: 'mat-b2',
      part: 'formula-application',
      conceptSlug: 'the-determinant-of-a-2x2-matrix',
      conceptTitle: 'The Determinant of a 2×2 Matrix',
      question: {
        id: 'mat-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the determinant of [[5, 3], [4, 2]].',
        hints: ['det = (5)(2) − (3)(4).'],
        correctAnswer: -2,
        explanation: '10 − 12 = −2.',
      },
    },
    {
      id: 'mat-c1',
      part: 'problem-solving',
      conceptSlug: 'matrix-multiplication',
      conceptTitle: 'Matrix Multiplication',
      question: {
        id: 'mat-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'For A=[[1,3],[2,0]] and B=[[2,1],[4,5]], find the (2,2) entry of AB.',
        hints: ['Row 2 of A: [2,0]. Column 2 of B: [1,5].', '(2×1)+(0×5).'],
        correctAnswer: 2,
        explanation: '(2×1)+(0×5) = 2.',
      },
    },
    {
      id: 'mat-c2',
      part: 'problem-solving',
      conceptSlug: 'the-inverse-of-a-2x2-matrix',
      conceptTitle: 'The Inverse of a 2×2 Matrix',
      question: {
        id: 'mat-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Find the inverse of [[1,0],[0,1]] (the identity matrix).',
        options: [
          { id: 'a', text: '[[1,0],[0,1]] — the identity matrix is its own inverse' },
          { id: 'b', text: '[[0,1],[1,0]]' },
          { id: 'c', text: '[[−1,0],[0,−1]]' },
          { id: 'd', text: 'It has no inverse' },
        ],
        correctOptionId: 'a',
        hints: ['det=1. Swap diagonal (no change since both are 1), negate off-diagonal (already 0).'],
        explanation: 'det=1×1−0×0=1. The formula gives back the identity matrix itself.',
      },
    },
    {
      id: 'mat-d1',
      part: 'real-life-application',
      conceptSlug: 'solving-simultaneous-equations-using-matrices',
      conceptTitle: 'Solving Simultaneous Equations Using Matrices',
      question: {
        id: 'mat-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is the matrix method (X = A⁻¹B) especially useful for large systems of equations?',
        options: [
          { id: 'a', text: 'It uses the same two steps (find A⁻¹, multiply by B) regardless of how many equations there are.' },
          { id: 'b', text: 'It only works for exactly two equations.' },
          { id: 'c', text: 'It avoids needing a determinant.' },
          { id: 'd', text: 'It never requires checking for a valid solution.' },
        ],
        correctOptionId: 'a',
        hints: ['Compare to elimination/substitution, which can get complicated with more variables.'],
        explanation: 'The same X=A⁻¹B process generalizes directly to larger systems, unlike ad hoc elimination strategies.',
      },
    },
    {
      id: 'mat-d2',
      part: 'real-life-application',
      conceptSlug: 'matrix-multiplication',
      conceptTitle: 'Matrix Multiplication',
      question: {
        id: 'mat-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A quantities matrix (recipes × ingredients) is multiplied by a cost matrix (ingredients × 1) to get total recipe costs. What must be true for this multiplication to work?',
        options: [
          { id: 'a', text: 'The number of ingredient columns in the first matrix must equal the number of ingredient rows in the second.' },
          { id: 'b', text: 'Both matrices must be square.' },
          { id: 'c', text: 'The matrices must have the same order.' },
          { id: 'd', text: 'The cost matrix must be the identity matrix.' },
        ],
        correctOptionId: 'a',
        hints: ['Matrix multiplication requires matching inner dimensions.'],
        explanation: 'Matrix multiplication requires columns of the first matrix to equal rows of the second — here, the shared "ingredients" dimension.',
      },
    },
    {
      id: 'mat-e1',
      part: 'challenge',
      conceptSlug: 'solving-simultaneous-equations-using-matrices',
      conceptTitle: 'Solving Simultaneous Equations Using Matrices',
      question: {
        id: 'mat-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Solve 3x + 2y = 16 and x + y = 7 using matrices. Find y. (A=[[3,2],[1,1]], det=1.)',
        hints: ['A⁻¹ = [[1,−2],[−1,3]] (det=1).', 'y = (−1)(16)+(3)(7).'],
        correctAnswer: 5,
        explanation: 'y = −16+21 = 5, and x = (1)(16)+(−2)(7) = 16−14 = 2. Check: 3(2)+2(5)=16 ✓, 2+5=7 ✓.',
      },
    },
    {
      id: 'mat-e2',
      part: 'challenge',
      conceptSlug: 'the-inverse-of-a-2x2-matrix',
      conceptTitle: 'The Inverse of a 2×2 Matrix',
      question: {
        id: 'mat-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A matrix [[2,4],[1,2]] is given. What happens when you try to find its inverse?',
        options: [
          { id: 'a', text: 'It has no inverse, since det = (2)(2)−(4)(1) = 0' },
          { id: 'b', text: 'Its inverse is [[2,−4],[−1,2]]' },
          { id: 'c', text: 'Its inverse is [[0.5,−1],[−0.25,0.5]]' },
          { id: 'd', text: 'Its inverse is the identity matrix' },
        ],
        correctOptionId: 'a',
        hints: ['Compute the determinant first.'],
        explanation: 'det = 4−4 = 0, so this matrix has no inverse — dividing by det(A)=0 is undefined.',
      },
    },
  ],
};
