import type { Assessment } from '@/types/content';

export const chapter8CAssessment: Assessment = {
  id: 'logarithmic-and-exponential-functions-assessment',
  questions: [
    {
      id: 'explog-a1',
      part: 'concept',
      conceptSlug: 'the-graph-of-an-exponential-function',
      conceptTitle: 'The Graph of an Exponential Function',
      question: {
        id: 'explog-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Evaluate y=4ˣ at x=2.',
        hints: ['4×4.'],
        correctAnswer: 16,
        explanation: '4²=16.',
      },
    },
    {
      id: 'explog-a2',
      part: 'concept',
      conceptSlug: 'the-graph-of-a-logarithmic-function',
      conceptTitle: 'The Graph of a Logarithmic Function',
      question: {
        id: 'explog-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Evaluate log₅(25).',
        hints: ['5 to what power gives 25?'],
        correctAnswer: 2,
        explanation: '5²=25, so log₅(25)=2.',
      },
    },
    {
      id: 'explog-b1',
      part: 'formula-application',
      conceptSlug: 'transformations-of-exponential-and-logarithmic-graphs',
      conceptTitle: 'Transformations of Exponential and Logarithmic Graphs',
      question: {
        id: 'explog-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the new horizontal asymptote of y=3ˣ+6 (compared to y=3ˣ, which has asymptote y=0).',
        hints: ['The vertical shift moves the asymptote by the same amount.'],
        correctAnswer: 6,
        explanation: '0+6=6.',
      },
    },
    {
      id: 'explog-b2',
      part: 'formula-application',
      conceptSlug: 'the-derivative-of-e-to-the-x',
      conceptTitle: 'The Derivative of eˣ',
      question: {
        id: 'explog-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find f\'(0) for f(x)=4eˣ.',
        hints: ["f'(x) = 4eˣ."],
        correctAnswer: 4,
        explanation: '4e⁰=4(1)=4.',
      },
    },
    {
      id: 'explog-c1',
      part: 'problem-solving',
      conceptSlug: 'the-derivative-of-general-exponential-functions',
      conceptTitle: 'The Derivative of General Exponential Functions',
      question: {
        id: 'explog-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find f\'(0) for f(x)=3ˣ (using f\'(x)=3ˣ·ln3, ln3≈1.0986). Round to 4 decimal places.',
        hints: ['3⁰=1.'],
        correctAnswer: 1.0986,
        tolerance: 0.001,
        explanation: '1×1.0986 = 1.0986.',
      },
    },
    {
      id: 'explog-c2',
      part: 'problem-solving',
      conceptSlug: 'the-derivative-of-the-natural-logarithm',
      conceptTitle: 'The Derivative of the Natural Logarithm',
      question: {
        id: 'explog-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find f\'(10) for f(x)=ln(x).',
        hints: ["f'(x) = 1/x."],
        correctAnswer: 0.1,
        explanation: '1/10 = 0.1.',
      },
    },
    {
      id: 'explog-d1',
      part: 'real-life-application',
      conceptSlug: 'the-derivative-of-general-logarithmic-functions',
      conceptTitle: 'The Derivative of General Logarithmic Functions',
      question: {
        id: 'explog-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A chemist models radioactive decay using an exponential function and needs the instantaneous rate of decay at a specific time. Which mathematical tool do they need?',
        options: [
          { id: 'a', text: 'The derivative of the exponential function' },
          { id: 'b', text: 'The exponential function\'s y-intercept alone' },
          { id: 'c', text: 'The horizontal asymptote alone' },
          { id: 'd', text: 'The inverse logarithmic function only' },
        ],
        correctOptionId: 'a',
        hints: ['An instantaneous rate is exactly what a derivative gives.'],
        explanation: 'The derivative of the exponential decay function gives the instantaneous rate of decay at any time.',
      },
    },
    {
      id: 'explog-d2',
      part: 'real-life-application',
      conceptSlug: 'the-graph-of-an-exponential-function',
      conceptTitle: 'The Graph of an Exponential Function',
      question: {
        id: 'explog-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A biologist models bacterial population growth as P(t)=P₀×2ᵗ. What does this exponential model assume about the population\'s growth pattern?',
        options: [
          { id: 'a', text: 'The population doubles at every fixed time interval' },
          { id: 'b', text: 'The population grows by a fixed NUMBER of bacteria each interval' },
          { id: 'c', text: 'The population stays constant' },
          { id: 'd', text: 'The population decreases over time' },
        ],
        correctOptionId: 'a',
        hints: ['Think about what the base 2 means in this model.'],
        explanation: 'Base 2 in the exponent means the population doubles every time t increases by 1 unit.',
      },
    },
    {
      id: 'explog-e1',
      part: 'challenge',
      conceptSlug: 'the-graph-of-a-logarithmic-function',
      conceptTitle: 'The Graph of a Logarithmic Function',
      question: {
        id: 'explog-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'If log_b(x)=3 and b=4, find x.',
        hints: ['x = b to the power of the log value.'],
        correctAnswer: 64,
        explanation: '4³=64.',
      },
    },
    {
      id: 'explog-e2',
      part: 'challenge',
      conceptSlug: 'the-derivative-of-e-to-the-x',
      conceptTitle: 'The Derivative of eˣ',
      question: {
        id: 'explog-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find f\'(1) for f(x)=eˣ+ln(x). (e≈2.71828) Round to 2 decimal places.',
        hints: ["f'(x) = eˣ + 1/x."],
        correctAnswer: 3.72,
        tolerance: 0.01,
        explanation: 'f\'(1) = e¹ + 1/1 = 2.71828+1 ≈ 3.72.',
      },
    },
  ],
};
