import type { Assessment } from '@/types/content';

export const chapter9CCapacitorAssessment: Assessment = {
  id: 'capacitor-and-capacitance-assessment',
  questions: [
    {
      id: 'capacitor-a1',
      part: 'concept',
      conceptSlug: 'capacitors',
      conceptTitle: 'Capacitors',
      question: {
        id: 'capacitor-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a capacitor store between its two plates?',
        hints: ['Think about what accumulates on the plates.'],
        options: [
          { id: 'a', text: 'Equal and opposite electric charge' },
          { id: 'b', text: 'A continuous flow of current' },
          { id: 'c', text: 'Magnetic field energy only' },
          { id: 'd', text: 'Heat energy only' },
        ],
        correctOptionId: 'a',
        explanation: 'A capacitor stores equal and opposite charge on its two plates, separated by an insulating gap.',
      },
    },
    {
      id: 'capacitor-a2',
      part: 'concept',
      conceptSlug: 'capacitance-of-a-capacitor',
      conceptTitle: 'Capacitance of a Capacitor',
      question: {
        id: 'capacitor-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A capacitor stores 0.001 C of charge at 25 V. Find its capacitance, in μF.',
        hints: ['C = Q/V, then convert to μF.'],
        correctAnswer: 40,
        explanation: 'C = 0.001/25 = 4×10⁻⁵ F = 40 μF.',
      },
    },
    {
      id: 'capacitor-b1',
      part: 'formula-application',
      conceptSlug: 'parallel-plate-capacitor',
      conceptTitle: 'The Parallel-Plate Capacitor',
      question: {
        id: 'capacitor-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A parallel-plate capacitor has plates of area 0.05 m², separated by 0.002 m of air. Find its capacitance, in pF.',
        hints: ['C = ε₀εᵣA/d, with εᵣ=1.'],
        correctAnswer: 221.25,
        tolerance: 2,
        explanation: 'C = (8.85×10⁻¹²)(1)(0.05)/0.002 ≈ 2.2125×10⁻¹⁰ F ≈ 221.25 pF.',
      },
    },
    {
      id: 'capacitor-b2',
      part: 'formula-application',
      conceptSlug: 'energy-stored-in-a-capacitor',
      conceptTitle: 'Energy Stored in a Capacitor',
      question: {
        id: 'capacitor-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 50 μF capacitor is charged to 20 V. Find the energy stored, in mJ.',
        hints: ['E = ½CV², converting μF to F first.'],
        correctAnswer: 10,
        explanation: 'E = 0.5(5×10⁻⁵)(400) = 0.01 J = 10 mJ.',
      },
    },
    {
      id: 'capacitor-c1',
      part: 'problem-solving',
      conceptSlug: 'capacitors-in-series-and-parallel',
      conceptTitle: 'Combination of Capacitors',
      question: {
        id: 'capacitor-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the total capacitance of three capacitors — 2 μF, 3 μF, and 6 μF — connected in parallel.',
        hints: ['C_parallel = C₁+C₂+C₃.'],
        correctAnswer: 11,
        explanation: 'C = 2+3+6 = 11 μF.',
      },
    },
    {
      id: 'capacitor-c2',
      part: 'problem-solving',
      conceptSlug: 'capacitance-of-a-capacitor',
      conceptTitle: 'Capacitance of a Capacitor',
      question: {
        id: 'capacitor-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 25 μF capacitor stores 0.0015 C of charge. Find the voltage across it.',
        hints: ['Rearrange C=Q/V to solve for V.'],
        correctAnswer: 60,
        explanation: 'V = Q/C = 0.0015/(25×10⁻⁶) = 60 V.',
      },
    },
    {
      id: 'capacitor-d1',
      part: 'real-life-application',
      conceptSlug: 'capacitors',
      conceptTitle: 'Capacitors',
      question: {
        id: 'capacitor-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why do some circuits include a capacitor connected in parallel with the power supply?',
        hints: ['Capacitors can release stored charge quickly when needed.'],
        options: [
          { id: 'a', text: 'To smooth out voltage fluctuations by releasing stored charge when supply voltage dips' },
          { id: 'b', text: 'To permanently block all current in the circuit' },
          { id: 'c', text: 'To convert AC current into more AC current' },
          { id: 'd', text: "To increase the power supply's frequency" },
        ],
        correctOptionId: 'a',
        explanation: 'A capacitor acts as a small reservoir of charge, releasing energy to smooth momentary dips in supply voltage — a common filtering/smoothing application.',
      },
    },
    {
      id: 'capacitor-d2',
      part: 'real-life-application',
      conceptSlug: 'energy-stored-in-a-capacitor',
      conceptTitle: 'Energy Stored in a Capacitor',
      question: {
        id: 'capacitor-d2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'An engineer wants to triple the energy stored in a capacitor without changing its capacitance. By what factor should the voltage change?',
        hints: ['E ∝ V². Find the factor k such that k²=3.'],
        options: [
          { id: 'a', text: '√3 (about 1.73) times' },
          { id: 'b', text: '3 times' },
          { id: 'c', text: '1.5 times' },
          { id: 'd', text: '9 times' },
        ],
        correctOptionId: 'a',
        explanation: 'Since E=½CV², tripling E requires V to increase by a factor of √3, since (√3)²=3.',
      },
    },
    {
      id: 'capacitor-e1',
      part: 'challenge',
      conceptSlug: 'capacitors-in-series-and-parallel',
      conceptTitle: 'Combination of Capacitors',
      question: {
        id: 'capacitor-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two capacitors, 5 μF and X μF, are connected in series and produce a total capacitance of 3 μF. Find X.',
        hints: ['1/3 = 1/5 + 1/X. Solve for X.'],
        correctAnswer: 7.5,
        explanation: '1/X = 1/3−1/5 = 5/15−3/15 = 2/15. X = 15/2 = 7.5 μF.',
      },
    },
    {
      id: 'capacitor-e2',
      part: 'challenge',
      conceptSlug: 'parallel-plate-capacitor',
      conceptTitle: 'The Parallel-Plate Capacitor',
      question: {
        id: 'capacitor-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A parallel-plate capacitor has C=100 pF with air (εᵣ=1) between the plates. If a dielectric with εᵣ=5 is inserted (same area and separation), find the new capacitance.',
        hints: ['Capacitance is directly proportional to εᵣ.'],
        correctAnswer: 500,
        explanation: 'C_new = εᵣ × C_old = 5 × 100 = 500 pF.',
      },
    },
  ],
};
