import type { Assessment } from '@/types/content';

export const chapter4Assessment: Assessment = {
  id: 'functions-assessment',
  questions: [
    {
      id: 'fun-a1',
      part: 'concept',
      conceptSlug: 'meaning-of-a-product-set',
      conceptTitle: 'Meaning of a Product Set',
      question: {
        id: 'fun-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is A × B?',
        options: [
          { id: 'a', text: 'The set of all ordered pairs (a, b) with a ∈ A and b ∈ B' },
          { id: 'b', text: 'The set of elements common to both A and B' },
          { id: 'c', text: 'The set of elements in A or B but not both' },
          { id: 'd', text: 'The sum of the elements of A and B' },
        ],
        correctOptionId: 'a',
        hints: ['Product set = Cartesian product.'],
        explanation: 'A × B is the set of every ordered pair (a, b) formed by taking a from A and b from B.',
      },
    },
    {
      id: 'fun-a2',
      part: 'concept',
      conceptSlug: 'meaning-of-a-function',
      conceptTitle: 'Meaning of a Function',
      question: {
        id: 'fun-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What makes a relation a function?',
        options: [
          { id: 'a', text: 'Every input has exactly one output' },
          { id: 'b', text: 'Every output has exactly one input' },
          { id: 'c', text: 'The domain and range are equal' },
          { id: 'd', text: 'It contains only positive numbers' },
        ],
        correctOptionId: 'a',
        hints: ['Think about repeated inputs.'],
        explanation: 'A function requires every input to map to exactly one output — repeated outputs are fine.',
      },
    },
    {
      id: 'fun-b1',
      part: 'formula-application',
      conceptSlug: 'cardinality-of-a-product-set',
      conceptTitle: 'Cardinality of a Product Set',
      question: {
        id: 'fun-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'If n(A) = 8 and n(B) = 3, what is n(A × B)?',
        hints: ['n(A × B) = n(A) × n(B).'],
        correctAnswer: 24,
        explanation: 'n(A × B) = 8 × 3 = 24.',
      },
    },
    {
      id: 'fun-b2',
      part: 'formula-application',
      conceptSlug: 'function-notation-and-evaluating-functions',
      conceptTitle: 'Function Notation and Evaluating Functions',
      question: {
        id: 'fun-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'If f(x) = 3x² − x, find f(2).',
        hints: ['Substitute x = 2: 3(2)² − 2.'],
        correctAnswer: 10,
        explanation: 'f(2) = 3(4) − 2 = 12 − 2 = 10.',
      },
    },
    {
      id: 'fun-c1',
      part: 'problem-solving',
      conceptSlug: 'meaning-of-a-relation',
      conceptTitle: 'Meaning of a Relation',
      question: {
        id: 'fun-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What is the domain of the relation {(2,5), (4,5), (6,9)}?',
        options: [
          { id: 'a', text: '{2, 4, 6}' },
          { id: 'b', text: '{5, 9}' },
          { id: 'c', text: '{2, 4, 6, 5, 9}' },
          { id: 'd', text: '{5, 5, 9}' },
        ],
        correctOptionId: 'a',
        hints: ['The domain is the set of first coordinates.'],
        explanation: 'The first coordinates are 2, 4, and 6, so the domain is {2, 4, 6}.',
      },
    },
    {
      id: 'fun-c2',
      part: 'problem-solving',
      conceptSlug: 'domain-and-range-of-a-function',
      conceptTitle: 'Domain and Range of a Function',
      question: {
        id: 'fun-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'What value of x must be excluded from the domain of h(x) = 1/(x − 8)?',
        hints: ['The denominator cannot equal zero.'],
        correctAnswer: 8,
        explanation: 'x − 8 = 0 gives x = 8, which makes the denominator zero and must be excluded.',
      },
    },
    {
      id: 'fun-d1',
      part: 'real-life-application',
      conceptSlug: 'meaning-of-a-function',
      conceptTitle: 'Meaning of a Function',
      question: {
        id: 'fun-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A vending machine sometimes dispenses a different snack for the same button press. Is "button pressed → snack dispensed" a function?',
        options: [
          { id: 'a', text: 'No — the same input (button) produces more than one possible output.' },
          { id: 'b', text: 'Yes — every button dispenses a snack.' },
          { id: 'c', text: 'Yes, as long as the machine has enough snacks.' },
          { id: 'd', text: 'It cannot be determined.' },
        ],
        correctOptionId: 'a',
        hints: ['A function requires one output per input, every time.'],
        explanation: 'Since the same button (input) can give different snacks (outputs), this violates the function rule.',
      },
    },
    {
      id: 'fun-d2',
      part: 'real-life-application',
      conceptSlug: 'the-vertical-line-test',
      conceptTitle: 'The Vertical Line Test',
      question: {
        id: 'fun-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A sensor\'s time-vs-reading graph shows two different readings recorded at exactly the same time. What does the vertical line test say about this graph?',
        options: [
          { id: 'a', text: 'It is not a function of time, since a vertical line at that time crosses the graph twice.' },
          { id: 'b', text: 'It is still a function, since the readings are close in value.' },
          { id: 'c', text: 'The vertical line test does not apply to sensor data.' },
          { id: 'd', text: 'It is a function as long as the average of the two readings is used.' },
        ],
        correctOptionId: 'a',
        hints: ['Two outputs at the same input value fails the test.'],
        explanation: 'Two different readings at the same time means a vertical line at that time crosses the graph twice — it is not a function of time.',
      },
    },
    {
      id: 'fun-e1',
      part: 'challenge',
      conceptSlug: 'function-notation-and-evaluating-functions',
      conceptTitle: 'Function Notation and Evaluating Functions',
      question: {
        id: 'fun-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'If f(x) = x² − 4x + 7, find f(a+1) when a = 2 (i.e. find f(3)).',
        hints: ['First find a+1 = 3, then substitute x = 3 into f.'],
        correctAnswer: 4,
        explanation: 'f(3) = 3² − 4(3) + 7 = 9 − 12 + 7 = 4.',
      },
    },
    {
      id: 'fun-e2',
      part: 'challenge',
      conceptSlug: 'cardinality-of-a-product-set',
      conceptTitle: 'Cardinality of a Product Set',
      question: {
        id: 'fun-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Set A has 4 elements. How many elements does A × A have?',
        options: [
          { id: 'a', text: '16' },
          { id: 'b', text: '8' },
          { id: 'c', text: '4' },
          { id: 'd', text: '12' },
        ],
        correctOptionId: 'a',
        hints: ['n(A × A) = n(A) × n(A).'],
        explanation: 'n(A × A) = 4 × 4 = 16.',
      },
    },
  ],
};
