import type { Assessment } from '@/types/content';

export const chapter6CAssessment: Assessment = {
  id: 'circles-and-parabolas-assessment',
  questions: [
    {
      id: 'conic-a1',
      part: 'concept',
      conceptSlug: 'what-is-a-conic-section',
      conceptTitle: 'What Is a Conic Section?',
      question: {
        id: 'conic-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which equation represents a parabola?',
        options: [
          { id: 'a', text: 'y = 3x² + 1' },
          { id: 'b', text: 'x² + y² = 25' },
          { id: 'c', text: '(x−1)² + (y+2)² = 9' },
          { id: 'd', text: 'x² + y² − 4x = 0' },
        ],
        correctOptionId: 'a',
        hints: ['Look for the equation with only one squared variable.'],
        explanation: 'Only y=3x²+1 has a single squared variable; the others are circles.',
      },
    },
    {
      id: 'conic-a2',
      part: 'concept',
      conceptSlug: 'the-standard-equation-of-a-circle',
      conceptTitle: 'The Standard Equation of a Circle',
      question: {
        id: 'conic-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A circle has equation (x−2)²+(y+3)²=64. Find its radius.',
        hints: ['The right side is r².'],
        correctAnswer: 8,
        explanation: '√64 = 8.',
      },
    },
    {
      id: 'conic-b1',
      part: 'formula-application',
      conceptSlug: 'the-general-equation-of-a-circle',
      conceptTitle: 'The General Equation of a Circle',
      question: {
        id: 'conic-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the radius of the circle x²+y²−4x+6y−3=0.',
        hints: ['Group: (x²−4x)+(y²+6y)=3.', 'Complete the square for x and y.'],
        correctAnswer: 4,
        explanation: '(x−2)²+(y+3)² = 3+4+9 = 16, so radius = √16 = 4.',
      },
    },
    {
      id: 'conic-b2',
      part: 'formula-application',
      conceptSlug: 'the-standard-equation-of-a-parabola',
      conceptTitle: 'The Standard Equation of a Parabola',
      question: {
        id: 'conic-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'For the parabola x²=20y, find p.',
        hints: ['4p = 20.'],
        correctAnswer: 5,
        explanation: '4p=20, so p=5.',
      },
    },
    {
      id: 'conic-c1',
      part: 'problem-solving',
      conceptSlug: 'the-focus-directrix-definition-of-a-parabola',
      conceptTitle: 'The Focus-Directrix Definition of a Parabola',
      question: {
        id: 'conic-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A parabola has focus (0,4) and directrix y=−4. Find the distance from the point (8,4) to the focus.',
        hints: ['Apply the distance formula between (8,4) and (0,4).'],
        correctAnswer: 8,
        explanation: '√((8−0)²+(4−4)²) = √64 = 8.',
      },
    },
    {
      id: 'conic-c2',
      part: 'problem-solving',
      conceptSlug: 'the-general-equation-of-a-translated-parabola',
      conceptTitle: 'The General Equation of a Translated Parabola',
      question: {
        id: 'conic-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A parabola (x+3)²=12(y−1) has vertex (h,1). Find h.',
        hints: ['(x+3) means (x−h) with h negative.'],
        correctAnswer: -3,
        explanation: '(x+3) = (x−(−3)), so h=−3.',
      },
    },
    {
      id: 'conic-d1',
      part: 'real-life-application',
      conceptSlug: 'translation-of-axes',
      conceptTitle: 'Translation of Axes',
      question: {
        id: 'conic-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A surveyor moves their reference origin to a more convenient landmark on the map, then re-measures every point\'s coordinates relative to it. Which technique describes this?',
        options: [
          { id: 'a', text: 'Translation of axes' },
          { id: 'b', text: 'Rotation of axes' },
          { id: 'c', text: 'Completing the square' },
          { id: 'd', text: 'The focus-directrix definition' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation translation of axes is designed for.'],
        explanation: 'Translation of axes shifts the origin to a new, more convenient reference point.',
      },
    },
    {
      id: 'conic-d2',
      part: 'real-life-application',
      conceptSlug: 'rotation-of-axes',
      conceptTitle: 'Rotation of Axes',
      question: {
        id: 'conic-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An engineer analyzing a tilted conveyor belt rotates the coordinate axes to align with the belt\'s actual direction of motion, simplifying the equations of motion. Which technique is this?',
        options: [
          { id: 'a', text: 'Rotation of axes' },
          { id: 'b', text: 'Translation of axes' },
          { id: 'c', text: 'The standard circle equation' },
          { id: 'd', text: 'The focus-directrix definition' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation rotation of axes is designed for.'],
        explanation: 'Rotation of axes aligns the coordinate system with a tilted feature, simplifying its equations.',
      },
    },
    {
      id: 'conic-e1',
      part: 'challenge',
      conceptSlug: 'the-general-equation-of-a-circle',
      conceptTitle: 'The General Equation of a Circle',
      question: {
        id: 'conic-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the y-coordinate of the center of the circle x²+y²+8x−2y+13=0.',
        hints: ['Group: (x²+8x)+(y²−2y)=−13.', 'Complete the square for x and y.'],
        correctAnswer: 1,
        explanation: '(x+4)²+(y−1)² = −13+16+1 = 4. Center is (−4,1), so the y-coordinate is 1.',
      },
    },
    {
      id: 'conic-e2',
      part: 'challenge',
      conceptSlug: 'the-general-equation-of-a-translated-parabola',
      conceptTitle: 'The General Equation of a Translated Parabola',
      question: {
        id: 'conic-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A parabola (x−5)²=−8(y−2) has vertex (5,2) and p=−2 (opens downward). Find the y-coordinate of its focus, which is at (h, k+p).',
        hints: ['k+p = 2+(−2).'],
        correctAnswer: 0,
        explanation: '2+(−2) = 0.',
      },
    },
  ],
};
