import type { Assessment } from '@/types/content';

export const chapter8LensesAssessment: Assessment = {
  id: 'lenses-assessment',
  questions: [
    {
      id: 'ln-a1',
      part: 'concept',
      conceptSlug: 'refraction-at-a-curved-surface',
      conceptTitle: 'Refraction at a Curved Surface',
      question: {
        id: 'ln-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can a curved surface focus parallel light rays to a point, unlike a flat surface?',
        options: [
          { id: 'a', text: 'The local normal direction varies across the curve, so each ray refracts by a different, precisely coordinated amount.' },
          { id: 'b', text: 'All curved surfaces refract every ray by an identical fixed angle.' },
          { id: 'c', text: 'Curved surfaces do not actually refract light.' },
          { id: 'd', text: 'Focusing has nothing to do with surface shape.' },
        ],
        correctOptionId: 'a',
        hints: ['The normal at each point on a curve points differently.'],
        explanation: 'The varying local normal across a curved surface causes each ray to refract by a different amount, allowing convergence to a focus point.',
      },
    },
    {
      id: 'ln-a2',
      part: 'concept',
      conceptSlug: 'refraction-through-lenses',
      conceptTitle: 'Refraction Through Lenses',
      question: {
        id: 'ln-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What does a NEGATIVE magnification value indicate about the image?',
        options: [
          { id: 'a', text: 'The image is inverted relative to the object.' },
          { id: 'b', text: 'The image does not actually exist.' },
          { id: 'c', text: 'The image is always larger than the object.' },
          { id: 'd', text: 'The lens has no focal length.' },
        ],
        correctOptionId: 'a',
        hints: ['Sign carries orientation information; magnitude carries size information.'],
        explanation: 'A negative magnification indicates the image is inverted, regardless of its size relative to the object.',
      },
    },
    {
      id: 'ln-a3',
      part: 'concept',
      conceptSlug: 'power-of-a-lens',
      conceptTitle: 'Power of a Lens',
      question: {
        id: 'ln-a3-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why do opticians use dioptres (power) rather than focal length when prescribing lenses?',
        options: [
          { id: 'a', text: 'Lens powers add together when lenses are combined, unlike focal lengths.' },
          { id: 'b', text: 'Dioptres and focal length are exactly the same thing.' },
          { id: 'c', text: 'Focal length cannot be measured for real lenses.' },
          { id: 'd', text: 'Power has no relationship to focal length.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider what happens when combining two lenses.'],
        explanation: 'Since lens powers simply add when combined (unlike focal lengths), dioptres are the practical unit for prescriptions and combined optical systems.',
      },
    },
    {
      id: 'ln-b1',
      part: 'formula-application',
      conceptSlug: 'the-lens-equation',
      conceptTitle: 'The Lens Equation',
      question: {
        id: 'ln-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An object is placed at u = -25 cm from a lens with f = 5 cm. Find the image distance v.',
        hints: ['1/v = 1/f + 1/u.'],
        correctAnswer: 6.25,
        tolerance: 0.2,
        unit: 'cm',
        explanation: '1/v = 1/5 + 1/(-25) = 5/25 − 1/25 = 4/25 → v = 25/4 = 6.25 cm.',
      },
    },
    {
      id: 'ln-b2',
      part: 'formula-application',
      conceptSlug: 'power-of-a-lens',
      conceptTitle: 'Power of a Lens',
      question: {
        id: 'ln-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the power of a lens with focal length 0.2 m.',
        hints: ['P = 1/f.'],
        correctAnswer: 5,
        tolerance: 0.1,
        unit: 'D',
        explanation: 'P = 1/0.2 = 5 D.',
      },
    },
    {
      id: 'ln-c1',
      part: 'problem-solving',
      conceptSlug: 'refraction-through-lenses',
      conceptTitle: 'Refraction Through Lenses',
      question: {
        id: 'ln-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A lens forms an image at v = 12 cm from an object at u = -4 cm. Find the magnification.',
        hints: ['m = v/u.'],
        correctAnswer: -3,
        tolerance: 0.1,
        explanation: 'm = 12/(-4) = -3 (three times larger, inverted).',
      },
    },
    {
      id: 'ln-c2',
      part: 'problem-solving',
      conceptSlug: 'the-lens-equation',
      conceptTitle: 'The Lens Equation',
      question: {
        id: 'ln-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A lens forms a real image at v = 30 cm when the object is at u = -60 cm. Find the focal length f.',
        hints: ['1/f = 1/v − 1/u.'],
        correctAnswer: 20,
        tolerance: 0.5,
        unit: 'cm',
        explanation: '1/f = 1/30 − 1/(-60) = 1/30 + 1/60 = 2/60 + 1/60 = 3/60 = 1/20 → f = 20 cm.',
      },
    },
    {
      id: 'ln-d1',
      part: 'real-life-application',
      conceptSlug: 'the-lens-equation',
      conceptTitle: 'The Lens Equation',
      question: {
        id: 'ln-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How does a camera\'s autofocus system relate to the lens equation?',
        options: [
          { id: 'a', text: 'It effectively solves the lens equation in real time, adjusting the lens position so the image forms precisely on the sensor.' },
          { id: 'b', text: 'Autofocus has no relationship to the lens equation.' },
          { id: 'c', text: 'The lens equation only applies to eyeglasses, not cameras.' },
          { id: 'd', text: 'Cameras use a completely different set of physical laws.' },
        ],
        correctOptionId: 'a',
        hints: ['The camera needs to control where the image forms.'],
        explanation: "The camera adjusts lens position based on the same relationship described by the lens equation, ensuring the image lands precisely on the sensor.",
      },
    },
    {
      id: 'ln-d2',
      part: 'real-life-application',
      conceptSlug: 'refraction-through-lenses',
      conceptTitle: 'Refraction Through Lenses',
      question: {
        id: 'ln-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does holding a magnifying glass close to small text make the text look bigger?',
        options: [
          { id: 'a', text: 'When the object is closer than the focal length, the lens produces a virtual, upright, magnified image.' },
          { id: 'b', text: 'Magnifying glasses always shrink the image.' },
          { id: 'c', text: 'The lens equation does not apply to magnifying glasses.' },
          { id: 'd', text: 'Magnification is unrelated to object distance.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about the object-distance condition needed for a magnified, upright image.'],
        explanation: 'With the object closer than the focal length, a converging lens forms a virtual, upright, and enlarged image — exactly the effect used in a magnifying glass.',
      },
    },
    {
      id: 'ln-e1',
      part: 'challenge',
      conceptSlug: 'power-of-a-lens',
      conceptTitle: 'Power of a Lens',
      question: {
        id: 'ln-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Two thin lenses with powers +3 D and -1 D are placed close together. What is the combined power?',
        options: [
          { id: 'a', text: '+2 D, since lens powers simply add when lenses are placed together.' },
          { id: 'b', text: '+3 D, since only the stronger lens matters.' },
          { id: 'c', text: '-3 D.' },
          { id: 'd', text: 'Powers cannot be combined this way.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall why dioptres are the practical unit for combining lenses.'],
        explanation: 'Lens powers add directly when lenses are placed close together: +3 D + (−1 D) = +2 D.',
      },
    },
  ],
};
