import type { Assessment } from '@/types/content';

export const chapter10CAssessment: Assessment = {
  id: 'methods-of-integration-assessment',
  questions: [
    {
      id: 'integration-a1',
      part: 'concept',
      conceptSlug: 'antiderivatives-and-basic-integration-rules',
      conceptTitle: 'Antiderivatives and Basic Integration Rules',
      question: {
        id: 'integration-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Find ∫5x⁴ dx.',
        hints: ['Apply the Power Rule for integration with n=4.'],
        options: [
          { id: 'a', text: 'x⁵ + C' },
          { id: 'b', text: '5x⁵ + C' },
          { id: 'c', text: '20x³ + C' },
          { id: 'd', text: 'x⁵/5 + C' },
        ],
        correctOptionId: 'a',
        explanation: '∫5x⁴ dx = 5·(x⁵/5) = x⁵ + C.',
      },
    },
    {
      id: 'integration-a2',
      part: 'concept',
      conceptSlug: 'integrating-exponential-and-trigonometric-functions',
      conceptTitle: 'Integrating Exponential and Trigonometric Functions',
      question: {
        id: 'integration-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Find ∫(eˣ − sin(x)) dx.',
        hints: ['∫sin(x)dx = −cos(x), so subtracting it flips the sign again.'],
        options: [
          { id: 'a', text: 'eˣ + cos(x) + C' },
          { id: 'b', text: 'eˣ − cos(x) + C' },
          { id: 'c', text: 'eˣ + sin(x) + C' },
          { id: 'd', text: 'eˣ − sin(x) + C' },
        ],
        correctOptionId: 'a',
        explanation: '∫eˣdx = eˣ; ∫−sin(x)dx = −(−cos(x)) = cos(x). Combined: eˣ + cos(x) + C.',
      },
    },
    {
      id: 'integration-b1',
      part: 'formula-application',
      conceptSlug: 'integration-by-substitution',
      conceptTitle: 'Integration by Substitution',
      question: {
        id: 'integration-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Find ∫3x²(x³+2)⁴ dx.',
        hints: ['Let u = x³+2, so du = 3x² dx.'],
        options: [
          { id: 'a', text: '(x³+2)⁵/5 + C' },
          { id: 'b', text: '(x³+2)⁴/4 + C' },
          { id: 'c', text: '3x²(x³+2)⁵/5 + C' },
          { id: 'd', text: '(x³+2)⁵ + C' },
        ],
        correctOptionId: 'a',
        explanation: 'With u=x³+2, du=3x²dx, the integral becomes ∫u⁴du = u⁵/5+C = (x³+2)⁵/5+C.',
      },
    },
    {
      id: 'integration-b2',
      part: 'formula-application',
      conceptSlug: 'integration-by-parts',
      conceptTitle: 'Integration by Parts',
      question: {
        id: 'integration-b2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Find ∫x·ln(x) dx.',
        hints: ['Let u=ln(x), dv=x dx, so du=(1/x)dx and v=x²/2.'],
        options: [
          { id: 'a', text: '(x²/2)ln(x) − x²/4 + C' },
          { id: 'b', text: '(x²/2)ln(x) + x²/4 + C' },
          { id: 'c', text: 'x²ln(x) − x²/4 + C' },
          { id: 'd', text: '(x²/2)ln(x) − x² + C' },
        ],
        correctOptionId: 'a',
        explanation: '∫x ln(x)dx = (x²/2)ln(x) − ∫(x²/2)(1/x)dx = (x²/2)ln(x) − ∫(x/2)dx = (x²/2)ln(x) − x²/4 + C.',
      },
    },
    {
      id: 'integration-c1',
      part: 'problem-solving',
      conceptSlug: 'setting-up-a-partial-fraction-decomposition',
      conceptTitle: 'Setting Up a Partial Fraction Decomposition',
      question: {
        id: 'integration-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'For 2/[(x−2)(x+3)] = A/(x−2) + B/(x+3), find the value of B.',
        hints: ['Multiply both sides by (x−2)(x+3), then substitute x=−3.'],
        correctAnswer: -0.4,
        explanation: '2 = A(x+3)+B(x−2); at x=−3: 2 = B(−5) ⟹ B = −0.4.',
      },
    },
    {
      id: 'integration-c2',
      part: 'problem-solving',
      conceptSlug: 'integrating-using-partial-fractions',
      conceptTitle: 'Integrating Using Partial Fractions',
      question: {
        id: 'integration-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Given 2/[(x−2)(x+3)] = (0.4)/(x−2) − (0.4)/(x+3), find ∫2/[(x−2)(x+3)] dx.',
        hints: ['Integrate each partial fraction term to a logarithm.'],
        options: [
          { id: 'a', text: '0.4·ln|x−2| − 0.4·ln|x+3| + C' },
          { id: 'b', text: '0.4·ln|x−2| + 0.4·ln|x+3| + C' },
          { id: 'c', text: '2·ln|x−2| − 2·ln|x+3| + C' },
          { id: 'd', text: 'ln|x−2| − ln|x+3| + C' },
        ],
        correctOptionId: 'a',
        explanation: 'Each term A/(x−a) integrates to A·ln|x−a|, giving 0.4·ln|x−2| − 0.4·ln|x+3| + C.',
      },
    },
    {
      id: 'integration-d1',
      part: 'real-life-application',
      conceptSlug: 'antiderivatives-and-basic-integration-rules',
      conceptTitle: 'Antiderivatives and Basic Integration Rules',
      question: {
        id: 'integration-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A factory\'s marginal cost is C\'(x) = 6x + 2 dollars per unit, and fixed costs are C(0) = $50. Find the total cost C(10).',
        hints: ['Integrate C\'(x) to get C(x) = 3x² + 2x + C, then use C(0)=50 to find the constant.'],
        correctAnswer: 370,
        explanation: 'C(x) = 3x²+2x+50 (since C(0)=50). C(10) = 3(100)+2(10)+50 = 300+20+50 = 370.',
      },
    },
    {
      id: 'integration-d2',
      part: 'real-life-application',
      conceptSlug: 'integration-by-parts',
      conceptTitle: 'Integration by Parts',
      question: {
        id: 'integration-d2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'An engineer needs ∫t·e⁻ᵗ dt to find the total impulse of an exponentially-decaying force. Using u=t, dv=e⁻ᵗdt (so du=dt, v=−e⁻ᵗ), find the antiderivative.',
        hints: ['Apply ∫u dv = uv − ∫v du, then integrate the remaining term.'],
        options: [
          { id: 'a', text: '−(t+1)e⁻ᵗ + C' },
          { id: 'b', text: '(t+1)e⁻ᵗ + C' },
          { id: 'c', text: '−te⁻ᵗ + C' },
          { id: 'd', text: '(t−1)e⁻ᵗ + C' },
        ],
        correctOptionId: 'a',
        explanation: '∫te⁻ᵗdt = −te⁻ᵗ − ∫−e⁻ᵗdt = −te⁻ᵗ − e⁻ᵗ + C = −(t+1)e⁻ᵗ + C.',
      },
    },
    {
      id: 'integration-e1',
      part: 'challenge',
      conceptSlug: 'integration-by-substitution',
      conceptTitle: 'Integration by Substitution',
      question: {
        id: 'integration-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Find ∫x²(x³−1)² dx.',
        hints: ['Let u = x³−1, so du = 3x² dx, meaning x²dx = du/3.'],
        options: [
          { id: 'a', text: '(x³−1)³/9 + C' },
          { id: 'b', text: '(x³−1)³/3 + C' },
          { id: 'c', text: '(x³−1)²/6 + C' },
          { id: 'd', text: 'x³(x³−1)³/9 + C' },
        ],
        correctOptionId: 'a',
        explanation: 'With u=x³−1, du=3x²dx: ∫u²(du/3) = u³/9 + C = (x³−1)³/9 + C.',
      },
    },
    {
      id: 'integration-e2',
      part: 'challenge',
      conceptSlug: 'integrating-using-partial-fractions',
      conceptTitle: 'Integrating Using Partial Fractions',
      question: {
        id: 'integration-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Find ∫3/[(x−1)(x−4)] dx.',
        hints: ['Decompose first: 3/[(x−1)(x−4)] = A/(x−1) + B/(x−4), then integrate each term.'],
        options: [
          { id: 'a', text: '−ln|x−1| + ln|x−4| + C' },
          { id: 'b', text: 'ln|x−1| − ln|x−4| + C' },
          { id: 'c', text: '−ln|x−1| − ln|x−4| + C' },
          { id: 'd', text: '3ln|x−1| + 3ln|x−4| + C' },
        ],
        correctOptionId: 'a',
        explanation: 'Decomposition gives A=−1, B=1, so the integral is −ln|x−1| + ln|x−4| + C.',
      },
    },
  ],
};
