import type { Assessment } from '@/types/content';

export const chapter5CHeatAssessment: Assessment = {
  id: 'heat-transfer-and-thermodynamics-assessment',
  questions: [
    {
      id: 'heatthermo-a1',
      part: 'concept',
      conceptSlug: 'mechanisms-of-heat-transfer',
      conceptTitle: 'Mechanisms of Heat Transfer',
      question: {
        id: 'heatthermo-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A window (k=1.0 W/(m·K)) has area 1.5 m² and thickness 0.005 m, with a temperature difference of 15 K. Find the rate of heat loss.',
        hints: ['Q/t = kA(ΔT)/d.'],
        correctAnswer: 4500,
        explanation: 'Q/t = (1.0)(1.5)(15)/0.005 = 22.5/0.005 = 4500 W.',
      },
    },
    {
      id: 'heatthermo-a2',
      part: 'concept',
      conceptSlug: 'first-law-of-thermodynamics',
      conceptTitle: 'The First Law of Thermodynamics',
      question: {
        id: 'heatthermo-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A gas absorbs 6000 J of heat and does 4000 J of work. Find the change in its internal energy.',
        hints: ['ΔU = Q−W.'],
        correctAnswer: 2000,
        explanation: 'ΔU = 6000−4000 = 2000 J.',
      },
    },
    {
      id: 'heatthermo-b1',
      part: 'formula-application',
      conceptSlug: 'radiation-and-stefan-boltzmann-law',
      conceptTitle: 'Radiation and the Stefan-Boltzmann Law',
      question: {
        id: 'heatthermo-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A black body (ε=1) with area 0.1 m² is at 500 K. Find the power it radiates. (500⁴=6.25×10¹⁰)',
        hints: ['P = εσAT⁴.'],
        correctAnswer: 354.4,
        tolerance: 1,
        explanation: 'P = (1)(5.67×10⁻⁸)(0.1)(6.25×10¹⁰) ≈ 354.4 W.',
      },
    },
    {
      id: 'heatthermo-b2',
      part: 'formula-application',
      conceptSlug: 'internal-energy-and-work',
      conceptTitle: 'Internal Energy and Work',
      question: {
        id: 'heatthermo-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A gas expands at constant pressure 100000 Pa from 0.01 m³ to 0.03 m³. Find the work it does.',
        hints: ['W = PΔV.'],
        correctAnswer: 2000,
        explanation: 'W = 100000 × (0.03−0.01) = 100000 × 0.02 = 2000 J.',
      },
    },
    {
      id: 'heatthermo-c1',
      part: 'problem-solving',
      conceptSlug: 'heat-engines-and-efficiency',
      conceptTitle: 'Heat Engines and Efficiency',
      question: {
        id: 'heatthermo-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A heat engine has an efficiency of 35% and absorbs 10000 J from its hot reservoir. Find its work output.',
        hints: ['W = η × Qₕ.'],
        correctAnswer: 3500,
        explanation: 'W = 0.35 × 10000 = 3500 J.',
      },
    },
    {
      id: 'heatthermo-c2',
      part: 'problem-solving',
      conceptSlug: 'mechanisms-of-heat-transfer',
      conceptTitle: 'Mechanisms of Heat Transfer',
      question: {
        id: 'heatthermo-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A material of area 0.5 m² and thickness 0.02 m conducts heat at a rate of 100 W, with a temperature difference of 40 K. Find its thermal conductivity k.',
        hints: ['Rearrange Q/t=kA(ΔT)/d to solve for k.'],
        correctAnswer: 0.1,
        explanation: 'k = (Q/t)(d)/(AΔT) = (100)(0.02)/[(0.5)(40)] = 2/20 = 0.1 W/(m·K).',
      },
    },
    {
      id: 'heatthermo-d1',
      part: 'real-life-application',
      conceptSlug: 'radiation-and-stefan-boltzmann-law',
      conceptTitle: 'Radiation and the Stefan-Boltzmann Law',
      question: {
        id: 'heatthermo-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Two identical metal spheres are heated to 400 K and 800 K. Approximately how many times more power does the hotter sphere radiate?',
        hints: ['P∝T⁴. The temperature doubled.'],
        options: [
          { id: 'a', text: '16 times' },
          { id: 'b', text: '2 times' },
          { id: 'c', text: '4 times' },
          { id: 'd', text: '8 times' },
        ],
        correctOptionId: 'a',
        explanation: 'Since P∝T⁴, doubling T multiplies power by 2⁴=16.',
      },
    },
    {
      id: 'heatthermo-d2',
      part: 'real-life-application',
      conceptSlug: 'heat-engines-and-efficiency',
      conceptTitle: 'Heat Engines and Efficiency',
      question: {
        id: 'heatthermo-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which best explains why no real heat engine can be 100% efficient?',
        hints: ['This is a fundamental law of thermodynamics, not just an engineering limitation.'],
        options: [
          { id: 'a', text: 'The second law of thermodynamics requires some heat to always be expelled to a cold reservoir' },
          { id: 'b', text: 'Engines are simply badly designed' },
          { id: 'c', text: 'Friction alone is responsible' },
          { id: 'd', text: 'Heat engines could reach 100% efficiency with perfect materials' },
        ],
        correctOptionId: 'a',
        explanation: 'The second law of thermodynamics fundamentally requires waste heat (Qc) to be expelled, regardless of engineering quality.',
      },
    },
    {
      id: 'heatthermo-e1',
      part: 'challenge',
      conceptSlug: 'first-law-of-thermodynamics',
      conceptTitle: 'The First Law of Thermodynamics',
      question: {
        id: 'heatthermo-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "Over one complete thermodynamic cycle, a gas's internal energy returns to its starting value. If the gas absorbs 15000 J of heat total during the cycle, how much net work does it do?",
        hints: ['Over a full cycle, ΔU=0, so ΔU=Q−W means Q=W.'],
        correctAnswer: 15000,
        explanation: 'Since ΔU=0 for a complete cycle, 0=Q−W, so W=Q=15000 J.',
      },
    },
    {
      id: 'heatthermo-e2',
      part: 'challenge',
      conceptSlug: 'internal-energy-and-work',
      conceptTitle: 'Internal Energy and Work',
      question: {
        id: 'heatthermo-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A gas first expands at constant pressure 120000 Pa from 0.02 m³ to 0.05 m³, then is compressed at constant pressure 80000 Pa from 0.05 m³ back to 0.03 m³. Find the net work done by the gas over both steps.',
        hints: ['Find W for each step (W=PΔV), then add them (compression gives negative W).'],
        correctAnswer: 2000,
        explanation: 'Step 1: W₁=120000×0.03=3600 J. Step 2: W₂=80000×(−0.02)=−1600 J. Net: 3600−1600=2000 J.',
      },
    },
  ],
};
