import type { Assessment } from '@/types/content';

export const chapter8CInterferenceAssessment: Assessment = {
  id: 'interference-and-diffraction-of-light-assessment',
  questions: [
    {
      id: 'interfdiff-a1',
      part: 'concept',
      conceptSlug: 'huygens-principle',
      conceptTitle: "Huygens' Principle",
      question: {
        id: 'interfdiff-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: "According to Huygens' principle, how is a new wavefront constructed from an old one?",
        hints: ['Think about the envelope of many small sources.'],
        options: [
          { id: 'a', text: 'As the envelope of secondary wavelets spreading from every point on the old wavefront' },
          { id: 'b', text: 'By simply moving the old wavefront forward unchanged' },
          { id: 'c', text: 'Only from the two edge points of the wavefront' },
          { id: 'd', text: 'It cannot be constructed geometrically at all' },
        ],
        correctOptionId: 'a',
        explanation: 'Every point on the old wavefront emits a secondary wavelet; the new wavefront is the common tangent (envelope) of all of them.',
      },
    },
    {
      id: 'interfdiff-a2',
      part: 'concept',
      conceptSlug: 'interference-of-light',
      conceptTitle: 'Interference of Light',
      question: {
        id: 'interfdiff-a2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Light of wavelength 450 nm passes through slits 0.4 mm apart, forming a pattern on a screen 1 m away. Find the fringe spacing, in mm.',
        hints: ['Δy = λL/d.'],
        correctAnswer: 1.125,
        explanation: 'Δy = (450×10⁻⁹)(1)/(0.4×10⁻³) = 1.125×10⁻³ m = 1.125 mm.',
      },
    },
    {
      id: 'interfdiff-b1',
      part: 'formula-application',
      conceptSlug: 'diffraction-of-light',
      conceptTitle: 'Diffraction of Light',
      question: {
        id: 'interfdiff-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Light of wavelength 550 nm passes through a single slit 0.25 mm wide. Find the angle of the first minimum, in degrees.',
        hints: ['sinθ = mλ/a, with m=1.'],
        correctAnswer: 0.126,
        tolerance: 0.01,
        explanation: 'sinθ = (550×10⁻⁹)/(0.25×10⁻³) = 0.0022. θ ≈ 0.126°.',
      },
    },
    {
      id: 'interfdiff-b2',
      part: 'formula-application',
      conceptSlug: 'diffraction-grating',
      conceptTitle: 'The Diffraction Grating',
      question: {
        id: 'interfdiff-b2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A grating has 500 lines per millimetre. Find the first-order (m=1) diffraction angle for light of wavelength 600 nm.',
        hints: ['Find d=1/(500 lines/mm) first, then apply sinθ=mλ/d.'],
        correctAnswer: 17.46,
        tolerance: 0.2,
        explanation: 'd=1/500000 m=2000 nm. sinθ=600/2000=0.3. θ=sin⁻¹(0.3)≈17.46°.',
      },
    },
    {
      id: 'interfdiff-c1',
      part: 'problem-solving',
      conceptSlug: 'interference-of-light',
      conceptTitle: 'Interference of Light',
      question: {
        id: 'interfdiff-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In a double-slit setup, the fringe spacing is measured as 3 mm, with L=2.5 m and d=0.4 mm. Find the wavelength used, in nm.',
        hints: ['Rearrange Δy=λL/d to solve for λ.'],
        correctAnswer: 480,
        explanation: 'λ = Δy·d/L = (0.003)(0.0004)/2.5 = 4.8×10⁻⁷ m = 480 nm.',
      },
    },
    {
      id: 'interfdiff-c2',
      part: 'problem-solving',
      conceptSlug: 'diffraction-grating',
      conceptTitle: 'The Diffraction Grating',
      question: {
        id: 'interfdiff-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "A grating diffracts light of wavelength 500 nm at 14.5° for m=1. Find the grating's line density, in lines per mm.",
        hints: ['Find d=mλ/sinθ first, then convert to lines per mm (1/d, with d in mm).'],
        correctAnswer: 500,
        tolerance: 5,
        explanation: 'd = 500×10⁻⁹/sin(14.5°) ≈ 1997 nm ≈ 0.001997 mm. Lines/mm = 1/0.001997 ≈ 500.',
      },
    },
    {
      id: 'interfdiff-d1',
      part: 'real-life-application',
      conceptSlug: 'huygens-principle',
      conceptTitle: "Huygens' Principle",
      question: {
        id: 'interfdiff-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can a person hear music playing in another room even when the door is only slightly ajar, without seeing the source?',
        hints: ['This is diffraction — the same effect explained by Huygens\' principle.'],
        options: [
          { id: 'a', text: "Sound diffracts through the gap, spreading according to Huygens' principle" },
          { id: 'b', text: 'Sound cannot pass through any gap at all' },
          { id: 'c', text: 'The door material is somehow transparent to sound' },
          { id: 'd', text: 'Only light diffracts, never sound' },
        ],
        correctOptionId: 'a',
        explanation: "The narrow gap acts like a slit, and sound waves diffract through it, spreading into the room — exactly what Huygens' principle predicts.",
      },
    },
    {
      id: 'interfdiff-d2',
      part: 'real-life-application',
      conceptSlug: 'diffraction-of-light',
      conceptTitle: 'Diffraction of Light',
      question: {
        id: 'interfdiff-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why do larger telescope apertures (openings) produce sharper images of distant stars?',
        hints: ['Think about how the diffraction angle depends on slit/aperture width.'],
        options: [
          { id: 'a', text: 'A larger aperture reduces the diffraction-limited blur angle' },
          { id: 'b', text: 'Aperture size has nothing to do with diffraction' },
          { id: 'c', text: 'Larger apertures always distort images more' },
          { id: 'd', text: 'Aperture size only affects color, not sharpness' },
        ],
        correctOptionId: 'a',
        explanation: 'Since sinθ=λ/a for the diffraction limit, a larger aperture a produces a smaller diffraction angle θ, meaning less blur and a sharper image.',
      },
    },
    {
      id: 'interfdiff-e1',
      part: 'challenge',
      conceptSlug: 'interference-of-light',
      conceptTitle: 'Interference of Light',
      question: {
        id: 'interfdiff-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'In a double-slit experiment, the 4th bright fringe (m=4) appears 10 mm from the center on a screen 2 m away, with slits 0.5 mm apart. Find the wavelength used, in nm. (Use y=mλL/d.)',
        hints: ['Rearrange y=mλL/d to solve for λ.'],
        correctAnswer: 625,
        explanation: 'λ = y·d/(m·L) = (0.01)(0.0005)/(4×2) = 5×10⁻⁶/8 = 6.25×10⁻⁷ m = 625 nm.',
      },
    },
    {
      id: 'interfdiff-e2',
      part: 'challenge',
      conceptSlug: 'diffraction-grating',
      conceptTitle: 'The Diffraction Grating',
      question: {
        id: 'interfdiff-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A grating produces its second-order (m=2) maximum for red light (λ=700 nm) at the same angle as some other wavelength\'s third-order (m=3) maximum. Find that other wavelength, in nm.',
        hints: ['At the same angle and same grating, m₁λ₁ = m₂λ₂.'],
        correctAnswer: 466.7,
        tolerance: 1,
        explanation: '2(700) = 3λ₂. λ₂ = 1400/3 ≈ 466.7 nm.',
      },
    },
  ],
};
