import type { Assessment } from '@/types/content';

export const chapter1CAssessment: Assessment = {
  id: 'complex-numbers-assessment',
  questions: [
    {
      id: 'cplx-a1',
      part: 'concept',
      conceptSlug: 'the-imaginary-unit-and-i-squared',
      conceptTitle: 'The Imaginary Unit and i²',
      question: {
        id: 'cplx-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is i²?',
        options: [
          { id: 'a', text: '−1' },
          { id: 'b', text: '1' },
          { id: 'c', text: 'i' },
          { id: 'd', text: '0' },
        ],
        correctOptionId: 'a',
        hints: ['This is the defining property of i.'],
        explanation: 'i is defined so that i² = −1.',
      },
    },
    {
      id: 'cplx-a2',
      part: 'concept',
      conceptSlug: 'complex-numbers-in-standard-form',
      conceptTitle: 'Complex Numbers in Standard Form',
      question: {
        id: 'cplx-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'In z = a + bi, what is "b" called?',
        options: [
          { id: 'a', text: 'The imaginary part (a real number)' },
          { id: 'b', text: 'The modulus' },
          { id: 'c', text: 'The real part' },
          { id: 'd', text: 'The argument' },
        ],
        correctOptionId: 'a',
        hints: ['It\'s the real coefficient of i.'],
        explanation: 'b is the imaginary part of z — a real number, the coefficient of i.',
      },
    },
    {
      id: 'cplx-b1',
      part: 'formula-application',
      conceptSlug: 'adding-and-subtracting-complex-numbers',
      conceptTitle: 'Adding and Subtracting Complex Numbers',
      question: {
        id: 'cplx-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Compute (6−3i) + (−2+5i).',
        options: [
          { id: 'a', text: '4 + 2i' },
          { id: 'b', text: '8 + 2i' },
          { id: 'c', text: '4 − 8i' },
          { id: 'd', text: '8 − 8i' },
        ],
        correctOptionId: 'a',
        hints: ['Combine real parts and imaginary parts separately.'],
        explanation: '6+(−2)=4, and −3+5=2, giving 4+2i.',
      },
    },
    {
      id: 'cplx-b2',
      part: 'formula-application',
      conceptSlug: 'the-complex-plane-and-modulus',
      conceptTitle: 'The Complex Plane and Modulus',
      question: {
        id: 'cplx-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find |z| for z = 5+12i.',
        hints: ['|z| = √(a²+b²).'],
        correctAnswer: 13,
        explanation: '√(25+144) = √169 = 13.',
      },
    },
    {
      id: 'cplx-c1',
      part: 'problem-solving',
      conceptSlug: 'multiplying-complex-numbers',
      conceptTitle: 'Multiplying Complex Numbers',
      question: {
        id: 'cplx-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Multiply (3+2i)(3−2i). (The result is purely real — enter just that number.)',
        hints: ['This is a number times its own conjugate.', 'Result = 3² + 2².'],
        correctAnswer: 13,
        explanation: '9 − 4i² = 9+4 = 13.',
      },
    },
    {
      id: 'cplx-c2',
      part: 'problem-solving',
      conceptSlug: 'dividing-complex-numbers-using-conjugates',
      conceptTitle: 'Dividing Complex Numbers Using Conjugates',
      question: {
        id: 'cplx-c2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Divide (2+6i) by (2+i).',
        options: [
          { id: 'a', text: '2 + 2i' },
          { id: 'b', text: '2 − 2i' },
          { id: 'c', text: '10 + 10i' },
          { id: 'd', text: '5 + 5i' },
        ],
        correctOptionId: 'a',
        hints: ['Multiply top and bottom by the conjugate, 2−i.'],
        explanation: 'Numerator: (2+6i)(2−i)=4−2i+12i−6i²=10+10i. Denominator: (2+i)(2−i)=5. Result: (10+10i)/5=2+2i.',
      },
    },
    {
      id: 'cplx-d1',
      part: 'real-life-application',
      conceptSlug: 'the-trigonometric-form-of-a-complex-number',
      conceptTitle: 'The Trigonometric (Polar) Form of a Complex Number',
      question: {
        id: 'cplx-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Electrical engineers represent AC circuit impedance as a complex number. Which form makes it easiest to multiply two impedances (by simply multiplying magnitudes and adding angles)?',
        options: [
          { id: 'a', text: 'Trigonometric (polar) form' },
          { id: 'b', text: 'Standard form (a+bi) only' },
          { id: 'c', text: 'It cannot be simplified either way' },
          { id: 'd', text: 'Only the real part matters' },
        ],
        correctOptionId: 'a',
        hints: ['Recall how multiplication works in trigonometric form.'],
        explanation: 'In trigonometric form, multiplying two complex numbers just multiplies their moduli and adds their angles — far simpler than standard form.',
      },
    },
    {
      id: 'cplx-d2',
      part: 'real-life-application',
      conceptSlug: 'de-moivres-theorem',
      conceptTitle: "De Moivre's Theorem",
      question: {
        id: 'cplx-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A signal-processing engineer needs to compute a complex number raised to the 10th power quickly. Which tool makes this direct, rather than tediously multiplying it out 10 times?',
        options: [
          { id: 'a', text: "De Moivre's Theorem" },
          { id: 'b', text: 'The complex conjugate rule' },
          { id: 'c', text: 'Standard form addition' },
          { id: 'd', text: 'The imaginary unit definition alone' },
        ],
        correctOptionId: 'a',
        hints: ['This theorem is specifically about raising complex numbers to powers.'],
        explanation: "De Moivre's Theorem directly raises the modulus to the 10th power and multiplies the angle by 10, in one step.",
      },
    },
    {
      id: 'cplx-e1',
      part: 'challenge',
      conceptSlug: 'finding-nth-roots-of-a-complex-number',
      conceptTitle: 'Finding nth Roots of a Complex Number',
      question: {
        id: 'cplx-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why are the nth roots of a complex number always evenly spaced around a circle?',
        options: [
          { id: 'a', text: 'Each root\'s angle is (θ+360°k)/n for consecutive integers k, spacing them exactly 360°/n apart, while all share the same modulus r^(1/n)' },
          { id: 'b', text: 'It is simply defined that way, with no underlying reason' },
          { id: 'c', text: 'Only some roots share the same modulus' },
          { id: 'd', text: 'The spacing only holds for square roots' },
        ],
        correctOptionId: 'a',
        hints: ['Look at how the angle formula changes as k increases by 1.'],
        explanation: 'Increasing k by 1 always adds exactly 360°/n to the angle, while r^(1/n) stays fixed — that\'s exactly what produces even spacing on a circle.',
      },
    },
    {
      id: 'cplx-e2',
      part: 'challenge',
      conceptSlug: 'the-imaginary-unit-and-i-squared',
      conceptTitle: 'The Imaginary Unit and i²',
      question: {
        id: 'cplx-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Simplify i¹⁰⁰ using the 4-cycle pattern of powers of i, and give the result as a real number.',
        hints: ['100 ÷ 4 = 25, remainder 0.', 'A remainder of 0 matches i⁴=1.'],
        correctAnswer: 1,
        explanation: '100 is an exact multiple of 4, so i¹⁰⁰ = i⁴ = 1.',
      },
    },
  ],
};
