import type { Assessment } from '@/types/content';

export const chapter1MotionInAPlaneAssessment: Assessment = {
  id: 'motion-in-a-plane-assessment',
  questions: [
    {
      id: 'map-a1',
      part: 'concept',
      conceptSlug: 'projectile-motion-basics',
      conceptTitle: 'Projectile Motion: Independence of Horizontal and Vertical Motion',
      question: {
        id: 'map-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a projectile follow a curved (parabolic) path instead of a straight line?',
        options: [
          { id: 'a', text: 'Horizontal velocity stays constant while vertical velocity continuously accelerates due to gravity.' },
          { id: 'b', text: 'Both horizontal and vertical velocity accelerate equally.' },
          { id: 'c', text: 'Gravity acts horizontally, not vertically.' },
          { id: 'd', text: 'The projectile has no horizontal velocity at all.' },
        ],
        correctOptionId: 'a',
        hints: ['Gravity only acts in one of the two directions.'],
        explanation: 'The constant horizontal motion combined with accelerating vertical motion produces the characteristic curved, parabolic trajectory.',
      },
    },
    {
      id: 'map-a2',
      part: 'concept',
      conceptSlug: 'centripetal-acceleration-in-a-plane',
      conceptTitle: 'Centripetal Acceleration',
      question: {
        id: 'map-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An object moves at a constant 10 m/s around a circle. Is it accelerating?',
        options: [
          { id: 'a', text: 'Yes, because its direction is constantly changing even though its speed is constant.' },
          { id: 'b', text: 'No, constant speed always means zero acceleration.' },
          { id: 'c', text: 'Only if the circle is very large.' },
          { id: 'd', text: 'Only if it is speeding up.' },
        ],
        correctOptionId: 'a',
        hints: ['Velocity includes both speed AND direction.'],
        explanation: 'Since velocity is a vector, a continuously changing direction means continuously changing velocity — this is centripetal acceleration, even at constant speed.',
      },
    },
    {
      id: 'map-b1',
      part: 'formula-application',
      conceptSlug: 'resolving-vectors-in-two-dimensions',
      conceptTitle: 'Resolving Vectors into Components',
      question: {
        id: 'map-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A velocity of 30 m/s acts at 40° above the horizontal (cos40° ≈ 0.766). Find its horizontal component.',
        hints: ['vₓ = v cosθ.'],
        correctAnswer: 23.0,
        tolerance: 0.3,
        unit: 'm/s',
        explanation: 'vₓ = 30 × 0.766 ≈ 23.0 m/s.',
      },
    },
    {
      id: 'map-b2',
      part: 'formula-application',
      conceptSlug: 'centripetal-force-in-a-plane',
      conceptTitle: 'Centripetal Force',
      question: {
        id: 'map-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 2 kg object moves in a circle of radius 4 m at 8 m/s. Find the centripetal force required.',
        hints: ['F = mv²/r.'],
        correctAnswer: 32,
        tolerance: 0.5,
        unit: 'N',
        explanation: 'F = 2 × 8² / 4 = 2 × 64/4 = 128/4 = 32 N.',
      },
    },
    {
      id: 'map-c1',
      part: 'problem-solving',
      conceptSlug: 'time-of-flight-in-projectile-motion',
      conceptTitle: 'Time of Flight',
      question: {
        id: 'map-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A ball is launched at 18 m/s at 50° above horizontal (sin50° ≈ 0.766). Find its time of flight (g = 9.8 m/s²).',
        hints: ['T = 2u sinθ / g.'],
        correctAnswer: 2.81,
        tolerance: 0.1,
        unit: 's',
        explanation: 'T = (2 × 18 × 0.766) / 9.8 = 27.58/9.8 ≈ 2.81 s.',
      },
    },
    {
      id: 'map-c2',
      part: 'problem-solving',
      conceptSlug: 'horizontal-range-in-projectile-motion',
      conceptTitle: 'Horizontal Range',
      question: {
        id: 'map-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Two projectiles are launched at the same speed, one at 30° and one at 60°. How do their ranges compare?',
        options: [
          { id: 'a', text: 'They are equal, because 30° and 60° are complementary angles (sin2θ is the same for both).' },
          { id: 'b', text: 'The 30° launch always travels farther.' },
          { id: 'c', text: 'The 60° launch always travels farther.' },
          { id: 'd', text: 'Range cannot be compared without knowing the mass.' },
        ],
        correctOptionId: 'a',
        hints: ['Compute sin(2×30°) and sin(2×60°) and compare.'],
        explanation: 'sin(60°) = sin(120°), so both angles give the same sin2θ value and therefore the same range, despite their very different trajectories.',
      },
    },
    {
      id: 'map-d1',
      part: 'real-life-application',
      conceptSlug: 'centripetal-force-in-a-plane',
      conceptTitle: 'Centripetal Force',
      question: {
        id: 'map-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What provides the centripetal force that keeps the Moon in orbit around Earth?',
        options: [
          { id: 'a', text: "Earth's gravitational pull on the Moon" },
          { id: 'b', text: 'A centrifugal force pushing the Moon outward' },
          { id: 'c', text: 'The Moon\'s own engine-like thrust' },
          { id: 'd', text: 'Friction between the Moon and space' },
        ],
        correctOptionId: 'a',
        hints: ['What real force pulls the Moon toward Earth?'],
        explanation: "Earth's gravity supplies the inward (centripetal) force needed to keep the Moon moving along its curved orbital path.",
      },
    },
    {
      id: 'map-d2',
      part: 'real-life-application',
      conceptSlug: 'horizontal-range-in-projectile-motion',
      conceptTitle: 'Horizontal Range',
      question: {
        id: 'map-d2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why do long jumpers typically launch at an angle noticeably less than 45°, even though 45° maximises range for a projectile?',
        options: [
          { id: 'a', text: 'The idealised 45° result assumes launch and landing heights are equal and ignores factors like running speed carried into the jump, which real athletes must also account for.' },
          { id: 'b', text: '45° always gives the shortest possible range.' },
          { id: 'c', text: 'Human legs cannot generate any horizontal velocity.' },
          { id: 'd', text: 'Gravity is different for jumping than for other projectiles.' },
        ],
        correctOptionId: 'a',
        hints: ['The formula assumes idealised conditions that do not perfectly match a real jump.'],
        explanation: 'The formula\'s 45°-for-maximum-range result is an idealisation; real athletes balance angle against horizontal speed carried from their run-up, among other factors, so the practical optimal angle is lower.',
      },
    },
    {
      id: 'map-e1',
      part: 'challenge',
      conceptSlug: 'maximum-height-in-projectile-motion',
      conceptTitle: 'Maximum Height',
      question: {
        id: 'map-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'If a projectile\'s launch speed is doubled (angle unchanged), what happens to its maximum height?',
        options: [
          { id: 'a', text: 'It quadruples, since H depends on u².' },
          { id: 'b', text: 'It doubles.' },
          { id: 'c', text: 'It stays the same.' },
          { id: 'd', text: 'It halves.' },
        ],
        correctOptionId: 'a',
        hints: ['H = u²sin²θ/2g — what happens when u is squared?'],
        explanation: 'Since H is proportional to u², doubling u multiplies H by 2² = 4, quadrupling the maximum height.',
      },
    },
  ],
};
