import type { Formula } from '@/types/content';

export const chapter1MotionInAPlaneFormulas: Record<string, Formula> = {
  'vector-resolution-formula': {
    slug: 'vector-resolution-formula',
    name: 'Resolving a Vector into Components',
    expression: 'vₓ = v cosθ, vy = v sinθ',
    meaning: 'Any vector at an angle can be split into a horizontal (x) component and a vertical (y) component that together produce the same effect as the original vector.',
    variables: [
      { symbol: 'v', meaning: 'Magnitude of the original vector (e.g. speed, m/s)' },
      { symbol: 'θ', meaning: 'Angle the vector makes with the horizontal (x) axis, in degrees or radians' },
      { symbol: 'vₓ', meaning: 'Horizontal (x) component of the vector' },
      { symbol: 'vy', meaning: 'Vertical (y) component of the vector' },
    ],
    whenToUse: 'Use whenever a vector (velocity, force, displacement) acts at an angle and you need to analyse its horizontal and vertical effects separately.',
    relatedConceptSlugs: ['resolving-vectors-in-two-dimensions', 'projectile-motion-basics'],
  },
  'resultant-vector-formula': {
    slug: 'resultant-vector-formula',
    name: 'Resultant of Perpendicular Components',
    expression: 'R = √(vₓ² + vy²), θ = tan⁻¹(vy / vₓ)',
    meaning: 'Given two perpendicular components of a vector, this formula recombines them into a single resultant vector with a magnitude and direction.',
    variables: [
      { symbol: 'R', meaning: 'Magnitude of the resultant vector' },
      { symbol: 'vₓ', meaning: 'Horizontal (x) component' },
      { symbol: 'vy', meaning: 'Vertical (y) component' },
      { symbol: 'θ', meaning: 'Angle of the resultant above the x-axis' },
    ],
    whenToUse: 'Use to combine two perpendicular components (e.g. two forces, or a velocity\'s x and y parts) back into one overall vector.',
    relatedConceptSlugs: ['resultant-of-two-dimensional-vectors'],
  },
  'time-of-flight-formula': {
    slug: 'time-of-flight-formula',
    name: 'Time of Flight (Projectile Motion)',
    expression: 'T = 2u sinθ / g',
    meaning: 'The total time a projectile stays in the air, from launch until it returns to its launch height.',
    variables: [
      { symbol: 'T', meaning: 'Time of flight, in seconds' },
      { symbol: 'u', meaning: 'Initial launch speed, in m/s' },
      { symbol: 'θ', meaning: 'Launch angle above the horizontal' },
      { symbol: 'g', meaning: 'Acceleration due to gravity, 9.8 m/s²' },
    ],
    whenToUse: 'Use to find how long a projectile launched at an angle stays airborne before landing at the same height it was launched from.',
    relatedConceptSlugs: ['time-of-flight-in-projectile-motion'],
  },
  'maximum-height-formula': {
    slug: 'maximum-height-formula',
    name: 'Maximum Height (Projectile Motion)',
    expression: 'H = u² sin²θ / 2g',
    meaning: "The highest vertical point a projectile reaches, where its vertical velocity momentarily becomes zero.",
    variables: [
      { symbol: 'H', meaning: 'Maximum height, in metres' },
      { symbol: 'u', meaning: 'Initial launch speed, in m/s' },
      { symbol: 'θ', meaning: 'Launch angle above the horizontal' },
      { symbol: 'g', meaning: 'Acceleration due to gravity, 9.8 m/s²' },
    ],
    whenToUse: 'Use to find the peak height of a projectile\'s trajectory.',
    relatedConceptSlugs: ['maximum-height-in-projectile-motion'],
  },
  'horizontal-range-formula': {
    slug: 'horizontal-range-formula',
    name: 'Horizontal Range (Projectile Motion)',
    expression: 'R = u² sin2θ / g',
    meaning: 'The total horizontal distance a projectile travels before landing back at its launch height.',
    variables: [
      { symbol: 'R', meaning: 'Horizontal range, in metres' },
      { symbol: 'u', meaning: 'Initial launch speed, in m/s' },
      { symbol: 'θ', meaning: 'Launch angle above the horizontal' },
      { symbol: 'g', meaning: 'Acceleration due to gravity, 9.8 m/s²' },
    ],
    whenToUse: 'Use to find how far a projectile travels horizontally — note the range is maximised when θ = 45°, since sin2θ is then at its maximum value of 1.',
    relatedConceptSlugs: ['horizontal-range-in-projectile-motion'],
  },
  'period-frequency-formula': {
    slug: 'period-frequency-formula',
    name: 'Period, Frequency and Speed in Circular Motion',
    expression: 'T = 2πr / v, f = 1/T',
    meaning: 'Relates how long one full revolution takes (period) to the radius and speed of circular motion, and how frequency is the reciprocal of period.',
    variables: [
      { symbol: 'T', meaning: 'Period — time for one complete revolution, in seconds' },
      { symbol: 'r', meaning: 'Radius of the circular path, in metres' },
      { symbol: 'v', meaning: 'Constant speed along the circular path, in m/s' },
      { symbol: 'f', meaning: 'Frequency — number of revolutions per second, in Hz' },
    ],
    whenToUse: 'Use to relate the speed, radius, period, and frequency of any object moving at constant speed in a circle.',
    relatedConceptSlugs: ['period-and-frequency-in-circular-motion'],
  },
  'centripetal-acceleration-formula': {
    slug: 'centripetal-acceleration-formula',
    name: 'Centripetal Acceleration',
    expression: 'a = v² / r',
    meaning: 'The acceleration directed toward the centre of a circular path, responsible for continuously changing the direction of an object\'s velocity.',
    variables: [
      { symbol: 'a', meaning: 'Centripetal acceleration, in m/s²' },
      { symbol: 'v', meaning: 'Speed along the circular path, in m/s' },
      { symbol: 'r', meaning: 'Radius of the circular path, in metres' },
    ],
    whenToUse: 'Use whenever an object moves at constant speed along a circular path and you need the acceleration causing that curved motion.',
    relatedConceptSlugs: ['centripetal-acceleration-in-a-plane'],
  },
  'centripetal-force-in-a-plane-formula': {
    slug: 'centripetal-force-in-a-plane-formula',
    name: 'Centripetal Force',
    expression: 'F = mv² / r',
    meaning: 'The net force directed toward the centre of a circular path that is required to keep an object moving in that circle.',
    variables: [
      { symbol: 'F', meaning: 'Centripetal force, in newtons (N)' },
      { symbol: 'm', meaning: 'Mass of the object, in kg' },
      { symbol: 'v', meaning: 'Speed along the circular path, in m/s' },
      { symbol: 'r', meaning: 'Radius of the circular path, in metres' },
    ],
    whenToUse: 'Use to find the net inward force needed to keep an object of known mass moving in a circle of known radius and speed.',
    relatedConceptSlugs: ['centripetal-force-in-a-plane'],
  },
};
