import type { Assessment } from '@/types/content';

export const chapter7Assessment: Assessment = {
  id: 'probability-assessment',
  questions: [
    {
      id: 'prob-a1',
      part: 'concept',
      conceptSlug: 'meaning-of-probability-and-sample-space',
      conceptTitle: 'Meaning of Probability and Sample Space',
      question: {
        id: 'prob-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is the sample space?',
        options: [
          { id: 'a', text: 'The set of every possible outcome of an experiment' },
          { id: 'b', text: 'The single most likely outcome' },
          { id: 'c', text: 'The probability of an event' },
          { id: 'd', text: 'The number of favourable outcomes only' },
        ],
        correctOptionId: 'a',
        hints: ['Sample space = "S" in P(E) = n(E)/n(S).'],
        explanation: 'The sample space is every possible outcome; an event is a chosen subset of it.',
      },
    },
    {
      id: 'prob-a2',
      part: 'concept',
      conceptSlug: 'independent-events-and-the-multiplication-rule',
      conceptTitle: 'Independent Events and the Multiplication Rule',
      question: {
        id: 'prob-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does it mean for two events to be independent?',
        options: [
          { id: 'a', text: 'The outcome of one has no effect on the probability of the other' },
          { id: 'b', text: 'They cannot both happen' },
          { id: 'c', text: 'They always happen together' },
          { id: 'd', text: 'Their probabilities are equal' },
        ],
        correctOptionId: 'a',
        hints: ['Think of two separate coin tosses.'],
        explanation: 'Independent events have no influence on each other\'s probability.',
      },
    },
    {
      id: 'prob-b1',
      part: 'formula-application',
      conceptSlug: 'the-complement-rule',
      conceptTitle: 'The Complement Rule',
      question: {
        id: 'prob-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'P(E) = 0.72. Find P(E\').',
        hints: ["P(E') = 1 − P(E)."],
        correctAnswer: 0.28,
        explanation: '1 − 0.72 = 0.28.',
      },
    },
    {
      id: 'prob-b2',
      part: 'formula-application',
      conceptSlug: 'the-addition-rule-for-combined-events',
      conceptTitle: 'The Addition Rule for Combined Events',
      question: {
        id: 'prob-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'P(A) = 0.4, P(B) = 0.5, P(A∩B) = 0.1. Find P(A∪B).',
        hints: ['P(A∪B) = P(A) + P(B) − P(A∩B).'],
        correctAnswer: 0.8,
        explanation: '0.4 + 0.5 − 0.1 = 0.8.',
      },
    },
    {
      id: 'prob-c1',
      part: 'problem-solving',
      conceptSlug: 'independent-events-and-the-multiplication-rule',
      conceptTitle: 'Independent Events and the Multiplication Rule',
      question: {
        id: 'prob-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A fair coin is tossed 3 times. Find the probability of getting heads all three times.',
        hints: ['P(H)×P(H)×P(H) = (1/2)³.'],
        correctAnswer: 0.125,
        explanation: '(1/2)³ = 1/8 = 0.125.',
      },
    },
    {
      id: 'prob-c2',
      part: 'problem-solving',
      conceptSlug: 'conditional-probability',
      conceptTitle: 'Conditional Probability',
      question: {
        id: 'prob-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'P(A∩B) = 0.24 and P(B) = 0.4. Find P(A|B).',
        hints: ['P(A|B) = P(A∩B)/P(B).'],
        correctAnswer: 0.6,
        explanation: '0.24 / 0.4 = 0.6.',
      },
    },
    {
      id: 'prob-d1',
      part: 'real-life-application',
      conceptSlug: 'the-complement-rule',
      conceptTitle: 'The Complement Rule',
      question: {
        id: 'prob-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is the complement rule useful for "at least one defect in a batch" quality-control questions?',
        options: [
          { id: 'a', text: '"No defects at all" is usually much easier to compute directly than every "at least one" case.' },
          { id: 'b', text: 'Defects are always independent events.' },
          { id: 'c', text: 'It avoids needing a sample space.' },
          { id: 'd', text: 'It only works for exactly two items.' },
        ],
        correctOptionId: 'a',
        hints: ['Compare computing P(no defects) versus listing every way to have at least one.'],
        explanation: 'Computing "zero defects" directly is far simpler, then subtracting from 1 gives "at least one" instantly.',
      },
    },
    {
      id: 'prob-d2',
      part: 'real-life-application',
      conceptSlug: 'expected-frequency',
      conceptTitle: 'Expected Frequency',
      question: {
        id: 'prob-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An insurance company has 5,000 policyholders, each with a 0.02 probability of filing a claim this year. Find the expected number of claims.',
        hints: ['E = n × P(event) = 5000 × 0.02.'],
        correctAnswer: 100,
        explanation: '5000 × 0.02 = 100.',
      },
    },
    {
      id: 'prob-e1',
      part: 'challenge',
      conceptSlug: 'the-addition-rule-for-combined-events',
      conceptTitle: 'The Addition Rule for Combined Events',
      question: {
        id: 'prob-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A card is drawn from a standard 52-card deck. Find P(spade or face card), as a decimal rounded to 2 places. (13 spades, 12 face cards, 3 of the face cards are spades.)',
        hints: ['P(spade)=13/52, P(face)=12/52, P(spade∩face)=3/52.'],
        correctAnswer: 0.42,
        tolerance: 0.01,
        explanation: 'P = 13/52 + 12/52 − 3/52 = 22/52 ≈ 0.42.',
      },
    },
    {
      id: 'prob-e2',
      part: 'challenge',
      conceptSlug: 'conditional-probability',
      conceptTitle: 'Conditional Probability',
      question: {
        id: 'prob-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'If A and B are independent, what is P(A|B)?',
        options: [
          { id: 'a', text: 'P(A) — knowing B occurred does not change A\'s probability' },
          { id: 'b', text: 'P(B)' },
          { id: 'c', text: '0' },
          { id: 'd', text: '1' },
        ],
        correctOptionId: 'a',
        hints: ['Substitute P(A∩B) = P(A)P(B) into the conditional probability formula.'],
        explanation: 'P(A|B) = P(A∩B)/P(B) = P(A)P(B)/P(B) = P(A), confirming that independence means B gives no new information about A.',
      },
    },
  ],
};
