import type { Assessment } from '@/types/content';

export const chapter10CElectricalAssessment: Assessment = {
  id: 'electrical-energy-power-and-heating-effect-assessment',
  questions: [
    {
      id: 'elecenergy-a1',
      part: 'concept',
      conceptSlug: 'electromotive-force-and-circuits',
      conceptTitle: 'Electromotive Force and Electric Circuits',
      question: {
        id: 'elecenergy-a1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A battery has EMF 6 V and internal resistance 0.4 Ω. Find its terminal voltage when it drives 1.5 A.',
        hints: ['V = ε − Ir.'],
        correctAnswer: 5.4,
        explanation: 'V = 6 − (1.5)(0.4) = 6 − 0.6 = 5.4 V.',
      },
    },
    {
      id: 'elecenergy-a2',
      part: 'concept',
      conceptSlug: 'electrical-energy-and-power',
      conceptTitle: 'Electrical Energy and Electrical Power',
      question: {
        id: 'elecenergy-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A device operates at 9 V, drawing 2 A. Find its power.',
        hints: ['P = VI.'],
        correctAnswer: 18,
        explanation: 'P = 9 × 2 = 18 W.',
      },
    },
    {
      id: 'elecenergy-b1',
      part: 'formula-application',
      conceptSlug: 'joules-law-of-heating',
      conceptTitle: "Joule's Law of Heating",
      question: {
        id: 'elecenergy-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A current of 5 A flows through a 2 Ω resistor for 20 seconds. Find the heat generated.',
        hints: ['H = I²Rt.'],
        correctAnswer: 1000,
        explanation: 'H = (5²)(2)(20) = (25)(2)(20) = 1000 J.',
      },
    },
    {
      id: 'elecenergy-b2',
      part: 'formula-application',
      conceptSlug: 'applications-of-heating-effect',
      conceptTitle: 'Applications of the Heating Effect of Current',
      question: {
        id: 'elecenergy-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A heater delivers 800 W at 200 V. Find the resistance of its heating element.',
        hints: ['R = V²/P.'],
        correctAnswer: 50,
        explanation: 'R = 200²/800 = 40000/800 = 50 Ω.',
      },
    },
    {
      id: 'elecenergy-c1',
      part: 'problem-solving',
      conceptSlug: 'batteries-in-series-and-parallel',
      conceptTitle: 'Batteries in Series and in Parallel',
      question: {
        id: 'elecenergy-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Four identical 2 V cells, each with internal resistance 0.1 Ω, are connected in series. Find the total internal resistance.',
        hints: ['r_total = r₁+r₂+r₃+r₄.'],
        correctAnswer: 0.4,
        explanation: 'r_total = 4 × 0.1 = 0.4 Ω.',
      },
    },
    {
      id: 'elecenergy-c2',
      part: 'problem-solving',
      conceptSlug: 'electromotive-force-and-circuits',
      conceptTitle: 'Electromotive Force and Electric Circuits',
      question: {
        id: 'elecenergy-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "A battery's terminal voltage reads 11.4 V while supplying 3 A, with an EMF of 12 V. Find its internal resistance.",
        hints: ['Rearrange V=ε−Ir to solve for r.'],
        correctAnswer: 0.2,
        explanation: 'r = (ε−V)/I = (12−11.4)/3 = 0.6/3 = 0.2 Ω.',
      },
    },
    {
      id: 'elecenergy-d1',
      part: 'real-life-application',
      conceptSlug: 'joules-law-of-heating',
      conceptTitle: "Joule's Law of Heating",
      question: {
        id: 'elecenergy-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A fuse wire is designed to melt (breaking the circuit) when current exceeds a safe limit. Which physics principle explains this?',
        hints: ['Think about how heat generated depends on current.'],
        options: [
          { id: 'a', text: 'Joule heating (H=I²Rt) generates excess heat in the fuse wire as current increases' },
          { id: 'b', text: 'The fuse becomes magnetic and repels current' },
          { id: 'c', text: 'Fuses work by blocking voltage, not current' },
          { id: 'd', text: 'Fuses melt due to sunlight exposure' },
        ],
        correctOptionId: 'a',
        explanation: "A fuse is a thin wire with a specific resistance — excess current causes it to generate enough Joule heat (H=I²Rt) to melt, breaking the circuit and protecting the rest of it.",
      },
    },
    {
      id: 'elecenergy-d2',
      part: 'real-life-application',
      conceptSlug: 'batteries-in-series-and-parallel',
      conceptTitle: 'Batteries in Series and in Parallel',
      question: {
        id: 'elecenergy-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A power bank contains multiple lithium cells wired in parallel rather than series. What is the main benefit?',
        hints: ['Parallel identical cells keep the same voltage but change something else.'],
        options: [
          { id: 'a', text: 'It increases the total current (charge) capacity while keeping the same voltage' },
          { id: 'b', text: 'It multiplies the voltage output' },
          { id: 'c', text: 'It has no effect on performance at all' },
          { id: 'd', text: 'It reduces the total charge stored' },
        ],
        correctOptionId: 'a',
        explanation: 'Parallel identical cells keep the same voltage but combine their charge capacity, letting the power bank supply more current (or charge) over time.',
      },
    },
    {
      id: 'elecenergy-e1',
      part: 'challenge',
      conceptSlug: 'electrical-energy-and-power',
      conceptTitle: 'Electrical Energy and Electrical Power',
      question: {
        id: 'elecenergy-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An appliance rated at 2000 W runs for 3 hours. Find the energy used, in kWh.',
        hints: ['E = Pt, with P in kW and t in hours.'],
        correctAnswer: 6,
        explanation: 'E = 2 kW × 3 h = 6 kWh.',
      },
    },
    {
      id: 'elecenergy-e2',
      part: 'challenge',
      conceptSlug: 'applications-of-heating-effect',
      conceptTitle: 'Applications of the Heating Effect of Current',
      question: {
        id: 'elecenergy-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two identical heating elements, each 40 Ω, are connected in parallel and operated at 200 V. Find the total power dissipated.',
        hints: ['Find the parallel resistance first (R/2 for two identical resistors), then apply P=V²/R.'],
        correctAnswer: 2000,
        explanation: 'R_total = 40/2 = 20 Ω. P = 200²/20 = 40000/20 = 2000 W.',
      },
    },
  ],
};
