import type { Formula } from '@/types/content';

export const chapter10CElectricalFormulas: Record<string, Formula> = {
  'terminal-voltage-formula': {
    slug: 'terminal-voltage-formula',
    name: 'Terminal Voltage of a Battery',
    expression: 'V = ε − Ir',
    meaning: "A real battery's terminal voltage (what a circuit actually sees) is always slightly less than its full EMF, because some voltage is lost driving current through the battery's own internal resistance.",
    variables: [
      { symbol: 'V', meaning: 'terminal voltage, in volts (V)' },
      { symbol: 'ε', meaning: 'electromotive force (EMF) of the battery, in volts (V)' },
      { symbol: 'I', meaning: 'current flowing through the circuit, in amperes (A)' },
      { symbol: 'r', meaning: "the battery's internal resistance, in ohms (Ω)" },
    ],
    whenToUse: "Whenever the actual voltage a circuit experiences (as opposed to the battery's ideal EMF) needs to be found, accounting for internal resistance.",
    relatedConceptSlugs: ['electromotive-force-and-circuits'],
  },
  'battery-combination-formula': {
    slug: 'battery-combination-formula',
    name: 'Batteries in Series and in Parallel',
    expression: 'Series: ε_total = ε₁+ε₂+…, r_total = r₁+r₂+…;   Parallel (identical cells): ε_total = ε, r_total = r/n',
    meaning: 'Connecting batteries in series adds up their EMFs (and internal resistances) to give a higher voltage; connecting identical batteries in parallel keeps the same EMF but reduces the effective internal resistance, letting more current be supplied.',
    variables: [
      { symbol: 'ε_total', meaning: 'total (equivalent) EMF of the combination, in volts (V)' },
      { symbol: 'r_total', meaning: 'total (equivalent) internal resistance, in ohms (Ω)' },
      { symbol: 'n', meaning: 'number of identical cells connected in parallel' },
    ],
    whenToUse: 'Whenever the total EMF and internal resistance of several batteries connected in series or parallel needs to be found.',
    relatedConceptSlugs: ['batteries-in-series-and-parallel'],
  },
  'electrical-power-formula': {
    slug: 'electrical-power-formula',
    name: 'Electrical Power and Energy',
    expression: 'P = VI = I²R = V²/R;   E = Pt',
    meaning: 'Electrical power is the rate at which electrical energy is converted (to heat, light, motion, etc.); the total energy used over a time interval is simply power multiplied by time.',
    variables: [
      { symbol: 'P', meaning: 'electrical power, in watts (W)' },
      { symbol: 'V', meaning: 'voltage across the component, in volts (V)' },
      { symbol: 'I', meaning: 'current through the component, in amperes (A)' },
      { symbol: 'R', meaning: 'resistance of the component, in ohms (Ω)' },
      { symbol: 'E', meaning: 'total electrical energy used, in joules (J)' },
      { symbol: 't', meaning: 'time, in seconds (s)' },
    ],
    whenToUse: 'Whenever the electrical power delivered to a component, or the total energy used over some time, needs to be found.',
    relatedConceptSlugs: ['electrical-energy-and-power'],
  },
  'joules-law-formula': {
    slug: 'joules-law-formula',
    name: "Joule's Law of Heating",
    expression: 'H = I²Rt',
    meaning: 'When current flows through a resistor, electrical energy is converted into heat at a rate that grows with the SQUARE of the current — the total heat generated over a time t is I²Rt.',
    variables: [
      { symbol: 'H', meaning: 'heat generated, in joules (J)' },
      { symbol: 'I', meaning: 'current through the resistor, in amperes (A)' },
      { symbol: 'R', meaning: 'resistance, in ohms (Ω)' },
      { symbol: 't', meaning: 'time current flows, in seconds (s)' },
    ],
    whenToUse: 'Whenever the heat generated by current flowing through a resistance over a given time needs to be found.',
    relatedConceptSlugs: ['joules-law-of-heating'],
  },
  'heating-element-resistance-formula': {
    slug: 'heating-element-resistance-formula',
    name: 'Resistance for a Target Heating Power',
    expression: 'R = V²/P',
    meaning: 'A heating device (like an electric heater or iron) is designed with a specific resistance so that, at its rated operating voltage, it dissipates exactly its intended power as heat.',
    variables: [
      { symbol: 'R', meaning: 'resistance of the heating element, in ohms (Ω)' },
      { symbol: 'V', meaning: 'operating voltage, in volts (V)' },
      { symbol: 'P', meaning: 'target (rated) power output, in watts (W)' },
    ],
    whenToUse: 'Whenever designing (or checking) a heating element\'s resistance to deliver a specific power at a known operating voltage.',
    relatedConceptSlugs: ['applications-of-heating-effect'],
  },
};
