import type { Assessment } from '@/types/content';

export const chapter3AForcesAssessment: Assessment = {
  id: 'forces-assessment',
  questions: [
    {
      id: 'forces-a1',
      part: 'concept',
      conceptSlug: 'newtons-first-law',
      conceptTitle: "Newton's First Law",
      question: {
        id: 'forces-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'A hockey puck slides on frictionless ice with no other horizontal forces acting. What happens to its velocity?',
        hints: ['With zero net force, the first law applies directly.'],
        options: [
          { id: 'a', text: 'It gradually slows down' },
          { id: 'b', text: 'It stays constant' },
          { id: 'c', text: 'It speeds up' },
          { id: 'd', text: 'It stops immediately' },
        ],
        correctOptionId: 'b',
        explanation: 'With zero net force, Newton\'s first law says the velocity stays exactly constant.',
      },
    },
    {
      id: 'forces-a2',
      part: 'concept',
      conceptSlug: 'newtons-third-law',
      conceptTitle: "Newton's Third Law",
      question: {
        id: 'forces-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A rocket engine pushes exhaust gas downward. What is the third-law reaction force?',
        hints: ['The reaction acts on the OTHER object involved — the rocket.'],
        options: [
          { id: 'a', text: 'The gas pushes the rocket upward' },
          { id: 'b', text: 'The rocket pushes the gas upward' },
          { id: 'c', text: 'Air resistance slows the rocket' },
          { id: 'd', text: 'There is no reaction force in a vacuum' },
        ],
        correctOptionId: 'a',
        explanation: "The action is the rocket pushing gas downward; the reaction is the gas pushing the rocket upward, with equal magnitude.",
      },
    },
    {
      id: 'forces-b1',
      part: 'formula-application',
      conceptSlug: 'newtons-second-law',
      conceptTitle: "Newton's Second Law",
      question: {
        id: 'forces-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A net force of 36 N acts on an 8 kg cart. Find its acceleration.',
        hints: ['a = F/m.', '36/8.'],
        correctAnswer: 4.5,
        unit: 'm/s²',
        explanation: 'a = F/m = 36/8 = 4.5 m/s².',
      },
    },
    {
      id: 'forces-b2',
      part: 'formula-application',
      conceptSlug: 'mass-and-weight',
      conceptTitle: 'Mass and Weight',
      question: {
        id: 'forces-b2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the weight of a 12 kg mass on Earth (g = 9.8 m/s²).',
        hints: ['W = mg.', '12 × 9.8.'],
        correctAnswer: 117.6,
        unit: 'N',
        explanation: 'W = 12 × 9.8 = 117.6 N.',
      },
    },
    {
      id: 'forces-c1',
      part: 'problem-solving',
      conceptSlug: 'contact-forces',
      conceptTitle: 'Contact Forces: Friction, Normal Reaction and Tension',
      question: {
        id: 'forces-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A wooden block presses on a table with a normal force of 80 N. The coefficient of friction is 0.35. Find the maximum friction force.',
        hints: ['F(friction) = μN.', '0.35 × 80.'],
        correctAnswer: 28,
        unit: 'N',
        explanation: 'F(friction) = 0.35 × 80 = 28 N.',
      },
    },
    {
      id: 'forces-c2',
      part: 'problem-solving',
      conceptSlug: 'newtons-law-of-gravitation',
      conceptTitle: "Newton's Law of Gravitation",
      question: {
        id: 'forces-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the gravitational force between a 20 kg mass and a 100 kg mass, 5 m apart (G = 6.67 × 10⁻¹¹ N·m²/kg²).',
        hints: ['F = Gm₁m₂/r².', '(6.67×10⁻¹¹ × 20 × 100) / 5².'],
        correctAnswer: 5.34e-9,
        tolerance: 0.1e-9,
        unit: 'N',
        explanation: 'F = (6.67×10⁻¹¹ × 20 × 100)/25 = (1.334×10⁻⁷)/25 ≈ 5.34×10⁻⁹ N.',
      },
    },
    {
      id: 'forces-d1',
      part: 'real-life-application',
      conceptSlug: 'resultant-force-and-equilibrium',
      conceptTitle: 'Resultant Force and Equilibrium',
      question: {
        id: 'forces-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A sled is pulled forward with 90 N while friction resists with 65 N. Find the resultant force.',
        hints: ['Assign signs, then add.', '90 − 65.'],
        correctAnswer: 25,
        unit: 'N',
        explanation: 'Resultant = 90 − 65 = 25 N (forward).',
      },
    },
    {
      id: 'forces-d2',
      part: 'real-life-application',
      conceptSlug: 'momentum-and-impulse',
      conceptTitle: 'Momentum and Impulse',
      question: {
        id: 'forces-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 0.15 kg baseball moving at 30 m/s is caught and brought to rest by a glove in 0.05 s. Find the size of the average force exerted by the glove.',
        hints: ['F = Δp / Δt.', '(0.15 × 30) / 0.05.'],
        correctAnswer: 90,
        unit: 'N',
        explanation: 'Δp = 0.15×30 = 4.5 kg·m/s. F = Δp/Δt = 4.5/0.05 = 90 N.',
      },
    },
    {
      id: 'forces-e1',
      part: 'challenge',
      conceptSlug: 'freely-falling-bodies',
      conceptTitle: 'Freely Falling Bodies',
      question: {
        id: 'forces-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A 0.2 kg stone and a 7 kg bowling ball are dropped simultaneously from the same height in a vacuum chamber (no air resistance). By what factor does the bowling ball\'s acceleration differ from the stone\'s? (Enter 1 if they are the same.)',
        hints: ['Mass cancels out in F = ma and W = mg for free fall.'],
        correctAnswer: 1,
        explanation: 'In free fall, acceleration equals g for every mass — the factor is exactly 1 (identical acceleration).',
      },
    },
    {
      id: 'forces-e2',
      part: 'challenge',
      conceptSlug: 'conservation-of-momentum',
      conceptTitle: 'The Law of Conservation of Momentum',
      question: {
        id: 'forces-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A 2 kg trolley moving at 5 m/s collides with a stationary 3 kg trolley. After the collision, the 2 kg trolley bounces back at 1 m/s. Find the velocity of the 3 kg trolley after the collision.',
        hints: ['Total momentum before = total momentum after.', 'Give the rebounding trolley a negative velocity: 2×5 = 2×(−1) + 3×v.'],
        correctAnswer: 4,
        unit: 'm/s',
        explanation: '2×5 = 2×(−1) + 3v → 10 = −2 + 3v → 3v = 12 → v = 4 m/s (in the original direction of motion).',
      },
    },
  ],
};
