import type { Assessment } from '@/types/content';

export const chapter9AElectricityAssessment: Assessment = {
  id: 'electricity-assessment',
  questions: [
    {
      id: 'electricity-a1',
      part: 'concept',
      conceptSlug: 'electric-charge-a-level',
      conceptTitle: 'Electric Charge',
      question: {
        id: 'electricity-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'A positively charged rod is brought near a negatively charged sphere (without touching). What happens?',
        hints: ['Unlike charges follow one simple rule.'],
        options: [
          { id: 'a', text: 'They attract each other' },
          { id: 'b', text: 'They repel each other' },
          { id: 'c', text: 'Nothing happens' },
          { id: 'd', text: 'They both become neutral' },
        ],
        correctOptionId: 'a',
        explanation: 'Unlike charges (positive and negative) always attract each other.',
      },
    },
    {
      id: 'electricity-a2',
      part: 'concept',
      conceptSlug: 'conductors-insulators-semiconductors-a-level',
      conceptTitle: 'Conductors, Insulators and Semiconductors',
      question: {
        id: 'electricity-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which of these is the best electrical insulator?',
        hints: ['An insulator has tightly bound electrons.'],
        options: [
          { id: 'a', text: 'Copper' },
          { id: 'b', text: 'Rubber' },
          { id: 'c', text: 'Silicon' },
          { id: 'd', text: 'Aluminium' },
        ],
        correctOptionId: 'b',
        explanation: 'Rubber has tightly bound electrons that cannot move freely, making it an excellent insulator; copper and aluminium are conductors, and silicon is a semiconductor.',
      },
    },
    {
      id: 'electricity-b1',
      part: 'formula-application',
      conceptSlug: 'coulombs-law-a-level',
      conceptTitle: "Coulomb's Law",
      question: {
        id: 'electricity-b1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two charges of +6 × 10⁻⁶ C and +1 × 10⁻⁶ C are 0.3 m apart. Find the force between them (k = 9 × 10⁹ N·m²/C²).',
        hints: ['F = kq₁q₂/r².', '(9×10⁹ × 6×10⁻⁶ × 1×10⁻⁶) / 0.3².'],
        correctAnswer: 0.6,
        unit: 'N',
        explanation: 'F = (9×10⁹ × 6×10⁻⁶ × 1×10⁻⁶)/0.09 = 0.054/0.09 = 0.6 N.',
      },
    },
    {
      id: 'electricity-b2',
      part: 'formula-application',
      conceptSlug: 'matter-and-electricity-a-level',
      conceptTitle: 'Matter and Electricity',
      question: {
        id: 'electricity-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the total charge of 1 × 10¹⁵ electrons (e = 1.6 × 10⁻¹⁹ C).',
        hints: ['Q = ne.', '1×10¹⁵ × 1.6×10⁻¹⁹.'],
        correctAnswer: 0.00016,
        unit: 'C',
        explanation: 'Q = 1×10¹⁵ × 1.6×10⁻¹⁹ = 1.6×10⁻⁴ C.',
      },
    },
    {
      id: 'electricity-c1',
      part: 'problem-solving',
      conceptSlug: 'electrification-a-level',
      conceptTitle: 'Electrification',
      question: {
        id: 'electricity-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A plastic rod is rubbed with a wool cloth, and the rod becomes negatively charged. What happened to the wool?',
        hints: ['Charging by friction transfers electrons between the two materials.'],
        options: [
          { id: 'a', text: 'The wool lost electrons, becoming positively charged' },
          { id: 'b', text: 'The wool gained electrons, becoming negatively charged' },
          { id: 'c', text: 'The wool stayed exactly neutral' },
          { id: 'd', text: 'The wool lost protons' },
        ],
        correctOptionId: 'a',
        explanation: 'Since the rod gained electrons (becoming negative), the wool must have lost those same electrons, becoming positively charged.',
      },
    },
    {
      id: 'electricity-c2',
      part: 'problem-solving',
      conceptSlug: 'coulombs-law-a-level',
      conceptTitle: "Coulomb's Law",
      question: {
        id: 'electricity-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two charges of +2 × 10⁻⁶ C and +3 × 10⁻⁶ C experience a force of 0.054 N. Find their separation r (k = 9 × 10⁹ N·m²/C²).',
        hints: ['Rearrange F = kq₁q₂/r² to r² = kq₁q₂/F.', '(9×10⁹ × 2×10⁻⁶ × 3×10⁻⁶) / 0.054.'],
        correctAnswer: 1,
        unit: 'm',
        explanation: 'r² = (9×10⁹×2×10⁻⁶×3×10⁻⁶)/0.054 = 0.054/0.054 = 1, so r = 1 m.',
      },
    },
    {
      id: 'electricity-d1',
      part: 'real-life-application',
      conceptSlug: 'electric-charge-a-level',
      conceptTitle: 'Electric Charge',
      question: {
        id: 'electricity-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a plastic comb, after being rubbed on dry hair, pick up small pieces of paper?',
        hints: ['The paper starts out neutral, not pre-charged.'],
        options: [
          { id: 'a', text: 'The charged comb induces an opposite charge on the paper, which then attracts it' },
          { id: 'b', text: 'The paper is always positively charged to begin with' },
          { id: 'c', text: 'Static electricity does not actually explain this' },
          { id: 'd', text: 'The comb repels the paper into the air' },
        ],
        correctOptionId: 'a',
        explanation: "The charged comb induces an opposite charge on the nearby neutral paper's surface, and this induced charge is then attracted to the comb.",
      },
    },
    {
      id: 'electricity-d2',
      part: 'real-life-application',
      conceptSlug: 'electrification-a-level',
      conceptTitle: 'Electrification',
      question: {
        id: 'electricity-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A person touching the dome of a Van de Graaff generator becomes charged, making their hair stand on end. Which method of electrification is this?',
        hints: ['This involves direct physical contact.'],
        options: [
          { id: 'a', text: 'Charging by friction' },
          { id: 'b', text: 'Charging by conduction' },
          { id: 'c', text: 'Charging by induction' },
          { id: 'd', text: 'None of these — this cannot really happen' },
        ],
        correctOptionId: 'b',
        explanation: "Direct contact with the already-charged dome transfers charge onto the person, which is charging by conduction.",
      },
    },
    {
      id: 'electricity-e1',
      part: 'challenge',
      conceptSlug: 'coulombs-law-a-level',
      conceptTitle: "Coulomb's Law",
      question: {
        id: 'electricity-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two EQUAL charges are 0.1 m apart and repel each other with a force of 0.9 N. Find the magnitude of each charge (k = 9 × 10⁹ N·m²/C²).',
        hints: ['F = kq²/r², since both charges are equal.', 'q² = Fr²/k.'],
        correctAnswer: 0.000001,
        unit: 'C',
        explanation: 'q² = (0.9×0.01)/9×10⁹ = 0.009/9×10⁹ = 1×10⁻¹², so q = 1×10⁻⁶ C (1 μC).',
      },
    },
    {
      id: 'electricity-e2',
      part: 'challenge',
      conceptSlug: 'matter-and-electricity-a-level',
      conceptTitle: 'Matter and Electricity',
      question: {
        id: 'electricity-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A charged sphere has a charge of +4.8 × 10⁻¹⁸ C, meaning it is missing some electrons. Find how many electrons are missing (e = 1.6 × 10⁻¹⁹ C).',
        hints: ['n = Q/e.', '4.8×10⁻¹⁸ / 1.6×10⁻¹⁹.'],
        correctAnswer: 30,
        explanation: 'n = 4.8×10⁻¹⁸ / 1.6×10⁻¹⁹ = 30 electrons missing.',
      },
    },
  ],
};
