import type { Assessment } from '@/types/content';

export const chapter2PhysicsAssessment: Assessment = {
  id: 'motion-assessment',
  questions: [
    {
      id: 'motion-a1',
      part: 'concept',
      conceptSlug: 'vectors-and-scalars',
      conceptTitle: 'Vectors and Scalars',
      question: {
        id: 'motion-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which of the following is a scalar quantity?',
        hints: ['A scalar has size only, no direction.'],
        options: [
          { id: 'a', text: 'Velocity' },
          { id: 'b', text: 'Time' },
          { id: 'c', text: 'Displacement' },
          { id: 'd', text: 'Force' },
        ],
        correctOptionId: 'b',
        explanation: 'Time has only a size (magnitude) and no direction, so it is a scalar; velocity, displacement and force are all vectors.',
      },
    },
    {
      id: 'motion-a2',
      part: 'concept',
      conceptSlug: 'distance-and-displacement',
      conceptTitle: 'Distance and Displacement',
      question: {
        id: 'motion-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A hiker walks 400 m north, then 300 m south. Find the magnitude of the displacement.',
        hints: ['Displacement is the net change in position.', '400 − 300.'],
        correctAnswer: 100,
        unit: 'm',
        explanation: 'Displacement = 400 − 300 = 100 m (north).',
      },
    },
    {
      id: 'motion-b1',
      part: 'formula-application',
      conceptSlug: 'speed',
      conceptTitle: 'Speed',
      question: {
        id: 'motion-b1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A train covers 240 m in 12 s. What is its speed?',
        hints: ['speed = distance / time.', '240/12.'],
        correctAnswer: 20,
        unit: 'm/s',
        explanation: 'speed = 240/12 = 20 m/s.',
      },
    },
    {
      id: 'motion-b2',
      part: 'formula-application',
      conceptSlug: 'velocity',
      conceptTitle: 'Velocity',
      question: {
        id: 'motion-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: "A hiker's displacement is 60 m east in 15 s. Find the size of the velocity.",
        hints: ['velocity = displacement / time.', '60/15.'],
        correctAnswer: 4,
        unit: 'm/s',
        explanation: 'velocity = 60/15 = 4 m/s (east).',
      },
    },
    {
      id: 'motion-c1',
      part: 'problem-solving',
      conceptSlug: 'acceleration',
      conceptTitle: 'Acceleration',
      question: {
        id: 'motion-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A motorcycle accelerates from 4 m/s to 22 m/s in 6 s. Find its acceleration.',
        hints: ['a = (v − u) / t.', '(22 − 4) / 6.'],
        correctAnswer: 3,
        unit: 'm/s²',
        explanation: 'a = (22 − 4)/6 = 18/6 = 3 m/s².',
      },
    },
    {
      id: 'motion-c2',
      part: 'problem-solving',
      conceptSlug: 'the-first-equation-of-motion',
      conceptTitle: 'The First Equation of Motion (v = u + at)',
      question: {
        id: 'motion-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A skater starts at 3 m/s and accelerates at 2 m/s² for 5 s. Find the final velocity.',
        hints: ['v = u + at.', '3 + (2 × 5).'],
        correctAnswer: 13,
        unit: 'm/s',
        explanation: 'v = 3 + (2×5) = 3 + 10 = 13 m/s.',
      },
    },
    {
      id: 'motion-d1',
      part: 'real-life-application',
      conceptSlug: 'the-second-equation-of-motion',
      conceptTitle: 'The Second Equation of Motion (s = ut + ½at²)',
      question: {
        id: 'motion-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A cyclist pulls away from a stop sign at 1 m/s and accelerates at 0.5 m/s² for 8 s. Find the distance travelled.',
        hints: ['s = ut + ½at².', '(1 × 8) + ½ × 0.5 × 8².'],
        correctAnswer: 24,
        unit: 'm',
        explanation: 's = (1×8) + ½×0.5×64 = 8 + 16 = 24 m.',
      },
    },
    {
      id: 'motion-d2',
      part: 'real-life-application',
      conceptSlug: 'free-fall',
      conceptTitle: 'Free Fall',
      question: {
        id: 'motion-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A stone is dropped from a bridge and falls for 2.5 s before hitting the water. Using g = 9.8 m/s², find how far it falls.',
        hints: ['s = ut + ½at², with u = 0.', '½ × 9.8 × 2.5².'],
        correctAnswer: 30.6,
        tolerance: 0.2,
        unit: 'm',
        explanation: 's = ½ × 9.8 × 2.5² = ½ × 9.8 × 6.25 = 30.625 ≈ 30.6 m.',
      },
    },
    {
      id: 'motion-e1',
      part: 'challenge',
      conceptSlug: 'the-third-equation-of-motion',
      conceptTitle: 'The Third Equation of Motion (v² = u² + 2as)',
      question: {
        id: 'motion-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A car starts at 6 m/s and accelerates uniformly to 26 m/s over a distance of 160 m. Find its acceleration.',
        hints: ['v² = u² + 2as, rearranged to solve for a.', '(26² − 6²) / (2 × 160).'],
        correctAnswer: 2,
        unit: 'm/s²',
        explanation: 'a = (26² − 6²) / (2×160) = (676 − 36)/320 = 640/320 = 2 m/s².',
      },
    },
    {
      id: 'motion-e2',
      part: 'challenge',
      conceptSlug: 'velocity-time-graphs',
      conceptTitle: 'Velocity-Time Graphs',
      question: {
        id: 'motion-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A velocity-time graph is a straight line from (0 s, 4 m/s) to (8 s, 20 m/s). Find the total displacement using the area under the graph.',
        hints: ['The area under a velocity-time graph is displacement.', 'The shape is a trapezium: area = ½(sum of parallel sides) × height.'],
        correctAnswer: 96,
        unit: 'm',
        explanation: 'Displacement = area of trapezium = ½ × (4 + 20) × 8 = ½ × 24 × 8 = 96 m.',
      },
    },
  ],
};
