import type { Assessment } from '@/types/content';

export const chapter9CAssessment: Assessment = {
  id: 'applications-of-derivatives-assessment',
  questions: [
    {
      id: 'appderiv-a1',
      part: 'concept',
      conceptSlug: 'reviewing-derivatives-of-various-function-types',
      conceptTitle: 'Reviewing Derivatives of Various Function Types',
      question: {
        id: 'appderiv-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: "Find f'(x) for f(x) = 5x² + cos(x).",
        hints: ['Differentiate each term separately.'],
        options: [
          { id: 'a', text: "f'(x) = 10x − sin(x)" },
          { id: 'b', text: "f'(x) = 10x + sin(x)" },
          { id: 'c', text: "f'(x) = 5x − sin(x)" },
          { id: 'd', text: "f'(x) = 10x − cos(x)" },
        ],
        correctOptionId: 'a',
        explanation: 'Power rule gives 10x for 5x²; the derivative of cos(x) is −sin(x).',
      },
    },
    {
      id: 'appderiv-a2',
      part: 'concept',
      conceptSlug: 'critical-points-and-where-they-occur',
      conceptTitle: 'Critical Points and Where They Occur',
      question: {
        id: 'appderiv-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the critical point of f(x) = x² − 6x + 5.',
        hints: ["Set f'(x)=0 and solve for x."],
        correctAnswer: 3,
        explanation: "f'(x) = 2x − 6 = 0 ⟹ x = 3.",
      },
    },
    {
      id: 'appderiv-b1',
      part: 'formula-application',
      conceptSlug: 'increasing-and-decreasing-intervals',
      conceptTitle: 'Increasing and Decreasing Intervals',
      question: {
        id: 'appderiv-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'f(x) = x² − 6x + 5 has a critical point at x=3. Is f increasing or decreasing on (3, ∞)?',
        hints: ["Test f'(x)=2x−6 at a sample point like x=4."],
        options: [
          { id: 'a', text: 'Increasing' },
          { id: 'b', text: 'Decreasing' },
          { id: 'c', text: 'Constant' },
          { id: 'd', text: 'Cannot be determined' },
        ],
        correctOptionId: 'a',
        explanation: "f'(4) = 2(4)−6 = 2 > 0, so f is increasing on (3,∞).",
      },
    },
    {
      id: 'appderiv-b2',
      part: 'formula-application',
      conceptSlug: 'the-second-derivative-and-concavity',
      conceptTitle: 'The Second Derivative and Concavity',
      question: {
        id: 'appderiv-b2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Is f(x) = x³ − 3x concave up or concave down at x=2?',
        hints: ["Compute f''(2) and check its sign."],
        options: [
          { id: 'a', text: 'Concave up' },
          { id: 'b', text: 'Concave down' },
          { id: 'c', text: 'Neither — it is an inflection point' },
          { id: 'd', text: 'Cannot be determined' },
        ],
        correctOptionId: 'a',
        explanation: "f''(x)=6x, so f''(2)=12 > 0, meaning concave up.",
      },
    },
    {
      id: 'appderiv-c1',
      part: 'problem-solving',
      conceptSlug: 'finding-absolute-and-local-extrema',
      conceptTitle: 'Finding Absolute and Local Extrema',
      question: {
        id: 'appderiv-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the absolute minimum of f(x) = x³ − 3x on [0, 2].',
        hints: ['Check the critical point inside [0,2] and both endpoints.'],
        correctAnswer: -2,
        explanation: 'f(0)=0, f(1)=−2 (the only critical point in range), f(2)=2 — the smallest is −2.',
      },
    },
    {
      id: 'appderiv-c2',
      part: 'problem-solving',
      conceptSlug: 'the-second-derivative-test-for-extrema',
      conceptTitle: 'The Second Derivative Test for Extrema',
      question: {
        id: 'appderiv-c2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'For f(x) = x³ − 3x, use the Second Derivative Test to classify the critical point at x = −1.',
        options: [
          { id: 'a', text: 'Local maximum' },
          { id: 'b', text: 'Local minimum' },
          { id: 'c', text: 'Inflection point' },
          { id: 'd', text: 'Inconclusive' },
        ],
        correctOptionId: 'a',
        hints: ["Compute f''(−1) and check its sign."],
        explanation: "f''(x)=6x, so f''(−1)=−6 < 0, which the Second Derivative Test classifies as a local maximum.",
      },
    },
    {
      id: 'appderiv-d1',
      part: 'real-life-application',
      conceptSlug: 'linear-approximation-using-derivatives',
      conceptTitle: 'Linear Approximation Using Derivatives',
      question: {
        id: 'appderiv-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A technician needs a quick estimate of √9.1 without a calculator, using linear approximation at a=9 (f(9)=3, f\'(9)=1/6). What is the estimate?',
        hints: ['L(x) = f(9) + f\'(9)(x−9).'],
        correctAnswer: 3.0167,
        tolerance: 0.01,
        explanation: 'L(9.1) = 3 + (1/6)(0.1) = 3 + 0.0167 ≈ 3.0167.',
      },
    },
    {
      id: 'appderiv-d2',
      part: 'real-life-application',
      conceptSlug: 'critical-points-and-where-they-occur',
      conceptTitle: 'Critical Points and Where They Occur',
      question: {
        id: 'appderiv-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A ball thrown into the air reaches its peak height at the exact instant its velocity (the derivative of height) equals zero. What is this instant called in calculus?',
        options: [
          { id: 'a', text: 'A critical point' },
          { id: 'b', text: 'An absolute minimum' },
          { id: 'c', text: 'An inflection point' },
          { id: 'd', text: 'A vertical asymptote' },
        ],
        correctOptionId: 'a',
        hints: ['A point where the derivative equals zero is exactly the definition.'],
        explanation: 'A point where the derivative is zero (or undefined) is, by definition, a critical point.',
      },
    },
    {
      id: 'appderiv-e1',
      part: 'challenge',
      conceptSlug: 'finding-absolute-and-local-extrema',
      conceptTitle: 'Finding Absolute and Local Extrema',
      question: {
        id: 'appderiv-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the absolute maximum of f(x) = x³ − 3x on [−3, 3].',
        hints: ['Check both critical points (x=±1) and both endpoints (x=±3).'],
        correctAnswer: 18,
        explanation: 'f(−3)=−18, f(−1)=2, f(1)=−2, f(3)=18 — the largest is 18, at x=3.',
      },
    },
    {
      id: 'appderiv-e2',
      part: 'challenge',
      conceptSlug: 'linear-approximation-using-derivatives',
      conceptTitle: 'Linear Approximation Using Derivatives',
      question: {
        id: 'appderiv-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Using f(x)=∛x and a=8 (f(8)=2, f\'(8)=1/12), estimate ∛8.3.',
        hints: ['L(x) = f(8) + f\'(8)(x−8).'],
        correctAnswer: 2.025,
        tolerance: 0.01,
        explanation: 'L(8.3) = 2 + (1/12)(0.3) = 2 + 0.025 = 2.025.',
      },
    },
  ],
};
