import type { Assessment } from '@/types/content';

export const chapter9ElectricFieldAssessment: Assessment = {
  id: 'electric-field-assessment',
  questions: [
    {
      id: 'ef-a1',
      part: 'concept',
      conceptSlug: 'coulombs-law',
      conceptTitle: "Coulomb's Law",
      question: {
        id: 'ef-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'If the distance between two charges is doubled, what happens to the force between them?',
        options: [
          { id: 'a', text: 'It becomes one-quarter as strong (inverse-square law).' },
          { id: 'b', text: 'It becomes half as strong.' },
          { id: 'c', text: 'It stays exactly the same.' },
          { id: 'd', text: 'It doubles.' },
        ],
        correctOptionId: 'a',
        hints: ['F depends on 1/r².'],
        explanation: 'Since force depends on 1/r², doubling r reduces force to 1/4 of its original value.',
      },
    },
    {
      id: 'ef-a2',
      part: 'concept',
      conceptSlug: 'equipotential-surfaces',
      conceptTitle: 'Equipotential Surfaces',
      question: {
        id: 'ef-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How are equipotential surfaces oriented relative to electric field lines?',
        options: [
          { id: 'a', text: 'Always perpendicular to field lines.' },
          { id: 'b', text: 'Always parallel to field lines.' },
          { id: 'c', text: 'They have no fixed relationship to field lines.' },
          { id: 'd', text: 'Equipotential surfaces do not exist near field lines.' },
        ],
        correctOptionId: 'a',
        hints: ['Zero work along the surface implies a specific geometric relationship to the field.'],
        explanation: 'Equipotential surfaces are always perpendicular to field lines, since no work is needed to move along them.',
      },
    },
    {
      id: 'ef-a3',
      part: 'concept',
      conceptSlug: 'electric-charge-distribution',
      conceptTitle: 'Electric Charge Distribution',
      question: {
        id: 'ef-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Where does charge concentrate most densely on an irregularly shaped charged conductor?',
        options: [
          { id: 'a', text: 'At sharply curved points.' },
          { id: 'b', text: 'On flat regions only.' },
          { id: 'c', text: 'Charge always distributes perfectly evenly regardless of shape.' },
          { id: 'd', text: 'Charge distribution is random and unpredictable.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall the lightning rod example.'],
        explanation: 'Charge density is highest at sharply curved points due to the geometry of mutual repulsion on the surface.',
      },
    },
    {
      id: 'ef-b1',
      part: 'formula-application',
      conceptSlug: 'electric-field-and-field-intensity',
      conceptTitle: 'Electric Field and Electric Field Intensity',
      question: {
        id: 'ef-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A charge of 3 × 10⁻⁶ C experiences a force of 0.6 N. Find the electric field intensity.',
        hints: ['E = F/q.'],
        correctAnswer: 200000,
        tolerance: 3000,
        unit: 'N/C',
        explanation: 'E = 0.6/(3×10⁻⁶) = 200,000 N/C.',
      },
    },
    {
      id: 'ef-b2',
      part: 'formula-application',
      conceptSlug: 'potential-difference-between-parallel-plates',
      conceptTitle: 'Potential Difference Between Two Parallel Charged Plates',
      question: {
        id: 'ef-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Two parallel plates 0.01 m apart carry a potential difference of 500 V. Find the electric field strength between them.',
        hints: ['E = V/d.'],
        correctAnswer: 50000,
        tolerance: 1000,
        unit: 'V/m',
        explanation: 'E = 500/0.01 = 50,000 V/m.',
      },
    },
    {
      id: 'ef-c1',
      part: 'problem-solving',
      conceptSlug: 'coulombs-law',
      conceptTitle: "Coulomb's Law",
      question: {
        id: 'ef-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Two charges of 6 × 10⁻⁶ C and 1 × 10⁻⁶ C are 0.3 m apart. Find the force between them (k = 8.99 × 10⁹ N·m²/C²).',
        hints: ['F = kq₁q₂/r².'],
        correctAnswer: 0.599,
        tolerance: 0.02,
        unit: 'N',
        explanation: 'F = (8.99×10⁹ × 6×10⁻⁶ × 1×10⁻⁶)/0.3² = 53.94×10⁻³/0.09 ≈ 0.599 N.',
      },
    },
    {
      id: 'ef-c2',
      part: 'problem-solving',
      conceptSlug: 'electric-potential-and-potential-difference',
      conceptTitle: 'Electric Potential and Potential Difference',
      question: {
        id: 'ef-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the distance from a +8 × 10⁻⁶ C charge at which the electric potential is 71,920 V (k = 8.99 × 10⁹ N·m²/C²).',
        hints: ['V = kQ/r, rearranged: r = kQ/V.'],
        correctAnswer: 1,
        tolerance: 0.05,
        unit: 'm',
        explanation: 'r = (8.99×10⁹ × 8×10⁻⁶)/71,920 ≈ 71,920/71,920 = 1 m.',
      },
    },
    {
      id: 'ef-d1',
      part: 'real-life-application',
      conceptSlug: 'electric-potential-of-the-earth',
      conceptTitle: 'Electric Potential of the Earth',
      question: {
        id: 'ef-d1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why does grounding an appliance improve electrical safety?',
        options: [
          { id: 'a', text: 'It provides a safe path for stray current to flow to the Earth\'s stable zero-potential reference, rather than through a person.' },
          { id: 'b', text: 'Grounding has no effect on electrical safety.' },
          { id: 'c', text: 'Grounding increases the appliance\'s voltage.' },
          { id: 'd', text: 'Grounding disconnects the appliance from all power.' },
        ],
        correctOptionId: 'a',
        hints: ["Think about where stray current would otherwise go."],
        explanation: 'Grounding gives stray current a safe path to the Earth rather than through a person touching the appliance.',
      },
    },
    {
      id: 'ef-d2',
      part: 'real-life-application',
      conceptSlug: 'electric-charge-distribution',
      conceptTitle: 'Electric Charge Distribution',
      question: {
        id: 'ef-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why are lightning rods designed with sharp points rather than flat tops?',
        options: [
          { id: 'a', text: 'Sharp points concentrate charge, creating a strong local field that helps manage or trigger a controlled discharge.' },
          { id: 'b', text: 'Sharp points repel all charge away from the rod.' },
          { id: 'c', text: 'Shape has no effect on how a lightning rod functions.' },
          { id: 'd', text: 'Flat tips work better for lightning rods.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall how charge density relates to surface curvature.'],
        explanation: "A sharp point's high charge concentration creates a strong local field, useful for managing electrical discharge safely.",
      },
    },
    {
      id: 'ef-e1',
      part: 'challenge',
      conceptSlug: 'electric-potential-and-potential-difference',
      conceptTitle: 'Electric Potential and Potential Difference',
      question: {
        id: 'ef-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A charge of 4 × 10⁻⁶ C is moved from a point at 500 V to a point at 200 V. What can you say about the work done?',
        options: [
          { id: 'a', text: 'The electric field does positive work on the positive charge, since it moves toward lower potential (W = qΔV = 4×10⁻⁶ × 300 = 1.2×10⁻³ J of work done BY the field).' },
          { id: 'b', text: 'No work is done, since potential changed.' },
          { id: 'c', text: 'The charge must be negative for any work to be done.' },
          { id: 'd', text: 'Potential difference is unrelated to work.' },
        ],
        correctOptionId: 'a',
        hints: ['A positive charge naturally moves from high to low potential, similar to how a mass falls from high to low gravitational potential.'],
        explanation: 'A positive charge moving from higher to lower potential has positive work done on it by the field, calculated as W = qΔV = 4×10⁻⁶ × (500−200) = 1.2×10⁻³ J.',
      },
    },
  ],
};
