import type { Assessment } from '@/types/content';

export const chapter7BAssessment: Assessment = {
  id: 'circles-advanced-assessment',
  questions: [
    {
      id: 'circ2-a1',
      part: 'concept',
      conceptSlug: 'the-tangent-radius-perpendicularity-theorem',
      conceptTitle: 'The Tangent-Radius Perpendicularity Theorem',
      question: {
        id: 'circ2-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What angle does a tangent line always make with the radius at the point of tangency?',
        options: [
          { id: 'a', text: '90°' },
          { id: 'b', text: '45°' },
          { id: 'c', text: '180°' },
          { id: 'd', text: 'It varies' },
        ],
        correctOptionId: 'a',
        hints: ['Tangent ⊥ radius.'],
        explanation: 'A tangent is always perpendicular (90°) to the radius at the point of tangency.',
      },
    },
    {
      id: 'circ2-a2',
      part: 'concept',
      conceptSlug: 'the-two-tangent-theorem',
      conceptTitle: 'The Two-Tangent Theorem',
      question: {
        id: 'circ2-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Two tangents are drawn to a circle from the same external point. How do their lengths compare?',
        options: [
          { id: 'a', text: 'They are always equal' },
          { id: 'b', text: 'One is always twice the other' },
          { id: 'c', text: 'They cannot be compared' },
          { id: 'd', text: 'They are equal only for a diameter' },
        ],
        correctOptionId: 'a',
        hints: ['This is the whole content of the theorem.'],
        explanation: 'Tangents from the same external point are always equal in length.',
      },
    },
    {
      id: 'circ2-b1',
      part: 'formula-application',
      conceptSlug: 'the-tangent-radius-perpendicularity-theorem',
      conceptTitle: 'The Tangent-Radius Perpendicularity Theorem',
      question: {
        id: 'circ2-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A circle has radius 9. A tangent from external point P touches at T, with OP = 15. Find PT.',
        hints: ['9² + PT² = 15².'],
        correctAnswer: 12,
        explanation: '81 + PT² = 225 → PT² = 144 → PT = 12.',
      },
    },
    {
      id: 'circ2-b2',
      part: 'formula-application',
      conceptSlug: 'the-tangent-chord-angle-theorem',
      conceptTitle: 'The Tangent-Chord Angle Theorem',
      question: {
        id: 'circ2-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A tangent-chord angle measures 73°. Find the inscribed angle in the alternate segment.',
        hints: ['They are always equal.'],
        correctAnswer: 73,
        explanation: 'By the theorem, the two angles are equal: 73°.',
      },
    },
    {
      id: 'circ2-c1',
      part: 'problem-solving',
      conceptSlug: 'the-two-tangent-theorem',
      conceptTitle: 'The Two-Tangent Theorem',
      question: {
        id: 'circ2-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Tangents from external point R touch a circle at S and T. RS = 4y − 3 and RT = 2y + 7. Find y.',
        hints: ['4y−3 = 2y+7.'],
        correctAnswer: 5,
        explanation: '4y−3=2y+7 → 2y=10 → y=5.',
      },
    },
    {
      id: 'circ2-c2',
      part: 'problem-solving',
      conceptSlug: 'proving-four-points-are-concyclic',
      conceptTitle: 'Proving Four Points Are Concyclic',
      question: {
        id: 'circ2-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'In quadrilateral ABCD, ∠A = 88° and ∠C = 92°. Are A, B, C, D concyclic?',
        options: [
          { id: 'a', text: 'Yes, since 88° + 92° = 180°' },
          { id: 'b', text: 'No, since the angles are different' },
          { id: 'c', text: 'Cannot be determined' },
          { id: 'd', text: 'Only if it is a square' },
        ],
        correctOptionId: 'a',
        hints: ['Check whether the opposite angles sum to 180°.'],
        explanation: '88°+92°=180° exactly, so the four points are concyclic.',
      },
    },
    {
      id: 'circ2-d1',
      part: 'real-life-application',
      conceptSlug: 'the-tangent-radius-perpendicularity-theorem',
      conceptTitle: 'The Tangent-Radius Perpendicularity Theorem',
      question: {
        id: 'circ2-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A cyclist rides in a straight line that just touches a circular roundabout at one point. What angle does this path make with the roundabout\'s radius at that point?',
        options: [
          { id: 'a', text: '90°, since the path acts as a tangent to the circle' },
          { id: 'b', text: '0°, since the path is straight' },
          { id: 'c', text: '180°' },
          { id: 'd', text: 'It depends on the cyclist\'s speed' },
        ],
        correctOptionId: 'a',
        hints: ['A straight path touching a circle at one point is a tangent.'],
        explanation: 'The path is a tangent to the circular roundabout, so it meets the radius there at exactly 90°.',
      },
    },
    {
      id: 'circ2-d2',
      part: 'real-life-application',
      conceptSlug: 'meaning-and-conditions-for-concyclic-points',
      conceptTitle: 'Meaning and Conditions for Concyclic Points',
      question: {
        id: 'circ2-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A surveyor measures the angle two different observation points make to a fixed baseline and finds both angles are exactly 40°, with both observers on the same side. What can be concluded?',
        options: [
          { id: 'a', text: 'All four points (baseline ends + two observers) are concyclic' },
          { id: 'b', text: 'The observers must be at the same location' },
          { id: 'c', text: 'Nothing can be concluded from angle measurements alone' },
          { id: 'd', text: 'The baseline must be a diameter' },
        ],
        correctOptionId: 'a',
        hints: ['Equal angles subtending the same segment, from the same side.'],
        explanation: 'Equal angles subtending the same segment from the same side is exactly the concyclic points condition.',
      },
    },
    {
      id: 'circ2-e1',
      part: 'challenge',
      conceptSlug: 'the-tangent-chord-angle-theorem',
      conceptTitle: 'The Tangent-Chord Angle Theorem',
      question: {
        id: 'circ2-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why does the tangent-chord angle equal the inscribed angle in the alternate segment (not the same segment)?',
        options: [
          { id: 'a', text: 'The proof (via the diameter through the point of tangency and angle-in-a-semicircle) specifically produces the alternate segment\'s angle, not the near one.' },
          { id: 'b', text: 'It is simply defined that way, with no underlying reason.' },
          { id: 'c', text: 'Both segments always have the same angle regardless.' },
          { id: 'd', text: 'It only works for tangents at the top of the circle.' },
        ],
        correctOptionId: 'a',
        hints: ['Recall the proof idea using the diameter from the point of tangency.'],
        explanation: 'The specific construction (diameter + angle in a semicircle) is what forces the equality to land with the alternate segment\'s inscribed angle.',
      },
    },
    {
      id: 'circ2-e2',
      part: 'challenge',
      conceptSlug: 'the-tangent-radius-perpendicularity-theorem',
      conceptTitle: 'The Tangent-Radius Perpendicularity Theorem',
      question: {
        id: 'circ2-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A circle has an unknown radius r. A tangent from external point P (OP=17) touches the circle at T, with PT=15. Find r.',
        hints: ['r² + 15² = 17².'],
        correctAnswer: 8,
        explanation: 'r² = 289 − 225 = 64, so r = 8.',
      },
    },
  ],
};
