import type { Assessment } from '@/types/content';

export const chapter6VibrationAssessment: Assessment = {
  id: 'vibration-of-strings-and-resonance-assessment',
  questions: [
    {
      id: 'vs-a1',
      part: 'concept',
      conceptSlug: 'stationary-waves',
      conceptTitle: 'Stationary Waves',
      question: {
        id: 'vs-a1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'How does a stationary wave form?',
        options: [
          { id: 'a', text: 'Two identical waves travelling in opposite directions overlap and interfere.' },
          { id: 'b', text: 'A single wave travels through a medium with no reflection.' },
          { id: 'c', text: 'Stationary waves require no wave interference at all.' },
          { id: 'd', text: 'Only light waves can form stationary waves.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about a wave and its own reflection.'],
        explanation: 'A stationary wave forms from the interference of two identical waves travelling in opposite directions, typically a wave and its reflection.',
      },
    },
    {
      id: 'vs-a2',
      part: 'concept',
      conceptSlug: 'organ-pipes',
      conceptTitle: 'Organ Pipes',
      question: {
        id: 'vs-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does a closed pipe of a given length produce a lower fundamental frequency than an open pipe of the same length?',
        options: [
          { id: 'a', text: 'A closed pipe fits its fundamental pattern at L = λ/4, requiring a longer wavelength (lower frequency) than the open pipe\'s L = λ/2.' },
          { id: 'b', text: 'Closed pipes are always physically longer.' },
          { id: 'c', text: 'Pipe boundary conditions have no effect on frequency.' },
          { id: 'd', text: 'Closed and open pipes always produce identical frequencies.' },
        ],
        correctOptionId: 'a',
        hints: ['Compare the fraction of a wavelength each type needs to fit.'],
        explanation: 'Since a closed pipe needs only L = λ/4 (versus L = λ/2 for an open pipe) at the same length, it resonates at a longer wavelength and therefore a lower frequency.',
      },
    },
    {
      id: 'vs-a3',
      part: 'concept',
      conceptSlug: 'intensity-of-waves',
      conceptTitle: 'Intensity of Waves',
      question: {
        id: 'vs-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does sound intensity decrease as you move farther from a speaker?',
        options: [
          { id: 'a', text: 'The same total power is spread over an increasingly large area as distance increases.' },
          { id: 'b', text: 'The speaker\'s power output changes with the position of the listener.' },
          { id: 'c', text: 'Intensity has no relationship to distance.' },
          { id: 'd', text: 'Sound waves gain power as they travel.' },
        ],
        correctOptionId: 'a',
        hints: ['I = P/A — what happens to A as distance increases?'],
        explanation: 'As the wave spreads out, its constant power is distributed over a larger area, reducing intensity.',
      },
    },
    {
      id: 'vs-b1',
      part: 'formula-application',
      conceptSlug: 'stationary-waves',
      conceptTitle: 'Stationary Waves',
      question: {
        id: 'vs-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Adjacent nodes in a stationary wave are 0.25 m apart. Find the wavelength.',
        hints: ['λ = 2 × node spacing.'],
        correctAnswer: 0.5,
        tolerance: 0.01,
        unit: 'm',
        explanation: 'λ = 2 × 0.25 = 0.5 m.',
      },
    },
    {
      id: 'vs-b2',
      part: 'formula-application',
      conceptSlug: 'resonance-column',
      conceptTitle: 'Resonance Column',
      question: {
        id: 'vs-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A tuning fork of 480 Hz resonates first in a closed tube at a length of 0.175 m. Find the speed of sound.',
        hints: ['λ = 4L, then v = fλ.'],
        correctAnswer: 336,
        tolerance: 5,
        unit: 'm/s',
        explanation: 'λ = 4 × 0.175 = 0.7 m. v = 480 × 0.7 = 336 m/s.',
      },
    },
    {
      id: 'vs-c1',
      part: 'problem-solving',
      conceptSlug: 'vibrating-strings',
      conceptTitle: 'Vibrating Strings',
      question: {
        id: 'vs-c1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A guitarist replaces a string with a thicker one (larger μ), keeping length and tension the same. What happens to the pitch?',
        options: [
          { id: 'a', text: 'It falls, since frequency is inversely related to √μ.' },
          { id: 'b', text: 'It rises.' },
          { id: 'c', text: 'μ has no effect on frequency.' },
          { id: 'd', text: 'The string stops vibrating entirely.' },
        ],
        correctOptionId: 'a',
        hints: ['f = (1/2L)√(T/μ) — what happens to f as μ increases?'],
        explanation: 'Since frequency depends on 1/√μ, increasing mass per unit length lowers the fundamental frequency, dropping the pitch.',
      },
    },
    {
      id: 'vs-c2',
      part: 'problem-solving',
      conceptSlug: 'organ-pipes',
      conceptTitle: 'Organ Pipes',
      question: {
        id: 'vs-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An open organ pipe needs a fundamental frequency of 170 Hz (v = 340 m/s). Find the required pipe length.',
        hints: ['L = v/2f.'],
        correctAnswer: 1,
        tolerance: 0.02,
        unit: 'm',
        explanation: 'L = 340/(2 × 170) = 340/340 = 1 m.',
      },
    },
    {
      id: 'vs-d1',
      part: 'real-life-application',
      conceptSlug: 'vibrating-strings',
      conceptTitle: 'Vibrating Strings',
      question: {
        id: 'vs-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does pressing a fret on a guitar (shortening the vibrating string length) raise the pitch?',
        options: [
          { id: 'a', text: 'Frequency is inversely proportional to length, so a shorter vibrating length gives a higher frequency.' },
          { id: 'b', text: 'Fretting changes the string\'s tension only.' },
          { id: 'c', text: 'Length has no relationship to pitch.' },
          { id: 'd', text: 'Shorter strings always produce lower pitch.' },
        ],
        correctOptionId: 'a',
        hints: ['f = (1/2L)√(T/μ) — L appears in the denominator.'],
        explanation: 'Since f is inversely proportional to L, shortening the vibrating length raises the frequency (pitch).',
      },
    },
    {
      id: 'vs-d2',
      part: 'real-life-application',
      conceptSlug: 'resonance-column',
      conceptTitle: 'Resonance Column',
      question: {
        id: 'vs-d2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why does the pitch change as you pour liquid into (or out of) a bottle while blowing across its top?',
        options: [
          { id: 'a', text: 'Changing the liquid level changes the length of the resonating air column, changing its resonant frequency.' },
          { id: 'b', text: 'The liquid itself produces the sound, not the air.' },
          { id: 'c', text: 'Pitch is unrelated to the air column length.' },
          { id: 'd', text: 'Only the bottle material affects pitch.' },
        ],
        correctOptionId: 'a',
        hints: ['This is the same physics as a resonance column.'],
        explanation: 'The liquid level determines the closed air column length, and resonant frequency depends directly on that length (L = λ/4 for the fundamental).',
      },
    },
    {
      id: 'vs-e1',
      part: 'challenge',
      conceptSlug: 'organ-pipes',
      conceptTitle: 'Organ Pipes',
      question: {
        id: 'vs-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'An open pipe and a closed pipe have the same length. What is the ratio of the open pipe\'s fundamental frequency to the closed pipe\'s fundamental frequency?',
        options: [
          { id: 'a', text: '2:1 — the open pipe\'s fundamental is exactly double the closed pipe\'s, since L=λ/2 versus L=λ/4 at the same L.' },
          { id: 'b', text: '1:1 — they are always identical.' },
          { id: 'c', text: '4:1.' },
          { id: 'd', text: '1:2 — the closed pipe has the higher frequency.' },
        ],
        correctOptionId: 'a',
        hints: ['Compare the wavelengths implied by L=λ/2 and L=λ/4 at the same L, then use f=v/λ.'],
        explanation: "At the same length L, the closed pipe's wavelength (4L) is twice the open pipe's wavelength (2L), so the closed pipe's frequency is half the open pipe's — a 2:1 ratio in the open pipe's favour.",
      },
    },
  ],
};
