import type { Assessment } from '@/types/content';

export const chapter6Assessment: Assessment = {
  id: 'absolute-value-functions-assessment',
  questions: [
    {
      id: 'abs-a1',
      part: 'concept',
      conceptSlug: 'graphing-y-equals-abs-x-minus-h-plus-k',
      conceptTitle: 'Graphing y = |x − h| + k',
      question: {
        id: 'abs-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What shape does y = |x − h| + k always make?',
        options: [
          { id: 'a', text: 'A V-shape opening upward, with vertex (h, k)' },
          { id: 'b', text: 'A U-shaped parabola' },
          { id: 'c', text: 'A straight line' },
          { id: 'd', text: 'A circle' },
        ],
        correctOptionId: 'a',
        hints: ['Absolute value graphs are always V-shaped, not curved.'],
        explanation: 'y = |x − h| + k is always a V-shape opening upward, with its sharp vertex at (h, k).',
      },
    },
    {
      id: 'abs-a2',
      part: 'concept',
      conceptSlug: 'effect-of-a-on-the-absolute-value-graph',
      conceptTitle: 'The Effect of a on the Graph of y = a|x|',
      question: {
        id: 'abs-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a negative a do to the graph of y = a|x|?',
        options: [
          { id: 'a', text: 'Flips it to open downward' },
          { id: 'b', text: 'Moves the vertex left' },
          { id: 'c', text: 'Makes it a straight line' },
          { id: 'd', text: 'Has no effect' },
        ],
        correctOptionId: 'a',
        hints: ['Compare y=|x| to y=-|x|.'],
        explanation: 'A negative a flips the V to open downward, with a maximum vertex instead of a minimum.',
      },
    },
    {
      id: 'abs-b1',
      part: 'formula-application',
      conceptSlug: 'graphing-y-equals-a-abs-x-minus-h-plus-k',
      conceptTitle: 'Graphing the General y = a|x − h| + k',
      question: {
        id: 'abs-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What is the vertex of y = 3|x − 2| + 5?',
        options: [
          { id: 'a', text: '(2, 5)' },
          { id: 'b', text: '(−2, 5)' },
          { id: 'c', text: '(2, −5)' },
          { id: 'd', text: '(3, 2)' },
        ],
        correctOptionId: 'a',
        hints: ['Vertex = (h, k).'],
        explanation: 'Matching to y = a|x−h|+k gives h=2, k=5, so the vertex is (2, 5).',
      },
    },
    {
      id: 'abs-b2',
      part: 'formula-application',
      conceptSlug: 'solving-absolute-value-equations',
      conceptTitle: 'Solving |x − p| = q',
      question: {
        id: 'abs-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Solve |x − 10| = 3 for the smaller solution.',
        hints: ['x = 10 + 3 or x = 10 − 3.'],
        correctAnswer: 7,
        explanation: 'x = 13 or x = 7. The smaller solution is 7.',
      },
    },
    {
      id: 'abs-c1',
      part: 'problem-solving',
      conceptSlug: 'solving-absolute-value-inequalities',
      conceptTitle: 'Solving Inequalities Involving |x − p|',
      question: {
        id: 'abs-c1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Solve |x − 6| ≤ 2.',
        options: [
          { id: 'a', text: '4 ≤ x ≤ 8' },
          { id: 'b', text: 'x ≤ 4 or x ≥ 8' },
          { id: 'c', text: 'x ≤ 4' },
          { id: 'd', text: 'x ≥ 8' },
        ],
        correctOptionId: 'a',
        hints: ['This is a "less than or equal" inequality — expect one interval.'],
        explanation: '6−2 ≤ x ≤ 6+2, giving 4 ≤ x ≤ 8.',
      },
    },
    {
      id: 'abs-c2',
      part: 'problem-solving',
      conceptSlug: 'graphing-y-equals-negative-abs-x-minus-h-plus-k',
      conceptTitle: 'Graphing y = −|x − h| + k',
      question: {
        id: 'abs-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'What is the maximum value (the y-coordinate of the vertex) of y = −|x − 7| + 9?',
        hints: ['The vertex is (h, k) = (7, 9).'],
        correctAnswer: 9,
        explanation: 'The vertex is (7, 9), and since a = −1 < 0, this is the maximum value, 9.',
      },
    },
    {
      id: 'abs-d1',
      part: 'real-life-application',
      conceptSlug: 'solving-absolute-value-equations',
      conceptTitle: 'Solving |x − p| = q',
      question: {
        id: 'abs-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A bolt must be within 0.2 mm of a target 15 mm diameter. The acceptable boundary is |diameter − 15| = 0.2. What are the boundary diameters?',
        options: [
          { id: 'a', text: '15.2 mm and 14.8 mm' },
          { id: 'b', text: '15.2 mm only' },
          { id: 'c', text: '0.2 mm and 15 mm' },
          { id: 'd', text: '14.8 mm only' },
        ],
        correctOptionId: 'a',
        hints: ['diameter = 15 + 0.2 or diameter = 15 − 0.2.'],
        explanation: 'diameter = 15.2 mm or 14.8 mm — the two boundary values, 0.2 mm on either side of the target.',
      },
    },
    {
      id: 'abs-d2',
      part: 'real-life-application',
      conceptSlug: 'solving-absolute-value-inequalities',
      conceptTitle: 'Solving Inequalities Involving |x − p|',
      question: {
        id: 'abs-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A greenhouse alarm triggers when |temperature − 22| > 4 (°C). Which readings trigger the alarm?',
        options: [
          { id: 'a', text: 'Below 18°C or above 26°C' },
          { id: 'b', text: 'Between 18°C and 26°C' },
          { id: 'c', text: 'Exactly 22°C' },
          { id: 'd', text: 'Below 4°C' },
        ],
        correctOptionId: 'a',
        hints: ['This is a "greater than" inequality — expect two separate ranges.'],
        explanation: 'temperature < 22−4 or temperature > 22+4, i.e. below 18°C or above 26°C.',
      },
    },
    {
      id: 'abs-e1',
      part: 'challenge',
      conceptSlug: 'graphing-y-equals-a-abs-x-minus-h-plus-k',
      conceptTitle: 'Graphing the General y = a|x − h| + k',
      question: {
        id: 'abs-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A V-shaped graph has vertex (3, −2) and passes through (5, 4). What is a? (Use y = a|x−3| − 2.)',
        options: [
          { id: 'a', text: 'a = 3' },
          { id: 'b', text: 'a = 2' },
          { id: 'c', text: 'a = 6' },
          { id: 'd', text: 'a = −3' },
        ],
        correctOptionId: 'a',
        hints: ['4 = a|5−3| − 2 → 6 = 2a.'],
        explanation: '4 = a(2) − 2, so 2a = 6, giving a = 3.',
      },
    },
    {
      id: 'abs-e2',
      part: 'challenge',
      conceptSlug: 'solving-absolute-value-equations',
      conceptTitle: 'Solving |x − p| = q',
      question: {
        id: 'abs-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Solve 2|x − 4| − 6 = 0 for the larger solution. (Hint: first isolate the absolute value.)',
        hints: ['2|x−4| = 6, so |x−4| = 3.', 'x = 4+3 or x = 4−3.'],
        correctAnswer: 7,
        explanation: '|x−4| = 3, so x = 7 or x = 1. The larger solution is 7.',
      },
    },
  ],
};
