import type { Assessment } from '@/types/content';

export const chapter2CForcesAssessment: Assessment = {
  id: 'forces-in-circular-motion-assessment',
  questions: [
    // Part A — Concept
    {
      id: 'fcm-a1',
      part: 'concept',
      conceptSlug: 'centripetal-force',
      conceptTitle: 'Centripetal Force',
      question: {
        id: 'fcm-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which direction does a centripetal force always point?',
        options: [
          { id: 'a', text: 'Toward the centre of the circular path' },
          { id: 'b', text: 'Tangent to the circle, in the direction of motion' },
          { id: 'c', text: 'Directly outward, away from the centre' },
          { id: 'd', text: 'It has no fixed direction — it depends on the object\'s speed' },
        ],
        correctOptionId: 'a',
        hints: ["It's in the name — 'centre-seeking.'"],
        explanation: 'A centripetal force always points toward the centre of the circle, which is what continuously bends the object\'s path into a curve.',
      },
    },
    {
      id: 'fcm-a2',
      part: 'concept',
      conceptSlug: 'centrifugal-force-a-fictitious-force',
      conceptTitle: 'Centrifugal Force — A Fictitious Force',
      question: {
        id: 'fcm-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'From the point of view of someone standing outside a spinning fairground ride, why does a rider feel pushed outward?',
        options: [
          { id: 'a', text: 'A real force is pushing the rider away from the centre.' },
          { id: 'b', text: "The rider's own inertia carries them in a straight line while the ride curves around them; the seat then pushes inward on the rider." },
          { id: 'c', text: 'Centripetal force reverses direction once the ride reaches top speed.' },
          { id: 'd', text: 'Gravity pulls the rider sideways at high rotation speeds.' },
        ],
        correctOptionId: 'b',
        hints: ['Think about what a real, inward force actually does to the rider — and what happens without one.'],
        explanation: "Only an inward (centripetal) force is real; the outward sensation is the rider's inertia resisting the curve, not an actual outward push.",
      },
    },
    {
      id: 'fcm-a3',
      part: 'concept',
      conceptSlug: 'vertical-circular-motion',
      conceptTitle: 'Vertical Circular Motion',
      question: {
        id: 'fcm-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is the string tension different at the top versus the bottom of a vertical circle, even at the same speed?',
        options: [
          { id: 'a', text: 'Gravity acts downward at every point, so it helps supply Fc at the top but opposes it at the bottom.' },
          { id: 'b', text: 'The string gets physically longer at the top of the circle.' },
          { id: 'c', text: "Centripetal force only exists at the bottom of a vertical circle." },
          { id: 'd', text: "Air resistance is greater at the top of the loop." },
        ],
        correctOptionId: 'a',
        hints: ["Gravity's direction never changes — but its relationship to 'toward the centre' does, depending on where you are on the circle."],
        explanation: 'Gravity always points straight down. At the top of the loop that is toward the centre (helping supply Fc); at the bottom it is away from the centre (opposing Fc), so tension must make up the difference each time.',
      },
    },

    // Part B — Formula & Application
    {
      id: 'fcm-b1',
      part: 'formula-application',
      conceptSlug: 'centripetal-force',
      conceptTitle: 'Centripetal Force',
      question: {
        id: 'fcm-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 1 kg object moves in a circle of radius 2 m at 6 m/s. Find the centripetal force acting on it.',
        hints: ['Fc = mv²/r.', '(1 × 6²) / 2.'],
        correctAnswer: 18,
        unit: 'N',
        explanation: 'Fc = (1 × 36) / 2 = 36/2 = 18 N.',
      },
    },
    {
      id: 'fcm-b2',
      part: 'formula-application',
      conceptSlug: 'tension-as-centripetal-force',
      conceptTitle: 'Tension as Centripetal Force',
      question: {
        id: 'fcm-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A 0.4 kg ball on a 0.6 m string swings in a horizontal circle at 3 rad/s. Find the tension in the string.',
        hints: ['T = mrω².', '0.4 × 0.6 × 3².'],
        correctAnswer: 2.16,
        tolerance: 0.05,
        unit: 'N',
        explanation: 'T = 0.4 × 0.6 × 9 = 2.16 N.',
      },
    },
    {
      id: 'fcm-b3',
      part: 'formula-application',
      conceptSlug: 'friction-as-centripetal-force',
      conceptTitle: 'Friction as Centripetal Force',
      question: {
        id: 'fcm-b3-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A car turns on a flat road of radius 80 m with μ = 0.3 (g = 9.8 m/s²). Find the maximum safe speed, v_max = √(μgr), in m/s.',
        hints: ['v_max = √(μgr).', '√(0.3 × 9.8 × 80).'],
        correctAnswer: 15.3,
        tolerance: 0.2,
        unit: 'm/s',
        explanation: 'v_max = √(0.3 × 9.8 × 80) = √235.2 ≈ 15.3 m/s.',
      },
    },

    // Part C — Problem Solving
    {
      id: 'fcm-c1',
      part: 'problem-solving',
      conceptSlug: 'vertical-circular-motion',
      conceptTitle: 'Vertical Circular Motion',
      question: {
        id: 'fcm-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A 1 kg ball on a 0.5 m string moves at 3 m/s at the bottom of a vertical circle. Find the tension there (g = 9.8 m/s²).',
        hints: ['T = mv²/r + mg.', '(1 × 3²)/0.5 + (1 × 9.8).'],
        correctAnswer: 27.8,
        tolerance: 0.2,
        unit: 'N',
        explanation: 'T = (1 × 9)/0.5 + 9.8 = 18 + 9.8 = 27.8 N.',
      },
    },
    {
      id: 'fcm-c2',
      part: 'problem-solving',
      conceptSlug: 'circular-motion-on-a-banked-curve',
      conceptTitle: 'Circular Motion on a Banked Curve',
      question: {
        id: 'fcm-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the ideal (frictionless) banking angle, in degrees, for a curve of radius 120 m designed for 22 m/s (g = 9.8 m/s²). Round to one decimal place.',
        hints: ['tan θ = v² / (rg).', '22² / (120 × 9.8) = 484/1176 ≈ 0.412.'],
        correctAnswer: 22.4,
        tolerance: 0.3,
        unit: '°',
        explanation: 'tan θ = 484/1176 ≈ 0.412, so θ = arctan(0.412) ≈ 22.4°.',
      },
    },

    // Part D — Real-Life Application
    {
      id: 'fcm-d1',
      part: 'real-life-application',
      conceptSlug: 'gravity-as-centripetal-force',
      conceptTitle: 'Gravity as Centripetal Force',
      question: {
        id: 'fcm-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why do astronauts aboard the International Space Station appear weightless?',
        options: [
          { id: 'a', text: "They have travelled far enough that Earth's gravity no longer reaches them." },
          { id: 'b', text: 'The station and everyone in it are in continuous free fall around Earth, with gravity acting as the centripetal force.' },
          { id: 'c', text: 'Artificial gravity generators are switched off during flight.' },
          { id: 'd', text: 'The Sun\'s gravity cancels out Earth\'s gravity at that altitude.' },
        ],
        correctOptionId: 'b',
        hints: ["Earth's gravity at that altitude is still almost as strong as at the surface.", 'What force is keeping the station in its orbit?'],
        explanation: "Earth's gravity still acts strongly at ISS altitude — it is exactly what supplies the centripetal force keeping the station in orbit. The station and its crew are in continuous free fall, which is what produces the sensation of weightlessness.",
      },
    },

    // Part E — Challenge
    {
      id: 'fcm-e1',
      part: 'challenge',
      conceptSlug: 'vertical-circular-motion',
      conceptTitle: 'Vertical Circular Motion',
      question: {
        id: 'fcm-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A 1200 kg car crests the top of a hill shaped like part of a circle of radius 40 m, travelling at 15 m/s (g = 9.8 m/s²). Find the normal force from the road on the car at that instant, using N = mg − mv²/r.',
        hints: ['At the top of a convex hill, weight acts toward the centre (downward) and the normal force acts away from it (upward): mg − N = mv²/r.', 'mg = 1200 × 9.8 = 11760 N. mv²/r = 1200 × 15² / 40.'],
        correctAnswer: 5010,
        tolerance: 20,
        unit: 'N',
        explanation: 'mv²/r = 1200 × 225 / 40 = 6750 N. N = mg − mv²/r = 11760 − 6750 = 5010 N — positive, so the car stays on the road (it would leave the road only if the required centripetal force exceeded its weight).',
      },
    },
  ],
};
