import type { Assessment } from '@/types/content';

export const chapter10CurrentAssessment: Assessment = {
  id: 'electric-current-and-magnetic-effect-assessment',
  questions: [
    {
      id: 'ec-a1',
      part: 'concept',
      conceptSlug: 'current-and-effects-of-current',
      conceptTitle: 'Current and Effects of Current',
      question: {
        id: 'ec-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which of these is NOT one of the three main effects of electric current?',
        options: [
          { id: 'a', text: 'Gravitational effect' },
          { id: 'b', text: 'Heating effect' },
          { id: 'c', text: 'Magnetic effect' },
          { id: 'd', text: 'Chemical effect' },
        ],
        correctOptionId: 'a',
        hints: ['Current has three well-known effects.'],
        explanation: 'The three main effects of current are heating, magnetic, and chemical — not gravitational.',
      },
    },
    {
      id: 'ec-a2',
      part: 'concept',
      conceptSlug: 'resistors-in-parallel-b-level',
      conceptTitle: 'Resistors in Parallel',
      question: {
        id: 'ec-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does adding more resistors in parallel DECREASE the total resistance?',
        options: [
          { id: 'a', text: 'Each additional resistor provides another independent path for current, making overall flow easier.' },
          { id: 'b', text: 'Parallel resistors always increase total resistance.' },
          { id: 'c', text: 'Adding resistors in parallel has no effect on total resistance.' },
          { id: 'd', text: 'Parallel resistors cancel each other out completely.' },
        ],
        correctOptionId: 'a',
        hints: ['More paths make it easier, not harder, for current to flow overall.'],
        explanation: 'More parallel paths make it easier overall for current to flow, decreasing total resistance below the smallest individual resistor.',
      },
    },
    {
      id: 'ec-a3',
      part: 'concept',
      conceptSlug: 'ammeter-and-voltmeter',
      conceptTitle: 'Ammeter and Voltmeter',
      question: {
        id: 'ec-a3-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why must an ammeter have very LOW resistance?',
        options: [
          { id: 'a', text: 'So inserting it in series barely affects the current it is measuring.' },
          { id: 'b', text: 'So it can be connected in parallel safely.' },
          { id: 'c', text: 'High resistance would make it measure voltage instead.' },
          { id: 'd', text: 'Resistance has no relevance to ammeter design.' },
        ],
        correctOptionId: 'a',
        hints: ['The ammeter needs to let current pass through it largely undisturbed.'],
        explanation: 'A low-resistance ammeter barely disturbs the circuit current when inserted in series, giving an accurate reading.',
      },
    },
    {
      id: 'ec-b1',
      part: 'formula-application',
      conceptSlug: 'ohms-law-and-resistance',
      conceptTitle: "Ohm's Law and Electrical Resistance",
      question: {
        id: 'ec-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A resistor of 8 Ω has a current of 1.5 A flowing through it. Find the potential difference across it.',
        hints: ['V = IR.'],
        correctAnswer: 12,
        tolerance: 0.3,
        unit: 'V',
        explanation: 'V = 1.5 × 8 = 12 V.',
      },
    },
    {
      id: 'ec-b2',
      part: 'formula-application',
      conceptSlug: 'resistors-in-series-b-level',
      conceptTitle: 'Resistors in Series',
      question: {
        id: 'ec-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Four resistors of 2 Ω, 3 Ω, 5 Ω, and 10 Ω are connected in series. Find the total resistance.',
        hints: ['Rₛ = R₁+R₂+R₃+R₄.'],
        correctAnswer: 20,
        tolerance: 0.5,
        unit: 'Ω',
        explanation: 'Rₛ = 2+3+5+10 = 20 Ω.',
      },
    },
    {
      id: 'ec-c1',
      part: 'problem-solving',
      conceptSlug: 'resistors-in-parallel-b-level',
      conceptTitle: 'Resistors in Parallel',
      question: {
        id: 'ec-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Three resistors of 6 Ω each are connected in parallel. Find the total resistance.',
        hints: ['1/Rₚ = 1/6 + 1/6 + 1/6.'],
        correctAnswer: 2,
        tolerance: 0.1,
        unit: 'Ω',
        explanation: '1/Rₚ = 3/6 = 1/2 → Rₚ = 2 Ω.',
      },
    },
    {
      id: 'ec-c2',
      part: 'problem-solving',
      conceptSlug: 'resistors-b-level',
      conceptTitle: 'Resistors',
      question: {
        id: 'ec-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A wire with resistivity 1.6 × 10⁻⁸ Ω·m has resistance 0.04 Ω and length 5 m. Find its cross-sectional area.',
        hints: ['R = ρL/A, rearranged: A = ρL/R.'],
        correctAnswer: 2e-6,
        tolerance: 0.2e-6,
        unit: 'm²',
        explanation: 'A = (1.6×10⁻⁸ × 5)/0.04 = (8×10⁻⁸)/0.04 = 2×10⁻⁶ m².',
      },
    },
    {
      id: 'ec-d1',
      part: 'real-life-application',
      conceptSlug: 'electromagnets',
      conceptTitle: 'Electromagnets',
      question: {
        id: 'ec-d1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Why do scrapyards use electromagnets rather than permanent magnets to lift and sort metal?',
        options: [
          { id: 'a', text: 'The electromagnet can be switched on to grip metal and off to release it precisely.' },
          { id: 'b', text: 'Electromagnets are always physically smaller than permanent magnets.' },
          { id: 'c', text: 'Permanent magnets are stronger, so they are avoided.' },
          { id: 'd', text: 'Electromagnets never require electricity.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about the practical need to release the metal after lifting it.'],
        explanation: 'Electromagnets can be turned on and off electrically, letting the crane grip and precisely release metal, which a permanent magnet cannot conveniently do.',
      },
    },
    {
      id: 'ec-d2',
      part: 'real-life-application',
      conceptSlug: 'resistors-in-series-b-level',
      conceptTitle: 'Resistors in Series',
      question: {
        id: 'ec-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does an old-style string of series-wired Christmas lights go completely dark if one bulb burns out?',
        options: [
          { id: 'a', text: 'Series components share a single current path, so one broken bulb interrupts the whole circuit.' },
          { id: 'b', text: 'Series wiring has no relationship to circuit continuity.' },
          { id: 'c', text: 'Only the burnt-out bulb goes dark; the rest stay lit.' },
          { id: 'd', text: 'Parallel wiring is what causes this behaviour.' },
        ],
        correctOptionId: 'a',
        hints: ['Series components share one single current path.'],
        explanation: 'A break anywhere in a series circuit interrupts the single shared current path, stopping current everywhere in the string.',
      },
    },
    {
      id: 'ec-e1',
      part: 'challenge',
      conceptSlug: 'resistors-in-parallel-b-level',
      conceptTitle: 'Resistors in Parallel',
      question: {
        id: 'ec-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A 10 Ω resistor is connected in parallel with a very large resistance (approaching infinity). What happens to the total resistance?',
        options: [
          { id: 'a', text: 'It approaches 10 Ω, since the very large resistor carries negligible current and barely affects the combination.' },
          { id: 'b', text: 'It approaches infinity.' },
          { id: 'c', text: 'It approaches zero.' },
          { id: 'd', text: 'It becomes undefined.' },
        ],
        correctOptionId: 'a',
        hints: ['Consider 1/Rₚ = 1/10 + 1/R as R becomes very large — what happens to 1/R?'],
        explanation: 'As R approaches infinity, 1/R approaches 0, so 1/Rₚ approaches 1/10, meaning Rₚ approaches 10 Ω — the very large resistor contributes negligibly.',
      },
    },
  ],
};
