import type { Assessment } from '@/types/content';

export const chapter2CAssessment: Assessment = {
  id: 'mathematical-induction-assessment',
  questions: [
    {
      id: 'induct-a1',
      part: 'concept',
      conceptSlug: 'the-principle-of-mathematical-induction',
      conceptTitle: 'The Principle of Mathematical Induction',
      question: {
        id: 'induct-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What are the two required steps of a mathematical induction proof?',
        options: [
          { id: 'a', text: 'Base case, then inductive step' },
          { id: 'b', text: 'Direct proof, then contradiction' },
          { id: 'c', text: 'Substitution, then factoring' },
          { id: 'd', text: 'Base case only, repeated for every n' },
        ],
        correctOptionId: 'a',
        hints: ['One step verifies a starting point; the other carries the truth forward.'],
        explanation: 'A complete induction proof always needs both the base case and the inductive step.',
      },
    },
    {
      id: 'induct-a2',
      part: 'concept',
      conceptSlug: 'proving-summation-formulas-by-induction',
      conceptTitle: 'Proving Summation Formulas by Induction',
      question: {
        id: 'induct-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'When proving a summation formula, what should be added to both sides during the inductive step?',
        options: [
          { id: 'a', text: 'The next term, the (k+1)th term' },
          { id: 'b', text: 'The number 1' },
          { id: 'c', text: 'The base case value' },
          { id: 'd', text: 'Nothing — just substitute n=k+1 directly' },
        ],
        correctOptionId: 'a',
        hints: ['What new term appears when extending the sum from k terms to k+1 terms?'],
        explanation: 'The inductive step adds the new (k+1)th term to both sides of the inductive hypothesis.',
      },
    },
    {
      id: 'induct-b1',
      part: 'formula-application',
      conceptSlug: 'proving-summation-formulas-by-induction',
      conceptTitle: 'Proving Summation Formulas by Induction',
      question: {
        id: 'induct-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Using 1+2+...+n = n(n+1)/2, find the sum of the first 20 positive integers.',
        hints: ['Substitute n=20.'],
        correctAnswer: 210,
        explanation: '20(21)/2 = 210.',
      },
    },
    {
      id: 'induct-b2',
      part: 'formula-application',
      conceptSlug: 'proving-divisibility-statements-by-induction',
      conceptTitle: 'Proving Divisibility Statements by Induction',
      question: {
        id: 'induct-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Verify the base case for "5ⁿ − 1 is divisible by 4" at n=1: what is 5¹ − 1?',
        hints: ['Substitute n=1.'],
        correctAnswer: 4,
        explanation: '5 − 1 = 4.',
      },
    },
    {
      id: 'induct-c1',
      part: 'problem-solving',
      conceptSlug: 'proving-inequalities-by-induction',
      conceptTitle: 'Proving Inequalities by Induction',
      question: {
        id: 'induct-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Verify the base case for "n! > 3ⁿ for n≥7" at n=7: what is 7!?',
        hints: ['7! = 7×6×5×4×3×2×1.'],
        correctAnswer: 5040,
        explanation: '7! = 5040 (and indeed 5040 > 3⁷ = 2187).',
      },
    },
    {
      id: 'induct-c2',
      part: 'problem-solving',
      conceptSlug: 'the-principle-of-mathematical-induction',
      conceptTitle: 'The Principle of Mathematical Induction',
      question: {
        id: 'induct-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'If P(5) is true and the inductive step "P(k) ⟹ P(k+1)" holds for all k ≥ 5, what is the smallest n > 5 for which P(n) is guaranteed true by induction?',
        hints: ['Apply the inductive step once, starting from k=5.'],
        correctAnswer: 6,
        explanation: 'The inductive step with k=5 gives P(6) directly.',
      },
    },
    {
      id: 'induct-d1',
      part: 'real-life-application',
      conceptSlug: 'proving-summation-formulas-by-induction',
      conceptTitle: 'Proving Summation Formulas by Induction',
      question: {
        id: 'induct-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A network engineer wants to prove a summation formula for the total cables needed to connect n junction boxes is correct for EVERY possible n, not just the sizes tested. Which technique proves this?',
        options: [
          { id: 'a', text: 'Mathematical induction' },
          { id: 'b', text: 'Checking a few large values of n by hand' },
          { id: 'c', text: 'Guessing based on a pattern, with no proof' },
          { id: 'd', text: 'Direct substitution only' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly what induction is designed to prove.'],
        explanation: 'Induction rigorously proves the formula holds for every n, not just the ones checked directly.',
      },
    },
    {
      id: 'induct-d2',
      part: 'real-life-application',
      conceptSlug: 'proving-divisibility-statements-by-induction',
      conceptTitle: 'Proving Divisibility Statements by Induction',
      question: {
        id: 'induct-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A cryptography engineer needs a computed value to always be divisible by a fixed number, at every step of an unbounded process. Which technique proves this holds at every step?',
        options: [
          { id: 'a', text: 'A divisibility induction proof' },
          { id: 'b', text: 'Testing the first ten steps only' },
          { id: 'c', text: 'Assuming it based on a pattern' },
          { id: 'd', text: 'Rounding the computed value' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation divisibility induction is designed for.'],
        explanation: 'A divisibility induction proof rigorously confirms the property at every single step, not just the ones checked by hand.',
      },
    },
    {
      id: 'induct-e1',
      part: 'challenge',
      conceptSlug: 'proving-inequalities-by-induction',
      conceptTitle: 'Proving Inequalities by Induction',
      question: {
        id: 'induct-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Why is the base case alone not sufficient to prove a statement for all positive integers?',
        options: [
          { id: 'a', text: 'It only confirms the very first case; without the inductive step, there is no guarantee the statement continues to hold afterward' },
          { id: 'b', text: 'The base case is never actually needed' },
          { id: 'c', text: 'It proves the statement for all integers automatically' },
          { id: 'd', text: 'It only works for inequalities, not equations' },
        ],
        correctOptionId: 'a',
        hints: ['Think about what the inductive step actually adds beyond the base case.'],
        explanation: 'The base case confirms only n=1 (or the starting value); the inductive step is what extends the truth to every subsequent integer.',
      },
    },
    {
      id: 'induct-e2',
      part: 'challenge',
      conceptSlug: 'the-principle-of-mathematical-induction',
      conceptTitle: 'The Principle of Mathematical Induction',
      question: {
        id: 'induct-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'The inequality "n² ≥ 2n+1" is false at n=1 (1≥3 is false) and n=2 (4≥5 is false), but becomes true at n=3 (9≥7 is true) and stays true afterward. What is the correct base case value to start this induction proof?',
        hints: ['Find the smallest n where the inequality actually holds.'],
        correctAnswer: 3,
        explanation: 'The base case must start at n=3, the first value where the inequality is actually true.',
      },
    },
  ],
};
