import type { Assessment } from '@/types/content';

export const chapter3CAssessment: Assessment = {
  id: 'analytic-solid-geometry-assessment',
  questions: [
    {
      id: 'solid-a1',
      part: 'concept',
      conceptSlug: 'the-three-dimensional-coordinate-system',
      conceptTitle: 'The Three-Dimensional Coordinate System',
      question: {
        id: 'solid-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'How many coordinates are needed to describe a point in three-dimensional space?',
        hints: ['One for each axis: x, y, and z.'],
        correctAnswer: 3,
        explanation: 'A point in 3D space is described by an ordered triple (x, y, z) — three coordinates.',
      },
    },
    {
      id: 'solid-a2',
      part: 'concept',
      conceptSlug: 'the-distance-and-midpoint-formulas-in-3d',
      conceptTitle: 'The Distance and Midpoint Formulas in 3D',
      question: {
        id: 'solid-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the distance between (0,0,0) and (3,4,12).',
        hints: ['d = √(x²+y²+z²) here, since one point is the origin.'],
        correctAnswer: 13,
        explanation: '√(9+16+144) = √169 = 13.',
      },
    },
    {
      id: 'solid-b1',
      part: 'formula-application',
      conceptSlug: 'direction-numbers-of-a-line',
      conceptTitle: 'Direction Numbers of a Line',
      question: {
        id: 'solid-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the direction number "a" for the line through (1,1,1) and (7,3,9).',
        hints: ['a = x₂ − x₁.'],
        correctAnswer: 6,
        explanation: '7 − 1 = 6.',
      },
    },
    {
      id: 'solid-b2',
      part: 'formula-application',
      conceptSlug: 'symmetric-and-parametric-equations-of-a-line',
      conceptTitle: 'Symmetric and Parametric Equations of a Line',
      question: {
        id: 'solid-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'For the parametric line x=1+2t, y=3−t, z=4+5t, find the x-coordinate at t=2.',
        hints: ['Substitute t=2 into the x equation.'],
        correctAnswer: 5,
        explanation: '1+2(2) = 5.',
      },
    },
    {
      id: 'solid-c1',
      part: 'problem-solving',
      conceptSlug: 'the-normal-vector-and-equation-of-a-plane',
      conceptTitle: 'The Normal Vector and Equation of a Plane',
      question: {
        id: 'solid-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find d, for the plane through (1,0,2) with normal vector (2,3,1), written as 2x+3y+z=d.',
        hints: ['d = a·x₀ + b·y₀ + c·z₀.'],
        correctAnswer: 4,
        explanation: 'd = 2(1)+3(0)+1(2) = 4.',
      },
    },
    {
      id: 'solid-c2',
      part: 'problem-solving',
      conceptSlug: 'the-standard-equation-of-a-sphere',
      conceptTitle: 'The Standard Equation of a Sphere',
      question: {
        id: 'solid-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A sphere has center (0,0,0) and radius 6. What is the right-hand side of its equation x²+y²+z²=?',
        hints: ['The right side is r².'],
        correctAnswer: 36,
        explanation: '6² = 36.',
      },
    },
    {
      id: 'solid-d1',
      part: 'real-life-application',
      conceptSlug: 'the-distance-from-a-point-to-a-plane',
      conceptTitle: 'The Distance from a Point to a Plane',
      question: {
        id: 'solid-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A drone\'s flight-planning software calculates how close the drone will pass to a flat rooftop, modeled as a plane. Which technique gives this directly?',
        options: [
          { id: 'a', text: 'The distance-from-a-point-to-a-plane formula' },
          { id: 'b', text: 'The direction numbers formula' },
          { id: 'c', text: 'Completing the square' },
          { id: 'd', text: 'The midpoint formula' },
        ],
        correctOptionId: 'a',
        hints: ['This is exactly the situation this formula is designed for.'],
        explanation: 'This formula computes the drone\'s shortest distance to the rooftop plane directly from its coordinates and the plane\'s equation.',
      },
    },
    {
      id: 'solid-d2',
      part: 'real-life-application',
      conceptSlug: 'finding-the-center-and-radius-by-completing-the-square',
      conceptTitle: 'Finding the Center and Radius by Completing the Square',
      question: {
        id: 'solid-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Engineers are given a satellite\'s signal-coverage sphere as an expanded (non-standard) equation and need its actual center and radius. What technique finds these?',
        options: [
          { id: 'a', text: 'Completing the square' },
          { id: 'b', text: 'Finding direction numbers' },
          { id: 'c', text: 'The distance-to-plane formula' },
          { id: 'd', text: 'Averaging the coefficients' },
        ],
        correctOptionId: 'a',
        hints: ['This converts an expanded sphere equation back into standard form.'],
        explanation: 'Completing the square on the x, y, and z terms recovers the standard form, revealing the center and radius directly.',
      },
    },
    {
      id: 'solid-e1',
      part: 'challenge',
      conceptSlug: 'the-distance-and-midpoint-formulas-in-3d',
      conceptTitle: 'The Distance and Midpoint Formulas in 3D',
      question: {
        id: 'solid-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the midpoint\'s y-coordinate for A(−3,7,2) and B(9,−1,10).',
        hints: ['Midpoint y-coordinate = (y₁+y₂)/2.'],
        correctAnswer: 3,
        explanation: '(7+(−1))/2 = 6/2 = 3.',
      },
    },
    {
      id: 'solid-e2',
      part: 'challenge',
      conceptSlug: 'the-normal-vector-and-equation-of-a-plane',
      conceptTitle: 'The Normal Vector and Equation of a Plane',
      question: {
        id: 'solid-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A plane has equation 6x+8y+0z=50. Find the distance from the origin to this plane.',
        hints: ['distance = |ax₀+by₀+cz₀−d| / √(a²+b²+c²), with (x₀,y₀,z₀)=(0,0,0).'],
        correctAnswer: 5,
        explanation: '|0−50| / √(36+64+0) = 50/10 = 5.',
      },
    },
  ],
};
