import type { Assessment } from '@/types/content';

export const chapter12CDigitalAssessment: Assessment = {
  id: 'digital-electronics-and-communication-system-assessment',
  questions: [
    {
      id: 'digital-a1',
      part: 'concept',
      conceptSlug: 'electronic-systems',
      conceptTitle: 'Electronic Systems',
      question: {
        id: 'digital-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'In a thermostat that turns on a heater when the room gets cold, what is the PROCESS stage?',
        hints: ['Think about which stage makes the decision, not senses or acts.'],
        options: [
          { id: 'a', text: 'The circuit comparing the sensed temperature to the target setting' },
          { id: 'b', text: 'The temperature sensor itself' },
          { id: 'c', text: 'The heater switching on' },
          { id: 'd', text: "The room's air" },
        ],
        correctOptionId: 'a',
        explanation: 'The comparator circuit makes the decision (process stage), between the sensor (input) and the heater (output).',
      },
    },
    {
      id: 'digital-a2',
      part: 'concept',
      conceptSlug: 'analog-and-digital-signals',
      conceptTitle: 'Analog and Digital Signals',
      question: {
        id: 'digital-a2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Convert the binary number 1110 to decimal.',
        hints: ['1x8 + 1x4 + 1x2 + 0x1.'],
        correctAnswer: 14,
        explanation: '8+4+2+0 = 14.',
      },
    },
    {
      id: 'digital-b1',
      part: 'formula-application',
      conceptSlug: 'logic-gates-and-truth-tables',
      conceptTitle: 'Logic Gates and Truth Tables',
      question: {
        id: 'digital-b1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'For an AND gate with inputs A=1 and B=1, find the output Y.',
        hints: ['AND outputs 1 only if both inputs are 1.'],
        correctAnswer: 1,
        explanation: 'Both inputs are 1, so Y=1.',
      },
    },
    {
      id: 'digital-b2',
      part: 'formula-application',
      conceptSlug: 'analog-and-digital-signals',
      conceptTitle: 'Analog and Digital Signals',
      question: {
        id: 'digital-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Convert the binary number 10011 to decimal.',
        hints: ['1x16 + 0x8 + 0x4 + 1x2 + 1x1.'],
        correctAnswer: 19,
        explanation: '16+0+0+2+1 = 19.',
      },
    },
    {
      id: 'digital-c1',
      part: 'problem-solving',
      conceptSlug: 'logic-gates-and-truth-tables',
      conceptTitle: 'Logic Gates and Truth Tables',
      question: {
        id: 'digital-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A NOT gate has input A=0. Find the output Y.',
        hints: ['NOT flips the input.'],
        correctAnswer: 1,
        explanation: 'NOT flips 0 to 1, so Y=1.',
      },
    },
    {
      id: 'digital-c2',
      part: 'problem-solving',
      conceptSlug: 'communication-systems-basics',
      conceptTitle: 'Basic Electronic Communication',
      question: {
        id: 'digital-c2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Which best distinguishes a transmitter from a receiver?',
        hints: ['Think about the direction of information flow for each.'],
        options: [
          { id: 'a', text: 'A transmitter converts information into a signal to send; a receiver converts a received signal back into information' },
          { id: 'b', text: 'They perform exactly the same function' },
          { id: 'c', text: 'A transmitter only works with digital signals' },
          { id: 'd', text: 'A receiver creates the original message from nothing' },
        ],
        correctOptionId: 'a',
        explanation: 'The transmitter encodes information into a transmittable signal; the receiver decodes a received signal back into usable information.',
      },
    },
    {
      id: 'digital-d1',
      part: 'real-life-application',
      conceptSlug: 'electronic-systems',
      conceptTitle: 'Electronic Systems',
      question: {
        id: 'digital-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A digital thermometer displays a number when placed under the tongue. What is its OUTPUT stage?',
        hints: ['Think about the final result the user actually sees.'],
        options: [
          { id: 'a', text: 'The digital display showing the temperature' },
          { id: 'b', text: 'The temperature sensor' },
          { id: 'c', text: 'The internal processing circuit' },
          { id: 'd', text: 'The battery' },
        ],
        correctOptionId: 'a',
        explanation: 'The display is the final output the system produces for the user to read.',
      },
    },
    {
      id: 'digital-d2',
      part: 'real-life-application',
      conceptSlug: 'communication-systems-basics',
      conceptTitle: 'Basic Electronic Communication',
      question: {
        id: 'digital-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is FM radio generally less affected by electrical interference than AM radio?',
        hints: ['Think about what each modulation type encodes information in.'],
        options: [
          { id: 'a', text: 'FM encodes information in frequency changes, which amplitude-affecting noise does not disrupt as much' },
          { id: 'b', text: 'FM signals travel slower than AM signals' },
          { id: 'c', text: 'AM signals do not use radio waves at all' },
          { id: 'd', text: 'FM radio only works at night' },
        ],
        correctOptionId: 'a',
        explanation: 'Electrical interference typically affects a signal\'s amplitude — since FM encodes information in frequency rather than amplitude, it is much less disrupted by this kind of noise.',
      },
    },
    {
      id: 'digital-e1',
      part: 'challenge',
      conceptSlug: 'analog-and-digital-signals',
      conceptTitle: 'Analog and Digital Signals',
      question: {
        id: 'digital-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Which binary number equals the decimal number 25?',
        hints: ['25 = 16+8+1.'],
        options: [
          { id: 'a', text: '11001' },
          { id: 'b', text: '11010' },
          { id: 'c', text: '10101' },
          { id: 'd', text: '11101' },
        ],
        correctOptionId: 'a',
        explanation: '25 = 16+8+0+0+1, so the binary representation is 11001.',
      },
    },
    {
      id: 'digital-e2',
      part: 'challenge',
      conceptSlug: 'logic-gates-and-truth-tables',
      conceptTitle: 'Logic Gates and Truth Tables',
      question: {
        id: 'digital-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A circuit outputs 1 only when EXACTLY ONE of its two inputs is 1 (not both, not neither). Which gate is this?',
        hints: ['This is a special, commonly-used gate distinct from basic OR.'],
        options: [
          { id: 'a', text: 'XOR (exclusive OR)' },
          { id: 'b', text: 'AND' },
          { id: 'c', text: 'OR' },
          { id: 'd', text: 'NOT' },
        ],
        correctOptionId: 'a',
        explanation: 'XOR ("exclusive OR") outputs 1 only when its inputs differ — exactly one is 1 and the other is 0.',
      },
    },
  ],
};
