import type { Assessment } from '@/types/content';

export const chapter2BAssessment: Assessment = {
  id: 'binomial-theorem-assessment',
  questions: [
    {
      id: 'bin-a1',
      part: 'concept',
      conceptSlug: 'meaning-of-binomial-coefficients',
      conceptTitle: 'Meaning of Binomial Coefficients and Pascal\'s Triangle',
      question: {
        id: 'bin-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does ⁿCᵣ count?',
        options: [
          { id: 'a', text: 'The number of ways to choose r items from n, order not mattering' },
          { id: 'b', text: 'The number of ways to arrange r items from n, in order' },
          { id: 'c', text: 'n divided by r' },
          { id: 'd', text: 'The sum of the first n integers' },
        ],
        correctOptionId: 'a',
        hints: ['"n choose r" — combinations, not permutations.'],
        explanation: 'ⁿCᵣ counts combinations — choosing r items from n where order does not matter.',
      },
    },
    {
      id: 'bin-a2',
      part: 'concept',
      conceptSlug: 'the-binomial-theorem',
      conceptTitle: 'The Binomial Theorem',
      question: {
        id: 'bin-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'In every term of the expansion of (a+b)ⁿ, what do the exponents of a and b add up to?',
        options: [
          { id: 'a', text: 'n' },
          { id: 'b', text: 'r' },
          { id: 'c', text: '2n' },
          { id: 'd', text: '0' },
        ],
        correctOptionId: 'a',
        hints: ['Each term is aⁿ⁻ʳbʳ.'],
        explanation: '(n−r) + r = n, in every term.',
      },
    },
    {
      id: 'bin-b1',
      part: 'formula-application',
      conceptSlug: 'meaning-of-binomial-coefficients',
      conceptTitle: 'Meaning of Binomial Coefficients and Pascal\'s Triangle',
      question: {
        id: 'bin-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Evaluate ⁷C₂.',
        hints: ['⁷C₂ = 7×6/(2×1).'],
        correctAnswer: 21,
        explanation: '7×6/2 = 42/2 = 21.',
      },
    },
    {
      id: 'bin-b2',
      part: 'formula-application',
      conceptSlug: 'the-general-term-of-a-binomial-expansion',
      conceptTitle: 'The General Term of a Binomial Expansion',
      question: {
        id: 'bin-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the 3rd term of (x + 2)⁴. (Give just the numeric coefficient.)',
        hints: ['3rd term: r=2.', 'T3 = ⁴C₂ x² (2)².'],
        correctAnswer: 24,
        explanation: '⁴C₂=6, 2²=4, 6×4=24, so T3=24x².',
      },
    },
    {
      id: 'bin-c1',
      part: 'problem-solving',
      conceptSlug: 'expanding-small-binomial-powers',
      conceptTitle: 'Expanding Small Binomial Powers',
      question: {
        id: 'bin-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Expand (x + 1)⁴.',
        options: [
          { id: 'a', text: 'x⁴ + 4x³ + 6x² + 4x + 1' },
          { id: 'b', text: 'x⁴ + 4x³ + 4x² + 4x + 1' },
          { id: 'c', text: 'x⁴ + 6x³ + 4x² + 6x + 1' },
          { id: 'd', text: 'x⁴ + x³ + x² + x + 1' },
        ],
        correctOptionId: 'a',
        hints: ['Row 4 of Pascal\'s triangle: 1, 4, 6, 4, 1.'],
        explanation: 'Coefficients 1,4,6,4,1 paired with x⁴,x³,x²,x,1.',
      },
    },
    {
      id: 'bin-c2',
      part: 'problem-solving',
      conceptSlug: 'finding-the-coefficient-of-a-specific-term',
      conceptTitle: 'Finding the Coefficient of a Specific Term',
      question: {
        id: 'bin-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the coefficient of x² in the expansion of (x + 3)⁴.',
        hints: ['4 − r = 2 → r = 2.', 'Coefficient = ⁴C₂ × 3².'],
        correctAnswer: 54,
        explanation: '⁴C₂=6, 3²=9, 6×9=54.',
      },
    },
    {
      id: 'bin-d1',
      part: 'real-life-application',
      conceptSlug: 'meaning-of-binomial-coefficients',
      conceptTitle: 'Meaning of Binomial Coefficients and Pascal\'s Triangle',
      question: {
        id: 'bin-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A club of 8 members wants to know how many different 3-person committees are possible. Find ⁸C₃.',
        hints: ['⁸C₃ = 8×7×6/(3×2×1).'],
        correctAnswer: 56,
        explanation: '8×7×6=336, 336/6=56.',
      },
    },
    {
      id: 'bin-d2',
      part: 'real-life-application',
      conceptSlug: 'the-binomial-theorem',
      conceptTitle: 'The Binomial Theorem',
      question: {
        id: 'bin-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is the binomial theorem more practical than Pascal\'s triangle for expanding (x+1)²⁰?',
        options: [
          { id: 'a', text: 'The theorem gives any term directly, without building 20 rows of a triangle by hand.' },
          { id: 'b', text: 'Pascal\'s triangle only works for even powers.' },
          { id: 'c', text: 'The binomial theorem does not use combinations.' },
          { id: 'd', text: 'They give different, incompatible answers.' },
        ],
        correctOptionId: 'a',
        hints: ['Think about how many rows of Pascal\'s triangle you would need.'],
        explanation: 'Building 20 rows of Pascal\'s triangle is impractical; the theorem computes any needed term directly via ⁿCᵣ.',
      },
    },
    {
      id: 'bin-e1',
      part: 'challenge',
      conceptSlug: 'the-general-term-of-a-binomial-expansion',
      conceptTitle: 'The General Term of a Binomial Expansion',
      question: {
        id: 'bin-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the 5th term of (x + 2)⁶. (Give just the numeric coefficient.)',
        hints: ['5th term: r=4.', 'T5 = ⁶C₄ x² (2)⁴.'],
        correctAnswer: 240,
        explanation: '⁶C₄=15, 2⁴=16, 15×16=240, so T5=240x².',
      },
    },
    {
      id: 'bin-e2',
      part: 'challenge',
      conceptSlug: 'finding-the-coefficient-of-a-specific-term',
      conceptTitle: 'Finding the Coefficient of a Specific Term',
      question: {
        id: 'bin-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the coefficient of x⁵ in the expansion of (x + 1)⁷.',
        hints: ['7 − r = 5 → r = 2.', 'Coefficient = ⁷C₂ × 1².'],
        correctAnswer: 21,
        explanation: '⁷C₂=21, 1²=1, 21×1=21.',
      },
    },
  ],
};
