import type { Assessment } from '@/types/content';

export const chapter6CSoundAssessment: Assessment = {
  id: 'effects-and-characteristics-of-sound-assessment',
  questions: [
    {
      id: 'sound-a1',
      part: 'concept',
      conceptSlug: 'propagation-of-sound',
      conceptTitle: 'Propagation of Sound in a Medium',
      question: {
        id: 'sound-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the speed of sound in air at 0°C.',
        hints: ['v = 331+0.6T.'],
        correctAnswer: 331,
        explanation: 'v = 331+0.6(0) = 331 m/s.',
      },
    },
    {
      id: 'sound-a2',
      part: 'concept',
      conceptSlug: 'properties-of-sound-waves',
      conceptTitle: 'Properties of Sound Waves',
      question: {
        id: 'sound-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A sound wave travels at 1500 m/s (in water) with a frequency of 500 Hz. Find its wavelength.',
        hints: ['λ = v/f.'],
        correctAnswer: 3,
        explanation: 'λ = 1500/500 = 3 m.',
      },
    },
    {
      id: 'sound-b1',
      part: 'formula-application',
      conceptSlug: 'echo',
      conceptTitle: 'Echo',
      question: {
        id: 'sound-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: "A sailor sends a sonar pulse and hears its echo 2 s later (v=1500 m/s in water). Find the ocean depth.",
        hints: ['d = vt/2.'],
        correctAnswer: 1500,
        explanation: 'd = (1500)(2)/2 = 1500 m.',
      },
    },
    {
      id: 'sound-b2',
      part: 'formula-application',
      conceptSlug: 'doppler-effect',
      conceptTitle: 'The Doppler Effect',
      question: {
        id: 'sound-b2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A source emits sound at 600 Hz while moving away from a stationary observer at 30 m/s (v=340 m/s). Find the frequency heard.',
        hints: ["Source receding: f' = f(v)/(v+v_s)."],
        correctAnswer: 551.4,
        tolerance: 1,
        explanation: "f' = 600(340)/(340+30) = 204000/370 ≈ 551.4 Hz.",
      },
    },
    {
      id: 'sound-c1',
      part: 'problem-solving',
      conceptSlug: 'audibility-and-hearing-range',
      conceptTitle: 'Audibility',
      question: {
        id: 'sound-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'In air (v=340 m/s), find the minimum distance for a person to hear a distinct echo.',
        hints: ['d_min = (v × 0.1)/2.'],
        correctAnswer: 17,
        explanation: 'd_min = (340)(0.1)/2 = 34/2 = 17 m.',
      },
    },
    {
      id: 'sound-c2',
      part: 'problem-solving',
      conceptSlug: 'doppler-effect',
      conceptTitle: 'The Doppler Effect',
      question: {
        id: 'sound-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'An observer moves away from a stationary source at 10 m/s (v=340 m/s, f=450 Hz). Find the frequency heard.',
        hints: ["Observer receding: f' = f(v−v₀)/v."],
        correctAnswer: 436.8,
        tolerance: 1,
        explanation: "f' = 450(340−10)/340 = 450(330)/340 = 148500/340 ≈ 436.8 Hz.",
      },
    },
    {
      id: 'sound-d1',
      part: 'real-life-application',
      conceptSlug: 'echo',
      conceptTitle: 'Echo',
      question: {
        id: 'sound-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A bat uses echolocation, emitting ultrasonic clicks and listening for their echoes to navigate in the dark. What does the TIME DELAY of the echo directly tell the bat?',
        hints: ['This is the same principle as d=vt/2.'],
        options: [
          { id: 'a', text: 'The distance to nearby objects' },
          { id: 'b', text: 'The loudness of the object' },
          { id: 'c', text: 'The color of the object' },
          { id: 'd', text: 'The temperature of the object' },
        ],
        correctOptionId: 'a',
        explanation: 'The round-trip time of the echo directly gives distance, via d=vt/2 — exactly how a bat judges how far away obstacles and prey are.',
      },
    },
    {
      id: 'sound-d2',
      part: 'real-life-application',
      conceptSlug: 'propagation-of-sound',
      conceptTitle: 'Propagation of Sound in a Medium',
      question: {
        id: 'sound-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Astronauts standing outside on the Moon cannot talk to each other directly through the air and must use radio instead. Why?',
        hints: ['Sound needs a medium to travel through.'],
        options: [
          { id: 'a', text: 'The Moon has no atmosphere, so there is no medium for sound to travel through' },
          { id: 'b', text: 'Sound travels too fast on the Moon to be understood' },
          { id: 'c', text: 'Radio is simply more polite' },
          { id: 'd', text: 'Sound only works in cold environments' },
        ],
        correctOptionId: 'a',
        explanation: 'With no atmosphere, there are no particles to carry a sound wave — sound cannot propagate through the Moon\'s vacuum, so radio waves (which do not need a medium) must be used instead.',
      },
    },
    {
      id: 'sound-e1',
      part: 'challenge',
      conceptSlug: 'doppler-effect',
      conceptTitle: 'The Doppler Effect',
      question: {
        id: 'sound-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'A source emits sound at 1000 Hz and moves toward a listener who is also moving toward the source, both at 20 m/s (v=340 m/s). Find the frequency heard.',
        hints: ["Both approaching: f' = f(v+v₀)/(v−v_s)."],
        correctAnswer: 1125,
        explanation: "f' = 1000(340+20)/(340−20) = 1000(360)/320 = 360000/320 = 1125 Hz.",
      },
    },
    {
      id: 'sound-e2',
      part: 'challenge',
      conceptSlug: 'properties-of-sound-waves',
      conceptTitle: 'Properties of Sound Waves',
      question: {
        id: 'sound-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Sound wave A travels at 340 m/s with wavelength 0.85 m. Find its frequency.',
        hints: ['f = v/λ.'],
        correctAnswer: 400,
        explanation: 'f = 340/0.85 = 400 Hz.',
      },
    },
  ],
};
