import type { Assessment } from '@/types/content';

export const chapter7AWaveAssessment: Assessment = {
  id: 'wave-and-sound-assessment',
  questions: [
    {
      id: 'wave-a1',
      part: 'concept',
      conceptSlug: 'describing-wave-motion-a-level',
      conceptTitle: 'Describing Wave Motion',
      question: {
        id: 'wave-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a water wave transport as it travels across a pond?',
        hints: ['The water itself does not travel with the wave.'],
        options: [
          { id: 'a', text: 'Water molecules' },
          { id: 'b', text: 'Energy' },
          { id: 'c', text: 'Mass' },
          { id: 'd', text: 'Nothing — it is an illusion' },
        ],
        correctOptionId: 'b',
        explanation: 'A wave transports energy from place to place; the water particles themselves simply oscillate about a fixed position.',
      },
    },
    {
      id: 'wave-a2',
      part: 'concept',
      conceptSlug: 'transverse-and-longitudinal-waves-a-level',
      conceptTitle: 'Transverse and Longitudinal Waves',
      question: {
        id: 'wave-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A wave pushed and pulled along the length of a slinky spring forms compressions and rarefactions. What type of wave is this?',
        hints: ['Compressions and rarefactions are the signature of one wave type.'],
        options: [
          { id: 'a', text: 'Transverse' },
          { id: 'b', text: 'Longitudinal' },
          { id: 'c', text: 'Neither — this is not a real wave' },
          { id: 'd', text: 'Both, simultaneously' },
        ],
        correctOptionId: 'b',
        explanation: 'Compressions and rarefactions, formed by particles oscillating parallel to the direction of travel, are the signature of a longitudinal wave.',
      },
    },
    {
      id: 'wave-b1',
      part: 'formula-application',
      conceptSlug: 'wave-characteristics-a-level',
      conceptTitle: 'Characteristics of Waves',
      question: {
        id: 'wave-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A wave has a frequency of 25 Hz and travels at 100 m/s. Find its wavelength.',
        hints: ['Rearrange v = fλ to λ = v/f.', '100/25.'],
        correctAnswer: 4,
        unit: 'm',
        explanation: 'λ = v/f = 100/25 = 4 m.',
      },
    },
    {
      id: 'wave-b2',
      part: 'formula-application',
      conceptSlug: 'speed-of-sound-a-level',
      conceptTitle: 'The Speed of Sound',
      question: {
        id: 'wave-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An echo from a wall returns after 0.5 s. Using the speed of sound in air as 340 m/s, find the distance to the wall.',
        hints: ['d = vt/2.', '(340 × 0.5) / 2.'],
        correctAnswer: 85,
        unit: 'm',
        explanation: 'd = (340×0.5)/2 = 170/2 = 85 m.',
      },
    },
    {
      id: 'wave-c1',
      part: 'problem-solving',
      conceptSlug: 'wave-graphs-a-level',
      conceptTitle: 'Graphical Representation of a Wave',
      question: {
        id: 'wave-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A displacement-distance graph shows successive peaks at 0 m, 3 m, 6 m, and 9 m. Find the wavelength.',
        hints: ['The distance between two consecutive peaks is the wavelength.'],
        correctAnswer: 3,
        unit: 'm',
        explanation: 'The peaks are 3 m apart, so the wavelength is 3 m.',
      },
    },
    {
      id: 'wave-c2',
      part: 'problem-solving',
      conceptSlug: 'wave-reflection-refraction-diffraction-a-level',
      conceptTitle: 'Reflection, Refraction and Diffraction of Waves',
      question: {
        id: 'wave-c2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'A wave bounces off a flat wall with an angle of incidence of 40°. Find the angle of reflection.',
        hints: ['The law of reflection: angle of incidence = angle of reflection.'],
        correctAnswer: 40,
        unit: '°',
        explanation: 'By the law of reflection, the angle of reflection equals the angle of incidence: 40°.',
      },
    },
    {
      id: 'wave-d1',
      part: 'real-life-application',
      conceptSlug: 'sound-waves-a-level',
      conceptTitle: 'Sound Waves',
      question: {
        id: 'wave-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why can astronauts on a spacewalk not hear each other by shouting directly across the vacuum of space?',
        hints: ['Sound needs a medium to travel through.'],
        options: [
          { id: 'a', text: 'There is no medium (no particles) in a vacuum to carry the sound' },
          { id: 'b', text: 'Space is too cold for sound waves' },
          { id: 'c', text: 'Sound travels too fast in a vacuum to be heard' },
          { id: 'd', text: 'Astronauts\' helmets block all sound' },
        ],
        correctOptionId: 'a',
        explanation: 'Sound is a mechanical wave that needs a medium (particles) to travel through — a vacuum has none, so sound cannot travel across it at all.',
      },
    },
    {
      id: 'wave-d2',
      part: 'real-life-application',
      conceptSlug: 'wave-characteristics-a-level',
      conceptTitle: 'Characteristics of Waves',
      question: {
        id: 'wave-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A guitar string produces the musical note "concert A" at 440 Hz. Using the speed of sound in air as 340 m/s, find the wavelength of this sound. (Round to 2 decimal places.)',
        hints: ['λ = v/f.', '340/440.'],
        correctAnswer: 0.77,
        tolerance: 0.01,
        unit: 'm',
        explanation: 'λ = 340/440 ≈ 0.77 m.',
      },
    },
    {
      id: 'wave-e1',
      part: 'challenge',
      conceptSlug: 'speed-of-sound-a-level',
      conceptTitle: 'The Speed of Sound',
      question: {
        id: 'wave-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: "A ship's sonar sends a pulse and receives the echo 2.4 s later; the sea floor beneath it is known to be 1800 m deep. Find the speed of sound in seawater implied by this measurement.",
        hints: ['Rearrange d = vt/2 to v = 2d/t.', '(2 × 1800) / 2.4.'],
        correctAnswer: 1500,
        unit: 'm/s',
        explanation: 'v = 2d/t = (2×1800)/2.4 = 3600/2.4 = 1500 m/s.',
      },
    },
    {
      id: 'wave-e2',
      part: 'challenge',
      conceptSlug: 'wave-reflection-refraction-diffraction-a-level',
      conceptTitle: 'Reflection, Refraction and Diffraction of Waves',
      question: {
        id: 'wave-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A doorway is 0.9 m wide. A bass tone has a wavelength of 3.4 m, and a treble tone has a wavelength of 0.068 m. Which diffracts MORE strongly through the doorway, and why?',
        hints: ['Diffraction is strongest when the wavelength is comparable to (or larger than) the gap.'],
        options: [
          { id: 'a', text: 'The bass tone, because its wavelength is comparable to (larger than) the doorway width' },
          { id: 'b', text: 'The treble tone, because higher frequencies always diffract more' },
          { id: 'c', text: 'Both diffract by exactly the same amount' },
          { id: 'd', text: 'Neither diffracts at all through a doorway' },
        ],
        correctOptionId: 'a',
        explanation: "The bass tone's much longer wavelength (3.4 m) is comparable to the doorway's width, producing strong diffraction; the treble tone's tiny wavelength (0.068 m) diffracts far less, staying more directional.",
      },
    },
  ],
};
