import type { Assessment } from '@/types/content';

export const chapter2Assessment: Assessment = {
  id: 'exponents-and-radicals-assessment',
  questions: [
    {
      id: 'ear-a1',
      part: 'concept',
      conceptSlug: 'zero-and-negative-exponents',
      conceptTitle: 'Zero and Negative Exponents',
      question: {
        id: 'ear-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does a negative exponent do to a base?',
        options: [
          { id: 'a', text: 'Makes the result negative' },
          { id: 'b', text: 'Takes the reciprocal of the base raised to the positive exponent' },
          { id: 'c', text: 'Makes the result equal to zero' },
          { id: 'd', text: 'Has no effect' },
        ],
        correctOptionId: 'b',
        hints: ['a⁻ⁿ = 1/aⁿ.'],
        explanation: 'A negative exponent means "take the reciprocal", not "make negative": 2⁻³ = 1/8, a positive number.',
      },
    },
    {
      id: 'ear-a2',
      part: 'concept',
      conceptSlug: 'meaning-of-a-radical',
      conceptTitle: 'Meaning of a Radical',
      question: {
        id: 'ear-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What question does ⁿ√a answer?',
        options: [
          { id: 'a', text: 'What number, raised to the nth power, gives a?' },
          { id: 'b', text: 'What number, multiplied by n, gives a?' },
          { id: 'c', text: 'What number, added to n, gives a?' },
          { id: 'd', text: 'What is a divided by n?' },
        ],
        correctOptionId: 'a',
        hints: ['A radical undoes raising to a power.'],
        explanation: 'ⁿ√a is the number that, raised to the nth power, reproduces a.',
      },
    },
    {
      id: 'ear-b1',
      part: 'formula-application',
      conceptSlug: 'product-and-quotient-rules-of-exponents',
      conceptTitle: 'Product and Quotient Rules',
      question: {
        id: 'ear-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Simplify x⁷ / x², and give the resulting exponent on x.',
        hints: ['Same base — subtract the exponents.'],
        correctAnswer: 5,
        explanation: 'x⁷ / x² = x⁷⁻² = x⁵.',
      },
    },
    {
      id: 'ear-b2',
      part: 'formula-application',
      conceptSlug: 'fractional-exponents',
      conceptTitle: 'Fractional Exponents',
      question: {
        id: 'ear-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Evaluate 4^(3/2).',
        hints: ['4^(3/2) = (√4)³.', '√4 = 2.'],
        correctAnswer: 8,
        explanation: '4^(3/2) = (√4)³ = 2³ = 8.',
      },
    },
    {
      id: 'ear-c1',
      part: 'problem-solving',
      conceptSlug: 'simplifying-radicals',
      conceptTitle: 'Simplifying Radicals',
      question: {
        id: 'ear-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Simplify √72.',
        options: [
          { id: 'a', text: '6√2' },
          { id: 'b', text: '2√18' },
          { id: 'c', text: '8√9' },
          { id: 'd', text: '3√8' },
        ],
        correctOptionId: 'a',
        hints: ['72 = 36 × 2, and 36 is a perfect square.'],
        explanation: '√72 = √36 · √2 = 6√2.',
      },
    },
    {
      id: 'ear-c2',
      part: 'problem-solving',
      conceptSlug: 'dividing-radicals-and-rationalizing-denominators',
      conceptTitle: 'Dividing Radicals and Rationalizing Denominators',
      question: {
        id: 'ear-c2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Rationalize 6/√3.',
        options: [
          { id: 'a', text: '2√3' },
          { id: 'b', text: '6√3' },
          { id: 'c', text: '3√3' },
          { id: 'd', text: '√3' },
        ],
        correctOptionId: 'a',
        hints: ['Multiply top and bottom by √3.', '6√3/3 simplifies.'],
        explanation: '6/√3 × √3/√3 = 6√3/3 = 2√3.',
      },
    },
    {
      id: 'ear-d1',
      part: 'real-life-application',
      conceptSlug: 'exponential-growth-and-decay',
      conceptTitle: 'Exponential Growth and Decay',
      question: {
        id: 'ear-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A bacteria culture of 200 cells doubles every hour. How many cells after 4 hours?',
        hints: ['This is A = A₀ · 2ᵗ, a growth factor of exactly 2 per period.', '200 × 2⁴.'],
        correctAnswer: 3200,
        explanation: 'A = 200 × 2⁴ = 200 × 16 = 3200 cells.',
      },
    },
    {
      id: 'ear-d2',
      part: 'real-life-application',
      conceptSlug: 'solving-exponential-equations-with-equal-bases',
      conceptTitle: 'Solving Exponential Equations with Equal Bases',
      question: {
        id: 'ear-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A viral video\'s views follow V = 100 · 3ᵗ (t in days). After how many days does it reach 8,100 views?',
        options: [
          { id: 'a', text: '4 days' },
          { id: 'b', text: '3 days' },
          { id: 'c', text: '81 days' },
          { id: 'd', text: '8 days' },
        ],
        correctOptionId: 'a',
        hints: ['8100/100 = 81 = 3⁴.'],
        explanation: '100 · 3ᵗ = 8100 → 3ᵗ = 81 = 3⁴ → t = 4 days.',
      },
    },
    {
      id: 'ear-e1',
      part: 'challenge',
      conceptSlug: 'power-of-a-power-and-product-rules',
      conceptTitle: 'Power of a Power, Power of a Product',
      question: {
        id: 'ear-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Simplify (2x²y)³.',
        options: [
          { id: 'a', text: '8x⁶y³' },
          { id: 'b', text: '2x⁶y³' },
          { id: 'c', text: '8x⁵y³' },
          { id: 'd', text: '6x⁶y³' },
        ],
        correctOptionId: 'a',
        hints: ['Apply the power to every factor: 2, x², and y separately.', '(x²)³ = x⁶.'],
        explanation: '(2x²y)³ = 2³ · (x²)³ · y³ = 8x⁶y³.',
      },
    },
    {
      id: 'ear-e2',
      part: 'challenge',
      conceptSlug: 'multiplying-radicals',
      conceptTitle: 'Multiplying Radicals',
      question: {
        id: 'ear-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Simplify (2√3)(3√6).',
        options: [
          { id: 'a', text: '18√2' },
          { id: 'b', text: '6√18' },
          { id: 'c', text: '6√9' },
          { id: 'd', text: '5√18' },
        ],
        correctOptionId: 'a',
        hints: ['Multiply coefficients: 2×3. Multiply radicands: 3×6=18.', '√18 = 3√2, so combine with the coefficient.'],
        explanation: '(2√3)(3√6) = 6√18 = 6·3√2 = 18√2.',
      },
    },
  ],
};
