import type { Assessment } from '@/types/content';

export const chapter11CAssessment: Assessment = {
  id: 'applications-of-integration-assessment',
  questions: [
    {
      id: 'appint-a1',
      part: 'concept',
      conceptSlug: 'the-definite-integral-and-the-fundamental-theorem-of-calculus',
      conceptTitle: 'The Definite Integral and the Fundamental Theorem of Calculus',
      question: {
        id: 'appint-a1-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Evaluate ∫₀² 4x³ dx.',
        hints: ['Find an antiderivative of 4x³, then apply F(2)−F(0).'],
        correctAnswer: 16,
        explanation: 'F(x)=x⁴. F(2)−F(0) = 16 − 0 = 16.',
      },
    },
    {
      id: 'appint-a2',
      part: 'concept',
      conceptSlug: 'area-under-a-curve',
      conceptTitle: 'Area Under a Curve',
      question: {
        id: 'appint-a2-q',
        type: 'numeric',
        difficulty: 'easy',
        prompt: 'Find the area under y = 2x, from x = 0 to x = 3.',
        hints: ['Area = ∫₀³ 2x dx.'],
        correctAnswer: 9,
        explanation: 'F(x)=x². F(3)−F(0) = 9 − 0 = 9.',
      },
    },
    {
      id: 'appint-b1',
      part: 'formula-application',
      conceptSlug: 'area-between-two-curves',
      conceptTitle: 'Area Between Two Curves',
      question: {
        id: 'appint-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the area between f(x) = 4 and g(x) = x², between their intersection points.',
        hints: ['They intersect at x=±2. Area = ∫₋₂² (4−x²) dx.'],
        correctAnswer: 10.667,
        tolerance: 0.01,
        explanation: 'F(x)=4x−x³/3. F(2)−F(−2) = (8−8/3) − (−8+8/3) = 16 − 16/3 = 32/3 ≈ 10.667.',
      },
    },
    {
      id: 'appint-b2',
      part: 'formula-application',
      conceptSlug: 'volume-of-revolution-the-disk-method',
      conceptTitle: 'Volume of Revolution: The Disk Method',
      question: {
        id: 'appint-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the volume when the region under y=3, from x=0 to x=2, is rotated around the x-axis.',
        hints: ['V = π∫₀² 9 dx.'],
        correctAnswer: 56.549,
        tolerance: 0.01,
        explanation: 'V = π(9)(2) = 18π ≈ 56.549.',
      },
    },
    {
      id: 'appint-c1',
      part: 'problem-solving',
      conceptSlug: 'volume-of-revolution-the-washer-method',
      conceptTitle: 'Volume of Revolution: The Washer Method',
      question: {
        id: 'appint-c1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the volume when the region between R(x)=√x (outer) and r(x)=x/2 (inner), from x=0 to x=4, is rotated around the x-axis.',
        hints: ['V = π∫₀⁴ (x − x²/4) dx.'],
        correctAnswer: 8.378,
        tolerance: 0.01,
        explanation: 'V = π[x²/2 − x³/12]₀⁴ = π(8 − 64/12) = π(8 − 5.333) ≈ 8.378.',
      },
    },
    {
      id: 'appint-c2',
      part: 'problem-solving',
      conceptSlug: 'the-definite-integral-and-the-fundamental-theorem-of-calculus',
      conceptTitle: 'The Definite Integral and the Fundamental Theorem of Calculus',
      question: {
        id: 'appint-c2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Evaluate ∫₋₁¹ (3x² + 1) dx.',
        hints: ['F(x) = x³ + x.'],
        correctAnswer: 4,
        explanation: 'F(1)−F(−1) = (1+1) − (−1−1) = 2 − (−2) = 4.',
      },
    },
    {
      id: 'appint-d1',
      part: 'real-life-application',
      conceptSlug: 'area-under-a-curve',
      conceptTitle: 'Area Under a Curve',
      question: {
        id: 'appint-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A factory\'s production rate is r(t) = 50 + 2t units per day. What does ∫₀¹⁰ r(t) dt represent?',
        hints: ['The area under a rate function gives an accumulated total.'],
        options: [
          { id: 'a', text: 'The total number of units produced over the first 10 days' },
          { id: 'b', text: 'The production rate at exactly day 10' },
          { id: 'c', text: 'The average daily production rate' },
          { id: 'd', text: 'The maximum production rate reached' },
        ],
        correctOptionId: 'a',
        explanation: 'The area under a rate function over a time interval gives the total accumulated quantity — here, total units produced over the first 10 days.',
      },
    },
    {
      id: 'appint-d2',
      part: 'real-life-application',
      conceptSlug: 'volume-of-revolution-the-disk-method',
      conceptTitle: 'Volume of Revolution: The Disk Method',
      question: {
        id: 'appint-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A ceramicist designs a vase by rotating a profile curve y=f(x) around the x-axis (the vase\'s central axis). Which formula computes the vase\'s volume?',
        hints: ['Each circular cross-section has radius f(x).'],
        options: [
          { id: 'a', text: 'V = π∫[f(x)]² dx' },
          { id: 'b', text: 'V = ∫f(x) dx' },
          { id: 'c', text: 'V = 2π∫f(x) dx' },
          { id: 'd', text: 'V = π∫f(x) dx' },
        ],
        correctOptionId: 'a',
        explanation: 'The disk method requires squaring the radius function before integrating: V=π∫[f(x)]²dx.',
      },
    },
    {
      id: 'appint-e1',
      part: 'challenge',
      conceptSlug: 'area-between-two-curves',
      conceptTitle: 'Area Between Two Curves',
      question: {
        id: 'appint-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the area enclosed between f(x) = 8−x² and g(x) = x².',
        hints: ['They intersect at x=±2. Area = ∫₋₂² (8−2x²) dx.'],
        correctAnswer: 21.333,
        tolerance: 0.01,
        explanation: 'F(x)=8x−2x³/3. F(2)−F(−2) = (16−16/3) − (−16+16/3) = 32 − 32/3 = 64/3 ≈ 21.333.',
      },
    },
    {
      id: 'appint-e2',
      part: 'challenge',
      conceptSlug: 'volume-of-revolution-the-washer-method',
      conceptTitle: 'Volume of Revolution: The Washer Method',
      question: {
        id: 'appint-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the volume when the region between R(x)=x+1 (outer) and r(x)=x (inner), from x=0 to x=2, is rotated around the x-axis.',
        hints: ['V = π∫₀² [(x+1)² − x²] dx = π∫₀² (2x+1) dx.'],
        correctAnswer: 18.85,
        tolerance: 0.01,
        explanation: 'V = π[x²+x]₀² = π(4+2) = 6π ≈ 18.850.',
      },
    },
  ],
};
