import type { Assessment } from '@/types/content';

export const chapter4BAssessment: Assessment = {
  id: 'sequences-and-series-assessment',
  questions: [
    {
      id: 'seq-a1',
      part: 'concept',
      conceptSlug: 'introduction-to-sequences-and-series',
      conceptTitle: 'Introduction to Sequences and Series',
      question: {
        id: 'seq-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What is the difference between a sequence and a series?',
        options: [
          { id: 'a', text: 'A sequence is a list of terms; a series is the sum of those terms' },
          { id: 'b', text: 'They are exactly the same thing' },
          { id: 'c', text: 'A series is a list; a sequence is a sum' },
          { id: 'd', text: 'A sequence only has 2 terms' },
        ],
        correctOptionId: 'a',
        hints: ['Series = "sum".'],
        explanation: 'A sequence lists terms; a series sums them.',
      },
    },
    {
      id: 'seq-a2',
      part: 'concept',
      conceptSlug: 'geometric-progressions',
      conceptTitle: 'Geometric Progression (G.P.)',
      question: {
        id: 'seq-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What defines a geometric progression?',
        options: [
          { id: 'a', text: 'Each term is found by multiplying the previous term by a fixed ratio' },
          { id: 'b', text: 'Each term is found by adding a fixed number to the previous term' },
          { id: 'c', text: 'The terms are always increasing' },
          { id: 'd', text: 'The terms are always whole numbers' },
        ],
        correctOptionId: 'a',
        hints: ['"Geometric" → ratio, not difference.'],
        explanation: 'A G.P. has a common RATIO between consecutive terms.',
      },
    },
    {
      id: 'seq-b1',
      part: 'formula-application',
      conceptSlug: 'arithmetic-progressions',
      conceptTitle: 'Arithmetic Progression (A.P.)',
      question: {
        id: 'seq-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An A.P. has a₁=10 and d=−3. Find the 7th term.',
        hints: ['a₇ = 10 + 6(−3).'],
        correctAnswer: -8,
        explanation: 'a₇ = 10 − 18 = −8.',
      },
    },
    {
      id: 'seq-b2',
      part: 'formula-application',
      conceptSlug: 'geometric-series',
      conceptTitle: 'Geometric Series',
      question: {
        id: 'seq-b2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Find the sum of the first 3 terms of the G.P. with a₁=4 and r=2.',
        hints: ['S₃ = 4(1−2³)/(1−2).'],
        correctAnswer: 28,
        explanation: 'S₃ = 4(1−8)/(−1) = 4(−7)/(−1) = 28.',
      },
    },
    {
      id: 'seq-c1',
      part: 'problem-solving',
      conceptSlug: 'arithmetic-series',
      conceptTitle: 'Arithmetic Series',
      question: {
        id: 'seq-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An A.P. has a₁=6, d=4. Find the sum of the first 12 terms.',
        hints: ['First find a₁₂ = 6 + 11(4).', 'Then S₁₂ = 12/2 × (6 + a₁₂).'],
        correctAnswer: 336,
        explanation: 'a₁₂=6+44=50. S₁₂=6×(6+50)=6×56=336.',
      },
    },
    {
      id: 'seq-c2',
      part: 'problem-solving',
      conceptSlug: 'infinite-geometric-series',
      conceptTitle: 'Infinite Geometric Series',
      question: {
        id: 'seq-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Find the sum of 20 + 5 + 1.25 + ... continuing forever.',
        hints: ['r = 5/20 = 0.25.', 'S∞ = 20/(1−0.25).'],
        correctAnswer: 26.67,
        tolerance: 0.05,
        explanation: 'S∞ = 20/0.75 ≈ 26.67.',
      },
    },
    {
      id: 'seq-d1',
      part: 'real-life-application',
      conceptSlug: 'arithmetic-progressions',
      conceptTitle: 'Arithmetic Progression (A.P.)',
      question: {
        id: 'seq-d1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'A theatre\'s rows have seats increasing by 3 per row, starting at 15 seats in row 1. How many seats are in row 6?',
        hints: ['a₆ = 15 + 5(3).'],
        correctAnswer: 30,
        explanation: 'a₆ = 15 + 15 = 30.',
      },
    },
    {
      id: 'seq-d2',
      part: 'real-life-application',
      conceptSlug: 'geometric-progressions',
      conceptTitle: 'Geometric Progression (G.P.)',
      question: {
        id: 'seq-d2-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'An investment of $2000 grows by a factor of 1.1 each year. Find its value after 3 years (i.e. a₄, since a₁ is the initial value).',
        hints: ['a₄ = 2000 × 1.1³.'],
        correctAnswer: 2662,
        tolerance: 1,
        explanation: 'a₄ = 2000 × 1.331 = 2662.',
      },
    },
    {
      id: 'seq-e1',
      part: 'challenge',
      conceptSlug: 'geometric-series',
      conceptTitle: 'Geometric Series',
      question: {
        id: 'seq-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'How is the geometric series sum formula, Sₙ=a₁(1−rⁿ)/(1−r), actually derived?',
        options: [
          { id: 'a', text: 'By computing Sₙ − rSₙ, which cancels nearly every term, leaving Sₙ(1−r) = a₁(1−rⁿ).' },
          { id: 'b', text: 'By pairing the first and last terms, like the arithmetic series formula.' },
          { id: 'c', text: 'By taking the average of all n terms.' },
          { id: 'd', text: 'It cannot be derived; it is an empirical rule.' },
        ],
        correctOptionId: 'a',
        hints: ['This is the standard derivation technique, different from the arithmetic series proof.'],
        explanation: 'Subtracting rSₙ from Sₙ cancels almost every term, leaving a simple equation that rearranges into the formula.',
      },
    },
    {
      id: 'seq-e2',
      part: 'challenge',
      conceptSlug: 'infinite-geometric-series',
      conceptTitle: 'Infinite Geometric Series',
      question: {
        id: 'seq-e2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Convert the repeating decimal 0.777... to a fraction using the infinite geometric series formula (a₁=0.7, r=0.1). Give the answer as a fraction\'s numerator over 9 (just the numerator).',
        hints: ['S∞ = 0.7/(1−0.1) = 0.7/0.9.'],
        correctAnswer: 7,
        explanation: '0.7/0.9 = 7/9, so 0.777... = 7/9.',
      },
    },
  ],
};
