import type { Assessment } from '@/types/content';

export const chapter10AMagnetismAssessment: Assessment = {
  id: 'magnetism-assessment',
  questions: [
    {
      id: 'magnetism-a1',
      part: 'concept',
      conceptSlug: 'magnets-and-magnetic-materials-a-level',
      conceptTitle: 'Magnets and Magnetic Materials',
      question: {
        id: 'magnetism-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Which pair of magnetic poles will ATTRACT each other?',
        hints: ['Unlike poles attract.'],
        options: [
          { id: 'a', text: 'North and north' },
          { id: 'b', text: 'South and south' },
          { id: 'c', text: 'North and south' },
          { id: 'd', text: 'No pair of poles ever attracts' },
        ],
        correctOptionId: 'c',
        explanation: 'Unlike poles (north and south) always attract; like poles (N-N or S-S) always repel.',
      },
    },
    {
      id: 'magnetism-a2',
      part: 'concept',
      conceptSlug: 'theory-of-magnetism-a-level',
      conceptTitle: 'Theory of Magnetism',
      question: {
        id: 'magnetism-a2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'What best describes a magnetic domain?',
        hints: ['Think of it as a tiny building block of magnetism.'],
        options: [
          { id: 'a', text: 'A tiny region acting like a miniature magnet, with its own aligned atomic magnetic effects' },
          { id: 'b', text: 'A single electron orbiting an atom' },
          { id: 'c', text: 'A crack or defect inside a magnet' },
          { id: 'd', text: 'The outer coating of a magnet' },
        ],
        correctOptionId: 'a',
        explanation: 'A magnetic domain is a small region within a material where atomic magnetic effects are aligned, so the whole domain acts like a tiny magnet.',
      },
    },
    {
      id: 'magnetism-b1',
      part: 'formula-application',
      conceptSlug: 'magnetic-fields-a-level',
      conceptTitle: 'Magnetic Fields',
      question: {
        id: 'magnetism-b1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'In a diagram of the magnetic field around a bar magnet, where are the field lines drawn closest together?',
        hints: ['Closer lines mean a stronger field.'],
        options: [
          { id: 'a', text: 'Near the poles' },
          { id: 'b', text: 'Exactly halfway along the magnet\'s side' },
          { id: 'c', text: 'Far away from the magnet' },
          { id: 'd', text: 'The spacing is always exactly the same everywhere' },
        ],
        correctOptionId: 'a',
        explanation: 'Field lines are drawn closest together near the poles, where the magnetic field is strongest.',
      },
    },
    {
      id: 'magnetism-b2',
      part: 'formula-application',
      conceptSlug: 'magnetic-properties-iron-steel-a-level',
      conceptTitle: 'Magnetic Properties of Iron and Steel',
      question: {
        id: 'magnetism-b2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Steel is chosen for making permanent magnets mainly because:',
        hints: ['Think about what "hard" magnetic material means.'],
        options: [
          { id: 'a', text: 'It retains its magnetism for a long time once magnetized' },
          { id: 'b', text: 'It is the easiest material to magnetize' },
          { id: 'c', text: 'It is not actually magnetic at all' },
          { id: 'd', text: 'It loses magnetism instantly, which is desirable' },
        ],
        correctOptionId: 'a',
        explanation: 'Steel is a hard magnetic material — harder to magnetize initially, but it retains its magnetism for a long time, making it ideal for permanent magnets.',
      },
    },
    {
      id: 'magnetism-c1',
      part: 'problem-solving',
      conceptSlug: 'magnetisation-and-induced-magnetism-a-level',
      conceptTitle: 'Magnetisation and Induced Magnetism',
      question: {
        id: 'magnetism-c1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Placing an unmagnetized iron rod inside a coil carrying a strong steady electric current magnetizes the rod. What process does this demonstrate?',
        hints: ['A strong field from the coil aligns the domains inside the rod.'],
        options: [
          { id: 'a', text: 'Magnetisation by placing the material in a strong magnetic field' },
          { id: 'b', text: 'Demagnetisation' },
          { id: 'c', text: 'Charging by friction' },
          { id: 'd', text: 'Coulomb\'s law' },
        ],
        correctOptionId: 'a',
        explanation: "Placing a magnetic material inside a strong magnetic field (here, from the current-carrying coil) aligns its domains, magnetising it.",
      },
    },
    {
      id: 'magnetism-c2',
      part: 'problem-solving',
      conceptSlug: 'magnets-and-magnetic-materials-a-level',
      conceptTitle: 'Magnets and Magnetic Materials',
      question: {
        id: 'magnetism-c2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A student has four unlabeled metal rods; only one is an UNMAGNETIZED iron rod, the rest are non-magnetic metals. Which single test correctly identifies the iron rod?',
        hints: ['Attraction works on ferromagnetic material whether or not it is currently magnetized.'],
        options: [
          { id: 'a', text: 'Bring a strong magnet close to each rod — the iron rod alone will be attracted' },
          { id: 'b', text: 'Use a compass to check which rod has a north pole' },
          { id: 'c', text: 'Weigh each rod — the heaviest one is iron' },
          { id: 'd', text: 'There is no way to tell without magnetizing all four rods first' },
        ],
        correctOptionId: 'a',
        explanation: 'A ferromagnetic material like iron is attracted to a strong magnet whether or not it is itself currently magnetized — this attraction test works even without any pre-existing magnetism.',
      },
    },
    {
      id: 'magnetism-d1',
      part: 'real-life-application',
      conceptSlug: 'theory-of-magnetism-a-level',
      conceptTitle: 'Theory of Magnetism',
      question: {
        id: 'magnetism-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why does heating a magnet strongly cause it to lose its magnetism?',
        hints: ['Think about what heat energy does to aligned domains.'],
        options: [
          { id: 'a', text: 'The extra energy from heat disturbs the domains, shifting them back toward random directions' },
          { id: 'b', text: 'Heat destroys the atoms inside the magnet' },
          { id: 'c', text: 'Heat has no effect on magnetism at all' },
          { id: 'd', text: 'Heat always strengthens a magnet instead' },
        ],
        correctOptionId: 'a',
        explanation: 'The added thermal energy disturbs the aligned domains, knocking many back into random orientations and reducing the overall magnetism.',
      },
    },
    {
      id: 'magnetism-d2',
      part: 'real-life-application',
      conceptSlug: 'magnetic-properties-iron-steel-a-level',
      conceptTitle: 'Magnetic Properties of Iron and Steel',
      question: {
        id: 'magnetism-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'A scrap-yard crane uses an electromagnet to lift heavy scrap metal, then instantly drop it by switching off the current. Which material should its core be made from?',
        hints: ['The core needs to demagnetize instantly when switched off.'],
        options: [
          { id: 'a', text: 'Iron (a soft magnetic material)' },
          { id: 'b', text: 'Steel (a hard magnetic material)' },
          { id: 'c', text: 'Either material works exactly the same' },
          { id: 'd', text: 'A non-magnetic material like copper' },
        ],
        correctOptionId: 'a',
        explanation: 'Iron, a soft magnetic material, magnetizes strongly when the current flows and demagnetizes almost instantly when it stops — exactly what the crane needs to release scrap on command.',
      },
    },
    {
      id: 'magnetism-e1',
      part: 'challenge',
      conceptSlug: 'magnetic-fields-a-level',
      conceptTitle: 'Magnetic Fields',
      question: {
        id: 'magnetism-e1-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Two bar magnets are placed end to end with a small gap, a north pole facing a south pole. What is true of the magnetic field in that gap?',
        hints: ['Unlike poles facing each other reinforce the field between them.'],
        options: [
          { id: 'a', text: 'It is strong and roughly uniform, with field lines passing straight across from north to south' },
          { id: 'b', text: 'It is exactly zero, since the two fields cancel out' },
          { id: 'c', text: 'The field lines cross each other in the middle of the gap' },
          { id: 'd', text: 'There is no field at all between two separate magnets' },
        ],
        correctOptionId: 'a',
        explanation: "With a north pole facing a south pole, the two magnets' fields reinforce each other in the gap, producing a strong, roughly uniform field with lines passing straight across.",
      },
    },
    {
      id: 'magnetism-e2',
      part: 'challenge',
      conceptSlug: 'magnetisation-and-induced-magnetism-a-level',
      conceptTitle: 'Magnetisation and Induced Magnetism',
      question: {
        id: 'magnetism-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'A steel bar is magnetized by stroking it repeatedly, always in the SAME direction, with a strong magnet. Why does this produce a stronger magnet than stroking it back and forth in random directions?',
        hints: ['Think about what each stroke does to the ALREADY-aligned domains.'],
        options: [
          { id: 'a', text: 'Consistent, same-direction strokes progressively align more domains the same way; back-and-forth strokes partly re-randomize domains already aligned' },
          { id: 'b', text: 'Random strokes actually magnetize the bar faster' },
          { id: 'c', text: 'The direction of stroking has no effect on the final magnetism' },
          { id: 'd', text: 'Only the FIRST stroke ever matters, regardless of direction' },
        ],
        correctOptionId: 'a',
        explanation: 'Each same-direction stroke builds on the alignment from the last one, steadily increasing the number of aligned domains; strokes in varying directions can undo some of that alignment, limiting the final magnetism.',
      },
    },
  ],
};
