import type { Assessment } from '@/types/content';

export const chapter3Assessment: Assessment = {
  id: 'logarithms-assessment',
  questions: [
    {
      id: 'log-a1',
      part: 'concept',
      conceptSlug: 'meaning-of-a-logarithm',
      conceptTitle: 'Meaning of a Logarithm',
      question: {
        id: 'log-a1-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'What does log_b(x) represent?',
        options: [
          { id: 'a', text: 'The exponent that b must be raised to in order to get x' },
          { id: 'b', text: 'The product of b and x' },
          { id: 'c', text: 'The base that x must be raised to in order to get b' },
          { id: 'd', text: 'x divided by b' },
        ],
        correctOptionId: 'a',
        hints: ['log_b(x) = y ⇔ bʸ = x.'],
        explanation: 'A logarithm is the exponent — log_b(x) asks "what power of b gives x?"',
      },
    },
    {
      id: 'log-a2',
      part: 'concept',
      conceptSlug: 'common-logarithm',
      conceptTitle: 'The Common Logarithm',
      question: {
        id: 'log-a2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'When no base is written, "log(x)" is always assumed to mean:',
        options: [
          { id: 'a', text: 'log₁₀(x)' },
          { id: 'b', text: 'log_e(x)' },
          { id: 'c', text: 'log₂(x)' },
          { id: 'd', text: 'It is ambiguous' },
        ],
        correctOptionId: 'a',
        hints: ['The common logarithm has an unwritten base.'],
        explanation: 'An unwritten base always means base 10, the common logarithm.',
      },
    },
    {
      id: 'log-b1',
      part: 'formula-application',
      conceptSlug: 'evaluating-logarithms',
      conceptTitle: 'Evaluating Logarithms',
      question: {
        id: 'log-b1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'Evaluate log₃(243).',
        hints: ['3⁵ = 243.'],
        correctAnswer: 5,
        explanation: '3⁵ = 243, so log₃(243) = 5.',
      },
    },
    {
      id: 'log-b2',
      part: 'formula-application',
      conceptSlug: 'writing-numbers-in-scientific-notation',
      conceptTitle: 'Writing Numbers in Scientific Notation',
      question: {
        id: 'log-b2-q',
        type: 'multiple-choice',
        difficulty: 'easy',
        prompt: 'Write 6,200 in scientific notation.',
        options: [
          { id: 'a', text: '6.2 × 10³' },
          { id: 'b', text: '62 × 10²' },
          { id: 'c', text: '6.2 × 10⁴' },
          { id: 'd', text: '0.62 × 10⁴' },
        ],
        correctOptionId: 'a',
        hints: ['The decimal point moves 3 places.'],
        explanation: '6,200 = 6.2 × 10³.',
      },
    },
    {
      id: 'log-c1',
      part: 'problem-solving',
      conceptSlug: 'product-rule-of-logarithms',
      conceptTitle: 'Product Rule of Logarithms',
      question: {
        id: 'log-c1-q',
        type: 'numeric',
        difficulty: 'medium',
        prompt: 'If log_b(5) = 1.16 and log_b(4) = 0.86, find log_b(20). (Round to 2 decimal places.)',
        hints: ['log_b(20) = log_b(5 × 4) = log_b(5) + log_b(4).'],
        correctAnswer: 2.02,
        tolerance: 0.02,
        explanation: 'log_b(20) = log_b(5) + log_b(4) = 1.16 + 0.86 = 2.02.',
      },
    },
    {
      id: 'log-c2',
      part: 'problem-solving',
      conceptSlug: 'solving-logarithmic-equations',
      conceptTitle: 'Solving Logarithmic Equations',
      question: {
        id: 'log-c2-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Solve for x: log₂(x) = 6.',
        hints: ['Convert to exponential form: x = 2⁶.'],
        correctAnswer: 64,
        explanation: 'log₂(x) = 6 ⇔ x = 2⁶ = 64.',
      },
    },
    {
      id: 'log-d1',
      part: 'real-life-application',
      conceptSlug: 'common-logarithm',
      conceptTitle: 'The Common Logarithm',
      question: {
        id: 'log-d1-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'An earthquake of magnitude 6 releases how many times more energy-related amplitude than a magnitude 4 quake, on the base-10 Richter scale?',
        options: [
          { id: 'a', text: '100 times (10² , since the magnitudes differ by 2)' },
          { id: 'b', text: '2 times' },
          { id: 'c', text: '6 times' },
          { id: 'd', text: '10 times' },
        ],
        correctOptionId: 'a',
        hints: ['Each whole magnitude step is a factor of 10¹; a difference of 2 steps is 10².'],
        explanation: 'Since the Richter scale is base-10 logarithmic, a difference of 2 magnitudes means 10² = 100 times the amplitude.',
      },
    },
    {
      id: 'log-d2',
      part: 'real-life-application',
      conceptSlug: 'using-the-change-of-base-formula',
      conceptTitle: 'Using the Change of Base Formula',
      question: {
        id: 'log-d2-q',
        type: 'multiple-choice',
        difficulty: 'medium',
        prompt: 'Why is the change of base formula needed to evaluate log₆(40) on a typical calculator?',
        options: [
          { id: 'a', text: 'Calculators only have direct buttons for base 10 (log) and base e (ln), not base 6.' },
          { id: 'b', text: 'log₆(40) has no real value.' },
          { id: 'c', text: '40 is not a whole number.' },
          { id: 'd', text: 'Change of base is only needed for very large numbers.' },
        ],
        correctOptionId: 'a',
        hints: ['What logarithm buttons does an ordinary calculator have?'],
        explanation: 'Calculators compute base-10 or base-e logarithms directly; any other base needs the change of base formula to convert to one of those.',
      },
    },
    {
      id: 'log-e1',
      part: 'challenge',
      conceptSlug: 'power-rule-of-logarithms',
      conceptTitle: 'Power Rule of Logarithms',
      question: {
        id: 'log-e1-q',
        type: 'numeric',
        difficulty: 'hard',
        prompt: 'Solve for x: log₄(x) · 3 = 6, i.e. 3 log₄(x) = 6 (find x).',
        hints: ['Divide both sides by 3 first: log₄(x) = 2.', 'Then convert to exponential form.'],
        correctAnswer: 16,
        explanation: '3 log₄(x) = 6 → log₄(x) = 2 → x = 4² = 16.',
      },
    },
    {
      id: 'log-e2',
      part: 'challenge',
      conceptSlug: 'natural-logarithm',
      conceptTitle: 'The Natural Logarithm',
      question: {
        id: 'log-e2-q',
        type: 'multiple-choice',
        difficulty: 'hard',
        prompt: 'Which value is closest to ln(20), given ln(2) ≈ 0.693 and ln(10) ≈ 2.303?',
        options: [
          { id: 'a', text: '2.996 (since ln(20) = ln(2×10) = ln2 + ln10)' },
          { id: 'b', text: '1.610' },
          { id: 'c', text: '0.693' },
          { id: 'd', text: '20' },
        ],
        correctOptionId: 'a',
        hints: ['Use the product rule: ln(20) = ln(2) + ln(10).'],
        explanation: 'ln(20) = ln(2×10) = ln2 + ln10 ≈ 0.693 + 2.303 = 2.996.',
      },
    },
  ],
};
